<?php
namespace ccxt;
include_once (__DIR__.'/../../ccxt.php');
// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -----------------------------------------------------------------------------

error_reporting(E_ALL);
date_default_timezone_set('UTC');

use ccxt\Precise;
use React\Async;
use React\Promise;


function main() {
    return Async\async(function () {
        $symbol = $process->argv[2] || 'XMR/BTC';
        $amount_from = $process->argv[3] || '1';
        $exchange = new \ccxt\async\wizardswap();
        // WizardSwap has no predefined markets —
        // dynamically load currencies and build a market on the fly.
        \React\Async\await($exchange->load_markets());
        var_dump();
        $ticker = \React\Async\await($exchange->fetch_ticker($symbol, array(
            'amount_from' => $amount_from,
        )));
        [$base, $quote] = explode('/', $symbol);
        var_dump();
        var_dump();
        var_dump(, $ticker['info']);
    }) ();
}


main()->catch($console->error);
