import testAlchemy from './test.alchemy.js';
import testObAlchemy from './test.ob.alchemy.js';
import testObBinance from './test.ob.binance.js';
import testObBinanceus from './test.ob.binanceus.js';
import testObBingx from './test.ob.bingx.js';
import testObBitget from './test.ob.bitget.js';
import testObBitmart from './test.ob.bitmart.js';
import testObBybit from './test.ob.bybit.js';
import testCoingecko from './test.coingecko.js';
import testDexscreener from './test.dexscreener.js';
import testObChangenow from './test.ob.changenow.js';
import testCoinrabbit from './test.coinrabbit.js';
import testObCoinrabbit from './test.ob.coinrabbit.js';
import testObCoingecko from './test.ob.coingecko.js';
import testObDexscreener from './test.ob.dexscreener.js';
import testObCoinbase from './test.ob.coinbase.js';
import testObCoinex from './test.ob.coinex.js';
import testObExchangeMarketStatus from './test.ob.exchange.marketstatus.js';
import testObCryptocom from './test.ob.cryptocom.js';
import testObGate from './test.ob.gate.js';
import testObHollaex from './test.ob.hollaex.js';
import testObHyperliquid from './test.ob.hyperliquid.js';
import testObHtx from './test.ob.htx.js';
import testObKucoin from './test.ob.kucoin.js';
import testObKucoinfutures from './test.ob.kucoinfutures.js';
import testObKraken from './test.ob.kraken.js';
import testObLbank from './test.ob.lbank.js';
import testObMexc from './test.ob.mexc.js';
import testObOkx from './test.ob.okx.js';
import testObPhemex from './test.ob.phemex.js';
import testObWeex from './test.ob.weex.js';
import testWizardswap from './test.wizardswap.js';
import testObWizardswap from './test.ob.wizardswap.js';

async function obTestsInit () {
    await testAlchemy ();
    await testObAlchemy ();
    await testObBinance ();
    await testObBinanceus ();
    await testObBingx ();
    await testObBitget ();
    await testObBitmart ();
    await testObBybit ();
    await testCoingecko ();
    await testDexscreener ();
    await testObChangenow ();
    await testCoinrabbit ();
    await testObCoinrabbit ();
    await testObCoingecko ();
    await testObDexscreener ();
    await testObCoinbase ();
    await testObCoinex ();
    await testObExchangeMarketStatus ();
    await testObCryptocom ();
    await testObGate ();
    await testObHollaex ();
    await testObHyperliquid ();
    await testObHtx ();
    await testObKucoin ();
    await testObKucoinfutures ();
    await testObKraken ();
    await testObLbank ();
    await testObMexc ();
    await testObOkx ();
    await testObPhemex ();
    await testObWeex ();
    await testWizardswap ();
    await testObWizardswap ();
}

export default obTestsInit;
