import testObAscendex from './test.ob.ascendex.js';
import testObBinance from './test.ob.binance.js';
import testObBinanceus from './test.ob.binanceus.js';
import testObBingx from './test.ob.bingx.js';
import testObBitget from './test.ob.bitget.js';
import testObBitmart from './test.ob.bitmart.js';
import testObBybit from './test.ob.bybit.js';
import testCoingecko from './test.coingecko.js';
import testDexscreener from './test.dexscreener.js';
import testObChangenow from './test.ob.changenow.js';
import testObCoingecko from './test.ob.coingecko.js';
import testObDexscreener from './test.ob.dexscreener.js';
import testObCoinbase from './test.ob.coinbase.js';
import testObCoinex from './test.ob.coinex.js';
import testObExchangeMarketStatus from './test.ob.exchange.marketstatus.js';
import testObCryptocom from './test.ob.cryptocom.js';
import testObGateio from './test.ob.gateio.js';
import testObHollaex from './test.ob.hollaex.js';
import testObHyperliquid from './test.ob.hyperliquid.js';
import testObHtx from './test.ob.htx.js';
import testObKucoin from './test.ob.kucoin.js';
import testObKucoinfutures from './test.ob.kucoinfutures.js';
import testObKraken from './test.ob.kraken.js';
import testObLbank from './test.ob.lbank.js';
import testObMexc from './test.ob.mexc.js';
import testObOkx from './test.ob.okx.js';
import testObPhemex from './test.ob.phemex.js';
import testObTrocador from './test.ob.trocador.js';
import testObSimpleswap from './test.ob.simpleswap.js';
import testObExolix from './test.ob.exolix.js';
import testObWizardswap from './test.ob.wizardswap.js';

async function obTestsInit () {
    await testObAscendex ();
    await testObBinance ();
    await testObBinanceus ();
    await testObBingx ();
    await testObBitget ();
    await testObBitmart ();
    await testObBybit ();
    await testCoingecko ();
    await testDexscreener ();
    await testObChangenow ();
    await testObCoingecko ();
    await testObDexscreener ();
    await testObCoinbase ();
    await testObCoinex ();
    await testObExchangeMarketStatus ();
    await testObCryptocom ();
    await testObGateio ();
    await testObHollaex ();
    await testObHyperliquid ();
    await testObHtx ();
    await testObKucoin ();
    await testObKucoinfutures ();
    await testObKraken ();
    await testObLbank ();
    await testObMexc ();
    await testObOkx ();
    await testObPhemex ();
    await testObSimpleswap ();
    await testObTrocador ();
    await testObExolix ();
    await testObWizardswap ();
}

export default obTestsInit;
