#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, JSON, Array, Object, Math, parse_int, shift_2, extend_2, normalize};

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Bithumb : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bithumb",
            "name": "Bithumb",
            "countries": [
                "KR"
            ],
            "enableRateLimit": true,
            "rateLimit": 500,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "CORS": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createOrderWithTakeProfitAndStopLossWs": false,
                "createReduceOnlyOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchOHLCV": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": false,
                "watchBalance": true,
                "watchOHLCV": false,
                "watchOrderBook": true,
                "watchOrders": true,
                "watchTicker": true,
                "watchTickers": true,
                "watchTrades": true,
                "withdraw": true,
                "ws": true
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/c9e0eefb-4777-46b9-8f09-9d7f7c4af82d",
                "api": {
                    "public": "https://api.{hostname}/public",
                    "private": "https://api.{hostname}",
                    "ws": {
                        "public": "wss://pubwss.bithumb.com/pub/ws",
                        "publicV2": "wss://ws-api.bithumb.com/websocket/v1",
                        "privateV2": "wss://ws-api.bithumb.com/websocket/v1/private"
                    }
                },
                "www": "https://www.bithumb.com",
                "doc": "https://apidocs.bithumb.com",
                "fees": "https://en.bithumb.com/customer_support/info_fee"
            },
            "api": {
                "public": {
                    "get": [
                        "ticker/ALL_{quoteId}",
                        "ticker/{baseId}_{quoteId}",
                        "orderbook/ALL_{quoteId}",
                        "orderbook/{baseId}_{quoteId}",
                        "transaction_history/{baseId}_{quoteId}",
                        "network-info",
                        "assetsstatus/multichain/ALL",
                        "assetsstatus/multichain/{currency}",
                        "withdraw/minimum/ALL",
                        "withdraw/minimum/{currency}",
                        "assetsstatus/ALL",
                        "assetsstatus/{baseId}",
                        "candlestick/{baseId}_{quoteId}/{interval}"
                    ]
                },
                "private": {
                    "post": [
                        "info/account",
                        "info/balance",
                        "info/wallet_address",
                        "info/ticker",
                        "info/orders",
                        "info/user_transactions",
                        "info/order_detail",
                        "trade/place",
                        "trade/cancel",
                        "trade/btc_withdrawal",
                        "trade/krw_deposit",
                        "trade/krw_withdrawal",
                        "trade/market_buy",
                        "trade/market_sell",
                        "trade/stop_limit"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1m",
                "3m": "3m",
                "5m": "5m",
                "10m": "10m",
                "30m": "30m",
                "1h": "1h",
                "6h": "6h",
                "12h": "12h",
                "1d": "24h"
            },
            "fees": {
                "trading": {
                    "taker": 0.0025,
                    "maker": 0.0025
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {},
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV",
                "ALT": "ArchLoot",
                "FTC": "FTC2",
                "SOC": "Soda Coin"
            },
            "precisionMode": 3,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "hostname": "bithumb.com",
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    }
                },
                "swap": {},
                "future": {}
            },
            "options": {
                "quoteCurrencies": {
                    "BTC": {
                        "limits": {
                            "cost": {
                                "min": 0.0002,
                                "max": 100
                            }
                        }
                    },
                    "KRW": {
                        "limits": {
                            "cost": {
                                "min": 500,
                                "max": 5000000000
                            }
                        }
                    },
                    "USDT": {
                        "limits": {
                            "cost": {}
                        }
                    }
                }
            },
            "streaming": {}
        }"###).unwrap())
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public"));
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut message_hash: Value = Value::from("ticker:") + market.get(Value::from("symbol"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": "ticker",
            "symbols": Value::Json(serde_json::Value::Array(vec![market.get(Value::from("base")) + Value::from("_") + market.get(Value::from("quote")).into()])),
            "tickTypes": Value::Json(serde_json::Value::Array(vec![self.safe_string(params.clone(), Value::from("tickTypes"), Value::from("24H")).into()]))
        }))).unwrap());
        return self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
    }

    async fn watch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public"));
        let mut market_ids: Value = Value::new_array();
        let mut message_hashes: Value = Value::new_array();
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into(), true.into(), true.into());
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut market: Value = self.market(symbol.clone());
            market_ids.push(market.get(Value::from("base")) + Value::from("_") + market.get(Value::from("quote")));
            message_hashes.push(Value::from("ticker:") + market.get(Value::from("symbol")));
            i += 1;
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": "ticker",
            "symbols": market_ids,
            "tickTypes": Value::Json(serde_json::Value::Array(vec![self.safe_string(params.clone(), Value::from("tickTypes"), Value::from("24H")).into()]))
        }))).unwrap());
        let mut message: Value = extend_2(request.clone(), params.clone());
        let mut new_ticker: Value = self.watch_multiple(url.clone(), message_hashes.clone(), message.clone(), message_hashes.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut result: Value = Value::new_object();
            result.set(new_ticker.get(Value::from("symbol")), new_ticker.clone());
            return result.clone();
        };
        return self.filter_by_array(self.get("tickers".into()), Value::from("symbol"), symbols.clone(), Value::Undefined);
    }

    fn handle_ticker(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "type" : "ticker",
        //        "content" : {
        //            "symbol" : "BTC_KRW",           // 통화코드
        //            "tickType" : "24H",                 // 변동 기준시간- 30M, 1H, 12H, 24H, MID
        //            "date" : "20200129",                // 일자
        //            "time" : "121844",                  // 시간
        //            "openPrice" : "2302",               // 시가
        //            "closePrice" : "2317",              // 종가
        //            "lowPrice" : "2272",                // 저가
        //            "highPrice" : "2344",               // 고가
        //            "value" : "2831915078.07065789",    // 누적거래금액
        //            "volume" : "1222314.51355788",  // 누적거래량
        //            "sellVolume" : "760129.34079004",   // 매도누적거래량
        //            "buyVolume" : "462185.17276784",    // 매수누적거래량
        //            "prevClosePrice" : "2326",          // 전일종가
        //            "chgRate" : "0.65",                 // 변동률
        //            "chgAmt" : "15",                    // 변동금액
        //            "volumePower" : "60.80"         // 체결강도
        //        }
        //    }
        //
        let mut content: Value = self.safe_dict(message.clone(), Value::from("content"), Value::new_object());
        let mut market_id: Value = self.safe_string(content.clone(), Value::from("symbol"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::from("_"), Value::Undefined);
        let mut ticker: Value = <Self as Bithumb>::parse_ws_ticker(self, content.clone(), Value::Undefined);
        let mut message_hash: Value = Value::from("ticker:") + symbol.clone();
        self.get("tickers".into()).set(symbol.clone(), ticker.clone());
        client.resolve(self.get("tickers".into()).get(symbol.clone()), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        //    {
        //        "symbol" : "BTC_KRW",           // 통화코드
        //        "tickType" : "24H",                 // 변동 기준시간- 30M, 1H, 12H, 24H, MID
        //        "date" : "20200129",                // 일자
        //        "time" : "121844",                  // 시간
        //        "openPrice" : "2302",               // 시가
        //        "closePrice" : "2317",              // 종가
        //        "lowPrice" : "2272",                // 저가
        //        "highPrice" : "2344",               // 고가
        //        "value" : "2831915078.07065789",    // 누적거래금액
        //        "volume" : "1222314.51355788",  // 누적거래량
        //        "sellVolume" : "760129.34079004",   // 매도누적거래량
        //        "buyVolume" : "462185.17276784",    // 매수누적거래량
        //        "prevClosePrice" : "2326",          // 전일종가
        //        "chgRate" : "0.65",                 // 변동률
        //        "chgAmt" : "15",                    // 변동금액
        //        "volumePower" : "60.80"         // 체결강도
        //    }
        //
        let mut date: Value = self.safe_string(ticker.clone(), Value::from("date"), Value::from(""));
        let mut time: Value = self.safe_string(ticker.clone(), Value::from("time"), Value::from(""));
        let mut datetime: Value = date.slice(Value::from(0), Value::from(4)) + Value::from("-") + date.slice(Value::from(4), Value::from(6)) + Value::from("-") + date.slice(Value::from(6), Value::from(8)) + Value::from("T") + time.slice(Value::from(0), Value::from(2)) + Value::from(":") + time.slice(Value::from(2), Value::from(4)) + Value::from(":") + time.slice(Value::from(4), Value::from(6));
        let mut market_id: Value = self.safe_string(ticker.clone(), Value::from("symbol"));
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": self.safe_symbol(market_id.clone(), market.clone(), Value::from("_"), Value::Undefined),
            "timestamp": self.parse8601(datetime.clone()),
            "datetime": datetime,
            "high": self.safe_string(ticker.clone(), Value::from("highPrice")),
            "low": self.safe_string(ticker.clone(), Value::from("lowPrice")),
            "bid": Value::Undefined,
            "bidVolume": self.safe_string(ticker.clone(), Value::from("buyVolume")),
            "ask": Value::Undefined,
            "askVolume": self.safe_string(ticker.clone(), Value::from("sellVolume")),
            "vwap": Value::Undefined,
            "open": self.safe_string(ticker.clone(), Value::from("openPrice")),
            "close": self.safe_string(ticker.clone(), Value::from("closePrice")),
            "last": Value::Undefined,
            "previousClose": self.safe_string(ticker.clone(), Value::from("prevClosePrice")),
            "change": self.safe_string(ticker.clone(), Value::from("chgAmt")),
            "percentage": self.safe_string(ticker.clone(), Value::from("chgRate")),
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("volume")),
            "quoteVolume": self.safe_string(ticker.clone(), Value::from("value")),
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public"));
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut message_hash: Value = Value::from("orderbook") + Value::from(":") + symbol.clone();
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": "orderbookdepth",
            "symbols": Value::Json(serde_json::Value::Array(vec![market.get(Value::from("base")) + Value::from("_") + market.get(Value::from("quote")).into()]))
        }))).unwrap());
        let mut orderbook: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
        return orderbook.limit();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "type" : "orderbookdepth",
        //            "content" : {
        //            "list" : [
        //                {
        //                    "symbol" : "BTC_KRW",
        //                    "orderType" : "ask",        // 주문타입 – bid / ask
        //                    "price" : "10593000",       // 호가
        //                    "quantity" : "1.11223318",  // 잔량
        //                    "total" : "3"               // 건수
        //                },
        //                {"symbol" : "BTC_KRW", "orderType" : "ask", "price" : "10596000", "quantity" : "0.5495", "total" : "8"},
        //                {"symbol" : "BTC_KRW", "orderType" : "ask", "price" : "10598000", "quantity" : "18.2085", "total" : "10"},
        //                {"symbol" : "BTC_KRW", "orderType" : "bid", "price" : "10532000", "quantity" : "0", "total" : "0"},
        //                {"symbol" : "BTC_KRW", "orderType" : "bid", "price" : "10572000", "quantity" : "2.3324", "total" : "4"},
        //                {"symbol" : "BTC_KRW", "orderType" : "bid", "price" : "10571000", "quantity" : "1.469", "total" : "3"},
        //                {"symbol" : "BTC_KRW", "orderType" : "bid", "price" : "10569000", "quantity" : "0.5152", "total" : "2"}
        //            ],
        //            "datetime":1580268255864325     // 일시
        //        }
        //    }
        //
        let mut content: Value = self.safe_dict(message.clone(), Value::from("content"), Value::new_object());
        let mut list: Value = self.safe_list(content.clone(), Value::from("list"), Value::new_array());
        let mut first: Value = self.safe_dict(list.clone(), Value::from(0), Value::new_object());
        let mut market_id: Value = self.safe_string(first.clone(), Value::from("symbol"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::from("_"), Value::Undefined);
        let mut timestamp_str: Value = self.safe_string(content.clone(), Value::from("datetime"));
        let mut timestamp: Value = self.parse_to_int(timestamp_str.slice(Value::from(0), Value::from(13)));
        if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
            let mut ob: Value = self.order_book(Value::Undefined, Value::Undefined);
            ob.set("symbol".into(), symbol.clone());
            self.get("orderbooks".into()).set(symbol.clone(), ob.clone());
        };
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        <Self as Bithumb>::handle_deltas(self, orderbook.clone(), list.clone());
        orderbook.set("timestamp".into(), timestamp.clone());
        orderbook.set("datetime".into(), self.iso8601(timestamp.clone()));
        let mut message_hash: Value = Value::from("orderbook") + Value::from(":") + symbol.clone();
        client.resolve(orderbook.clone(), message_hash.clone());
        Value::Undefined
    }

    fn handle_delta(&mut self, mut orderbook: Value, mut delta: Value) -> Value {
        //
        //    {
        //        symbol: "ETH_BTC",
        //        orderType: "bid",
        //        price: "0.07349517",
        //        quantity: "0",
        //        total: "0",
        //    }
        //
        let mut side_id: Value = self.safe_string(delta.clone(), Value::from("orderType"));
        let mut side: Value = if side_id.clone() == Value::from("bid") { Value::from("bids") } else { Value::from("asks") };
        let mut bid_ask: Value = self.parse_bid_ask(delta.clone(), Value::from("price"), Value::from("quantity"), Value::Undefined);
        let mut orderbook_side: Value = orderbook.get(side.clone());
        orderbook_side.store_array(bid_ask.clone());
        Value::Undefined
    }

    fn handle_deltas(&mut self, mut orderbook: Value, mut deltas: Value) -> Value {
        let mut i: usize = 0;
        while i < deltas.len() {
            <Self as Bithumb>::handle_delta(self, orderbook.clone(), deltas.get(i.into()));
            i += 1;
        };
        Value::Undefined
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public"));
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut message_hash: Value = Value::from("trade:") + symbol.clone();
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": "transaction",
            "symbols": Value::Json(serde_json::Value::Array(vec![market.get(Value::from("base")) + Value::from("_") + market.get(Value::from("quote")).into()]))
        }))).unwrap());
        let mut trades: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "type" : "transaction",
        //        "content" : {
        //            "list" : [
        //                {
        //                    "symbol" : "BTC_KRW",
        //                    "buySellGb" : "1",
        //                    "contPrice" : "10579000",
        //                    "contQty" : "0.01",
        //                    "contAmt" : "105790.00",
        //                    "contDtm" : "2020-01-29 12:24:18.830039",
        //                    "updn" : "dn"
        //                }
        //            ]
        //        }
        //    }
        //
        let mut content: Value = self.safe_dict(message.clone(), Value::from("content"), Value::new_object());
        let mut raw_trades: Value = self.safe_list(content.clone(), Value::from("list"), Value::new_array());
        let mut i: usize = 0;
        while i < raw_trades.len() {
            let mut raw_trade: Value = raw_trades.get(i.into());
            let mut market_id: Value = self.safe_string(raw_trade.clone(), Value::from("symbol"));
            let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::from("_"), Value::Undefined);
            if !self.get("trades".into()).contains_key(symbol.clone()) {
                let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
                let mut stored: Value = ArrayCache::new(limit);
                self.get("trades".into()).set(symbol.clone(), stored.clone());
            };
            let mut trades: Value = self.get("trades".into()).get(symbol.clone());
            let mut parsed: Value = <Self as Bithumb>::parse_ws_trade(self, raw_trade.clone(), Value::Undefined);
            trades.append(parsed.clone());
            let mut message_hash: Value = Value::from("trade") + Value::from(":") + symbol.clone();
            client.resolve(trades.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    fn parse_ws_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        //    {
        //        "symbol" : "BTC_KRW",
        //        "buySellGb" : "1",
        //        "contPrice" : "10579000",
        //        "contQty" : "0.01",
        //        "contAmt" : "105790.00",
        //        "contDtm" : "2020-01-29 12:24:18.830038",
        //        "updn" : "dn"
        //    }
        //
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("symbol"));
        let mut datetime: Value = self.safe_string(trade.clone(), Value::from("contDtm"));
        // that date is not UTC iso8601, but exchange's local time, -9hr difference
        let mut timestamp: Value = self.parse8601(datetime.clone()) - Value::from(32400000);
        let mut side_id: Value = self.safe_string(trade.clone(), Value::from("buySellGb"));
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "id": Value::Undefined,
            "info": trade,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": self.safe_symbol(market_id.clone(), market.clone(), Value::from("_"), Value::Undefined),
            "order": Value::Undefined,
            "type": Value::Undefined,
            "side": if side_id.clone() == Value::from("1") { Value::from("buy") } else { Value::from("sell") },
            "takerOrMaker": Value::Undefined,
            "price": self.safe_string(trade.clone(), Value::from("contPrice")),
            "amount": self.safe_string(trade.clone(), Value::from("contQty")),
            "cost": self.safe_string(trade.clone(), Value::from("contAmt")),
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    fn handle_error_message(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "status" : "5100",
        //        "resmsg" : "Invalid Filter Syntax"
        //    }
        //
        if !message.contains_key(Value::from("status")) {
            return true.into();
        };
        let mut error_code: Value = self.safe_string(message.clone(), Value::from("status"));
                if error_code.clone() != Value::from("0000") {
            let mut msg: Value = self.safe_string(message.clone(), Value::from("resmsg"));
            panic!(r###"ExchangeError::new(self.get("id".into()) + Value::from(" ") + msg.clone())"###);
        };
        return true.into();
        // catch block omitted (no exception support in Value runtime)
;
        return true.into();
    }

    async fn watch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Bithumb>::authenticate(self, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("privateV2"));
        let mut message_hash: Value = Value::from("myAsset");
        let mut request: Value = Value::Json(serde_json::Value::Array(vec![Value::Json(normalize(&Value::Json(json!({
            "ticket": "ccxt"
        }))).unwrap()).into(), Value::Json(normalize(&Value::Json(json!({
            "type": message_hash
        }))).unwrap()).into()]));
        let mut balance: Value = self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
        return balance.clone();
    }

    fn handle_balance(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "type": "myAsset",
        //        "assets": [
        //            {
        //                "currency": "KRW",
        //                "balance": "2061832.35",
        //                "locked": "3824127.3"
        //            }
        //        ],
        //        "asset_timestamp": 1727052537592,
        //        "timestamp": 1727052537687,
        //        "stream_type": "REALTIME"
        //    }
        //
        let mut message_hash: Value = Value::from("myAsset");
        let mut assets: Value = self.safe_list(message.clone(), Value::from("assets"), Value::new_array());
        if self.get("balance".into()).is_nullish() {
            self.set("balance".into(), Value::new_object());
        };
        let mut i: usize = 0;
        while i < assets.len() {
            let mut asset: Value = assets.get(i.into());
            let mut currency_id: Value = self.safe_string(asset.clone(), Value::from("currency"));
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("free".into(), self.safe_string(asset.clone(), Value::from("balance")));
            account.set("used".into(), self.safe_string(asset.clone(), Value::from("locked")));
            self.get("balance".into()).set(code.clone(), account.clone());
            i += 1;
        };
        self.get("balance".into()).set("info".into(), message.clone());
        let mut timestamp: Value = self.safe_integer(message.clone(), Value::from("timestamp"));
        self.get("balance".into()).set("timestamp".into(), timestamp.clone());
        self.get("balance".into()).set("datetime".into(), self.iso8601(timestamp.clone()));
        self.set("balance".into(), self.safe_balance(self.get("balance".into())));
        client.resolve(self.get("balance".into()), message_hash.clone());
        Value::Undefined
    }

    async fn authenticate(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.check_required_credentials(Value::Undefined);
        let mut ws_options: Value = self.safe_dict(self.get("options".into()), Value::from("ws"), Value::new_object());
        let mut authenticated: Value = self.safe_string(ws_options.clone(), Value::from("token"));
        if authenticated.clone().is_nullish() {
            let mut payload: Value = Value::Json(normalize(&Value::Json(json!({
                "access_key": self.get("apiKey".into()),
                "nonce": self.uuid(),
                "timestamp": self.milliseconds()
            }))).unwrap());
            let mut jwt_token: Value = jwt(payload.clone(), self.encode(self.get("secret".into())), sha256.clone());
            ws_options.set("token".into(), jwt_token.clone());
            ws_options.set("options".into(), Value::Json(normalize(&Value::Json(json!({
                "headers": Value::Json(normalize(&Value::Json(json!({
                    "authorization": Value::from("Bearer ") + jwt_token.clone()
                }))).unwrap())
            }))).unwrap()));
            self.get("options".into()).set("ws".into(), ws_options.clone());
        };
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("privateV2"));
        let mut client: Value = self.client(url.clone());
        return client.clone();
    }

    async fn watch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Bithumb>::authenticate(self, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("privateV2"));
        let mut message_hash: Value = Value::from("myOrder");
        let mut codes: Value = self.safe_list(params.clone(), Value::from("codes"), Value::new_array());
        let mut request: Value = Value::Json(serde_json::Value::Array(vec![Value::Json(normalize(&Value::Json(json!({
            "ticket": "ccxt"
        }))).unwrap()).into(), Value::Json(normalize(&Value::Json(json!({
            "type": message_hash,
            "codes": codes
        }))).unwrap()).into()]));
        if symbol.clone().is_nonnullish() {
            let mut market: Value = self.market(symbol.clone());
            symbol = market.get(Value::from("symbol"));
            message_hash = message_hash.clone() + Value::from(":") + symbol.clone();
        };
        let mut orders: Value = self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = orders.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_symbol_since_limit(orders.clone(), symbol.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_orders(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "type": "myOrder",
        //        "code": "KRW-BTC",
        //        "uuid": "C0101000000001818113",
        //        "ask_bid": "BID",
        //        "order_type": "limit",
        //        "state": "trade",
        //        "trade_uuid": "C0101000000001744207",
        //        "price": 1927000,
        //        "volume": 0.4697,
        //        "remaining_volume": 0.0803,
        //        "executed_volume": 0.4697,
        //        "trades_count": 1,
        //        "reserved_fee": 0,
        //        "remaining_fee": 0,
        //        "paid_fee": 0,
        //        "executed_funds": 905111.9000,
        //        "trade_timestamp": 1727052318148,
        //        "order_timestamp": 1727052318074,
        //        "timestamp": 1727052318369,
        //        "stream_type": "REALTIME"
        //    }
        //
        let mut message_hash: Value = Value::from("myOrder");
        let mut parsed: Value = <Self as Bithumb>::parse_ws_order(self, message.clone(), Value::Undefined);
        let mut symbol: Value = self.safe_string(parsed.clone(), Value::from("symbol"));
        // const orderId = this.safeString (parsed, 'id');
        if self.get("orders".into()).is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("ordersLimit"), Value::from(1000));
            self.set("orders".into(), ArrayCacheBySymbolById::new(limit));
        };
        let mut cached_orders: Value = self.get("orders".into());
        cached_orders.append(parsed.clone());
        client.resolve(cached_orders.clone(), message_hash.clone());
        let mut symbol_specific_message_hash: Value = message_hash.clone() + Value::from(":") + symbol.clone();
        client.resolve(cached_orders.clone(), symbol_specific_message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_order(&self, mut order: Value, mut market: Value) -> Value {
        //
        //    {
        //        "type": "myOrder",
        //        "code": "KRW-BTC",
        //        "uuid": "C0101000000001818113",
        //        "ask_bid": "BID",
        //        "order_type": "limit",
        //        "state": "trade",
        //        "trade_uuid": "C0101000000001744207",
        //        "price": 1927000,
        //        "volume": 0.4697,
        //        "remaining_volume": 0.0803,
        //        "executed_volume": 0.4697,
        //        "trades_count": 1,
        //        "reserved_fee": 0,
        //        "remaining_fee": 0,
        //        "paid_fee": 0,
        //        "executed_funds": 905111.9000,
        //        "trade_timestamp": 1727052318148,
        //        "order_timestamp": 1727052318074,
        //        "timestamp": 1727052318369,
        //        "stream_type": "REALTIME"
        //    }
        //
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("code"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::from("-"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("order_timestamp"));
        let mut side_id: Value = self.safe_string(order.clone(), Value::from("ask_bid"));
        let mut side: Value = if side_id.clone() == Value::from("BID") { Value::from("buy") } else { Value::from("sell") };
        let mut type_id: Value = self.safe_string(order.clone(), Value::from("order_type"));
        let mut r#type: Value = Value::Undefined;
        if type_id.clone() == Value::from("limit") {
            r#type = Value::from("limit");
        } else if type_id.clone() == Value::from("price") {
            r#type = Value::from("market");
        } else if type_id.clone() == Value::from("market") {
            r#type = Value::from("market");
        };
        let mut state_id: Value = self.safe_string(order.clone(), Value::from("state"));
        let mut status: Value = Value::Undefined;
        if state_id.clone() == Value::from("wait") {
            status = Value::from("open");
        } else if state_id.clone() == Value::from("trade") {
            status = Value::from("open");
        } else if state_id.clone() == Value::from("done") {
            status = Value::from("closed");
        } else if state_id.clone() == Value::from("cancel") {
            status = Value::from("canceled");
        };
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"));
        let mut amount: Value = self.safe_string(order.clone(), Value::from("volume"));
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("remaining_volume"));
        let mut filled: Value = self.safe_string(order.clone(), Value::from("executed_volume"));
        let mut cost: Value = self.safe_string(order.clone(), Value::from("executed_funds"));
        let mut fee_cost: Value = self.safe_string(order.clone(), Value::from("paid_fee"));
        let mut fee: Value = Value::Undefined;
        if fee_cost.clone().is_nonnullish() {
            let mut market_for_fee: Value = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
            let mut fee_currency: Value = self.safe_string(market_for_fee.clone(), Value::from("quote"));
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost,
                "currency": fee_currency
            }))).unwrap());
        };
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": order,
            "id": self.safe_string(order.clone(), Value::from("uuid")),
            "clientOrderId": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": self.safe_integer(order.clone(), Value::from("trade_timestamp")),
            "symbol": symbol,
            "type": r#type,
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "side": side,
            "price": price,
            "stopPrice": Value::Undefined,
            "triggerPrice": Value::Undefined,
            "amount": amount,
            "cost": cost,
            "average": Value::Undefined,
            "filled": filled,
            "remaining": remaining,
            "status": status,
            "fee": fee,
            "trades": Value::Undefined
        }))).unwrap()), market.clone());
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        if !<Self as Bithumb>::handle_error_message(self, client.clone(), message.clone()).is_truthy() {
            return Value::Undefined;
        };
        let mut topic: Value = self.safe_string(message.clone(), Value::from("type"));
        if topic.clone().is_nonnullish() {
            let mut methods: Value = Value::Json(normalize(&Value::Json(json!({
                "ticker": self.get("handleTicker".into()),
                "orderbookdepth": self.get("handleOrderBook".into()),
                "transaction": self.get("handleTrades".into()),
                "myAsset": self.get("handleBalance".into()),
                "myOrder": self.get("handleOrders".into())
            }))).unwrap());
            let mut method: Value = self.safe_value(methods.clone(), topic.clone());
            if method.clone().is_nonnullish() {
                method.call(self, client.clone(), message.clone());
            };
        };
        Value::Undefined
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetTickerallquoteid" => Bithumb::request(self, "ticker/ALL_{quoteId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickerbaseidquoteid" => Bithumb::request(self, "ticker/{baseId}_{quoteId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetOrderbookallquoteid" => Bithumb::request(self, "orderbook/ALL_{quoteId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetOrderbookbaseidquoteid" => Bithumb::request(self, "orderbook/{baseId}_{quoteId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTransactionhistorybaseidquoteid" => Bithumb::request(self, "transaction_history/{baseId}_{quoteId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetNetworkinfo" => Bithumb::request(self, "network-info".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetAssetsstatusmultichainall" => Bithumb::request(self, "assetsstatus/multichain/ALL".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetAssetsstatusmultichaincurrency" => Bithumb::request(self, "assetsstatus/multichain/{currency}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetWithdrawminimumall" => Bithumb::request(self, "withdraw/minimum/ALL".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetWithdrawminimumcurrency" => Bithumb::request(self, "withdraw/minimum/{currency}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetAssetsstatusall" => Bithumb::request(self, "assetsstatus/ALL".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetAssetsstatusbaseid" => Bithumb::request(self, "assetsstatus/{baseId}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCandlestickbaseidquoteidinterval" => Bithumb::request(self, "candlestick/{baseId}_{quoteId}/{interval}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfoaccount" => Bithumb::request(self, "info/account".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfobalance" => Bithumb::request(self, "info/balance".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfowalletaddress" => Bithumb::request(self, "info/wallet_address".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfoticker" => Bithumb::request(self, "info/ticker".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfoorders" => Bithumb::request(self, "info/orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfousertransactions" => Bithumb::request(self, "info/user_transactions".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostInfoorderdetail" => Bithumb::request(self, "info/order_detail".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradeplace" => Bithumb::request(self, "trade/place".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradecancel" => Bithumb::request(self, "trade/cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradebtcwithdrawal" => Bithumb::request(self, "trade/btc_withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradekrwdeposit" => Bithumb::request(self, "trade/krw_deposit".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradekrwwithdrawal" => Bithumb::request(self, "trade/krw_withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTrademarketbuy" => Bithumb::request(self, "trade/market_buy".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTrademarketsell" => Bithumb::request(self, "trade/market_sell".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradestoplimit" => Bithumb::request(self, "trade/stop_limit".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => unimplemented!(),
                }
            },
            _ => unimplemented!()
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BithumbImpl(Value);
impl Exchange for BithumbImpl {}
impl Bithumb for BithumbImpl {}
impl ValueTrait for BithumbImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Vec<Value> { self.0.keys() }
    fn values(&self) -> Vec<Value> { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value) -> Value { self.0.slice(start) }
}

impl BithumbImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BithumbImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bithumb::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

