#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Bittrade : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bittrade",
            "name": "BitTrade",
            "countries": [
                "JP"
            ],
            "enableRateLimit": true,
            "rateLimit": 100,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "swap": false,
                "future": false,
                "option": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "cancelOrders": true,
                "createLimitOrder": true,
                "createMarketBuyOrderWithCost": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createMarketOrderWithCost": false,
                "createMarketSellOrderWithCost": false,
                "createOrder": true,
                "createStopLimitOrder": false,
                "createStopMarketOrder": false,
                "createStopOrder": false,
                "editOrder": "emulated",
                "fetchAccounts": true,
                "fetchBalance": true,
                "fetchClosedOrders": true,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDeposits": true,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingRates": false,
                "fetchIndexOHLCV": false,
                "fetchL2OrderBook": true,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenOrders": true,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchOrderTrades": true,
                "fetchPremiumIndexOHLCV": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchTime": true,
                "fetchTrades": true,
                "fetchTradingLimits": true,
                "fetchWithdrawals": true,
                "watchBalance": false,
                "watchOHLCV": true,
                "watchOrderBook": true,
                "watchTicker": true,
                "watchTickers": false,
                "watchTrades": true,
                "watchTradesForSymbols": false,
                "withdraw": true,
                "ws": true
            },
            "urls": {
                "logo": "https://user-images.githubusercontent.com/1294454/85734211-85755480-b705-11ea-8b35-0b7f1db33a2f.jpg",
                "api": {
                    "market": "https://{hostname}",
                    "public": "https://{hostname}",
                    "private": "https://{hostname}",
                    "v2Public": "https://{hostname}",
                    "v2Private": "https://{hostname}",
                    "ws": {
                        "api": {
                            "public": "wss://{hostname}/ws",
                            "private": "wss://{hostname}/ws/v2"
                        }
                    }
                },
                "www": "https://www.bittrade.co.jp",
                "doc": "https://api-doc.bittrade.co.jp",
                "fees": "https://www.bittrade.co.jp/ja-jp/support/fee",
                "referral": "https://www.bittrade.co.jp/register/?invite_code=znnq3"
            },
            "api": {
                "v2Public": {
                    "get": {
                        "reference/currencies": 1,
                        "market-status": 1
                    }
                },
                "v2Private": {
                    "get": {
                        "account/ledger": 1,
                        "account/withdraw/quota": 1,
                        "account/withdraw/address": 1,
                        "account/deposit/address": 1,
                        "account/repayment": 5,
                        "reference/transact-fee-rate": 1,
                        "account/asset-valuation": 0.2,
                        "point/account": 5,
                        "sub-user/user-list": 1,
                        "sub-user/user-state": 1,
                        "sub-user/account-list": 1,
                        "sub-user/deposit-address": 1,
                        "sub-user/query-deposit": 1,
                        "user/api-key": 1,
                        "user/uid": 1,
                        "algo-orders/opening": 1,
                        "algo-orders/history": 1,
                        "algo-orders/specific": 1,
                        "c2c/offers": 1,
                        "c2c/offer": 1,
                        "c2c/transactions": 1,
                        "c2c/repayment": 1,
                        "c2c/account": 1,
                        "etp/reference": 1,
                        "etp/transactions": 5,
                        "etp/transaction": 5,
                        "etp/rebalance": 1,
                        "etp/limit": 1
                    },
                    "post": {
                        "account/transfer": 1,
                        "account/repayment": 5,
                        "point/transfer": 5,
                        "sub-user/management": 1,
                        "sub-user/creation": 1,
                        "sub-user/tradable-market": 1,
                        "sub-user/transferability": 1,
                        "sub-user/api-key-generation": 1,
                        "sub-user/api-key-modification": 1,
                        "sub-user/api-key-deletion": 1,
                        "sub-user/deduct-mode": 1,
                        "algo-orders": 1,
                        "algo-orders/cancel-all-after": 1,
                        "algo-orders/cancellation": 1,
                        "c2c/offer": 1,
                        "c2c/cancellation": 1,
                        "c2c/cancel-all": 1,
                        "c2c/repayment": 1,
                        "c2c/transfer": 1,
                        "etp/creation": 5,
                        "etp/redemption": 5,
                        "etp/{transactId}/cancel": 10,
                        "etp/batch-cancel": 50
                    }
                },
                "market": {
                    "get": {
                        "history/kline": 1,
                        "detail/merged": 1,
                        "depth": 1,
                        "trade": 1,
                        "history/trade": 1,
                        "detail": 1,
                        "tickers": 1,
                        "etp": 1
                    }
                },
                "public": {
                    "get": {
                        "common/symbols": 1,
                        "common/currencys": 1,
                        "common/timestamp": 1,
                        "common/exchange": 1,
                        "settings/currencys": 1
                    }
                },
                "private": {
                    "get": {
                        "account/accounts": 0.2,
                        "account/accounts/{id}/balance": 0.2,
                        "account/accounts/{sub-uid}": 1,
                        "account/history": 4,
                        "cross-margin/loan-info": 1,
                        "margin/loan-info": 1,
                        "fee/fee-rate/get": 1,
                        "order/openOrders": 0.4,
                        "order/orders": 0.4,
                        "order/orders/{id}": 0.4,
                        "order/orders/{id}/matchresults": 0.4,
                        "order/orders/getClientOrder": 0.4,
                        "order/history": 1,
                        "order/matchresults": 1,
                        "query/deposit-withdraw": 1,
                        "margin/loan-orders": 0.2,
                        "margin/accounts/balance": 0.2,
                        "cross-margin/loan-orders": 1,
                        "cross-margin/accounts/balance": 1,
                        "points/actions": 1,
                        "points/orders": 1,
                        "subuser/aggregate-balance": 10,
                        "stable-coin/exchange_rate": 1,
                        "stable-coin/quote": 1
                    },
                    "post": {
                        "account/transfer": 1,
                        "futures/transfer": 1,
                        "order/batch-orders": 0.4,
                        "order/orders/place": 0.2,
                        "order/orders/submitCancelClientOrder": 0.2,
                        "order/orders/batchCancelOpenOrders": 0.4,
                        "order/orders/{id}/submitcancel": 0.2,
                        "order/orders/batchcancel": 0.4,
                        "dw/withdraw/api/create": 1,
                        "dw/withdraw-virtual/{id}/cancel": 1,
                        "dw/transfer-in/margin": 10,
                        "dw/transfer-out/margin": 10,
                        "margin/orders": 10,
                        "margin/orders/{id}/repay": 10,
                        "cross-margin/transfer-in": 1,
                        "cross-margin/transfer-out": 1,
                        "cross-margin/orders": 1,
                        "cross-margin/orders/{id}/repay": 1,
                        "stable-coin/exchange": 1,
                        "subuser/transfer": 10
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1min",
                "5m": "5min",
                "15m": "15min",
                "30m": "30min",
                "1h": "60min",
                "4h": "4hour",
                "1d": "1day",
                "1w": "1week",
                "1M": "1mon",
                "1y": "1year"
            },
            "fees": {
                "trading": {
                    "tierBased": false,
                    "percentage": true,
                    "taker": 0.002,
                    "maker": 0.002,
                    "feeSide": "get"
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "broad": {},
                "exact": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV",
                "GET": "Themis",
                "GTC": "Game.com",
                "HIT": "HitChain",
                "PNT": "Penta",
                "SBTC": "Super Bitcoin",
                "BIFI": "Bitcoin File"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36",
            "version": "v1",
            "hostname": "api-cloud.bittrade.co.jp",
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "selfTradePrevention": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 120,
                        "untilDays": 2,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchClosedOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOHLCV": {
                        "limit": 2000
                    }
                },
                "swap": {},
                "future": {}
            },
            "options": {
                "defaultNetwork": "ERC20",
                "networks": {
                    "ETH": "erc20",
                    "TRX": "trc20",
                    "HRC20": "hrc20",
                    "HECO": "hrc20",
                    "HT": "hrc20",
                    "ALGO": "algo",
                    "OMNI": ""
                },
                "fetchOrdersByStatesMethod": "private_get_order_orders",
                "fetchOpenOrdersMethod": "fetch_open_orders_v1",
                "createMarketBuyOrderRequiresPrice": true,
                "fetchMarketsMethod": "publicGetCommonSymbols",
                "fetchBalanceMethod": "privateGetAccountAccountsIdBalance",
                "createOrderMethod": "privatePostOrderOrdersPlace",
                "currencyToPrecisionRoundingMode": 0,
                "language": "en-US",
                "broker": {
                    "id": "AA03022abc"
                },
                "tradesLimit": 1000,
                "OHLCVLimit": 1000,
                "api": "api",
                "ws": {
                    "gunzip": true
                }
            }
        }"###).unwrap())
    }

    fn request_id(&mut self) -> Value {
        self.lock_id();
        let mut request_id: Value = self.sum(self.safe_integer(self.get("options".into()), Value::from("requestId"), Value::from(0)), Value::from(1));
        self.get("options".into()).set("requestId".into(), request_id.clone());
        self.unlock_id();
        return request_id.to_string();
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        // only supports a limit of 150 at this time
        let mut message_hash: Value = Value::from("market.") + market.get(Value::from("id")) + Value::from(".detail");
        let mut api: Value = self.safe_string(self.get("options".into()), Value::from("api"), Value::from("api"));
        let mut hostname: Value = Value::Json(normalize(&Value::Json(json!({
            "hostname": self.get("hostname".into())
        }))).unwrap());
        let mut url: Value = self.implode_params(self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(api.clone()).get(Value::from("public")), hostname.clone());
        let mut request_id: Value = <Self as Bittrade>::request_id(self);
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "sub": message_hash,
            "id": request_id
        }))).unwrap());
        let mut subscription: Value = Value::Json(normalize(&Value::Json(json!({
            "id": request_id,
            "messageHash": message_hash,
            "symbol": symbol,
            "params": params
        }))).unwrap());
        return self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), subscription.clone()).await;
    }

    fn handle_ticker(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "ch": "market.btcusdt.detail",
        //         "ts": 1583494163784,
        //         "tick": {
        //             "id": 209988464418,
        //             "low": 8988,
        //             "high": 9155.41,
        //             "open": 9078.91,
        //             "close": 9136.46,
        //             "vol": 237813910.5928412,
        //             "amount": 26184.202558551195,
        //             "version": 209988464418,
        //             "count": 265673
        //         }
        //     }
        //
        let mut tick: Value = self.safe_value(message.clone(), Value::from("tick"), Value::new_object());
        let mut ch: Value = self.safe_string(message.clone(), Value::from("ch"), Value::Undefined);
        let mut parts: Value = ch.split(Value::from("."));
        let mut market_id: Value = self.safe_string(parts.clone(), Value::from(1), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut ticker: Value = self.parse_ticker(tick.clone(), market.clone());
        let mut timestamp: Value = self.safe_value(message.clone(), Value::from("ts"), Value::Undefined);
        ticker.set("timestamp".into(), timestamp.clone());
        ticker.set("datetime".into(), self.iso8601(timestamp.clone()));
        let mut symbol: Value = ticker.get(Value::from("symbol"));
        self.get("tickers".into()).set(symbol.clone(), ticker.clone());
        client.resolve(ticker.clone(), ch.clone());
        return message.clone();
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        // only supports a limit of 150 at this time
        let mut message_hash: Value = Value::from("market.") + market.get(Value::from("id")) + Value::from(".trade.detail");
        let mut api: Value = self.safe_string(self.get("options".into()), Value::from("api"), Value::from("api"));
        let mut hostname: Value = Value::Json(normalize(&Value::Json(json!({
            "hostname": self.get("hostname".into())
        }))).unwrap());
        let mut url: Value = self.implode_params(self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(api.clone()).get(Value::from("public")), hostname.clone());
        let mut request_id: Value = <Self as Bittrade>::request_id(self);
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "sub": message_hash,
            "id": request_id
        }))).unwrap());
        let mut subscription: Value = Value::Json(normalize(&Value::Json(json!({
            "id": request_id,
            "messageHash": message_hash,
            "symbol": symbol,
            "params": params
        }))).unwrap());
        let mut trades: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), subscription.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "ch": "market.btcusdt.trade.detail",
        //         "ts": 1583495834011,
        //         "tick": {
        //             "id": 105004645372,
        //             "ts": 1583495833751,
        //             "data": [
        //                 {
        //                     "id": 1.050046453727319e+22,
        //                     "ts": 1583495833751,
        //                     "tradeId": 102090727790,
        //                     "amount": 0.003893,
        //                     "price": 9150.01,
        //                     "direction": "sell"
        //                 }
        //             ]
        //         }
        //     }
        //
        let mut tick: Value = self.safe_value(message.clone(), Value::from("tick"), Value::new_object());
        let mut data: Value = self.safe_value(tick.clone(), Value::from("data"), Value::new_object());
        let mut ch: Value = self.safe_string(message.clone(), Value::from("ch"), Value::Undefined);
        let mut parts: Value = ch.split(Value::from("."));
        let mut market_id: Value = self.safe_string(parts.clone(), Value::from(1), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut trades_cache: Value = self.safe_value(self.get("trades".into()), symbol.clone(), Value::Undefined);
        if trades_cache.clone().is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            trades_cache = ArrayCache::new(limit);
            self.get("trades".into()).set(symbol.clone(), trades_cache.clone());
        };
        let mut i: usize = 0;
        while i < data.len() {
            let mut trade: Value = self.parse_trade(data.get(i.into()), market.clone());
            trades_cache.append(trade.clone());
            i += 1;
        };
        client.resolve(trades_cache.clone(), ch.clone());
        return message.clone();
    }

    async fn watch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        timeframe = timeframe.or_default(Value::from("1m"));
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut interval: Value = self.safe_string(self.get("timeframes".into()), timeframe.clone(), timeframe.clone());
        let mut message_hash: Value = Value::from("market.") + market.get(Value::from("id")) + Value::from(".kline.") + interval.clone();
        let mut api: Value = self.safe_string(self.get("options".into()), Value::from("api"), Value::from("api"));
        let mut hostname: Value = Value::Json(normalize(&Value::Json(json!({
            "hostname": self.get("hostname".into())
        }))).unwrap());
        let mut url: Value = self.implode_params(self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(api.clone()).get(Value::from("public")), hostname.clone());
        let mut request_id: Value = <Self as Bittrade>::request_id(self);
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "sub": message_hash,
            "id": request_id
        }))).unwrap());
        let mut subscription: Value = Value::Json(normalize(&Value::Json(json!({
            "id": request_id,
            "messageHash": message_hash,
            "symbol": symbol,
            "timeframe": timeframe,
            "params": params
        }))).unwrap());
        let mut ohlcv: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), subscription.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = ohlcv.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(ohlcv.clone(), since.clone(), limit.clone(), Value::from(0), true.into());
    }

    fn handle_ohlcv(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "ch": "market.btcusdt.kline.1min",
        //         "ts": 1583501786794,
        //         "tick": {
        //             "id": 1583501760,
        //             "open": 9094.5,
        //             "close": 9094.51,
        //             "low": 9094.5,
        //             "high": 9094.51,
        //             "amount": 0.44639786263800907,
        //             "vol": 4059.76919054,
        //             "count": 16
        //         }
        //     }
        //
        let mut ch: Value = self.safe_string(message.clone(), Value::from("ch"), Value::Undefined);
        let mut parts: Value = ch.split(Value::from("."));
        let mut market_id: Value = self.safe_string(parts.clone(), Value::from(1), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut interval: Value = self.safe_string(parts.clone(), Value::from(3), Value::Undefined);
        let mut timeframe: Value = self.find_timeframe(interval.clone());
        self.get("ohlcvs".into()).set(symbol.clone(), self.safe_value(self.get("ohlcvs".into()), symbol.clone(), Value::new_object()));
        let mut stored: Value = self.safe_value(self.get("ohlcvs".into()).get(symbol.clone()), timeframe.clone(), Value::Undefined);
        if stored.clone().is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("OHLCVLimit"), Value::from(1000));
            stored = ArrayCacheByTimestamp::new(limit);
            self.get("ohlcvs".into()).get(symbol.clone()).set(timeframe.clone(), stored.clone());
        };
        let mut tick: Value = self.safe_value(message.clone(), Value::from("tick"), Value::Undefined);
        let mut parsed: Value = self.parse_ohlcv(tick.clone(), market.clone());
        stored.append(parsed.clone());
        client.resolve(stored.clone(), ch.clone());
        Value::Undefined
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if limit.clone().is_nonnullish() && limit.clone() != Value::from(150) {
            panic!(r###"ExchangeError::new(self.get("id".into()) + Value::from(" watchOrderBook accepts limit = 150 only"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        // only supports a limit of 150 at this time
        limit = if limit.clone().is_nullish() { Value::from(150) } else { limit.clone() };
        let mut message_hash: Value = Value::from("market.") + market.get(Value::from("id")) + Value::from(".mbp.") + limit.to_string();
        let mut api: Value = self.safe_string(self.get("options".into()), Value::from("api"), Value::from("api"));
        let mut hostname: Value = Value::Json(normalize(&Value::Json(json!({
            "hostname": self.get("hostname".into())
        }))).unwrap());
        let mut url: Value = self.implode_params(self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(api.clone()).get(Value::from("public")), hostname.clone());
        let mut request_id: Value = <Self as Bittrade>::request_id(self);
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "sub": message_hash,
            "id": request_id
        }))).unwrap());
        let mut subscription: Value = Value::Json(normalize(&Value::Json(json!({
            "id": request_id,
            "messageHash": message_hash,
            "symbol": symbol,
            "limit": limit,
            "params": params,
            "method": self.get("handleOrderBookSubscription".into())
        }))).unwrap());
        let mut orderbook: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), subscription.clone()).await;
        return orderbook.limit();
    }

    fn handle_order_book_snapshot(&mut self, mut client: Value, mut message: Value, mut subscription: Value) -> Value {
        //
        //     {
        //         "id": 1583473663565,
        //         "rep": "market.btcusdt.mbp.150",
        //         "status": "ok",
        //         "data": {
        //             "seqNum": 104999417756,
        //             "bids": [
        //                 [9058.27, 0],
        //                 [9058.43, 0],
        //                 [9058.99, 0],
        //             ],
        //             "asks": [
        //                 [9084.27, 0.2],
        //                 [9085.69, 0],
        //                 [9085.81, 0],
        //             ]
        //         }
        //     }
        //
        let mut symbol: Value = self.safe_string(subscription.clone(), Value::from("symbol"), Value::Undefined);
        let mut message_hash: Value = self.safe_string(subscription.clone(), Value::from("messageHash"), Value::Undefined);
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        let mut data: Value = self.safe_value(message.clone(), Value::from("data"), Value::Undefined);
        let mut snapshot: Value = self.parse_order_book(data.clone(), symbol.clone(), Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined);
        snapshot.set("nonce".into(), self.safe_integer(data.clone(), Value::from("seqNum"), Value::Undefined));
        orderbook.reset(snapshot.clone());
        // unroll the accumulated deltas
        let mut messages: Value = orderbook.get(cache.clone());
        let mut i: usize = 0;
        while i < messages.len() {
            <Self as Bittrade>::handle_order_book_message(self, client.clone(), messages.get(i.into()), orderbook.clone());
            i += 1;
        };
        self.get("orderbooks".into()).set(symbol.clone(), orderbook.clone());
        client.resolve(orderbook.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn watch_order_book_snapshot(&mut self, mut client: Value, mut message: Value, mut subscription: Value) -> Value {
        let mut message_hash: Value = self.safe_string(subscription.clone(), Value::from("messageHash"), Value::Undefined);
                let mut symbol: Value = self.safe_string(subscription.clone(), Value::from("symbol"), Value::Undefined);
        let mut limit: Value = self.safe_integer(subscription.clone(), Value::from("limit"), Value::Undefined);
        let mut params: Value = self.safe_value(subscription.clone(), Value::from("params"), Value::Undefined);
        let mut api: Value = self.safe_string(self.get("options".into()), Value::from("api"), Value::from("api"));
        let mut hostname: Value = Value::Json(normalize(&Value::Json(json!({
            "hostname": self.get("hostname".into())
        }))).unwrap());
        let mut url: Value = self.implode_params(self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(api.clone()).get(Value::from("public")), hostname.clone());
        let mut request_id: Value = <Self as Bittrade>::request_id(self);
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "req": message_hash,
            "id": request_id
        }))).unwrap());
        let mut snapshot_subscription: Value = Value::Json(normalize(&Value::Json(json!({
            "id": request_id,
            "messageHash": message_hash,
            "symbol": symbol,
            "limit": limit,
            "params": params,
            "method": self.get("handleOrderBookSnapshot".into())
        }))).unwrap());
        let mut orderbook: Value = self.watch(url.clone(), request_id.clone(), request.clone(), request_id.clone(), snapshot_subscription.clone()).await;
        return orderbook.limit();
        // catch block omitted (no exception support in Value runtime)
;
        // this is a temporary subscription by a specific requestId
        // it has a very short lifetime until the snapshot is received over ws
        return Value::Undefined;
    }

    fn handle_delta(&mut self, mut bookside: Value, mut delta: Value) -> Value {
        let mut price: Value = self.safe_float(delta.clone(), Value::from(0), Value::Undefined);
        let mut amount: Value = self.safe_float(delta.clone(), Value::from(1), Value::Undefined);
        bookside.store(price.clone(), amount.clone());
        Value::Undefined
    }

    fn handle_deltas(&mut self, mut bookside: Value, mut deltas: Value) -> Value {
        let mut i: usize = 0;
        while i < deltas.len() {
            <Self as Bittrade>::handle_delta(self, bookside.clone(), deltas.get(i.into()));
            i += 1;
        };
        Value::Undefined
    }

    fn handle_order_book_message(&mut self, mut client: Value, mut message: Value, mut orderbook: Value) -> Value {
        //
        //     {
        //         "ch": "market.btcusdt.mbp.150",
        //         "ts": 1583472025885,
        //         "tick": {
        //             "seqNum": 104998984994,
        //             "prevSeqNum": 104998984977,
        //             "bids": [
        //                 [9058.27, 0],
        //                 [9058.43, 0],
        //                 [9058.99, 0],
        //             ],
        //             "asks": [
        //                 [9084.27, 0.2],
        //                 [9085.69, 0],
        //                 [9085.81, 0],
        //             ]
        //         }
        //     }
        //
        let mut tick: Value = self.safe_value(message.clone(), Value::from("tick"), Value::new_object());
        let mut seq_num: Value = self.safe_integer(tick.clone(), Value::from("seqNum"), Value::Undefined);
        let mut prev_seq_num: Value = self.safe_integer(tick.clone(), Value::from("prevSeqNum"), Value::Undefined);
        if prev_seq_num.clone() <= orderbook.get(Value::from("nonce")) && seq_num.clone() > orderbook.get(Value::from("nonce")) {
            let mut asks: Value = self.safe_value(tick.clone(), Value::from("asks"), Value::new_array());
            let mut bids: Value = self.safe_value(tick.clone(), Value::from("bids"), Value::new_array());
            <Self as Bittrade>::handle_deltas(self, orderbook.get(Value::from("asks")), asks.clone());
            <Self as Bittrade>::handle_deltas(self, orderbook.get(Value::from("bids")), bids.clone());
            orderbook.set("nonce".into(), seq_num.clone());
            let mut timestamp: Value = self.safe_integer(message.clone(), Value::from("ts"), Value::Undefined);
            orderbook.set("timestamp".into(), timestamp.clone());
            orderbook.set("datetime".into(), self.iso8601(timestamp.clone()));
        };
        return orderbook.clone();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // deltas
        //
        //     {
        //         "ch": "market.btcusdt.mbp.150",
        //         "ts": 1583472025885,
        //         "tick": {
        //             "seqNum": 104998984994,
        //             "prevSeqNum": 104998984977,
        //             "bids": [
        //                 [9058.27, 0],
        //                 [9058.43, 0],
        //                 [9058.99, 0],
        //             ],
        //             "asks": [
        //                 [9084.27, 0.2],
        //                 [9085.69, 0],
        //                 [9085.81, 0],
        //             ]
        //         }
        //     }
        //
        let mut message_hash: Value = self.safe_string(message.clone(), Value::from("ch"), Value::Undefined);
        let mut ch: Value = self.safe_value(message.clone(), Value::from("ch"), Value::Undefined);
        let mut parts: Value = ch.split(Value::from("."));
        let mut market_id: Value = self.safe_string(parts.clone(), Value::from(1), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        if orderbook.get(Value::from("nonce")).is_nullish() {
            orderbook.get(cache.clone()).push(message.clone());
        } else {
            <Self as Bittrade>::handle_order_book_message(self, client.clone(), message.clone(), orderbook.clone());
            client.resolve(orderbook.clone(), message_hash.clone());
        };
        Value::Undefined
    }

    fn handle_order_book_subscription(&mut self, mut client: Value, mut message: Value, mut subscription: Value) -> Value {
        let mut symbol: Value = self.safe_string(subscription.clone(), Value::from("symbol"), Value::Undefined);
        let mut limit: Value = self.safe_integer(subscription.clone(), Value::from("limit"), Value::Undefined);
        if self.get("orderbooks".into()).contains_key(symbol.clone()) {
            self.get("orderbooks".into()).get(symbol.clone());
        };
        self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::new_object(), limit.clone()));
        // watch the snapshot in a separate async call
        self.spawn(self.get("watchOrderBookSnapshot".into()), client.clone(), message.clone(), subscription.clone());
        Value::Undefined
    }

    fn handle_subscription_status(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "id": 1583414227,
        //         "status": "ok",
        //         "subbed": "market.btcusdt.mbp.150",
        //         "ts": 1583414229143
        //     }
        //
        let mut id: Value = self.safe_string(message.clone(), Value::from("id"), Value::Undefined);
        let mut subscriptions_by_id: Value = self.index_by(client.get(subscriptions.clone()), Value::from("id"));
        let mut subscription: Value = self.safe_value(subscriptions_by_id.clone(), id.clone(), Value::Undefined);
        if subscription.clone().is_nonnullish() {
            let mut method: Value = self.safe_value(subscription.clone(), Value::from("method"), Value::Undefined);
            if method.clone().is_nonnullish() {
                return method.call(self, client.clone(), message.clone(), subscription.clone());
            };
            // clean up
            if client.get(subscriptions.clone()).contains_key(id.clone()) {
                client.get(subscriptions.clone()).get(id.clone());
            };
        };
        return message.clone();
    }

    fn handle_system_status(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // todo: answer the question whether handleSystemStatus should be renamed
        // and unified as handleStatus for any usage pattern that
        // involves system status and maintenance updates
        //
        //     {
        //         "id": "1578090234088", // connectId
        //         "type": "welcome",
        //     }
        //
        return message.clone();
    }

    fn handle_subject(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "ch": "market.btcusdt.mbp.150",
        //         "ts": 1583472025885,
        //         "tick": {
        //             "seqNum": 104998984994,
        //             "prevSeqNum": 104998984977,
        //             "bids": [
        //                 [9058.27, 0],
        //                 [9058.43, 0],
        //                 [9058.99, 0],
        //             ],
        //             "asks": [
        //                 [9084.27, 0.2],
        //                 [9085.69, 0],
        //                 [9085.81, 0],
        //             ]
        //         }
        //     }
        //
        let mut ch: Value = self.safe_value(message.clone(), Value::from("ch"), Value::Undefined);
        let mut parts: Value = ch.split(Value::from("."));
        let mut r#type: Value = self.safe_string(parts.clone(), Value::from(0), Value::Undefined);
        if r#type.clone() == Value::from("market") {
            let mut method_name: Value = self.safe_string(parts.clone(), Value::from(2), Value::Undefined);
            let mut methods: Value = Value::Json(normalize(&Value::Json(json!({
                "mbp": self.get("handleOrderBook".into()),
                "detail": self.get("handleTicker".into()),
                "trade": self.get("handleTrades".into()),
                "kline": self.get("handleOHLCV".into())
            }))).unwrap());
            // ...
            let mut method: Value = self.safe_value(methods.clone(), method_name.clone(), Value::Undefined);
            if method.clone().is_nonnullish() {
                method.call(self, client.clone(), message.clone());
            };
        };
        Value::Undefined
    }

    async fn pong(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     { ping: 1583491673714 }
        //
        client.send(Value::Json(normalize(&Value::Json(json!({
            "pong": self.safe_integer(message.clone(), Value::from("ping"), Value::Undefined)
        }))).unwrap())).await;
        Value::Undefined
    }

    fn handle_ping(&mut self, mut client: Value, mut message: Value) -> Value {
        self.spawn(self.get("pong".into()), client.clone(), message.clone());
        Value::Undefined
    }

    fn handle_error_message(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "ts": 1586323747018,
        //         "status": "error",
        //         'err-code': "bad-request",
        //         'err-msg': "invalid mbp.150.symbol linkusdt",
        //         "id": "2"
        //     }
        //
        let mut status: Value = self.safe_string(message.clone(), Value::from("status"), Value::Undefined);
        if status.clone() == Value::from("error") {
            let mut id: Value = self.safe_string(message.clone(), Value::from("id"), Value::Undefined);
            let mut subscriptions_by_id: Value = self.index_by(client.get(subscriptions.clone()), Value::from("id"));
            let mut subscription: Value = self.safe_value(subscriptions_by_id.clone(), id.clone(), Value::Undefined);
            if subscription.clone().is_nonnullish() {
                let mut error_code: Value = self.safe_string(message.clone(), Value::from("err-code"), Value::Undefined);
                                self.throw_exactly_matched_exception(self.get("exceptions".into()).get(Value::from("exact")), error_code.clone(), self.json(message.clone()));
                // catch block omitted (no exception support in Value runtime)
;
            };
            return false.into();
        };
        return message.clone();
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        if <Self as Bittrade>::handle_error_message(self, client.clone(), message.clone()).is_truthy() {
            //
            //     {"id":1583414227,"status":"ok","subbed":"market.btcusdt.mbp.150","ts":1583414229143}
            //
            //           ________________________
            //
            // sometimes bittrade responds with half of a JSON response like
            //
            //     " {"ch":"market.ethbtc.m "
            //
            // this is passed to handleMessage as a string since it failed to be decoded as JSON
            //
            if self.safe_string(message.clone(), Value::from("id"), Value::Undefined).is_nonnullish() {
                <Self as Bittrade>::handle_subscription_status(self, client.clone(), message.clone());
            } else if self.safe_string(message.clone(), Value::from("ch"), Value::Undefined).is_nonnullish() {
                // route by channel aka topic aka subject
                <Self as Bittrade>::handle_subject(self, client.clone(), message.clone());
            } else if self.safe_string(message.clone(), Value::from("ping"), Value::Undefined).is_nonnullish() {
                <Self as Bittrade>::handle_ping(self, client.clone(), message.clone());
            };
        };
        Value::Undefined
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "v2publicGetReferencecurrencies" => self.request("reference/currencies".into(), "v2Public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2publicGetMarketstatus" => self.request("market-status".into(), "v2Public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountledger" => self.request("account/ledger".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountwithdrawquota" => self.request("account/withdraw/quota".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountwithdrawaddress" => self.request("account/withdraw/address".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountdepositaddress" => self.request("account/deposit/address".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountrepayment" => self.request("account/repayment".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetReferencetransactfeerate" => self.request("reference/transact-fee-rate".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAccountassetvaluation" => self.request("account/asset-valuation".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetPointaccount" => self.request("point/account".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetSubuseruserlist" => self.request("sub-user/user-list".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetSubuseruserstate" => self.request("sub-user/user-state".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetSubuseraccountlist" => self.request("sub-user/account-list".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetSubuserdepositaddress" => self.request("sub-user/deposit-address".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetSubuserquerydeposit" => self.request("sub-user/query-deposit".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetUserapikey" => self.request("user/api-key".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetUseruid" => self.request("user/uid".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAlgoordersopening" => self.request("algo-orders/opening".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAlgoordershistory" => self.request("algo-orders/history".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetAlgoordersspecific" => self.request("algo-orders/specific".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetC2coffers" => self.request("c2c/offers".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetC2coffer" => self.request("c2c/offer".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetC2ctransactions" => self.request("c2c/transactions".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetC2crepayment" => self.request("c2c/repayment".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetC2caccount" => self.request("c2c/account".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetEtpreference" => self.request("etp/reference".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetEtptransactions" => self.request("etp/transactions".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetEtptransaction" => self.request("etp/transaction".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetEtprebalance" => self.request("etp/rebalance".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privateGetEtplimit" => self.request("etp/limit".into(), "v2Private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostAccounttransfer" => self.request("account/transfer".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostAccountrepayment" => self.request("account/repayment".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostPointtransfer" => self.request("point/transfer".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubusermanagement" => self.request("sub-user/management".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubusercreation" => self.request("sub-user/creation".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubusertradablemarket" => self.request("sub-user/tradable-market".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubusertransferability" => self.request("sub-user/transferability".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubuserapikeygeneration" => self.request("sub-user/api-key-generation".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubuserapikeymodification" => self.request("sub-user/api-key-modification".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubuserapikeydeletion" => self.request("sub-user/api-key-deletion".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostSubuserdeductmode" => self.request("sub-user/deduct-mode".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostAlgoorders" => self.request("algo-orders".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostAlgoorderscancelallafter" => self.request("algo-orders/cancel-all-after".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostAlgoorderscancellation" => self.request("algo-orders/cancellation".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostC2coffer" => self.request("c2c/offer".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostC2ccancellation" => self.request("c2c/cancellation".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostC2ccancelall" => self.request("c2c/cancel-all".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostC2crepayment" => self.request("c2c/repayment".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostC2ctransfer" => self.request("c2c/transfer".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostEtpcreation" => self.request("etp/creation".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostEtpredemption" => self.request("etp/redemption".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostEtptransactidcancel" => self.request("etp/{transactId}/cancel".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v2privatePostEtpbatchcancel" => self.request("etp/batch-cancel".into(), "v2Private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetHistorykline" => self.request("history/kline".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetDetailmerged" => self.request("detail/merged".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetDepth" => self.request("depth".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetTrade" => self.request("trade".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetHistorytrade" => self.request("history/trade".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetDetail" => self.request("detail".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetTickers" => self.request("tickers".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketGetEtp" => self.request("etp".into(), "market".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCommonsymbols" => self.request("common/symbols".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCommoncurrencys" => self.request("common/currencys".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCommontimestamp" => self.request("common/timestamp".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCommonexchange" => self.request("common/exchange".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetSettingscurrencys" => self.request("settings/currencys".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountaccounts" => self.request("account/accounts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountaccountsidbalance" => self.request("account/accounts/{id}/balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountaccountssubuid" => self.request("account/accounts/{sub-uid}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccounthistory" => self.request("account/history".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetCrossmarginloaninfo" => self.request("cross-margin/loan-info".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetMarginloaninfo" => self.request("margin/loan-info".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetFeefeerateget" => self.request("fee/fee-rate/get".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderopenorders" => self.request("order/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderorders" => self.request("order/orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderordersid" => self.request("order/orders/{id}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderordersidmatchresults" => self.request("order/orders/{id}/matchresults".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderordersgetclientorder" => self.request("order/orders/getClientOrder".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderhistory" => self.request("order/history".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrdermatchresults" => self.request("order/matchresults".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetQuerydepositwithdraw" => self.request("query/deposit-withdraw".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetMarginloanorders" => self.request("margin/loan-orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetMarginaccountsbalance" => self.request("margin/accounts/balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetCrossmarginloanorders" => self.request("cross-margin/loan-orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetCrossmarginaccountsbalance" => self.request("cross-margin/accounts/balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetPointsactions" => self.request("points/actions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetPointsorders" => self.request("points/orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetSubuseraggregatebalance" => self.request("subuser/aggregate-balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetStablecoinexchangerate" => self.request("stable-coin/exchange_rate".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetStablecoinquote" => self.request("stable-coin/quote".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAccounttransfer" => self.request("account/transfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostFuturestransfer" => self.request("futures/transfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderbatchorders" => self.request("order/batch-orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderordersplace" => self.request("order/orders/place".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderorderssubmitcancelclientorder" => self.request("order/orders/submitCancelClientOrder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderordersbatchcancelopenorders" => self.request("order/orders/batchCancelOpenOrders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderordersidsubmitcancel" => self.request("order/orders/{id}/submitcancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderordersbatchcancel" => self.request("order/orders/batchcancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostDwwithdrawapicreate" => self.request("dw/withdraw/api/create".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostDwwithdrawvirtualidcancel" => self.request("dw/withdraw-virtual/{id}/cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostDwtransferinmargin" => self.request("dw/transfer-in/margin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostDwtransferoutmargin" => self.request("dw/transfer-out/margin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostMarginorders" => self.request("margin/orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostMarginordersidrepay" => self.request("margin/orders/{id}/repay".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCrossmargintransferin" => self.request("cross-margin/transfer-in".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCrossmargintransferout" => self.request("cross-margin/transfer-out".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCrossmarginorders" => self.request("cross-margin/orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCrossmarginordersidrepay" => self.request("cross-margin/orders/{id}/repay".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostStablecoinexchange" => self.request("stable-coin/exchange".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostSubusertransfer" => self.request("subuser/transfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BittradeImpl(Value);
impl Exchange for BittradeImpl {}
impl Bittrade for BittradeImpl {}
impl ValueTrait for BittradeImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BittradeImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BittradeImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bittrade::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

