#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, JSON, Array, Object, Math, parse_int, shift_2, extend_2, normalize};

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Bullish : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bullish",
            "name": "Bullish",
            "countries": [
                "DE"
            ],
            "enableRateLimit": true,
            "rateLimit": 20,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowMargin": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "cancelOrders": false,
                "createDepositAddress": false,
                "createLimitBuyOrder": true,
                "createLimitOrder": true,
                "createLimitSellOrder": true,
                "createMarketBuyOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createMarketSellOrder": true,
                "createOrder": true,
                "createPostOnlyOrder": true,
                "createTriggerOrder": true,
                "deposit": false,
                "editOrder": true,
                "fetchAccounts": true,
                "fetchBalance": true,
                "fetchBidsAsks": false,
                "fetchBorrowInterest": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": true,
                "fetchCanceledAndClosedOrders": true,
                "fetchCanceledOrders": true,
                "fetchClosedOrder": false,
                "fetchClosedOrders": true,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDeposit": false,
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDeposits": false,
                "fetchDepositsWithdrawals": true,
                "fetchDepositWithdrawFee": false,
                "fetchDepositWithdrawFees": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": true,
                "fetchFundingRates": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchL2OrderBook": true,
                "fetchL3OrderBook": false,
                "fetchLedger": false,
                "fetchLeverage": false,
                "fetchLeverageTiers": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrder": false,
                "fetchOpenOrders": true,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrderBooks": false,
                "fetchOrders": true,
                "fetchOrderTrades": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": true,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchStatus": false,
                "fetchTicker": true,
                "fetchTickers": false,
                "fetchTime": true,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": false,
                "fetchTradingLimits": false,
                "fetchTransactionFee": false,
                "fetchTransactionFees": false,
                "fetchTransactions": false,
                "fetchTransfers": true,
                "fetchWithdrawal": false,
                "fetchWithdrawals": false,
                "fetchWithdrawalWhitelist": false,
                "reduceMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "signIn": true,
                "transfer": true,
                "watchBalance": true,
                "watchMyTrades": true,
                "watchOHLCV": false,
                "watchOrderBook": true,
                "watchOrders": true,
                "watchPositions": true,
                "watchTicker": true,
                "watchTickers": false,
                "watchTrades": true,
                "withdraw": true,
                "ws": true,
                "repayMargin": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/68f0686b-84f0-4da9-a751-f7089af3a9ed",
                "api": {
                    "public": "https://api.exchange.bullish.com/trading-api",
                    "private": "https://api.exchange.bullish.com/trading-api",
                    "ws": {
                        "public": "wss://api.exchange.bullish.com",
                        "private": "wss://api.exchange.bullish.com/trading-api/v1/private-data"
                    }
                },
                "www": "https://bullish.com/",
                "doc": [
                    "https://api.exchange.bullish.com/docs/api/rest/"
                ],
                "test": {
                    "public": "https://api.simnext.bullish-test.com/trading-api",
                    "private": "https://api.simnext.bullish-test.com/trading-api",
                    "ws": {
                        "public": "wss://api.simnext.bullish-test.com",
                        "private": "wss://api.simnext.bullish-test.com/trading-api/v1/private-data"
                    }
                },
                "referral": ""
            },
            "api": {
                "public": {
                    "get": {
                        "v1/nonce": 1,
                        "v1/time": 1,
                        "v1/assets": 1,
                        "v1/assets/{symbol}": 1,
                        "v1/markets": 1,
                        "v1/markets/{symbol}": 1,
                        "v1/history/markets/{symbol}": 1,
                        "v1/markets/{symbol}/orderbook/hybrid": 1,
                        "v1/markets/{symbol}/trades": 1,
                        "v1/markets/{symbol}/tick": 1,
                        "v1/markets/{symbol}/candle": 1,
                        "v1/history/markets/{symbol}/trades": 1,
                        "v1/history/markets/{symbol}/funding-rate": 1,
                        "v1/index-prices": 1,
                        "v1/index-prices/{assetSymbol}": 1,
                        "v1/expiry-prices/{symbol}": 1,
                        "v1/option-ladder": 1,
                        "v1/option-ladder/{symbol}": 1
                    }
                },
                "private": {
                    "get": {
                        "v2/orders": 1,
                        "v2/history/orders": 1,
                        "v2/orders/{orderId}": 1,
                        "v2/amm-instructions": 1,
                        "v2/amm-instructions/{instructionId}": 1,
                        "v1/wallets/transactions": 1,
                        "v1/wallets/limits/{symbol}": 1,
                        "v1/wallets/deposit-instructions/crypto/{symbol}": 1,
                        "v1/wallets/withdrawal-instructions/crypto/{symbol}": 1,
                        "v1/wallets/deposit-instructions/fiat/{symbol}": 1,
                        "v1/wallets/withdrawal-instructions/fiat/{symbol}": 1,
                        "v1/wallets/self-hosted/verification-attempts": 1,
                        "v1/trades": 5,
                        "v1/history/trades": 5,
                        "v1/trades/{tradeId}": 5,
                        "v1/trades/client-order-id/{clientOrderId}": 1,
                        "v1/accounts/asset": 1,
                        "v1/accounts/asset/{symbol}": 1,
                        "v1/users/logout": 1,
                        "v1/users/hmac/login": 1,
                        "v1/accounts/trading-accounts": 1,
                        "v1/accounts/trading-accounts/{tradingAccountId}": 1,
                        "v1/derivatives-positions": 1,
                        "v1/history/derivatives-settlement": 1,
                        "v1/history/transfer": 1,
                        "v1/history/borrow-interest": 1,
                        "v2/mmp-configuration": 1,
                        "v2/otc-trades": 1,
                        "v2/otc-trades/{otcTradeId}": 1,
                        "v2/otc-trades/unconfirmed-trade": 1
                    },
                    "post": {
                        "v2/orders": 5,
                        "v2/command": 5,
                        "v2/amm-instructions": 1,
                        "v1/wallets/withdrawal": 1,
                        "v2/users/login": 1,
                        "v1/simulate-portfolio-margin": 1,
                        "v1/wallets/self-hosted/initiate": 1,
                        "v2/mmp-configuration": 1,
                        "v2/otc-trades": 1,
                        "v2/otc-command": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1m",
                "5m": "5m",
                "30m": "30m",
                "1h": "1h",
                "6h": "6h",
                "12h": "12h",
                "1d": "1d"
            },
            "fees": {
                "trading": {
                    "tierBased": false,
                    "percentage": true,
                    "taker": 0.001,
                    "maker": 0.001
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v3",
            "options": {
                "timeDifference": 0,
                "adjustForTimeDifference": false,
                "networks": {
                    "BTC": "BTC",
                    "EOS": "EOS",
                    "ERC20": "ETH"
                },
                "defaultNetwork": "ERC20",
                "defaultNetworks": {
                    "USDC": "ERC20"
                },
                "ws": {
                    "cookies": {}
                }
            },
            "features": {
                "default": {
                    "sandbox": true,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": false,
                        "marketBuyRequiresPrice": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 90,
                        "symbolRequired": false,
                        "untilDays": 90
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 90,
                        "untilDays": 90,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 90,
                        "untilDays": 90,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchCanceledAndClosedOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 90,
                        "untilDays": 90,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchClosedOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 1,
                        "daysBackCanceled": 1,
                        "untilDays": 1,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchCanceledOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 1,
                        "untilDays": 1,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    }
                },
                "spot": {
                    "extends": "default"
                },
                "swap": {
                    "linear": {
                        "extends": "default"
                    }
                },
                "future": {
                    "linear": {
                        "extends": "default"
                    }
                }
            },
            "streaming": {
                "keepAlive": 99000
            }
        }"###).unwrap())
    }

    fn request_id(&mut self) -> Value {
        let mut request_id: Value = self.sum(self.safe_integer(self.get("options".into()), Value::from("requestId"), Value::from(0)), Value::from(1));
        self.get("options".into()).set("requestId".into(), request_id.clone());
        return request_id.clone();
    }

    fn ping(&mut self, mut client: Value) -> Value {
        // bullish does not support built-in ws protocol-level ping-pong
        // https://api.exchange.bullish.com/docs/api/rest/trading-api/v2/#overview--keep-websocket-open
        let mut id: Value = <Self as Bullish>::request_id(self).to_string();
        return Value::Json(normalize(&Value::Json(json!({
            "jsonrpc": "2.0",
            "type": "command",
            "method": "keepalivePing",
            "params": Value::new_object(),
            "id": id
        }))).unwrap());
    }

    fn handle_pong(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "id": "7",
        //         "jsonrpc": "2.0",
        //         "result": {
        //             "responseCodeName": "OK",
        //             "responseCode": "200",
        //             "message": "Keep alive pong"
        //         }
        //     }
        //
        client.set("last_pong".into(), self.milliseconds());
        return message.clone();
    }

    async fn watch_public(&mut self, mut url: Value, mut message_hash: Value, mut request: Value, mut params: Value) -> Value {
        request = request.or_default(Value::new_object());
        params = params.or_default(Value::new_object());
        let mut id: Value = <Self as Bullish>::request_id(self).to_string();
        let mut message: Value = Value::Json(normalize(&Value::Json(json!({
            "jsonrpc": "2.0",
            "type": "command",
            "method": "subscribe",
            "params": request,
            "id": id
        }))).unwrap());
        let mut full_url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public")) + url.clone();
        return self.watch(full_url.clone(), message_hash.clone(), self.deep_extend_2(message.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
    }

    async fn watch_private(&mut self, mut message_hash: Value, mut subscribe_hash: Value, mut request: Value, mut params: Value) -> Value {
        request = request.or_default(Value::new_object());
        params = params.or_default(Value::new_object());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("private"));
        let mut token: Value = self.handle_token().await;
        let mut cookies: Value = Value::Json(normalize(&Value::Json(json!({
            "JWT_COOKIE": token
        }))).unwrap());
        self.get("options".into()).get(Value::from("ws")).set("cookies".into(), cookies.clone());
        let mut id: Value = <Self as Bullish>::request_id(self).to_string();
        let mut message: Value = Value::Json(normalize(&Value::Json(json!({
            "jsonrpc": "2.0",
            "type": "command",
            "method": "subscribe",
            "params": request,
            "id": id
        }))).unwrap());
        let mut result: Value = self.watch(url.clone(), message_hash.clone(), self.deep_extend_2(message.clone(), params.clone()), subscribe_hash.clone(), Value::Undefined).await;
        return result.clone();
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut message_hash: Value = Value::from("trades::") + market.get(Value::from("symbol"));
        let mut url: Value = Value::from("/trading-api/v1/market-data/trades");
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "anonymousTrades",
            "symbol": market.get(Value::from("id"))
        }))).unwrap());
        let mut trades: Value = <Self as Bullish>::watch_public(self, url.clone(), message_hash.clone(), request.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "type": "snapshot",
        //         "dataType": "V1TAAnonymousTradeUpdate",
        //         "data": {
        //             "trades": [
        //                 {
        //                     "tradeId": "100086000000609304",
        //                     "isTaker": true,
        //                     "price": "104889.2063",
        //                     "createdAtTimestamp": "1749124509118",
        //                     "quantity": "0.01000000",
        //                     "publishedAtTimestamp": "1749124531466",
        //                     "side": "BUY",
        //                     "createdAtDatetime": "2025-06-05T11:55:09.118Z",
        //                     "symbol": "BTCUSDC"
        //                 }
        //             ],
        //             "createdAtTimestamp": "1749124509118",
        //             "publishedAtTimestamp": "1749124531466",
        //             "symbol": "BTCUSDC"
        //         }
        //     }
        //
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut market_id: Value = self.safe_string(data.clone(), Value::from("symbol"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut market: Value = self.market(symbol.clone());
        let mut raw_trades: Value = self.safe_list(data.clone(), Value::from("trades"), Value::new_array());
        let mut trades: Value = self.parse_trades(raw_trades.clone(), market.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        if !self.get("trades".into()).contains_key(symbol.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            let mut trades_array_cache: Value = ArrayCache::new(limit);
            self.get("trades".into()).set(symbol.clone(), trades_array_cache.clone());
        };
        let mut trades_array: Value = self.get("trades".into()).get(symbol.clone());
        let mut i: usize = 0;
        while i < trades.len() {
            trades_array.append(trades.get(i.into()));
            i += 1;
        };
        self.get("trades".into()).set(symbol.clone(), trades_array.clone());
        let mut message_hash: Value = Value::from("trades::") + market.get(Value::from("symbol"));
        client.resolve(trades_array.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public")) + Value::from("/trading-api/v1/market-data/tick/") + market.get(Value::from("id"));
        let mut message_hash: Value = Value::from("ticker::") + symbol.clone();
        return self.watch(url.clone(), message_hash.clone(), params.clone(), message_hash.clone(), Value::Undefined).await;
    }

    fn handle_ticker(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "type": "update",
        //         "dataType": "V1TATickerResponse",
        //         "data": {
        //             "askVolume": "0.00100822",
        //             "average": "104423.1806",
        //             "baseVolume": "472.83799258",
        //             "bestAsk": "104324.6000",
        //             "bestBid": "104324.5000",
        //             "bidVolume": "0.00020146",
        //             "change": "-198.4864",
        //             "close": "104323.9374",
        //             "createdAtTimestamp": "1749132838951",
        //             "publishedAtTimestamp": "1749132838955",
        //             "high": "105966.6577",
        //             "last": "104323.9374",
        //             "lastTradeDatetime": "2025-06-05T14:13:56.111Z",
        //             "lastTradeSize": "0.02396100",
        //             "low": "104246.6662",
        //             "open": "104522.4238",
        //             "percentage": "-0.19",
        //             "quoteVolume": "49662592.6712",
        //             "symbol": "BTC-USDC-PERP",
        //             "type": "ticker",
        //             "vwap": "105030.6996",
        //             "currentPrice": "104324.7747",
        //             "ammData": [
        //                 {
        //                     "feeTierId": "1",
        //                     "currentPrice": "104324.7747",
        //                     "baseReservesQuantity": "8.27911366",
        //                     "quoteReservesQuantity": "1067283.0234",
        //                     "bidSpreadFee": "0.00000000",
        //                     "askSpreadFee": "0.00000000"
        //                 }
        //             ],
        //             "createdAtDatetime": "2025-06-05T14:13:58.951Z",
        //             "markPrice": "104289.6884",
        //             "fundingRate": "-0.000192",
        //             "openInterest": "92.24146651"
        //         }
        //     }
        //
        let mut update_type: Value = self.safe_string(message.clone(), Value::from("type"), Value::from(""));
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut market_id: Value = self.safe_string(data.clone(), Value::from("symbol"));
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut parsed: Value = Value::Undefined;
        if update_type.clone() == Value::from("snapshot") {
            parsed = self.parse_ticker(data.clone(), market.clone());
        } else if update_type.clone() == Value::from("update") {
            let mut ticker: Value = self.safe_dict(self.get("tickers".into()), symbol.clone(), Value::new_object());
            let mut raw_ticker: Value = self.safe_dict(ticker.clone(), Value::from("info"), Value::new_object());
            let mut merged: Value = extend_2(raw_ticker.clone(), data.clone());
            parsed = self.parse_ticker(merged.clone(), market.clone());
        };
        self.get("tickers".into()).set(symbol.clone(), parsed.clone());
        let mut message_hash: Value = Value::from("ticker::") + symbol.clone();
        client.resolve(self.get("tickers".into()).get(symbol.clone()), message_hash.clone());
        Value::Undefined
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut url: Value = Value::from("/trading-api/v1/market-data/orderbook");
        let mut message_hash: Value = Value::from("orderbook::") + market.get(Value::from("symbol"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "l2Orderbook",
            "symbol": market.get(Value::from("id"))
        }))).unwrap());
        let mut orderbook: Value = <Self as Bullish>::watch_public(self, url.clone(), message_hash.clone(), request.clone(), params.clone()).await;
        return orderbook.limit();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "type": "snapshot",
        //         "dataType": "V1TALevel2",
        //         "data": {
        //             "timestamp": "1749372632028",
        //             "bids": [
        //                 "105523.3000",
        //                 "0.00046045",
        //             ],
        //             "asks": [
        //                 "105523.4000",
        //                 "0.00117112",
        //             ],
        //             "publishedAtTimestamp": "1749372632073",
        //             "datetime": "2025-06-08T08:50:32.028Z",
        //             "sequenceNumberRange": [ 1967862061, 1967862062 ],
        //             "symbol": "BTCUSDC"
        //         }
        //     }
        //
        // current channel is 'l2Orderbook' which returns only snapshots
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut market_id: Value = self.safe_string(data.clone(), Value::from("symbol"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut message_hash: Value = Value::from("orderbook::") + symbol.clone();
        let mut timestamp: Value = self.safe_integer(data.clone(), Value::from("timestamp"));
        if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
            self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::Undefined, Value::Undefined));
        };
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        let mut bids: Value = <Self as Bullish>::separate_bids_or_asks(self, self.safe_list(data.clone(), Value::from("bids"), Value::new_array()));
        let mut asks: Value = <Self as Bullish>::separate_bids_or_asks(self, self.safe_list(data.clone(), Value::from("asks"), Value::new_array()));
        let mut snapshot: Value = Value::Json(normalize(&Value::Json(json!({
            "bids": bids,
            "asks": asks
        }))).unwrap());
        let mut parsed: Value = self.parse_order_book(snapshot.clone(), symbol.clone(), timestamp.clone(), Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined);
        let mut sequence_number_range: Value = self.safe_list(data.clone(), Value::from("sequenceNumberRange"), Value::new_array());
        if sequence_number_range.len() > 0 {
            let mut last_index: Value = sequence_number_range.len().into() - Value::from(1);
            parsed.set("nonce".into(), self.safe_integer(sequence_number_range.clone(), last_index.clone()));
        };
        orderbook.reset(parsed.clone());
        self.get("orderbooks".into()).set(symbol.clone(), orderbook.clone());
        client.resolve(orderbook.clone(), message_hash.clone());
        Value::Undefined
    }

    fn separate_bids_or_asks(&mut self, mut entry: Value) -> Value {
        let mut result: Value = Value::new_array();
        // 300 = '54885.0000000'
        // 301 = '0.06141566'
        // 302 ='53714.0000000'
        let mut i: usize = 0;
        while i < entry.len() {
            if Value::from(i) % Value::from(2) != Value::from(0) {
                continue;
            };
            let mut price: Value = self.safe_string(entry.clone(), Value::from(i));
            let mut amount: Value = self.safe_string(entry.clone(), Value::from(i) + Value::from(1));
            result.push(Value::Json(serde_json::Value::Array(vec![price.clone().into(), amount.clone().into()])));
            i += 1;
        };
        return result.clone();
    }

    async fn watch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut subscribe_hash: Value = Value::from("orders");
        let mut message_hash: Value = subscribe_hash.clone();
        if symbol.clone().is_nonnullish() {
            symbol = self.symbol(symbol.clone());
            message_hash = message_hash.clone() + Value::from("::") + symbol.clone();
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "orders"
        }))).unwrap());
        let mut trading_account_id: Value = self.safe_string(params.clone(), Value::from("tradingAccountId"));
        if trading_account_id.clone().is_nonnullish() {
            request.set("tradingAccountId".into(), trading_account_id.clone());
            params = self.omit(params.clone(), Value::from("tradingAccountId"));
        };
        let mut orders: Value = <Self as Bullish>::watch_private(self, message_hash.clone(), subscribe_hash.clone(), request.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = orders.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_symbol_since_limit(orders.clone(), symbol.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_orders(&mut self, mut client: Value, mut message: Value) -> Value {
        // snapshot
        //     {
        //         "type": "snapshot",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TAOrder",
        //         "data": [ ... ] // could be an empty list or a list of orders
        //     }
        //
        // update
        //     {
        //         "type": "update",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TAOrder",
        //         "data": {
        //             "status": "OPEN",
        //             "createdAtTimestamp": "1751893427971",
        //             "quoteFee": "0.000000",
        //             "stopPrice": null,
        //             "quantityFilled": "0.00000000",
        //             "handle": null,
        //             "clientOrderId": null,
        //             "quantity": "0.10000000",
        //             "margin": false,
        //             "side": "BUY",
        //             "createdAtDatetime": "2025-07-07T13:03:47.971Z",
        //             "isLiquidation": false,
        //             "borrowedQuoteQuantity": null,
        //             "borrowedBaseQuantity": null,
        //             "timeInForce": "GTC",
        //             "borrowedQuantity": null,
        //             "baseFee": "0.000000",
        //             "quoteAmount": "0.0000000",
        //             "price": "0.0000000",
        //             "statusReason": "Order accepted",
        //             "type": "MKT",
        //             "statusReasonCode": 6014,
        //             "allowBorrow": false,
        //             "orderId": "862317981870850049",
        //             "publishedAtTimestamp": "1751893427975",
        //             "symbol": "ETHUSDT",
        //             "averageFillPrice": null
        //         }
        //     }
        //
        let mut r#type: Value = self.safe_string(message.clone(), Value::from("type"));
        let mut raw_orders: Value = Value::new_array();
        if r#type.clone() == Value::from("update") {
            let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
            raw_orders.push(data.clone());
        } else {
            // update is a single order
            raw_orders = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        };
        // snapshot is a list of orders
        if raw_orders.len() > 0 {
            if self.get("orders".into()).is_nullish() {
                let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("ordersLimit"), Value::from(1000));
                self.set("orders".into(), ArrayCacheBySymbolById::new(limit));
            };
            let mut orders: Value = self.get("orders".into());
            let mut symbols: Value = Value::new_object();
            let mut i: usize = 0;
            while i < raw_orders.len() {
                let mut raw_order: Value = raw_orders.get(i.into());
                let mut parsed_order: Value = self.parse_order(raw_order.clone(), Value::Undefined);
                orders.append(parsed_order.clone());
                let mut symbol: Value = self.safe_string(parsed_order.clone(), Value::from("symbol"));
                symbols.set(symbol.clone(), true.into());
                i += 1;
            };
            let mut message_hash: Value = Value::from("orders");
            client.resolve(orders.clone(), message_hash.clone());
            let mut keys: Value = Object::keys(symbols.clone());
            let mut i: usize = 0;
            while i < keys.len() {
                let mut hash_symbol: Value = keys.get(i.into());
                let mut symbol_message_hash: Value = message_hash.clone() + Value::from("::") + hash_symbol.clone();
                client.resolve(self.get("orders".into()), symbol_message_hash.clone());
                i += 1;
            };
        };
        Value::Undefined
    }

    async fn watch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut subscribe_hash: Value = Value::from("myTrades");
        let mut message_hash: Value = subscribe_hash.clone();
        if symbol.clone().is_nonnullish() {
            symbol = self.symbol(symbol.clone());
            message_hash = message_hash +  Value::from("::") + symbol.clone();
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "trades"
        }))).unwrap());
        let mut trading_account_id: Value = self.safe_string(params.clone(), Value::from("tradingAccountId"));
        if trading_account_id.clone().is_nonnullish() {
            request.set("tradingAccountId".into(), trading_account_id.clone());
            params = self.omit(params.clone(), Value::from("tradingAccountId"));
        };
        let mut trades: Value = <Self as Bullish>::watch_private(self, message_hash.clone(), subscribe_hash.clone(), request.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_my_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // snapshot
        //     {
        //         "type": "snapshot",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TATrade",
        //         "data": [ ... ] // could be an empty list or a list of trades
        //     }
        //
        // update
        //     {
        //         "type": "update",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TATrade",
        //         "data": {
        //             "clientOtcTradeId": null,
        //             "tradeId": "100203000003940164",
        //             "baseFee": "0.00000000",
        //             "isTaker": true,
        //             "quoteAmount": "253.6012195",
        //             "price": "2536.0121950",
        //             "createdAtTimestamp": "1751914859840",
        //             "quoteFee": "0.0000000",
        //             "tradeRebateAmount": null,
        //             "tradeRebateAssetSymbol": null,
        //             "handle": null,
        //             "otcTradeId": null,
        //             "otcMatchId": null,
        //             "orderId": "862407873644725249",
        //             "quantity": "0.10000000",
        //             "publishedAtTimestamp": "1751914859843",
        //             "side": "SELL",
        //             "createdAtDatetime": "2025-07-07T19:00:59.840Z",
        //             "symbol": "ETHUSDT"
        //         }
        //     }
        //
        let mut r#type: Value = self.safe_string(message.clone(), Value::from("type"));
        let mut raw_trades: Value = Value::new_array();
        if r#type.clone() == Value::from("update") {
            let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
            raw_trades.push(data.clone());
        } else {
            // update is a single trade
            raw_trades = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        };
        // snapshot is a list of trades
        if raw_trades.len() > 0 {
            if self.get("myTrades".into()).is_nullish() {
                let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
                self.set("my_trades".into(), ArrayCacheBySymbolById::new(limit));
            };
            let mut trades: Value = self.get("myTrades".into());
            let mut symbols: Value = Value::new_object();
            let mut i: usize = 0;
            while i < raw_trades.len() {
                let mut raw_trade: Value = raw_trades.get(i.into());
                let mut parsed_trade: Value = self.parse_trade(raw_trade.clone(), Value::Undefined);
                trades.append(parsed_trade.clone());
                let mut symbol: Value = self.safe_string(parsed_trade.clone(), Value::from("symbol"));
                symbols.set(symbol.clone(), true.into());
                i += 1;
            };
            let mut message_hash: Value = Value::from("myTrades");
            client.resolve(trades.clone(), message_hash.clone());
            let mut keys: Value = Object::keys(symbols.clone());
            let mut i: usize = 0;
            while i < keys.len() {
                let mut hash_symbol: Value = keys.get(i.into());
                let mut symbol_message_hash: Value = message_hash.clone() + Value::from("::") + hash_symbol.clone();
                client.resolve(self.get("myTrades".into()), symbol_message_hash.clone());
                i += 1;
            };
        };
        Value::Undefined
    }

    async fn watch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "assetAccounts"
        }))).unwrap());
        let mut message_hash: Value = Value::from("balance");
        let mut trading_account_id: Value = self.safe_string(params.clone(), Value::from("tradingAccountId"));
        if trading_account_id.clone().is_nonnullish() {
            params = self.omit(params.clone(), Value::from("tradingAccountId"));
            request.set("tradingAccountId".into(), trading_account_id.clone());
            message_hash = message_hash +  Value::from("::") + trading_account_id.clone();
        };
        return <Self as Bullish>::watch_private(self, message_hash.clone(), message_hash.clone(), request.clone(), params.clone()).await;
    }

    fn handle_balance(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // snapshot
        //     {
        //         "type": "snapshot",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TAAssetAccount",
        //         "data": [
        //             {
        //                 "updatedAtTimestamp": "1751989627509",
        //                 "borrowedQuantity": "0.0000",
        //                 "tradingAccountId": "111309424211255",
        //                 "loanedQuantity": "0.0000",
        //                 "lockedQuantity": "0.0000",
        //                 "assetId": "5",
        //                 "assetSymbol": "USDC",
        //                 "publishedAtTimestamp": "1751989627512",
        //                 "availableQuantity": "999672939.8767",
        //                 "updatedAtDatetime": "2025-07-08T15:47:07.509Z"
        //             }
        //         ]
        //     }
        //
        // update
        //     {
        //         "type": "update",
        //         "tradingAccountId": "111309424211255",
        //         "dataType": "V1TAAssetAccount",
        //         "data": {
        //             "updatedAtTimestamp": "1751989627509",
        //             "borrowedQuantity": "0.0000",
        //             "tradingAccountId": "111309424211255",
        //             "loanedQuantity": "0.0000",
        //             "lockedQuantity": "0.0000",
        //             "assetId": "5",
        //             "assetSymbol": "USDC",
        //             "publishedAtTimestamp": "1751989627512",
        //             "availableQuantity": "999672939.8767",
        //             "updatedAtDatetime": "2025-07-08T15:47:07.509Z"
        //         }
        //     }
        //
        let mut trading_account_id: Value = self.safe_string(message.clone(), Value::from("tradingAccountId"));
        if !self.get("balance".into()).contains_key(trading_account_id.clone()) {
            self.get("balance".into()).set(trading_account_id.clone(), Value::new_object());
        };
        let mut message_type: Value = self.safe_string(message.clone(), Value::from("type"));
        if message_type.clone() == Value::from("snapshot") {
            let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
            self.get("balance".into()).set(trading_account_id.clone(), self.parse_balance(data.clone()));
        } else {
            let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
            let mut asset_id: Value = self.safe_string(data.clone(), Value::from("assetSymbol"));
            let mut account: Value = self.account();
            account.set("total".into(), self.safe_string(data.clone(), Value::from("availableQuantity")));
            account.set("used".into(), self.safe_string(data.clone(), Value::from("lockedQuantity")));
            let mut code: Value = self.safe_currency_code(asset_id.clone(), Value::Undefined);
            self.get("balance".into()).get(trading_account_id.clone()).set(code.clone(), account.clone());
            self.get("balance".into()).get(trading_account_id.clone()).set("info".into(), message.clone());
            self.get("balance".into()).set(trading_account_id.clone(), self.safe_balance(self.get("balance".into()).get(trading_account_id.clone())));
        };
        let mut message_hash: Value = Value::from("balance");
        let mut trading_account_id_hash: Value = Value::from("::") + trading_account_id.clone();
        client.resolve(self.get("balance".into()).get(trading_account_id.clone()), message_hash.clone());
        client.resolve(self.get("balance".into()).get(trading_account_id.clone()), message_hash.clone() + trading_account_id_hash.clone());
        Value::Undefined
    }

    async fn watch_positions(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut subscribe_hash: Value = Value::from("positions");
        let mut message_hash: Value = subscribe_hash.clone();
        if !self.is_empty(symbols.clone()).is_truthy() {
            symbols = self.market_symbols(symbols.clone(), Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined);
            message_hash = message_hash +  Value::from("::") + symbols.join(Value::from(","));
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "topic": "derivativesPositionsV2"
        }))).unwrap());
        let mut positions: Value = <Self as Bullish>::watch_private(self, message_hash.clone(), subscribe_hash.clone(), request.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            return positions.clone();
        };
        return self.filter_by_symbols_since_limit(positions.clone(), symbols.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_positions(&mut self, mut client: Value, mut message: Value) -> Value {
        // exchange does not return messages for sandbox mode
        // current method is implemented blindly
        // todo: check if this works with not-sandbox mode
        let mut message_type: Value = self.safe_string(message.clone(), Value::from("type"));
        let mut raw_positions: Value = Value::new_array();
        if message_type.clone() == Value::from("update") {
            let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
            raw_positions.push(data.clone());
        } else {
            raw_positions = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        };
        if self.get("positions".into()).is_nullish() {
            self.set("positions".into(), ArrayCacheBySymbolBySide::new());
        };
        let mut positions: Value = self.get("positions".into());
        let mut new_positions: Value = Value::new_array();
        let mut i: usize = 0;
        while i < raw_positions.len() {
            let mut raw_position: Value = raw_positions.get(i.into());
            let mut position: Value = self.parse_position(raw_position.clone(), Value::Undefined);
            positions.append(position.clone());
            new_positions.push(position.clone());
            i += 1;
        };
        let mut message_hashes: Value = self.find_message_hashes(client.clone(), Value::from("positions::"));
        let mut i: usize = 0;
        while i < message_hashes.len() {
            let mut message_hash: Value = message_hashes.get(i.into());
            let mut parts: Value = message_hash.split(Value::from("::"));
            let mut symbols_string: Value = parts.get(Value::from(1));
            let mut symbols: Value = symbols_string.split(Value::from(","));
            let mut symbol_positions: Value = self.filter_by_array(new_positions.clone(), Value::from("symbol"), symbols.clone(), false.into());
            if !self.is_empty(symbol_positions.clone()).is_truthy() {
                client.resolve(symbol_positions.clone(), message_hash.clone());
            };
            i += 1;
        };
        client.resolve(positions.clone(), Value::from("positions"));
        Value::Undefined
    }

    fn handle_error_message(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "data": {
        //             "errorCode": 401,
        //             "errorCodeName": "UNAUTHORIZED",
        //             "message": "Unable to authenticate; JWT is missing/invalid or unauthorised to access account"
        //         },
        //         "dataType": "V1TAErrorResponse",
        //         "type": "error"
        //     }
        //
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut feedback: Value = self.get("id".into()) + Value::from(" ") + self.json(data.clone());
                let mut error_code: Value = self.safe_string(data.clone(), Value::from("errorCode"));
        let mut error_code_name: Value = self.safe_string(data.clone(), Value::from("errorCodeName"));
        self.throw_exactly_matched_exception(self.get("exceptions".into()).get(Value::from("exact")), error_code.clone(), feedback.clone());
        self.throw_broadly_matched_exception(self.get("exceptions".into()).get(Value::from("broad")), error_code_name.clone(), feedback.clone());
        panic!(r###"ExchangeError::new(feedback)"###);
        // catch block omitted (no exception support in Value runtime)
;
        Value::Undefined
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        let mut data_type: Value = self.safe_string(message.clone(), Value::from("dataType"));
        let mut result: Value = self.safe_dict(message.clone(), Value::from("result"), Value::Undefined);
        if result.clone().is_nonnullish() {
            let mut response: Value = self.safe_string(result.clone(), Value::from("message"));
            if response.clone() == Value::from("Keep alive pong") {
                <Self as Bullish>::handle_pong(self, client.clone(), message.clone());
            };
        } else if data_type.clone().is_nonnullish() {
            if data_type.clone() == Value::from("V1TAAnonymousTradeUpdate") {
                <Self as Bullish>::handle_trades(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TATickerResponse") {
                <Self as Bullish>::handle_ticker(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TALevel2") {
                <Self as Bullish>::handle_order_book(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TAOrder") {
                <Self as Bullish>::handle_orders(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TATrade") {
                <Self as Bullish>::handle_my_trades(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TAAssetAccount") {
                <Self as Bullish>::handle_balance(self, client.clone(), message.clone());
            };
            if data_type.clone() == Value::from("V1TAErrorResponse") {
                <Self as Bullish>::handle_error_message(self, client.clone(), message.clone());
            };
        };
        Value::Undefined
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetV1nonce" => Bullish::request(self, "v1/nonce".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1time" => Bullish::request(self, "v1/time".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1assets" => Bullish::request(self, "v1/assets".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1assetssymbol" => Bullish::request(self, "v1/assets/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1markets" => Bullish::request(self, "v1/markets".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1marketssymbol" => Bullish::request(self, "v1/markets/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1historymarketssymbol" => Bullish::request(self, "v1/history/markets/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1marketssymbolorderbookhybrid" => Bullish::request(self, "v1/markets/{symbol}/orderbook/hybrid".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1marketssymboltrades" => Bullish::request(self, "v1/markets/{symbol}/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1marketssymboltick" => Bullish::request(self, "v1/markets/{symbol}/tick".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1marketssymbolcandle" => Bullish::request(self, "v1/markets/{symbol}/candle".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1historymarketssymboltrades" => Bullish::request(self, "v1/history/markets/{symbol}/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1historymarketssymbolfundingrate" => Bullish::request(self, "v1/history/markets/{symbol}/funding-rate".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1indexprices" => Bullish::request(self, "v1/index-prices".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1indexpricesassetsymbol" => Bullish::request(self, "v1/index-prices/{assetSymbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1expirypricessymbol" => Bullish::request(self, "v1/expiry-prices/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1optionladder" => Bullish::request(self, "v1/option-ladder".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV1optionladdersymbol" => Bullish::request(self, "v1/option-ladder/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2orders" => Bullish::request(self, "v2/orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2historyorders" => Bullish::request(self, "v2/history/orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2ordersorderid" => Bullish::request(self, "v2/orders/{orderId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2amminstructions" => Bullish::request(self, "v2/amm-instructions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2amminstructionsinstructionid" => Bullish::request(self, "v2/amm-instructions/{instructionId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletstransactions" => Bullish::request(self, "v1/wallets/transactions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletslimitssymbol" => Bullish::request(self, "v1/wallets/limits/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletsdepositinstructionscryptosymbol" => Bullish::request(self, "v1/wallets/deposit-instructions/crypto/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletswithdrawalinstructionscryptosymbol" => Bullish::request(self, "v1/wallets/withdrawal-instructions/crypto/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletsdepositinstructionsfiatsymbol" => Bullish::request(self, "v1/wallets/deposit-instructions/fiat/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletswithdrawalinstructionsfiatsymbol" => Bullish::request(self, "v1/wallets/withdrawal-instructions/fiat/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1walletsselfhostedverificationattempts" => Bullish::request(self, "v1/wallets/self-hosted/verification-attempts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1trades" => Bullish::request(self, "v1/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1historytrades" => Bullish::request(self, "v1/history/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1tradestradeid" => Bullish::request(self, "v1/trades/{tradeId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1tradesclientorderidclientorderid" => Bullish::request(self, "v1/trades/client-order-id/{clientOrderId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1accountsasset" => Bullish::request(self, "v1/accounts/asset".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1accountsassetsymbol" => Bullish::request(self, "v1/accounts/asset/{symbol}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1userslogout" => Bullish::request(self, "v1/users/logout".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1usershmaclogin" => Bullish::request(self, "v1/users/hmac/login".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1accountstradingaccounts" => Bullish::request(self, "v1/accounts/trading-accounts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1accountstradingaccountstradingaccountid" => Bullish::request(self, "v1/accounts/trading-accounts/{tradingAccountId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1derivativespositions" => Bullish::request(self, "v1/derivatives-positions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1historyderivativessettlement" => Bullish::request(self, "v1/history/derivatives-settlement".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1historytransfer" => Bullish::request(self, "v1/history/transfer".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV1historyborrowinterest" => Bullish::request(self, "v1/history/borrow-interest".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2mmpconfiguration" => Bullish::request(self, "v2/mmp-configuration".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2otctrades" => Bullish::request(self, "v2/otc-trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2otctradesotctradeid" => Bullish::request(self, "v2/otc-trades/{otcTradeId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV2otctradesunconfirmedtrade" => Bullish::request(self, "v2/otc-trades/unconfirmed-trade".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2orders" => Bullish::request(self, "v2/orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2command" => Bullish::request(self, "v2/command".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2amminstructions" => Bullish::request(self, "v2/amm-instructions".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV1walletswithdrawal" => Bullish::request(self, "v1/wallets/withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2userslogin" => Bullish::request(self, "v2/users/login".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV1simulateportfoliomargin" => Bullish::request(self, "v1/simulate-portfolio-margin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV1walletsselfhostedinitiate" => Bullish::request(self, "v1/wallets/self-hosted/initiate".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2mmpconfiguration" => Bullish::request(self, "v2/mmp-configuration".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2otctrades" => Bullish::request(self, "v2/otc-trades".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV2otccommand" => Bullish::request(self, "v2/otc-command".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => unimplemented!(),
                }
            },
            _ => unimplemented!()
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BullishImpl(Value);
impl Exchange for BullishImpl {}
impl Bullish for BullishImpl {}
impl ValueTrait for BullishImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Vec<Value> { self.0.keys() }
    fn values(&self) -> Vec<Value> { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value) -> Value { self.0.slice(start) }
}

impl BullishImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BullishImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bullish::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

