#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, JSON, Array, Object, Math, parse_int, shift_2, extend_2, normalize};

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Hashkey : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "hashkey",
            "name": "HashKey Global",
            "countries": [
                "BM"
            ],
            "enableRateLimit": true,
            "rateLimit": 100,
            "timeout": 10000,
            "certified": true,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "sandbox": false,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "cancelOrders": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createDepositAddress": false,
                "createLimitOrder": true,
                "createMarketBuyOrderWithCost": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createMarketOrderWithCost": false,
                "createMarketSellOrderWithCost": false,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createReduceOnlyOrder": true,
                "createStopLimitOrder": true,
                "createStopLossOrder": false,
                "createStopMarketOrder": true,
                "createStopOrder": true,
                "createTakeProfitOrder": false,
                "createTrailingAmountOrder": false,
                "createTrailingPercentOrder": false,
                "createTriggerOrder": true,
                "editOrder": "emulated",
                "fetchAccounts": true,
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCanceledAndClosedOrders": true,
                "fetchCanceledOrders": true,
                "fetchClosedOrder": true,
                "fetchClosedOrders": false,
                "fetchConvertCurrencies": false,
                "fetchConvertQuote": false,
                "fetchConvertTrade": false,
                "fetchConvertTradeHistory": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDeposits": true,
                "fetchDepositsWithdrawals": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": true,
                "fetchFundingRateHistory": true,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": true,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLedger": true,
                "fetchLeverage": true,
                "fetchLeverages": false,
                "fetchLeverageTiers": true,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": "emulated",
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrder": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": false,
                "fetchOrderTrades": false,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": true,
                "fetchPositionsForSymbol": true,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchStatus": true,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchMarkPrices": false,
                "fetchTime": true,
                "fetchTrades": true,
                "fetchTradingFee": true,
                "fetchTradingFees": true,
                "fetchTransactions": false,
                "fetchTransfers": false,
                "fetchUnderlyingAssets": false,
                "fetchVolatilityHistory": false,
                "fetchWithdrawals": true,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": true,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": true,
                "watchBalance": true,
                "watchMyTrades": true,
                "watchOHLCV": true,
                "watchOrderBook": true,
                "watchOrders": true,
                "watchPositions": false,
                "watchTicker": true,
                "watchTrades": true,
                "watchTradesForSymbols": false,
                "withdraw": true,
                "ws": true,
                "cancelAllOrdersAfter": false,
                "cancelWithdraw": false,
                "createConvertTrade": false,
                "fetchAllGreeks": false,
                "fetchMarkPrice": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/6dd6127b-cc19-4a13-9b29-a98d81f80e98",
                "api": {
                    "public": "https://api-glb.hashkey.com",
                    "private": "https://api-glb.hashkey.com",
                    "ws": {
                        "public": "wss://stream-glb.hashkey.com/quote/ws/v1",
                        "private": "wss://stream-glb.hashkey.com/api/v1/ws"
                    },
                    "test": {
                        "ws": {
                            "public": "wss://stream-glb.sim.hashkeydev.com/quote/ws/v1",
                            "private": "wss://stream-glb.sim.hashkeydev.com/api/v1/ws"
                        }
                    }
                },
                "www": "https://global.hashkey.com/",
                "doc": "https://hashkeyglobal-apidoc.readme.io/",
                "fees": "https://support.global.hashkey.com/hc/en-us/articles/13199900083612-HashKey-Global-Fee-Structure",
                "test": {
                    "public": "https://api-glb.sim.hashkeydev.com",
                    "private": "https://api-glb.sim.hashkeydev.com"
                },
                "referral": "https://global.hashkey.com/en-US/register/invite?invite_code=82FQUN"
            },
            "api": {
                "public": {
                    "get": {
                        "api/v1/exchangeInfo": 5,
                        "quote/v1/depth": 1,
                        "quote/v1/trades": 1,
                        "quote/v1/klines": 1,
                        "quote/v1/ticker/24hr": 1,
                        "quote/v1/ticker/price": 1,
                        "quote/v1/ticker/bookTicker": 1,
                        "quote/v1/depth/merged": 1,
                        "quote/v1/markPrice": 1,
                        "quote/v1/index": 1,
                        "api/v1/futures/fundingRate": 1,
                        "api/v1/futures/historyFundingRate": 1,
                        "api/v1/ping": 1,
                        "api/v1/time": 1
                    }
                },
                "private": {
                    "get": {
                        "api/v1/spot/order": 1,
                        "api/v1/spot/openOrders": 1,
                        "api/v1/spot/tradeOrders": 5,
                        "api/v1/futures/leverage": 1,
                        "api/v1/futures/order": 1,
                        "api/v1/futures/openOrders": 1,
                        "api/v1/futures/userTrades": 1,
                        "api/v1/futures/positions": 1,
                        "api/v1/futures/historyOrders": 1,
                        "api/v1/futures/balance": 1,
                        "api/v1/futures/liquidationAssignStatus": 1,
                        "api/v1/futures/riskLimit": 1,
                        "api/v1/futures/commissionRate": 1,
                        "api/v1/futures/getBestOrder": 1,
                        "api/v1/account/vipInfo": 1,
                        "api/v1/account": 1,
                        "api/v1/account/trades": 5,
                        "api/v1/account/type": 5,
                        "api/v1/account/checkApiKey": 1,
                        "api/v1/account/balanceFlow": 5,
                        "api/v1/spot/subAccount/openOrders": 1,
                        "api/v1/spot/subAccount/tradeOrders": 1,
                        "api/v1/subAccount/trades": 1,
                        "api/v1/futures/subAccount/openOrders": 1,
                        "api/v1/futures/subAccount/historyOrders": 1,
                        "api/v1/futures/subAccount/userTrades": 1,
                        "api/v1/account/deposit/address": 1,
                        "api/v1/account/depositOrders": 1,
                        "api/v1/account/withdrawOrders": 1
                    },
                    "post": {
                        "api/v1/userDataStream": 1,
                        "api/v1/spot/orderTest": 1,
                        "api/v1/spot/order": 1,
                        "api/v1.1/spot/order": 1,
                        "api/v1/spot/batchOrders": 5,
                        "api/v1/futures/leverage": 1,
                        "api/v1/futures/order": 1,
                        "api/v1/futures/position/trading-stop": 3,
                        "api/v1/futures/batchOrders": 5,
                        "api/v1/account/assetTransfer": 1,
                        "api/v1/account/authAddress": 1,
                        "api/v1/account/withdraw": 1
                    },
                    "put": {
                        "api/v1/userDataStream": 1
                    },
                    "delete": {
                        "api/v1/spot/order": 1,
                        "api/v1/spot/openOrders": 5,
                        "api/v1/spot/cancelOrderByIds": 5,
                        "api/v1/futures/order": 1,
                        "api/v1/futures/batchOrders": 1,
                        "api/v1/futures/cancelOrderByIds": 1,
                        "api/v1/userDataStream": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1m",
                "3m": "3m",
                "5m": "5m",
                "15m": "15m",
                "30m": "30m",
                "1h": "1h",
                "2h": "2h",
                "4h": "4h",
                "6h": "6h",
                "8h": "8h",
                "12h": "12h",
                "1d": "1d",
                "1w": "1w",
                "1M": "1M"
            },
            "fees": {
                "trading": {
                    "spot": {
                        "tierBased": true,
                        "percentage": true,
                        "feeSide": "get",
                        "maker": 0.0012,
                        "taker": 0.0012,
                        "tiers": {
                            "maker": [
                                [
                                    0,
                                    0.0012
                                ],
                                [
                                    1000000,
                                    0.0008
                                ],
                                [
                                    5000000,
                                    0.0007
                                ],
                                [
                                    10000000,
                                    0.0006
                                ],
                                [
                                    50000000,
                                    0.0004
                                ],
                                [
                                    200000000,
                                    0.0003
                                ],
                                [
                                    400000000,
                                    0.0001
                                ],
                                [
                                    800000000,
                                    0
                                ]
                            ],
                            "taker": [
                                [
                                    0,
                                    0.0012
                                ],
                                [
                                    1000000,
                                    0.0009
                                ],
                                [
                                    5000000,
                                    0.00085
                                ],
                                [
                                    10000000,
                                    0.00075
                                ],
                                [
                                    50000000,
                                    0.00065
                                ],
                                [
                                    200000000,
                                    0.00045
                                ],
                                [
                                    400000000,
                                    0.0004
                                ],
                                [
                                    800000000,
                                    0.00035
                                ]
                            ]
                        }
                    },
                    "swap": {
                        "tierBased": true,
                        "percentage": true,
                        "feeSide": "get",
                        "maker": 0.00025,
                        "taker": 0.0006,
                        "tiers": {
                            "maker": [
                                [
                                    0,
                                    0.00025
                                ],
                                [
                                    1000000,
                                    0.00016
                                ],
                                [
                                    5000000,
                                    0.00014
                                ],
                                [
                                    10000000,
                                    0.00012
                                ],
                                [
                                    50000000,
                                    0.00008
                                ],
                                [
                                    200000000,
                                    0.00006
                                ],
                                [
                                    400000000,
                                    0.00002
                                ],
                                [
                                    800000000,
                                    0
                                ]
                            ],
                            "taker": [
                                [
                                    0,
                                    0.0006
                                ],
                                [
                                    1000000,
                                    0.0005
                                ],
                                [
                                    5000000,
                                    0.00045
                                ],
                                [
                                    10000000,
                                    0.0004
                                ],
                                [
                                    50000000,
                                    0.00035
                                ],
                                [
                                    200000000,
                                    0.0003
                                ],
                                [
                                    400000000,
                                    0.00025
                                ],
                                [
                                    800000000,
                                    0.0002
                                ]
                            ]
                        }
                    }
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "options": {
                "broker": "10000700011",
                "sandboxMode": false,
                "networks": {
                    "BTC": "BTC",
                    "ERC20": "ETH",
                    "AVAX": "AvalancheC",
                    "SOL": "Solana",
                    "MATIC": "Polygon",
                    "ATOM": "Cosmos",
                    "DOT": "Polkadot",
                    "LTC": "LTC",
                    "OPTIMISM": "Optimism",
                    "ARB": "Arbitrum",
                    "DOGE": "Dogecoin",
                    "TRC20": "Tron",
                    "ZKSYNC": "zkSync",
                    "TON": "TON",
                    "KLAYTN": "Klaytn",
                    "MERLINCHAIN": "Merlin Chain"
                },
                "networksById": {
                    "BTC": "BTC",
                    "Bitcoin": "BTC",
                    "ETH": "ERC20",
                    "ERC20": "ERC20",
                    "AvalancheC": "AVAX",
                    "AVAX C-Chain": "AVAX",
                    "Solana": "SOL",
                    "Cosmos": "ATOM",
                    "Arbitrum": "ARB",
                    "Polygon": "MATIC",
                    "Optimism": "OPTIMISM",
                    "Polkadot": "DOT",
                    "LTC": "LTC",
                    "Litecoin": "LTC",
                    "Dogecoin": "DOGE",
                    "Merlin Chain": "MERLINCHAIN",
                    "zkSync": "ZKSYNC",
                    "TRC20": "TRC20",
                    "Tron": "TRC20",
                    "TON": "TON",
                    "BSC(BEP20)": "BSC",
                    "Klaytn": "KLAYTN"
                },
                "defaultNetwork": "ERC20",
                "listenKeyRefreshRate": 3600000,
                "watchBalance": {
                    "fetchBalanceSnapshot": true,
                    "awaitBalanceSnapshot": false
                }
            },
            "features": {
                "default": {
                    "sandbox": true,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": true,
                        "selfTradePrevention": true,
                        "iceberg": false
                    },
                    "createOrders": {
                        "max": 20
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 30,
                        "untilDays": 30,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    }
                },
                "spot": {
                    "extends": "default"
                },
                "forDerivatives": {
                    "extends": "default",
                    "createOrder": {
                        "triggerPrice": true,
                        "selfTradePrevention": true
                    },
                    "fetchOpenOrders": {
                        "trigger": true,
                        "limit": 500
                    }
                },
                "swap": {
                    "linear": {
                        "extends": "forDerivatives"
                    }
                },
                "future": {}
            },
            "streaming": {
                "keepAlive": 10000
            }
        }"###).unwrap())
    }

    async fn wath_public(&mut self, mut market: Value, mut topic: Value, mut message_hash: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market.get(Value::from("id")),
            "topic": topic,
            "event": "sub"
        }))).unwrap());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("public"));
        return self.watch(url.clone(), message_hash.clone(), self.deep_extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
    }

    async fn watch_private(&mut self, mut message_hash: Value) -> Value {
        let mut listen_key: Value = <Self as Hashkey>::authenticate(self, Value::Undefined).await;
        let mut url: Value = <Self as Hashkey>::get_private_url(self, listen_key.clone());
        return self.watch(url.clone(), message_hash.clone(), Value::Undefined, message_hash.clone(), Value::Undefined).await;
    }

    fn get_private_url(&mut self, mut listen_key: Value) -> Value {
        return self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("private")) + Value::from("/") + listen_key.clone();
    }

    async fn watch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        timeframe = timeframe.or_default(Value::from("1m"));
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut interval: Value = self.safe_string(self.get("timeframes".into()), timeframe.clone(), timeframe.clone());
        let mut topic: Value = Value::from("kline_") + interval.clone();
        let mut message_hash: Value = Value::from("ohlcv:") + symbol.clone() + Value::from(":") + timeframe.clone();
        let mut ohlcv: Value = <Self as Hashkey>::wath_public(self, market.clone(), topic.clone(), message_hash.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = ohlcv.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(ohlcv.clone(), since.clone(), limit.clone(), Value::from(0), true.into());
    }

    fn handle_ohlcv(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "symbol": "DOGEUSDT",
        //         "symbolName": "DOGEUSDT",
        //         "topic": "kline",
        //         "params": {
        //             "realtimeInterval": "24h",
        //             "klineType": "1m"
        //         },
        //         "data": [
        //             {
        //                 "t": 1722861660000,
        //                 "s": "DOGEUSDT",
        //                 "sn": "DOGEUSDT",
        //                 "c": "0.08389",
        //                 "h": "0.08389",
        //                 "l": "0.08389",
        //                 "o": "0.08389",
        //                 "v": "0"
        //             }
        //         ],
        //         "f": true,
        //         "sendTime": 1722861664258,
        //         "shared": false
        //     }
        //
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"));
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        if !self.get("ohlcvs".into()).contains_key(symbol.clone()) {
            self.get("ohlcvs".into()).set(symbol.clone(), Value::new_object());
        };
        let mut params: Value = self.safe_dict(message.clone(), Value::from("params"), Value::Undefined);
        let mut kline_type: Value = self.safe_string(params.clone(), Value::from("klineType"));
        let mut timeframe: Value = self.find_timeframe(kline_type.clone(), Value::Undefined);
        if !self.get("ohlcvs".into()).get(symbol.clone()).contains_key(timeframe.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("OHLCVLimit"), Value::from(1000));
            self.get("ohlcvs".into()).get(symbol.clone()).set(timeframe.clone(), ArrayCacheByTimestamp::new(limit));
        };
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut stored: Value = self.get("ohlcvs".into()).get(symbol.clone()).get(timeframe.clone());
        let mut i: usize = 0;
        while i < data.len() {
            let mut candle: Value = self.safe_dict(data.clone(), Value::from(i), Value::new_object());
            let mut parsed: Value = <Self as Hashkey>::parse_ws_ohlcv(self, candle.clone(), market.clone());
            stored.append(parsed.clone());
            i += 1;
        };
        let mut message_hash: Value = Value::from("ohlcv:") + symbol.clone() + Value::from(":") + timeframe.clone();
        client.resolve(stored.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        //
        //     {
        //         "t": 1722861660000,
        //         "s": "DOGEUSDT",
        //         "sn": "DOGEUSDT",
        //         "c": "0.08389",
        //         "h": "0.08389",
        //         "l": "0.08389",
        //         "o": "0.08389",
        //         "v": "0"
        //     }
        //
        return Value::Json(serde_json::Value::Array(vec![self.safe_integer(ohlcv.clone(), Value::from("t")).into(), self.safe_number(ohlcv.clone(), Value::from("o"), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from("h"), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from("l"), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from("c"), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from("v"), Value::Undefined).into()]));
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut topic: Value = Value::from("realtimes");
        let mut message_hash: Value = Value::from("ticker:") + symbol.clone();
        return <Self as Hashkey>::wath_public(self, market.clone(), topic.clone(), message_hash.clone(), params.clone()).await;
    }

    fn handle_ticker(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "symbol": "ETHUSDT",
        //         "symbolName": "ETHUSDT",
        //         "topic": "realtimes",
        //         "params": {
        //             "realtimeInterval": "24h"
        //         },
        //         "data": [
        //             {
        //                 "t": 1722864411064,
        //                 "s": "ETHUSDT",
        //                 "sn": "ETHUSDT",
        //                 "c": "2195",
        //                 "h": "2918.85",
        //                 "l": "2135.5",
        //                 "o": "2915.78",
        //                 "v": "666.5019",
        //                 "qv": "1586902.757079",
        //                 "m": "-0.2472",
        //                 "e": 301
        //             }
        //         ],
        //         "f": false,
        //         "sendTime": 1722864411086,
        //         "shared": false
        //     }
        //
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut ticker: Value = self.parse_ticker(self.safe_dict(data.clone(), Value::from(0), Value::Undefined), Value::Undefined);
        let mut symbol: Value = ticker.get(Value::from("symbol"));
        let mut message_hash: Value = Value::from("ticker:") + symbol.clone();
        self.get("tickers".into()).set(symbol.clone(), ticker.clone());
        client.resolve(self.get("tickers".into()).get(symbol.clone()), message_hash.clone());
        Value::Undefined
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut topic: Value = Value::from("trade");
        let mut message_hash: Value = Value::from("trades:") + symbol.clone();
        let mut trades: Value = <Self as Hashkey>::wath_public(self, market.clone(), topic.clone(), message_hash.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "symbol": "ETHUSDT",
        //         "symbolName": "ETHUSDT",
        //         "topic": "trade",
        //         "params": {
        //             "realtimeInterval": "24h"
        //         },
        //         "data": [
        //             {
        //                 "v": "1745922896272048129",
        //                 "t": 1722866228075,
        //                 "p": "2340.41",
        //                 "q": "0.0132",
        //                 "m": true
        //             },
        //             ...
        //         ],
        //         "f": true,
        //         "sendTime": 1722869464248,
        //         "channelId": "668498fffeba4108-00000001-00113184-562e27d215e43f9c-c188b319",
        //         "shared": false
        //     }
        //
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"));
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        if !self.get("trades".into()).contains_key(symbol.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            self.get("trades".into()).set(symbol.clone(), ArrayCache::new(limit));
        };
        let mut stored: Value = self.get("trades".into()).get(symbol.clone());
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::Undefined);
        if data.clone().is_nonnullish() {
            data = self.sort_by(data.clone(), Value::from("t"));
            let mut i: usize = 0;
            while i < data.len() {
                let mut trade: Value = self.safe_dict(data.clone(), Value::from(i), Value::Undefined);
                let mut parsed: Value = <Self as Hashkey>::parse_ws_trade(self, trade.clone(), market.clone());
                stored.append(parsed.clone());
                i += 1;
            };
        };
        let mut message_hash: Value = Value::from("trades") + Value::from(":") + symbol.clone();
        client.resolve(stored.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        symbol = market.get(Value::from("symbol"));
        let mut topic: Value = Value::from("depth");
        let mut message_hash: Value = Value::from("orderbook:") + symbol.clone();
        let mut orderbook: Value = <Self as Hashkey>::wath_public(self, market.clone(), topic.clone(), message_hash.clone(), params.clone()).await;
        return orderbook.limit();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "symbol": "ETHUSDT",
        //         "symbolName": "ETHUSDT",
        //         "topic": "depth",
        //         "params": { "realtimeInterval": "24h" },
        //         "data": [
        //             {
        //                 "e": 301,
        //                 "s": "ETHUSDT",
        //                 "t": 1722873144371,
        //                 "v": "84661262_18",
        //                 "b": [
        //                     [ "1650", "0.0864" ],
        //                     ...
        //                 ],
        //                 "a": [
        //                     ["4085", "0.0074" ],
        //                     ...
        //                 ],
        //                 "o": 0
        //             }
        //         ],
        //         "f": false,
        //         "sendTime": 1722873144589,
        //         "channelId": "2265aafffe68b588-00000001-0011510c-9e9ca710b1500854-551830bd",
        //         "shared": false
        //     }
        //
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"));
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut message_hash: Value = Value::from("orderbook:") + symbol.clone();
        if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
            self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::new_object(), Value::Undefined));
        };
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut data_entry: Value = self.safe_dict(data.clone(), Value::from(0), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(data_entry.clone(), Value::from("t"));
        let mut snapshot: Value = self.parse_order_book(data_entry.clone(), symbol.clone(), timestamp.clone(), Value::from("b"), Value::from("a"), Value::Undefined, Value::Undefined, Value::Undefined);
        orderbook.reset(snapshot.clone());
        orderbook.set("nonce".into(), self.safe_integer(message.clone(), Value::from("id")));
        self.get("orderbooks".into()).set(symbol.clone(), orderbook.clone());
        client.resolve(orderbook.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn watch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut message_hash: Value = Value::from("orders");
        if symbol.clone().is_nonnullish() {
            symbol = self.symbol(symbol.clone());
            message_hash = message_hash.clone() + Value::from(":") + symbol.clone();
        };
        let mut orders: Value = <Self as Hashkey>::watch_private(self, message_hash.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = orders.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_symbol_since_limit(orders.clone(), symbol.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_order(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // swap
        //     {
        //         "e": "contractExecutionReport",
        //         "E": "1723037391181",
        //         "s": "ETHUSDT-PERPETUAL",
        //         "c": "1723037389677",
        //         "S": "BUY_OPEN",
        //         "o": "LIMIT",
        //         "f": "IOC",
        //         "q": "1",
        //         "p": "2561.75",
        //         "X": "FILLED",
        //         "i": "1747358716129257216",
        //         "l": "1",
        //         "z": "1",
        //         "L": "2463.36",
        //         "n": "0.001478016",
        //         "N": "USDT",
        //         "u": true,
        //         "w": true,
        //         "m": false,
        //         "O": "1723037391140",
        //         "Z": "2463.36",
        //         "C": false,
        //         "v": "5",
        //         "reqAmt": "0",
        //         "d": "1747358716255075840",
        //         "r": "0",
        //         "V": "2463.36",
        //         "P": "0",
        //         "lo": false,
        //         "lt": ""
        //     }
        //
        if self.get("orders".into()).is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("ordersLimit"), Value::from(1000));
            self.set("orders".into(), ArrayCacheBySymbolById::new(limit));
        };
        let mut parsed: Value = <Self as Hashkey>::parse_ws_order(self, message.clone(), Value::Undefined);
        let mut orders: Value = self.get("orders".into());
        orders.append(parsed.clone());
        let mut message_hash: Value = Value::from("orders");
        client.resolve(orders.clone(), message_hash.clone());
        let mut symbol: Value = parsed.get(Value::from("symbol"));
        let mut symbol_specific_message_hash: Value = message_hash.clone() + Value::from(":") + symbol.clone();
        client.resolve(orders.clone(), symbol_specific_message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_order(&self, mut order: Value, mut market: Value) -> Value {
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("s"));
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("O"));
        let mut side: Value = self.safe_string_lower(order.clone(), Value::from("S"));
        let mut reduce_only: Value = Value::Undefined;
        (side, reduce_only) = shift_2(self.parse_order_side_and_reduce_only(side.clone()));
        let mut r#type: Value = self.parse_order_type(self.safe_string(order.clone(), Value::from("o")));
        let mut time_in_force: Value = self.safe_string(order.clone(), Value::from("f"));
        let mut post_only: Value = Value::Undefined;
        (r#type, time_in_force, post_only) = shift_3(self.parse_order_type_time_in_force_and_post_only(r#type.clone(), time_in_force.clone()));
        if market.get(Value::from("contract")).is_truthy() {
            // swap orders are always have type 'LIMIT', thus we can not define the correct type
            r#type = Value::Undefined;
        };
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": self.safe_string(order.clone(), Value::from("i")),
            "clientOrderId": self.safe_string(order.clone(), Value::from("c")),
            "datetime": self.iso8601(timestamp.clone()),
            "timestamp": timestamp,
            "lastTradeTimestamp": Value::Undefined,
            "lastUpdateTimestamp": Value::Undefined,
            "status": self.parse_order_status(self.safe_string(order.clone(), Value::from("X"))),
            "symbol": market.get(Value::from("symbol")),
            "type": r#type,
            "timeInForce": time_in_force,
            "side": side,
            "price": self.safe_string(order.clone(), Value::from("p")),
            "average": self.safe_string(order.clone(), Value::from("V")),
            "amount": self.omit_zero(self.safe_string(order.clone(), Value::from("q"))),
            "filled": self.safe_string(order.clone(), Value::from("z")),
            "remaining": self.safe_string(order.clone(), Value::from("r")),
            "stopPrice": Value::Undefined,
            "triggerPrice": Value::Undefined,
            "takeProfitPrice": Value::Undefined,
            "stopLossPrice": Value::Undefined,
            "cost": self.omit_zero(self.safe_string(order.clone(), Value::from("Z"))),
            "trades": Value::Undefined,
            "fee": Value::Json(normalize(&Value::Json(json!({
                "currency": self.safe_currency_code(self.safe_string(order.clone(), Value::from("N")), Value::Undefined),
                "amount": self.omit_zero(self.safe_string(order.clone(), Value::from("n")))
            }))).unwrap()),
            "reduceOnly": reduce_only,
            "postOnly": post_only,
            "info": order
        }))).unwrap()), market.clone());
    }

    async fn watch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut message_hash: Value = Value::from("myTrades");
        if symbol.clone().is_nonnullish() {
            symbol = self.symbol(symbol.clone());
            message_hash = message_hash +  Value::from(":") + symbol.clone();
        };
        let mut trades: Value = <Self as Hashkey>::watch_private(self, message_hash.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_my_trade(&mut self, mut client: Value, mut message: Value, mut subscription: Value) -> Value {
        subscription = subscription.or_default(Value::new_object());
        //
        //     {
        //         "e": "ticketInfo",
        //         "E": "1723037391156",
        //         "s": "ETHUSDT-PERPETUAL",
        //         "q": "1.00",
        //         "t": "1723037391147",
        //         "p": "2463.36",
        //         "T": "1747358716187197441",
        //         "o": "1747358716129257216",
        //         "c": "1723037389677",
        //         "a": "1735619524953226496",
        //         "m": false,
        //         "S": "BUY"
        //     }
        //
        if self.get("myTrades".into()).is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            self.set("my_trades".into(), ArrayCacheBySymbolById::new(limit));
        };
        let mut trades_array: Value = self.get("myTrades".into());
        let mut parsed: Value = <Self as Hashkey>::parse_ws_trade(self, message.clone(), Value::Undefined);
        trades_array.append(parsed.clone());
        self.set("my_trades".into(), trades_array.clone());
        let mut message_hash: Value = Value::from("myTrades");
        client.resolve(trades_array.clone(), message_hash.clone());
        let mut symbol: Value = parsed.get(Value::from("symbol"));
        let mut symbol_specific_message_hash: Value = message_hash.clone() + Value::from(":") + symbol.clone();
        client.resolve(trades_array.clone(), symbol_specific_message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        // watchTrades
        //     {
        //         "v": "1745922896272048129",
        //         "t": 1722866228075,
        //         "p": "2340.41",
        //         "q": "0.0132",
        //         "m": true
        //     }
        //
        // watchMyTrades
        //     {
        //         "e": "ticketInfo",
        //         "E": "1723037391156",
        //         "s": "ETHUSDT-PERPETUAL",
        //         "q": "1.00",
        //         "t": "1723037391147",
        //         "p": "2463.36",
        //         "T": "1747358716187197441",
        //         "o": "1747358716129257216",
        //         "c": "1723037389677",
        //         "a": "1735619524953226496",
        //         "m": false,
        //         "S": "BUY"
        //     }
        //
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("s"));
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(trade.clone(), Value::from("t"));
        let mut is_maker: Value = self.safe_bool(trade.clone(), Value::from("m"), Value::Undefined);
        let mut taker_or_maker: Value = Value::Undefined;
        if is_maker.clone().is_nonnullish() {
            if is_maker.is_truthy() {
                taker_or_maker = Value::from("maker");
            } else {
                taker_or_maker = Value::from("taker");
            };
        };
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "id": self.safe_string_2(trade.clone(), Value::from("v"), Value::from("T")),
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "side": self.safe_string_lower(trade.clone(), Value::from("S")),
            "price": self.safe_string(trade.clone(), Value::from("p")),
            "amount": self.safe_string(trade.clone(), Value::from("q")),
            "cost": Value::Undefined,
            "takerOrMaker": taker_or_maker,
            "type": Value::Undefined,
            "order": self.safe_string(trade.clone(), Value::from("o")),
            "fee": Value::Undefined,
            "info": trade
        }))).unwrap()), market.clone());
    }

    async fn watch_positions(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut listen_key: Value = <Self as Hashkey>::authenticate(self, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined);
        let mut message_hash: Value = Value::from("positions");
        let mut message_hashes: Value = Value::new_array();
        if symbols.clone().is_nullish() {
            message_hashes.push(message_hash.clone());
        } else {
            let mut i: usize = 0;
            while i < symbols.len() {
                let mut symbol: Value = symbols.get(i.into());
                message_hashes.push(message_hash.clone() + Value::from(":") + symbol.clone());
                i += 1;
            };
        };
        let mut url: Value = <Self as Hashkey>::get_private_url(self, listen_key.clone());
        let mut positions: Value = self.watch_multiple(url.clone(), message_hashes.clone(), Value::Undefined, message_hashes.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            return positions.clone();
        };
        return self.filter_by_symbols_since_limit(self.get("positions".into()), symbols.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_position(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "e": "outboundContractPositionInfo",
        //         "E": "1723084699801",
        //         "A": "1735619524953226496",
        //         "s": "ETHUSDT-PERPETUAL",
        //         "S": "LONG",
        //         "p": "2429.6",
        //         "P": "2",
        //         "a": "2",
        //         "f": "10760.14",
        //         "m": "1.0085",
        //         "r": "-0.0029",
        //         "up": "0.0478",
        //         "pr": "0.0492",
        //         "pv": "4.8592",
        //         "v": "5.00",
        //         "mt": "CROSS",
        //         "mm": "0.0367"
        //     }
        //
        if self.get("positions".into()).is_nullish() {
            self.set("positions".into(), ArrayCacheBySymbolBySide::new());
        };
        let mut positions: Value = self.get("positions".into());
        let mut parsed: Value = <Self as Hashkey>::parse_ws_position(self, message.clone(), Value::Undefined);
        positions.append(parsed.clone());
        let mut message_hash: Value = Value::from("positions");
        client.resolve(parsed.clone(), message_hash.clone());
        let mut symbol: Value = parsed.get(Value::from("symbol"));
        client.resolve(parsed.clone(), message_hash.clone() + Value::from(":") + symbol.clone());
        Value::Undefined
    }

    fn parse_ws_position(&self, mut position: Value, mut market: Value) -> Value {
        let mut market_id: Value = self.safe_string(position.clone(), Value::from("s"));
        market = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(position.clone(), Value::from("E"));
        return self.safe_position(Value::Json(normalize(&Value::Json(json!({
            "symbol": market.get(Value::from("symbol")),
            "id": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "contracts": self.safe_number(position.clone(), Value::from("P"), Value::Undefined),
            "contractSize": Value::Undefined,
            "side": self.safe_string_lower(position.clone(), Value::from("S")),
            "notional": self.safe_number(position.clone(), Value::from("pv"), Value::Undefined),
            "leverage": self.safe_integer(position.clone(), Value::from("v")),
            "unrealizedPnl": self.safe_number(position.clone(), Value::from("up"), Value::Undefined),
            "realizedPnl": self.safe_number(position.clone(), Value::from("r"), Value::Undefined),
            "collateral": Value::Undefined,
            "entryPrice": self.safe_number(position.clone(), Value::from("p"), Value::Undefined),
            "markPrice": Value::Undefined,
            "liquidationPrice": self.safe_number(position.clone(), Value::from("f"), Value::Undefined),
            "marginMode": self.safe_string_lower(position.clone(), Value::from("mt")),
            "hedged": true,
            "maintenanceMargin": self.safe_number(position.clone(), Value::from("mm"), Value::Undefined),
            "maintenanceMarginPercentage": Value::Undefined,
            "initialMargin": self.safe_number(position.clone(), Value::from("m"), Value::Undefined),
            "initialMarginPercentage": Value::Undefined,
            "marginRatio": Value::Undefined,
            "lastUpdateTimestamp": Value::Undefined,
            "lastPrice": Value::Undefined,
            "stopLossPrice": Value::Undefined,
            "takeProfitPrice": Value::Undefined,
            "percentage": Value::Undefined,
            "info": position
        }))).unwrap()));
    }

    async fn watch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut listen_key: Value = <Self as Hashkey>::authenticate(self, Value::Undefined).await;
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut r#type: Value = Value::from("spot");
        (r#type, params) = shift_2(self.handle_market_type_and_params(Value::from("watchBalance"), Value::Undefined, params.clone(), r#type.clone()));
        let mut message_hash: Value = Value::from("balance:") + r#type.clone();
        let mut url: Value = <Self as Hashkey>::get_private_url(self, listen_key.clone());
        let mut client: Value = self.client(url.clone());
        <Self as Hashkey>::set_balance_cache(self, client.clone(), r#type.clone(), message_hash.clone());
        let mut fetch_balance_snapshot: Value = Value::Undefined;
        let mut await_balance_snapshot: Value = Value::Undefined;
        (fetch_balance_snapshot, params) = shift_2(self.handle_option_and_params(self.get("options".into()), Value::from("watchBalance"), Value::from("fetchBalanceSnapshot"), true.into()));
        (await_balance_snapshot, params) = shift_2(self.handle_option_and_params(self.get("options".into()), Value::from("watchBalance"), Value::from("awaitBalanceSnapshot"), false.into()));
        if fetch_balance_snapshot.is_truthy() && await_balance_snapshot.is_truthy() {
            client.future(r#type.clone() + Value::from(":fetchBalanceSnapshot")).await;
        };
        return self.watch(url.clone(), message_hash.clone(), Value::Undefined, message_hash.clone(), Value::Undefined).await;
    }

    fn set_balance_cache(&mut self, mut client: Value, mut r#type: Value, mut subscribe_hash: Value) -> Value {
        if client.get(subscriptions.clone()).contains_key(subscribe_hash.clone()) {
            return Value::Undefined;
        };
        let mut options: Value = self.safe_dict(self.get("options".into()), Value::from("watchBalance"), Value::Undefined);
        let mut snapshot: Value = self.safe_bool(options.clone(), Value::from("fetchBalanceSnapshot"), true.into());
        if snapshot.is_truthy() {
            let mut message_hash: Value = r#type.clone() + Value::from(":") + Value::from("fetchBalanceSnapshot");
            if !client.get(futures.clone()).contains_key(message_hash.clone()) {
                client.future(message_hash.clone());
                self.spawn(self.get("loadBalanceSnapshot".into()), client.clone(), message_hash.clone(), r#type.clone());
            };
        };
        self.get("balance".into()).set(r#type.clone(), Value::new_object());
        Value::Undefined
    }

    async fn load_balance_snapshot(&mut self, mut client: Value, mut message_hash: Value, mut r#type: Value) -> Value {
        let mut response: Value = self.fetch_balance(Value::Json(normalize(&Value::Json(json!({
            "type": r#type
        }))).unwrap())).await;
        self.get("balance".into()).set(r#type.clone(), extend_2(response.clone(), self.safe_value(self.get("balance".into()), r#type.clone(), Value::new_object())));
        // don't remove the future from the .futures cache
        if client.get(futures.clone()).contains_key(message_hash.clone()) {
            let mut future: Value = client.get(futures.clone()).get(message_hash.clone());
            future.resolve();
            client.resolve(self.get("balance".into()).get(r#type.clone()), Value::from("balance:") + r#type.clone());
        };
        Value::Undefined
    }

    fn handle_balance(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "e": "outboundContractAccountInfo",        // event type
        //                                                    // outboundContractAccountInfo
        //         "E": "1714717314118",                      // event time
        //         "T": true,                                 // can trade
        //         "W": true,                                 // can withdraw
        //         "D": true,                                 // can deposit
        //         "B": [                                     // balances changed
        //             {
        //                 "a": "USDT",                       // asset
        //                 "f": "474960.65",                  // free amount
        //                 "l": "24835.178056020383226869",   // locked amount
        //                 "r": ""                            // to be released
        //             }
        //         ]
        //     }
        //
        let mut event: Value = self.safe_string(message.clone(), Value::from("e"));
        let mut data: Value = self.safe_list(message.clone(), Value::from("B"), Value::new_array());
        let mut balance_update: Value = self.safe_dict(data.clone(), Value::from(0), Value::Undefined);
        let mut is_spot: Value = (event.clone() == Value::from("outboundAccountInfo")).into();
        let mut r#type: Value = if is_spot.is_truthy() { Value::from("spot") } else { Value::from("swap") };
        if !self.get("balance".into()).contains_key(r#type.clone()) {
            self.get("balance".into()).set(r#type.clone(), Value::new_object());
        };
        self.get("balance".into()).get(r#type.clone()).set("info".into(), message.clone());
        let mut currency_id: Value = self.safe_string(balance_update.clone(), Value::from("a"));
        let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
        let mut account: Value = self.account();
        account.set("free".into(), self.safe_string(balance_update.clone(), Value::from("f")));
        account.set("used".into(), self.safe_string(balance_update.clone(), Value::from("l")));
        self.get("balance".into()).get(r#type.clone()).set(code.clone(), account.clone());
        self.get("balance".into()).set(r#type.clone(), self.safe_balance(self.get("balance".into()).get(r#type.clone())));
        let mut message_hash: Value = Value::from("balance:") + r#type.clone();
        client.resolve(self.get("balance".into()).get(r#type.clone()), message_hash.clone());
        Value::Undefined
    }

    async fn authenticate(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut listen_key: Value = self.safe_string(self.get("options".into()), Value::from("listenKey"));
        if listen_key.clone().is_nonnullish() {
            return listen_key.clone();
        };
        let mut response: Value = self.private_post_api_v1_user_data_stream(params.clone()).await;
        //
        //    {
        //        "listenKey": "atbNEcWnBqnmgkfmYQeTuxKTpTStlZzgoPLJsZhzAOZTbAlxbHqGNWiYaUQzMtDz"
        //    }
        //
        listen_key = self.safe_string(response.clone(), Value::from("listenKey"));
        self.get("options".into()).set("listenKey".into(), listen_key.clone());
        let mut listen_key_refresh_rate: Value = self.safe_integer(self.get("options".into()), Value::from("listenKeyRefreshRate"), Value::from(3600000));
        self.delay(listen_key_refresh_rate.clone(), self.get("keepAliveListenKey".into()), listen_key.clone(), params.clone());
        return listen_key.clone();
    }

    async fn keep_alive_listen_key(&mut self, mut listen_key: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if listen_key.clone().is_nullish() {
            return Value::Undefined;
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "listenKey": listen_key
        }))).unwrap());
                self.private_put_api_v1_user_data_stream(extend_2(request.clone(), params.clone())).await;
        let mut listen_key_refresh_rate: Value = self.safe_integer(self.get("options".into()), Value::from("listenKeyRefreshRate"), Value::from(1200000));
        self.delay(listen_key_refresh_rate.clone(), self.get("keepAliveListenKey".into()), listen_key.clone(), params.clone());
        // catch block omitted (no exception support in Value runtime)
;
        Value::Undefined
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        if Array::is_array(message.clone()).is_truthy() {
            message = self.safe_dict(message.clone(), Value::from(0), Value::new_object());
        };
        let mut topic: Value = self.safe_string_2(message.clone(), Value::from("topic"), Value::from("e"));
        if topic.clone() == Value::from("kline") {
            <Self as Hashkey>::handle_ohlcv(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("realtimes") {
            <Self as Hashkey>::handle_ticker(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("trade") {
            <Self as Hashkey>::handle_trades(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("depth") {
            <Self as Hashkey>::handle_order_book(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("contractExecutionReport") || topic.clone() == Value::from("executionReport") {
            <Self as Hashkey>::handle_order(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("ticketInfo") {
            <Self as Hashkey>::handle_my_trade(self, client.clone(), message.clone(), Value::Undefined);
        } else if topic.clone() == Value::from("outboundContractPositionInfo") {
            <Self as Hashkey>::handle_position(self, client.clone(), message.clone());
        } else if topic.clone() == Value::from("outboundAccountInfo") || topic.clone() == Value::from("outboundContractAccountInfo") {
            <Self as Hashkey>::handle_balance(self, client.clone(), message.clone());
        };
        Value::Undefined
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetApiv1exchangeinfo" => Hashkey::request(self, "api/v1/exchangeInfo".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1depth" => Hashkey::request(self, "quote/v1/depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1trades" => Hashkey::request(self, "quote/v1/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1klines" => Hashkey::request(self, "quote/v1/klines".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1ticker24hr" => Hashkey::request(self, "quote/v1/ticker/24hr".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1tickerprice" => Hashkey::request(self, "quote/v1/ticker/price".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1tickerbookticker" => Hashkey::request(self, "quote/v1/ticker/bookTicker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1depthmerged" => Hashkey::request(self, "quote/v1/depth/merged".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1markprice" => Hashkey::request(self, "quote/v1/markPrice".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetQuotev1index" => Hashkey::request(self, "quote/v1/index".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetApiv1futuresfundingrate" => Hashkey::request(self, "api/v1/futures/fundingRate".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetApiv1futureshistoryfundingrate" => Hashkey::request(self, "api/v1/futures/historyFundingRate".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetApiv1ping" => Hashkey::request(self, "api/v1/ping".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetApiv1time" => Hashkey::request(self, "api/v1/time".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotorder" => Hashkey::request(self, "api/v1/spot/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotopenorders" => Hashkey::request(self, "api/v1/spot/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spottradeorders" => Hashkey::request(self, "api/v1/spot/tradeOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresleverage" => Hashkey::request(self, "api/v1/futures/leverage".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresorder" => Hashkey::request(self, "api/v1/futures/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresopenorders" => Hashkey::request(self, "api/v1/futures/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresusertrades" => Hashkey::request(self, "api/v1/futures/userTrades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futurespositions" => Hashkey::request(self, "api/v1/futures/positions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futureshistoryorders" => Hashkey::request(self, "api/v1/futures/historyOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresbalance" => Hashkey::request(self, "api/v1/futures/balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresliquidationassignstatus" => Hashkey::request(self, "api/v1/futures/liquidationAssignStatus".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresrisklimit" => Hashkey::request(self, "api/v1/futures/riskLimit".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futurescommissionrate" => Hashkey::request(self, "api/v1/futures/commissionRate".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresgetbestorder" => Hashkey::request(self, "api/v1/futures/getBestOrder".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountvipinfo" => Hashkey::request(self, "api/v1/account/vipInfo".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1account" => Hashkey::request(self, "api/v1/account".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accounttrades" => Hashkey::request(self, "api/v1/account/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accounttype" => Hashkey::request(self, "api/v1/account/type".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountcheckapikey" => Hashkey::request(self, "api/v1/account/checkApiKey".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountbalanceflow" => Hashkey::request(self, "api/v1/account/balanceFlow".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotsubaccountopenorders" => Hashkey::request(self, "api/v1/spot/subAccount/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotsubaccounttradeorders" => Hashkey::request(self, "api/v1/spot/subAccount/tradeOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1subaccounttrades" => Hashkey::request(self, "api/v1/subAccount/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuressubaccountopenorders" => Hashkey::request(self, "api/v1/futures/subAccount/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuressubaccounthistoryorders" => Hashkey::request(self, "api/v1/futures/subAccount/historyOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuressubaccountusertrades" => Hashkey::request(self, "api/v1/futures/subAccount/userTrades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountdepositaddress" => Hashkey::request(self, "api/v1/account/deposit/address".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountdepositorders" => Hashkey::request(self, "api/v1/account/depositOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountwithdraworders" => Hashkey::request(self, "api/v1/account/withdrawOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1userdatastream" => Hashkey::request(self, "api/v1/userDataStream".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotordertest" => Hashkey::request(self, "api/v1/spot/orderTest".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotorder" => Hashkey::request(self, "api/v1/spot/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv11spotorder" => Hashkey::request(self, "api/v1.1/spot/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotbatchorders" => Hashkey::request(self, "api/v1/spot/batchOrders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresleverage" => Hashkey::request(self, "api/v1/futures/leverage".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresorder" => Hashkey::request(self, "api/v1/futures/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futurespositiontradingstop" => Hashkey::request(self, "api/v1/futures/position/trading-stop".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresbatchorders" => Hashkey::request(self, "api/v1/futures/batchOrders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1accountassettransfer" => Hashkey::request(self, "api/v1/account/assetTransfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1accountauthaddress" => Hashkey::request(self, "api/v1/account/authAddress".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1accountwithdraw" => Hashkey::request(self, "api/v1/account/withdraw".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePutApiv1userdatastream" => Hashkey::request(self, "api/v1/userDataStream".into(), "private".into(), "PUT".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotorder" => Hashkey::request(self, "api/v1/spot/order".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotopenorders" => Hashkey::request(self, "api/v1/spot/openOrders".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotcancelorderbyids" => Hashkey::request(self, "api/v1/spot/cancelOrderByIds".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futuresorder" => Hashkey::request(self, "api/v1/futures/order".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futuresbatchorders" => Hashkey::request(self, "api/v1/futures/batchOrders".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futurescancelorderbyids" => Hashkey::request(self, "api/v1/futures/cancelOrderByIds".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1userdatastream" => Hashkey::request(self, "api/v1/userDataStream".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => unimplemented!(),
                }
            },
            _ => unimplemented!()
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HashkeyImpl(Value);
impl Exchange for HashkeyImpl {}
impl Hashkey for HashkeyImpl {}
impl ValueTrait for HashkeyImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Vec<Value> { self.0.keys() }
    fn values(&self) -> Vec<Value> { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value) -> Value { self.0.slice(start) }
}

impl HashkeyImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = HashkeyImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Hashkey::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

