// AUTO-GENERATED: rust exchange modules
#[cfg(feature = "full-exchanges")]
pub mod alpaca;
#[cfg(feature = "full-exchanges")]
pub mod apex;
#[cfg(feature = "full-exchanges")]
pub mod arkham;
#[cfg(feature = "full-exchanges")]
pub mod ascendex;
#[cfg(feature = "full-exchanges")]
pub mod aster;
#[cfg(feature = "full-exchanges")]
pub mod backpack;
#[cfg(feature = "full-exchanges")]
pub mod bequant;
#[cfg(feature = "full-exchanges")]
pub mod binance;
#[cfg(feature = "full-exchanges")]
pub mod binancecoinm;
#[cfg(feature = "full-exchanges")]
pub mod binanceus;
#[cfg(feature = "full-exchanges")]
pub mod binanceusdm;
#[cfg(feature = "full-exchanges")]
pub mod bingx;
#[cfg(feature = "full-exchanges")]
pub mod bitfinex;
#[cfg(feature = "full-exchanges")]
pub mod bitget;
#[cfg(feature = "full-exchanges")]
pub mod bithumb;
#[cfg(feature = "full-exchanges")]
pub mod bitmart;
#[cfg(feature = "full-exchanges")]
pub mod bitmex;
#[cfg(feature = "full-exchanges")]
pub mod bitopro;
#[cfg(feature = "full-exchanges")]
pub mod bitrue;
#[cfg(feature = "full-exchanges")]
pub mod bitstamp;
#[cfg(feature = "full-exchanges")]
pub mod bittrade;
#[cfg(feature = "full-exchanges")]
pub mod bitvavo;
#[cfg(feature = "full-exchanges")]
pub mod blockchaincom;
#[cfg(feature = "full-exchanges")]
pub mod blofin;
#[cfg(feature = "full-exchanges")]
pub mod bullish;
#[cfg(feature = "full-exchanges")]
pub mod bybit;
#[cfg(feature = "full-exchanges")]
pub mod bydfi;
#[cfg(feature = "full-exchanges")]
pub mod cex;
#[cfg(feature = "full-exchanges")]
pub mod coinbase;
#[cfg(feature = "full-exchanges")]
pub mod coinbaseadvanced;
#[cfg(feature = "full-exchanges")]
pub mod coinbaseexchange;
#[cfg(feature = "full-exchanges")]
pub mod coinbaseinternational;
#[cfg(feature = "full-exchanges")]
pub mod coincatch;
#[cfg(feature = "full-exchanges")]
pub mod coincheck;
#[cfg(feature = "full-exchanges")]
pub mod coinex;
#[cfg(feature = "full-exchanges")]
pub mod coinone;
#[cfg(feature = "full-exchanges")]
pub mod cryptocom;
#[cfg(feature = "full-exchanges")]
pub mod deepcoin;
#[cfg(feature = "full-exchanges")]
pub mod defx;
#[cfg(feature = "full-exchanges")]
pub mod deribit;
#[cfg(feature = "full-exchanges")]
pub mod derive;
#[cfg(feature = "full-exchanges")]
pub mod dydx;
#[cfg(feature = "full-exchanges")]
pub mod exmo;
#[cfg(feature = "full-exchanges")]
pub mod gate;
#[cfg(feature = "full-exchanges")]
pub mod gateio;
#[cfg(feature = "full-exchanges")]
pub mod gemini;
#[cfg(feature = "full-exchanges")]
pub mod hashkey;
#[cfg(feature = "full-exchanges")]
pub mod hitbtc;
#[cfg(feature = "full-exchanges")]
pub mod hollaex;
#[cfg(feature = "full-exchanges")]
pub mod htx;
#[cfg(feature = "full-exchanges")]
pub mod huobi;
#[cfg(feature = "full-exchanges")]
pub mod hyperliquid;
#[cfg(feature = "full-exchanges")]
pub mod independentreserve;
#[cfg(feature = "full-exchanges")]
pub mod kraken;
#[cfg(feature = "full-exchanges")]
pub mod krakenfutures;
#[cfg(feature = "full-exchanges")]
pub mod kucoin;
#[cfg(feature = "full-exchanges")]
pub mod kucoinfutures;
#[cfg(feature = "full-exchanges")]
pub mod lbank;
#[cfg(feature = "full-exchanges")]
pub mod luno;
#[cfg(feature = "full-exchanges")]
pub mod mexc;
#[cfg(feature = "full-exchanges")]
pub mod modetrade;
#[cfg(feature = "full-exchanges")]
pub mod myokx;
#[cfg(feature = "full-exchanges")]
pub mod ndax;
#[cfg(feature = "full-exchanges")]
pub mod okx;
#[cfg(feature = "full-exchanges")]
pub mod okxus;
#[cfg(feature = "full-exchanges")]
pub mod onetrading;
#[cfg(feature = "full-exchanges")]
pub mod oxfun;
#[cfg(feature = "full-exchanges")]
pub mod p2b;
#[cfg(feature = "full-exchanges")]
pub mod paradex;
#[cfg(feature = "full-exchanges")]
pub mod phemex;
#[cfg(feature = "full-exchanges")]
pub mod poloniex;
#[cfg(feature = "full-exchanges")]
pub mod probit;
#[cfg(feature = "full-exchanges")]
pub mod toobit;
#[cfg(feature = "full-exchanges")]
pub mod upbit;
#[cfg(feature = "full-exchanges")]
pub mod whitebit;
#[cfg(feature = "full-exchanges")]
pub mod woo;
#[cfg(feature = "full-exchanges")]
pub mod woofipro;
#[cfg(feature = "full-exchanges")]
pub mod xt;
