#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Oxfun : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "oxfun",
            "name": "OXFUN",
            "countries": [
                "PA"
            ],
            "enableRateLimit": true,
            "rateLimit": 120,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "sandbox": true,
                "spot": true,
                "margin": false,
                "swap": true,
                "future": false,
                "option": false,
                "addMargin": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "cancelOrderWs": true,
                "cancelOrders": true,
                "cancelOrdersWs": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createDepositAddress": false,
                "createLimitOrder": true,
                "createMarketBuyOrderWithCost": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createMarketOrderWithCost": false,
                "createMarketSellOrderWithCost": false,
                "createOrder": true,
                "createOrderWs": true,
                "createOrders": true,
                "createPostOnlyOrder": true,
                "createReduceOnlyOrder": false,
                "createStopLimitOrder": true,
                "createStopMarketOrder": true,
                "createStopOrder": true,
                "deposit": false,
                "editOrder": false,
                "editOrderWs": true,
                "fetchAccounts": true,
                "fetchBalance": true,
                "fetchBidsAsks": false,
                "fetchBorrowInterest": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchCanceledOrders": false,
                "fetchClosedOrder": false,
                "fetchClosedOrders": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDeposit": false,
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDeposits": true,
                "fetchDepositWithdrawFee": false,
                "fetchDepositWithdrawFees": false,
                "fetchFundingHistory": true,
                "fetchFundingRate": true,
                "fetchFundingRateHistory": true,
                "fetchFundingRates": true,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchL2OrderBook": true,
                "fetchL3OrderBook": false,
                "fetchLedger": false,
                "fetchLeverage": false,
                "fetchLeverageTiers": true,
                "fetchMarketLeverageTiers": "emulated",
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrder": false,
                "fetchOpenOrders": true,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrderBooks": false,
                "fetchOrders": false,
                "fetchOrderTrades": false,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": true,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchStatus": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchTime": false,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": false,
                "fetchTradingLimits": false,
                "fetchTransactionFee": false,
                "fetchTransactionFees": false,
                "fetchTransactions": false,
                "fetchTransfers": true,
                "fetchWithdrawal": false,
                "fetchWithdrawals": true,
                "fetchWithdrawalWhitelist": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "signIn": false,
                "transfer": true,
                "watchBalance": true,
                "watchMyTrades": false,
                "watchOHLCV": true,
                "watchOHLCVForSymbols": true,
                "watchOrderBook": true,
                "watchBidsAsks": true,
                "watchOrderBookForSymbols": true,
                "watchOrders": true,
                "watchTicker": true,
                "watchTickers": true,
                "watchTrades": true,
                "watchTradesForSymbols": true,
                "withdraw": true,
                "ws": true
            },
            "urls": {
                "logo": "https://github.com/ccxt/ccxt/assets/43336371/6a196124-c1ee-4fae-8573-962071b61a85",
                "api": {
                    "public": "https://api.ox.fun",
                    "private": "https://api.ox.fun",
                    "ws": "wss://api.ox.fun/v2/websocket",
                    "test": "wss://stgapi.ox.fun/v2/websocket"
                },
                "www": "https://ox.fun/",
                "doc": "https://docs.ox.fun/",
                "fees": "https://support.ox.fun/en/articles/8819866-trading-fees",
                "referral": "https://ox.fun/register?shareAccountId=5ZUD4a7G",
                "test": {
                    "public": "https://stgapi.ox.fun",
                    "private": "https://stgapi.ox.fun"
                }
            },
            "api": {
                "public": {
                    "get": {
                        "v3/markets": 1,
                        "v3/assets": 1,
                        "v3/tickers": 1,
                        "v3/funding/estimates": 1,
                        "v3/candles": 1,
                        "v3/depth": 1,
                        "v3/markets/operational": 1,
                        "v3/exchange-trades": 1,
                        "v3/funding/rates": 1,
                        "v3/leverage/tiers": 1
                    }
                },
                "private": {
                    "get": {
                        "v3/account": 1,
                        "v3/account/names": 1,
                        "v3/wallet": 1,
                        "v3/transfer": 1,
                        "v3/balances": 1,
                        "v3/positions": 1,
                        "v3/funding": 1,
                        "v3/deposit-addresses": 1,
                        "v3/deposit": 1,
                        "v3/withdrawal-addresses": 1,
                        "v3/withdrawal": 1,
                        "v3/withdrawal-fees": 1,
                        "v3/orders/status": 1,
                        "v3/orders/working": 1,
                        "v3/trades": 1
                    },
                    "post": {
                        "v3/transfer": 1,
                        "v3/withdrawal": 1,
                        "v3/orders/place": 1
                    },
                    "delete": {
                        "v3/orders/cancel": 1,
                        "v3/orders/cancel-all": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "60s",
                "5m": "300s",
                "15m": "900s",
                "30m": "1800s",
                "1h": "3600s",
                "2h": "7200s",
                "4h": "14400s",
                "1d": "86400s"
            },
            "fees": {
                "trading": {
                    "tierBased": true,
                    "percentage": true,
                    "taker": 0.0007,
                    "maker": 0.0002,
                    "tiers": {
                        "maker": [
                            [
                                0,
                                0.0002
                            ],
                            [
                                2500000,
                                0.0001
                            ],
                            [
                                25000000,
                                0
                            ]
                        ],
                        "taker": [
                            [
                                0,
                                0.0007
                            ],
                            [
                                2500000,
                                0.0005
                            ],
                            [
                                25000000,
                                0.0004
                            ]
                        ]
                    }
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v3",
            "options": {
                "sandboxMode": false,
                "networks": {
                    "BTC": "Bitcoin",
                    "ERC20": "Ethereum",
                    "AVAX": "Avalanche",
                    "SOL": "Solana",
                    "ARB": "Arbitrum",
                    "MATIC": "Polygon",
                    "FTM": "Fantom",
                    "BNB": "BNBSmartChain",
                    "OPTIMISM": "Optimism"
                },
                "networksById": {
                    "Bitcoin": "BTC",
                    "Ethereum": "ERC20",
                    "Avalanche": "AVAX",
                    "Solana": "SOL",
                    "Arbitrum": "ARB",
                    "Polygon": "MATIC",
                    "Fantom": "FTM",
                    "Base": "BASE",
                    "BNBSmartChain": "BNB",
                    "Optimism": "OPTIMISM"
                },
                "timeframes": {
                    "1m": "60s",
                    "3m": "180s",
                    "5m": "300s",
                    "15m": "900s",
                    "30m": "1800s",
                    "1h": "3600s",
                    "2h": "7200s",
                    "4h": "14400s",
                    "6h": "21600s",
                    "12h": "43200s",
                    "1d": "86400s"
                },
                "watchOrderBook": {
                    "channel": "depth"
                }
            },
            "features": {
                "default": {
                    "sandbox": true,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": false,
                        "selfTradePrevention": {
                            "EXPIRE_MAKER": true,
                            "EXPIRE_TAKER": true,
                            "EXPIRE_BOTH": true,
                            "NONE": true
                        },
                        "iceberg": true
                    },
                    "createOrders": {
                        "max": 10
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 500,
                        "daysBack": 100000,
                        "untilDays": 7,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOHLCV": {
                        "limit": 500
                    }
                },
                "spot": {
                    "extends": "default"
                },
                "swap": {
                    "linear": {
                        "extends": "default"
                    }
                },
                "future": {}
            },
            "streaming": {
                "keepAlive": 50000
            }
        }"###).unwrap())
    }

    async fn subscribe_multiple(&mut self, mut message_hashes: Value, mut args_array: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "subscribe",
            "args": args_array
        }))).unwrap());
        return self.watch_multiple(url.clone(), message_hashes.clone(), extend_2(request.clone(), params.clone()), message_hashes.clone(), Value::Undefined).await;
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Oxfun>::watch_trades_for_symbols(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn watch_trades_for_symbols(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into(), Value::Undefined, Value::Undefined);
        let mut args: Value = Value::new_array();
        let mut message_hashes: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut message_hash: Value = Value::from("trades") + Value::from(":") + symbol.clone();
            message_hashes.push(message_hash.clone());
            let mut market_id: Value = self.market_id(symbol.clone());
            let mut arg: Value = Value::from("trade:") + market_id.clone();
            args.push(arg.clone());
            i += 1;
        };
        let mut trades: Value = <Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut first: Value = self.safe_dict(trades.clone(), Value::from(0), Value::new_object());
            let mut trade_symbol: Value = self.safe_string(first.clone(), Value::from("symbol"), Value::Undefined);
            limit = trades.get_limit(trade_symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         table: 'trade',
        //         data: [
        //             {
        //                 side: 'SELL',
        //                 quantity: '0.074',
        //                 matchType: 'TAKER',
        //                 price: '3079.5',
        //                 marketCode: 'ETH-USD-SWAP-LIN',
        //                 tradeId: '400017157974517783',
        //                 timestamp: '1716124156643'
        //             }
        //         ]
        //     }
        //
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut i: usize = 0;
        while i < data.len() {
            let mut trade: Value = self.safe_dict(data.clone(), Value::from(i), Value::new_object());
            let mut parsed_trade: Value = <Self as Oxfun>::parse_ws_trade(self, trade.clone(), Value::Undefined);
            let mut symbol: Value = self.safe_string(parsed_trade.clone(), Value::from("symbol"), Value::Undefined);
            let mut message_hash: Value = Value::from("trades:") + symbol.clone();
            if !self.get("trades".into()).contains_key(symbol.clone()) {
                let mut trades_limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
                self.get("trades".into()).set(symbol.clone(), ArrayCache::new(trades_limit));
            };
            let mut stored: Value = self.get("trades".into()).get(symbol.clone());
            stored.append(parsed_trade.clone());
            client.resolve(stored.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    fn parse_ws_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        //     {
        //         side: 'SELL',
        //         quantity: '0.074',
        //         matchType: 'TAKER',
        //         price: '3079.5',
        //         marketCode: 'ETH-USD-SWAP-LIN',
        //         tradeId: '400017157974517783',
        //         timestamp: '1716124156643'
        //     }
        //
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("marketCode"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(trade.clone(), Value::from("timestamp"), Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "id": self.safe_string(trade.clone(), Value::from("tradeId"), Value::Undefined),
            "order": Value::Undefined,
            "type": Value::Undefined,
            "takerOrMaker": self.safe_string_lower(trade.clone(), Value::from("matchType"), Value::Undefined),
            "side": self.safe_string_lower(trade.clone(), Value::from("side"), Value::Undefined),
            "price": self.safe_number(trade.clone(), Value::from("price"), Value::Undefined),
            "amount": self.safe_number(trade.clone(), Value::from("quantity"), Value::Undefined),
            "cost": Value::Undefined,
            "fee": Value::Undefined
        }))).unwrap()), Value::Undefined);
    }

    async fn watch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        timeframe = timeframe.or_default(Value::from("1m"));
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut timeframes: Value = self.safe_dict(self.get("options".into()), Value::from("timeframes"), Value::new_object());
        let mut interval: Value = self.safe_string(timeframes.clone(), timeframe.clone(), timeframe.clone());
        let mut args: Value = Value::from("candles") + interval.clone() + Value::from(":") + market.get(Value::from("id"));
        let mut message_hash: Value = Value::from("ohlcv:") + symbol.clone() + Value::from(":") + timeframe.clone();
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "subscribe",
            "args": Value::Json(serde_json::Value::Array(vec![args.clone().into()]))
        }))).unwrap());
        let mut ohlcvs: Value = self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = ohlcvs.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(ohlcvs.clone(), since.clone(), limit.clone(), Value::from(0), true.into());
    }

    async fn watch_ohlcv_for_symbols(&mut self, mut symbols_and_timeframes: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut symbols_length: usize = symbols_and_timeframes.len();
        if symbols_length.clone() == Value::from(0) || !Array::is_array(symbols_and_timeframes.get(Value::from(0))).is_truthy() {
            panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" watchOHLCVForSymbols() requires a an array of symbols and timeframes, like  [['BTC/USDT:OX', '1m'], ['OX/USDT', '5m']]"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut args: Value = Value::new_array();
        let mut message_hashes: Value = Value::new_array();
        let mut timeframes: Value = self.safe_dict(self.get("options".into()), Value::from("timeframes"), Value::new_object());
        let mut i: usize = 0;
        while i < symbols_and_timeframes.len() {
            let mut symbol_and_timeframe: Value = symbols_and_timeframes.get(i.into());
            let mut sym: Value = symbol_and_timeframe.get(Value::from(0));
            let mut tf: Value = symbol_and_timeframe.get(Value::from(1));
            let mut market_id: Value = self.market_id(sym.clone());
            let mut interval: Value = self.safe_string(timeframes.clone(), tf.clone(), tf.clone());
            let mut arg: Value = Value::from("candles") + interval.clone() + Value::from(":") + market_id.clone();
            args.push(arg.clone());
            let mut message_hash: Value = Value::from("multi:ohlcv:") + sym.clone() + Value::from(":") + tf.clone();
            message_hashes.push(message_hash.clone());
            i += 1;
        };
        let (mut symbol, mut timeframe, mut candles) = shift_3(<Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await);
        if self.get("newUpdates".into()).is_truthy() {
            limit = candles.get_limit(symbol.clone(), limit.clone());
        };
        let mut filtered: Value = self.filter_by_since_limit(candles.clone(), since.clone(), limit.clone(), Value::from(0), true.into());
        return self.create_ohlcv_object(symbol.clone(), timeframe.clone(), filtered.clone());
    }

    fn handle_ohlcv(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "candles60s",
        //         "data": [
        //             {
        //                 "marketCode": "BTC-USD-SWAP-LIN",
        //                 "candle": [
        //                     "1594313762698", //timestamp
        //                     "9633.1",        //open
        //                     "9693.9",        //high
        //                     "9238.1",        //low
        //                     "9630.2",        //close
        //                     "45247",         //volume in OX
        //                     "5.3"            //volume in Contracts
        //                 ]
        //             }
        //         ]
        //     }
        //
        let mut table: Value = self.safe_string(message.clone(), Value::from("table"), Value::Undefined);
        let mut parts: Value = table.split(Value::from("candles"));
        let mut timeframe_id: Value = self.safe_string(parts.clone(), Value::from(1), Value::from(""));
        let mut timeframe: Value = self.find_timeframe(timeframe_id.clone(), Value::Undefined);
        let mut message_data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut data: Value = self.safe_dict(message_data.clone(), Value::from(0), Value::new_object());
        let mut market_id: Value = self.safe_string(data.clone(), Value::from("marketCode"), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        if !self.get("ohlcvs".into()).contains_key(symbol.clone()) {
            self.get("ohlcvs".into()).set(symbol.clone(), Value::new_object());
        };
        if !self.get("ohlcvs".into()).get(symbol.clone()).contains_key(timeframe.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("OHLCVLimit"), Value::from(1000));
            self.get("ohlcvs".into()).get(symbol.clone()).set(timeframe.clone(), ArrayCacheByTimestamp::new(limit));
        };
        let mut candle: Value = self.safe_list(data.clone(), Value::from("candle"), Value::new_array());
        let mut parsed: Value = <Self as Oxfun>::parse_ws_ohlcv(self, candle.clone(), market.clone());
        let mut stored: Value = self.get("ohlcvs".into()).get(symbol.clone()).get(timeframe.clone());
        stored.append(parsed.clone());
        let mut message_hash: Value = Value::from("ohlcv:") + symbol.clone() + Value::from(":") + timeframe.clone();
        client.resolve(stored.clone(), message_hash.clone());
        // for multiOHLCV we need special object, as opposed to other "multi"
        // methods, because OHLCV response item does not contain symbol
        // or timeframe, thus otherwise it would be unrecognizable
        let mut message_hash_for_multi: Value = Value::from("multi:") + message_hash.clone();
        client.resolve(Value::Json(serde_json::Value::Array(vec![symbol.clone().into(), timeframe.clone().into(), stored.clone().into()])), message_hash_for_multi.clone());
        Value::Undefined
    }

    fn parse_ws_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        //
        //     [
        //         "1594313762698", //timestamp
        //         "9633.1",        //open
        //         "9693.9",        //high
        //         "9238.1",        //low
        //         "9630.2",        //close
        //         "45247",         //volume in OX
        //         "5.3"            //volume in Contracts
        //     ]
        //
        return Value::Json(serde_json::Value::Array(vec![self.safe_integer(ohlcv.clone(), Value::from(0), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from(1), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from(2), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from(3), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from(4), Value::Undefined).into(), self.safe_number(ohlcv.clone(), Value::from(6), Value::Undefined).into()]));
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Oxfun>::watch_order_book_for_symbols(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), limit.clone(), params.clone()).await;
    }

    async fn watch_order_book_for_symbols(&mut self, mut symbols: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, Value::Undefined, Value::Undefined, Value::Undefined);
        let mut channel: Value = Value::from("depth");
        let mut options: Value = self.safe_dict(self.get("options".into()), Value::from("watchOrderBook"), Value::new_object());
        let mut default_channel: Value = self.safe_string(options.clone(), Value::from("channel"), Value::Undefined);
        if default_channel.clone().is_nonnullish() {
            channel = default_channel.clone();
        } else if limit.clone().is_nonnullish() {
            if limit.clone() <= Value::from(5) {
                channel = Value::from("depthL5");
            } else if limit.clone() <= Value::from(10) {
                channel = Value::from("depthL10");
            } else if limit.clone() <= Value::from(25) {
                channel = Value::from("depthL25");
            };
        };
        let mut args: Value = Value::new_array();
        let mut message_hashes: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut message_hash: Value = Value::from("orderbook:") + symbol.clone();
            message_hashes.push(message_hash.clone());
            let mut market_id: Value = self.market_id(symbol.clone());
            let mut arg: Value = channel.clone() + Value::from(":") + market_id.clone();
            args.push(arg.clone());
            i += 1;
        };
        let mut orderbook: Value = <Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await;
        return orderbook.limit();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "depth",
        //         "data": {
        //             "seqNum": "100170478917895032",
        //             "asks": [
        //                 [ 0.01, 100500 ],
        //                 ...
        //             ],
        //             "bids": [
        //                 [ 69.69696, 69 ],
        //                 ...
        //             ],
        //             "checksum": 261021645,
        //             "marketCode": "OX-USDT",
        //             "timestamp": 1716204786184
        //         },
        //         "action": "partial"
        //     }
        //
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut market_id: Value = self.safe_string(data.clone(), Value::from("marketCode"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(data.clone(), Value::from("timestamp"), Value::Undefined);
        let mut message_hash: Value = Value::from("orderbook:") + symbol.clone();
        if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
            self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::new_object(), Value::Undefined));
        };
        let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
        let mut snapshot: Value = self.parse_order_book(data.clone(), symbol.clone(), timestamp.clone(), Value::from("asks"), Value::from("bids"), Value::Undefined, Value::Undefined, Value::Undefined);
        orderbook.reset(snapshot.clone());
        orderbook.set("nonce".into(), self.safe_integer(data.clone(), Value::from("seqNum"), Value::Undefined));
        self.get("orderbooks".into()).set(symbol.clone(), orderbook.clone());
        client.resolve(orderbook.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut ticker: Value = <Self as Oxfun>::watch_tickers(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), params.clone()).await;
        return self.safe_value(ticker.clone(), symbol.clone(), Value::Undefined);
    }

    async fn watch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut all_symbols: Value = (symbols.clone().is_nullish()).into();
        let mut sym: Value = symbols.clone();
        let mut args: Value = Value::new_array();
        if all_symbols.is_truthy() {
            sym = self.get("symbols".into());
            args.push(Value::from("ticker:all"));
        };
        let mut message_hashes: Value = Value::new_array();
        let mut i: usize = 0;
        while i < sym.len() {
            let mut symbol: Value = sym.get(i.into());
            let mut message_hash: Value = Value::from("tickers") + Value::from(":") + symbol.clone();
            message_hashes.push(message_hash.clone());
            let mut market_id: Value = self.market_id(symbol.clone());
            if !all_symbols.is_truthy() {
                args.push(Value::from("ticker:") + market_id.clone());
            };
            i += 1;
        };
        let mut new_ticker: Value = <Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut result: Value = Value::new_object();
            result.set(new_ticker.get(Value::from("symbol")), new_ticker.clone());
            return result.clone();
        };
        return self.filter_by_array(self.get("tickers".into()), Value::from("symbol"), symbols.clone(), Value::Undefined);
    }

    fn handle_ticker(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "ticker",
        //         "data": [
        //             {
        //                 "last": "3088.6",
        //                 "open24h": "3087.2",
        //                 "high24h": "3142.0",
        //                 "low24h": "3053.9",
        //                 "volume24h": "450512672.1800",
        //                 "currencyVolume24h": "1458.579",
        //                 "openInterest": "3786.801",
        //                 "marketCode": "ETH-USD-SWAP-LIN",
        //                 "timestamp": "1716212747050",
        //                 "lastQty": "0.813",
        //                 "markPrice": "3088.6",
        //                 "lastMarkPrice": "3088.6",
        //                 "indexPrice": "3086.5"
        //             },
        //             ...
        //         ]
        //     }
        //
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut i: usize = 0;
        while i < data.len() {
            let mut raw_ticker: Value = self.safe_dict(data.clone(), Value::from(i), Value::new_object());
            let mut ticker: Value = self.parse_ticker(raw_ticker.clone(), Value::Undefined);
            let mut symbol: Value = ticker.get(Value::from("symbol"));
            let mut message_hash: Value = Value::from("tickers:") + symbol.clone();
            self.get("tickers".into()).set(symbol.clone(), ticker.clone());
            client.resolve(ticker.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    async fn watch_bids_asks(&mut self, mut symbols: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into(), Value::Undefined, Value::Undefined);
        let mut message_hashes: Value = Value::new_array();
        let mut args: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut market: Value = self.market(symbols.get(i.into()));
            args.push(Value::from("bestBidAsk:") + market.get(Value::from("id")));
            message_hashes.push(Value::from("bidask:") + market.get(Value::from("symbol")));
            i += 1;
        };
        let mut new_tickers: Value = <Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut tickers: Value = Value::new_object();
            tickers.set(new_tickers.get(Value::from("symbol")), new_tickers.clone());
            return tickers.clone();
        };
        return self.filter_by_array(self.get("bidsasks".into()), Value::from("symbol"), symbols.clone(), Value::Undefined);
    }

    fn handle_bid_ask(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //       "table": "bestBidAsk",
        //       "data": {
        //         "ask": [
        //           19045.0,
        //           1.0
        //         ],
        //         "checksum": 3790706311,
        //         "marketCode": "BTC-USD-SWAP-LIN",
        //         "bid": [
        //           19015.0,
        //           1.0
        //         ],
        //         "timestamp": "1665456882928"
        //       }
        //     }
        //
        let mut data: Value = self.safe_dict(message.clone(), Value::from("data"), Value::new_object());
        let mut parsed_ticker: Value = <Self as Oxfun>::parse_ws_bid_ask(self, data.clone());
        let mut symbol: Value = parsed_ticker.get(Value::from("symbol"));
        self.get("bidsasks".into()).set(symbol.clone(), parsed_ticker.clone());
        let mut message_hash: Value = Value::from("bidask:") + symbol.clone();
        client.resolve(parsed_ticker.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_bid_ask(&self, mut ticker: Value, mut market: Value) -> Value {
        let mut market_id: Value = self.safe_string(ticker.clone(), Value::from("marketCode"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut symbol: Value = self.safe_string(market.clone(), Value::from("symbol"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(ticker.clone(), Value::from("timestamp"), Value::Undefined);
        let mut ask: Value = self.safe_list(ticker.clone(), Value::from("ask"), Value::new_array());
        let mut bid: Value = self.safe_list(ticker.clone(), Value::from("bid"), Value::new_array());
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "ask": self.safe_number(ask.clone(), Value::from(0), Value::Undefined),
            "askVolume": self.safe_number(ask.clone(), Value::from(1), Value::Undefined),
            "bid": self.safe_number(bid.clone(), Value::from(0), Value::Undefined),
            "bidVolume": self.safe_number(bid.clone(), Value::from(1), Value::Undefined),
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn watch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self);
        let mut args: Value = Value::from("balance:all");
        let mut message_hash: Value = Value::from("balance");
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "subscribe",
            "args": Value::Json(serde_json::Value::Array(vec![args.clone().into()]))
        }))).unwrap());
        return self.watch(url.clone(), message_hash.clone(), extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
    }

    fn handle_balance(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "balance",
        //         "accountId": "106464",
        //         "timestamp": "1716549132780",
        //         "tradeType": "PORTFOLIO",
        //         "data": [
        //             {
        //                 "instrumentId": "xOX",
        //                 "total": "23.375591220",
        //                 "available": "23.375591220",
        //                 "reserved": "0",
        //                 "quantityLastUpdated": "1716509744262",
        //                 "locked": "0"
        //             },
        //             ...
        //         ]
        //     }
        //
        let mut balances: Value = self.safe_list(message.clone(), Value::from("data"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(message.clone(), Value::from("timestamp"), Value::Undefined);
        self.get("balance".into()).set("info".into(), message.clone());
        self.get("balance".into()).set("timestamp".into(), timestamp.clone());
        self.get("balance".into()).set("datetime".into(), self.iso8601(timestamp.clone()));
        let mut i: usize = 0;
        while i < balances.len() {
            let mut balance: Value = self.safe_dict(balances.clone(), Value::from(i), Value::new_object());
            let mut currency_id: Value = self.safe_string(balance.clone(), Value::from("instrumentId"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            if !self.get("balance".into()).contains_key(code.clone()) {
                self.get("balance".into()).set(code.clone(), self.account());
            };
            let mut account: Value = self.get("balance".into()).get(code.clone());
            account.set("total".into(), self.safe_string(balance.clone(), Value::from("total"), Value::Undefined));
            account.set("used".into(), self.safe_string(balance.clone(), Value::from("reserved"), Value::Undefined));
            account.set("free".into(), self.safe_string(balance.clone(), Value::from("available"), Value::Undefined));
            self.get("balance".into()).set(code.clone(), account.clone());
            i += 1;
        };
        self.set("balance".into(), self.safe_balance(self.get("balance".into())));
        client.resolve(self.get("balance".into()), Value::from("balance"));
        Value::Undefined
    }

    async fn watch_positions(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut all_symbols: Value = (symbols.clone().is_nullish()).into();
        let mut sym: Value = symbols.clone();
        let mut args: Value = Value::new_array();
        if all_symbols.is_truthy() {
            sym = self.get("symbols".into());
            args.push(Value::from("position:all"));
        };
        let mut message_hashes: Value = Value::new_array();
        let mut i: usize = 0;
        while i < sym.len() {
            let mut symbol: Value = sym.get(i.into());
            let mut message_hash: Value = Value::from("positions") + Value::from(":") + symbol.clone();
            message_hashes.push(message_hash.clone());
            let mut market_id: Value = self.market_id(symbol.clone());
            if !all_symbols.is_truthy() {
                args.push(Value::from("position:") + market_id.clone());
            };
            i += 1;
        };
        let mut new_positions: Value = <Self as Oxfun>::subscribe_multiple(self, message_hashes.clone(), args.clone(), params.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            return new_positions.clone();
        };
        return self.filter_by_symbols_since_limit(self.get("positions".into()), symbols.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_positions(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "position",
        //         "accountId": "106464",
        //         "timestamp": "1716550771582",
        //         "data": [
        //             {
        //                 "instrumentId": "ETH-USD-SWAP-LIN",
        //                 "quantity": "0.01",
        //                 "lastUpdated": "1716550757299",
        //                 "contractValCurrency": "ETH",
        //                 "entryPrice": "3709.6",
        //                 "positionPnl": "-5.000",
        //                 "estLiquidationPrice": "743.4",
        //                 "margin": "0",
        //                 "leverage": "0"
        //             }
        //         ]
        //     }
        //
        if self.get("positions".into()).is_nullish() {
            self.set("positions".into(), ArrayCacheBySymbolBySide::new());
        };
        let mut cache: Value = self.get("positions".into());
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut i: usize = 0;
        while i < data.len() {
            let mut raw_position: Value = self.safe_dict(data.clone(), Value::from(i), Value::new_object());
            let mut position: Value = <Self as Oxfun>::parse_ws_position(self, raw_position.clone());
            let mut symbol: Value = position.get(Value::from("symbol"));
            let mut message_hash: Value = Value::from("positions:") + symbol.clone();
            cache.append(position.clone());
            client.resolve(position.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    fn parse_ws_position(&self, mut position: Value, mut market: Value) -> Value {
        //
        //     {
        //         "instrumentId": "ETH-USD-SWAP-LIN",
        //         "quantity": "0.01",
        //         "lastUpdated": "1716550757299",
        //         "contractValCurrency": "ETH",
        //         "entryPrice": "3709.6",
        //         "positionPnl": "-5.000",
        //         "estLiquidationPrice": "743.4",
        //         "margin": "0", // Currently always reports 0
        //         "leverage": "0" // Currently always reports 0
        //     }
        //
        let mut market_id: Value = self.safe_string(position.clone(), Value::from("instrumentId"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        return self.safe_position(Value::Json(normalize(&Value::Json(json!({
            "info": position,
            "id": Value::Undefined,
            "symbol": market.get(Value::from("symbol")),
            "notional": Value::Undefined,
            "marginMode": "cross",
            "liquidationPrice": self.safe_number(position.clone(), Value::from("estLiquidationPrice"), Value::Undefined),
            "entryPrice": self.safe_number(position.clone(), Value::from("entryPrice"), Value::Undefined),
            "unrealizedPnl": self.safe_number(position.clone(), Value::from("positionPnl"), Value::Undefined),
            "realizedPnl": Value::Undefined,
            "percentage": Value::Undefined,
            "contracts": self.safe_number(position.clone(), Value::from("quantity"), Value::Undefined),
            "contractSize": Value::Undefined,
            "markPrice": Value::Undefined,
            "lastPrice": Value::Undefined,
            "side": Value::Undefined,
            "hedged": Value::Undefined,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "lastUpdateTimestamp": self.safe_integer(position.clone(), Value::from("lastUpdated"), Value::Undefined),
            "maintenanceMargin": Value::Undefined,
            "maintenanceMarginPercentage": Value::Undefined,
            "collateral": Value::Undefined,
            "initialMargin": Value::Undefined,
            "initialMarginPercentage": Value::Undefined,
            "leverage": Value::Undefined,
            "marginRatio": Value::Undefined,
            "stopLossPrice": Value::Undefined,
            "takeProfitPrice": Value::Undefined
        }))).unwrap()));
    }

    async fn watch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut message_hash: Value = Value::from("orders");
        let mut args: Value = Value::from("order:");
        let mut market: Value = self.safe_market(symbol.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        if symbol.clone().is_nullish() {
            args = args +  Value::from("all");
        } else {
            message_hash = message_hash +  Value::from(":") + symbol.clone();
            args = args +  Value::from(":") + market.get(Value::from("id"));
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "subscribe",
            "args": Value::Json(serde_json::Value::Array(vec![args.clone().into()]))
        }))).unwrap());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        let mut orders: Value = self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = orders.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_symbol_since_limit(orders.clone(), symbol.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_orders(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "table": "order",
        //         "data": [
        //             {
        //                 "accountId": "106464",
        //                 "clientOrderId": "1716713676233",
        //                 "orderId": "1000116921319",
        //                 "price": "1000.0",
        //                 "quantity": "0.01",
        //                 "amount": "0.0",
        //                 "side": "BUY",
        //                 "status": "OPEN",
        //                 "marketCode": "ETH-USD-SWAP-LIN",
        //                 "timeInForce": "MAKER_ONLY",
        //                 "timestamp": "1716713677834",
        //                 "remainQuantity": "0.01",
        //                 "limitPrice": "1000.0",
        //                 "notice": "OrderOpened",
        //                 "orderType": "LIMIT",
        //                 "isTriggered": "false",
        //                 "displayQuantity": "0.01"
        //             }
        //         ]
        //     }
        //
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut message_hash: Value = Value::from("orders");
        if self.get("orders".into()).is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("ordersLimit"), Value::from(1000));
            self.set("orders".into(), ArrayCacheBySymbolById::new(limit));
        };
        let mut orders: Value = self.get("orders".into());
        let mut i: usize = 0;
        while i < data.len() {
            let mut order: Value = self.safe_dict(data.clone(), Value::from(i), Value::new_object());
            let mut parsed_order: Value = self.parse_order(order.clone(), Value::Undefined);
            orders.append(parsed_order.clone());
            message_hash = message_hash +  Value::from(":") + parsed_order.get(Value::from("symbol"));
            client.resolve(self.get("orders".into()), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    async fn create_order_ws(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut message_hash: Value = self.nonce().to_string();
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "placeorder",
            "tag": message_hash
        }))).unwrap());
        params = self.omit(params.clone(), Value::from("tag"));
        let mut order_request: Value = <Self as Oxfun>::create_order_request(self, symbol.clone(), r#type.clone(), side.clone(), amount.clone(), price.clone(), params.clone());
        let mut timestamp: Value = self.safe_integer(order_request.clone(), Value::from("timestamp"), Value::Undefined);
        if timestamp.clone().is_nullish() {
            order_request.set("timestamp".into(), self.milliseconds());
        };
        request.set("data".into(), order_request.clone());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        return self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
    }

    async fn edit_order_ws(&mut self, mut id: Value, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut message_hash: Value = self.nonce().to_string();
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "modifyorder",
            "tag": message_hash
        }))).unwrap());
        params = self.omit(params.clone(), Value::from("tag"));
        let mut order_request: Value = <Self as Oxfun>::create_order_request(self, symbol.clone(), r#type.clone(), side.clone(), amount.clone(), price.clone(), params.clone());
        order_request = extend_2(order_request.clone(), Value::Json(normalize(&Value::Json(json!({
            "orderId": id
        }))).unwrap()));
        let mut timestamp: Value = self.safe_integer(order_request.clone(), Value::from("timestamp"), Value::Undefined);
        if timestamp.clone().is_nullish() {
            order_request.set("timestamp".into(), self.milliseconds());
        };
        request.set("data".into(), order_request.clone());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        return self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
    }

    fn handle_place_orders(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         "event": "placeorder",
        //         "submitted": true,
        //         "tag": "1716934577",
        //         "timestamp": "1716932973899",
        //         "data": {
        //             "marketCode": "ETH-USD-SWAP-LIN",
        //             "side": "BUY",
        //             "orderType": "LIMIT",
        //             "quantity": "0.010",
        //             "timeInForce": "GTC",
        //             "price": "400.0",
        //             "limitPrice": "400.0",
        //             "orderId": "1000117429736",
        //             "source": 13
        //         }
        //     }
        //
        //
        // Failure response format
        //     {
        //         "event": "placeorder",
        //         "submitted": false,
        //         "message": "JSON data format is invalid",
        //         "code": "20009",
        //         "timestamp": "1716932877381"
        //     }
        //
        let mut message_hash: Value = self.safe_string(message.clone(), Value::from("tag"), Value::Undefined);
        let mut submitted: Value = self.safe_bool(message.clone(), Value::from("submitted"), Value::Undefined);
        // filter out partial errors
        if !submitted.is_truthy() {
            let mut method: Value = self.safe_string(message.clone(), Value::from("event"), Value::Undefined);
            let mut string_msg: Value = self.json(message.clone());
            let mut code: Value = self.safe_integer(message.clone(), Value::from("code"), Value::Undefined);
            self.handle_errors(code.clone(), Value::from(""), client.get(url.clone()), method.clone(), Value::new_object(), string_msg.clone(), message.clone(), Value::new_object(), Value::new_object());
        };
        let mut data: Value = self.safe_value(message.clone(), Value::from("data"), Value::new_object());
        let mut order: Value = self.parse_order(data.clone(), Value::Undefined);
        client.resolve(order.clone(), message_hash.clone());
        Value::Undefined
    }

    async fn cancel_order_ws(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if symbol.clone().is_nullish() {
            panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" cancelOrderWs() requires a symbol argument"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut message_hash: Value = self.nonce().to_string();
        let mut data: Value = Value::Json(normalize(&Value::Json(json!({
            "marketCode": self.market_id(symbol.clone()),
            "orderId": id
        }))).unwrap());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "cancelorder",
            "tag": message_hash,
            "data": data
        }))).unwrap());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        return self.watch(url.clone(), message_hash.clone(), request.clone(), message_hash.clone(), Value::Undefined).await;
    }

    async fn cancel_orders_ws(&mut self, mut ids: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut ids_length: usize = ids.len();
        if ids_length.clone() > Value::from(20) {
            panic!(r###"BadRequest::new(self.get("id".into()) + Value::from(" cancelOrdersWs() accepts up to 20 ids at a time"))"###);
        };
        if symbol.clone().is_nullish() {
            panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" cancelOrdersWs() requires a symbol argument"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Oxfun>::authenticate(self).await;
        let mut message_hash: Value = self.nonce().to_string();
        let mut market_id: Value = self.market_id(symbol.clone());
        let mut data_array: Value = Value::new_array();
        let mut i: usize = 0;
        while i < ids_length.clone().into() {
            let mut data: Value = Value::Json(normalize(&Value::Json(json!({
                "instId": market_id,
                "ordId": ids.get(i.into())
            }))).unwrap());
            data_array.push(data.clone());
            i += 1;
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "op": "cancelorders",
            "tag": message_hash,
            "dataArray": data_array
        }))).unwrap());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        return self.watch(url.clone(), message_hash.clone(), self.deep_extend_2(request.clone(), params.clone()), message_hash.clone(), Value::Undefined).await;
    }

    async fn authenticate(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws"));
        let mut client: Value = self.client(url.clone());
        let mut message_hash: Value = Value::from("authenticated");
        let mut future: Value = client.reusable_future(message_hash.clone());
        let mut authenticated: Value = self.safe_dict(client.get(subscriptions.clone()), message_hash.clone(), Value::Undefined);
        if authenticated.clone().is_nullish() {
            self.check_required_credentials(Value::Undefined);
            let mut timestamp: Value = self.milliseconds();
            let mut payload: Value = timestamp.to_string() + Value::from("GET/auth/self/verify");
            let mut signature: Value = self.hmac(self.encode(payload.clone()), self.encode(self.get("secret".into())), sha256().clone(), Value::from("base64"));
            let mut request: Value = Value::Json(normalize(&Value::Json(json!({
                "op": "login",
                "data": Value::Json(normalize(&Value::Json(json!({
                    "apiKey": self.get("apiKey".into()),
                    "timestamp": timestamp,
                    "signature": signature
                }))).unwrap())
            }))).unwrap());
            let mut message: Value = extend_2(request.clone(), params.clone());
            self.watch(url.clone(), message_hash.clone(), message.clone(), message_hash.clone(), Value::Undefined);
        };
        return future.clone();
    }

    fn handle_authentication_message(&mut self, mut client: Value, mut message: Value) -> Value {
        let mut authenticated: Value = self.safe_bool(message.clone(), Value::from("success"), false.into());
        let mut message_hash: Value = Value::from("authenticated");
        if authenticated.is_truthy() {
            // we resolve the future here permanently so authentication only happens once
            let mut future: Value = self.safe_dict(client.get(futures.clone()), message_hash.clone(), Value::Undefined);
            future.resolve(true.into());
        } else {
            let mut error: Value = AuthenticationError::new(self.json(message.clone()));
            client.reject(error.clone(), message_hash.clone());
            if client.get(subscriptions.clone()).contains_key(message_hash.clone()) {
                client.get(subscriptions.clone()).get(message_hash.clone());
            };
        };
        Value::Undefined
    }

    fn ping(&mut self, mut client: Value) -> Value {
        return Value::from("ping");
    }

    fn handle_pong(&mut self, mut client: Value, mut message: Value) -> Value {
        client.set("last_pong".into(), self.milliseconds());
        return message.clone();
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        if message.clone() == Value::from("pong") {
            <Self as Oxfun>::handle_pong(self, client.clone(), message.clone());
            return Value::Undefined;
        };
        let mut table: Value = self.safe_string(message.clone(), Value::from("table"), Value::Undefined);
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut event: Value = self.safe_string(message.clone(), Value::from("event"), Value::Undefined);
        if table.clone().is_nonnullish() && data.clone().is_nonnullish() {
            if table.clone() == Value::from("trade") {
                <Self as Oxfun>::handle_trades(self, client.clone(), message.clone());
            };
            if table.clone() == Value::from("ticker") {
                <Self as Oxfun>::handle_ticker(self, client.clone(), message.clone());
            };
            if table.index_of(Value::from("candles")) > Value::from(1).neg() {
                <Self as Oxfun>::handle_ohlcv(self, client.clone(), message.clone());
            };
            if table.index_of(Value::from("depth")) > Value::from(1).neg() {
                <Self as Oxfun>::handle_order_book(self, client.clone(), message.clone());
            };
            if table.index_of(Value::from("balance")) > Value::from(1).neg() {
                <Self as Oxfun>::handle_balance(self, client.clone(), message.clone());
            };
            if table.index_of(Value::from("position")) > Value::from(1).neg() {
                <Self as Oxfun>::handle_positions(self, client.clone(), message.clone());
            };
            if table.index_of(Value::from("order")) > Value::from(1).neg() {
                <Self as Oxfun>::handle_orders(self, client.clone(), message.clone());
            };
            if table.clone() == Value::from("bestBidAsk") {
                <Self as Oxfun>::handle_bid_ask(self, client.clone(), message.clone());
            };
        } else {
            if event.clone() == Value::from("login") {
                <Self as Oxfun>::handle_authentication_message(self, client.clone(), message.clone());
            };
            if event.clone() == Value::from("placeorder") || event.clone() == Value::from("modifyorder") || event.clone() == Value::from("cancelorder") {
                <Self as Oxfun>::handle_place_orders(self, client.clone(), message.clone());
            };
        };
        Value::Undefined
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetV3markets" => self.request("v3/markets".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3assets" => self.request("v3/assets".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3tickers" => self.request("v3/tickers".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3fundingestimates" => self.request("v3/funding/estimates".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3candles" => self.request("v3/candles".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3depth" => self.request("v3/depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3marketsoperational" => self.request("v3/markets/operational".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3exchangetrades" => self.request("v3/exchange-trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3fundingrates" => self.request("v3/funding/rates".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetV3leveragetiers" => self.request("v3/leverage/tiers".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3account" => self.request("v3/account".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3accountnames" => self.request("v3/account/names".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3wallet" => self.request("v3/wallet".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3transfer" => self.request("v3/transfer".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3balances" => self.request("v3/balances".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3positions" => self.request("v3/positions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3funding" => self.request("v3/funding".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3depositaddresses" => self.request("v3/deposit-addresses".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3deposit" => self.request("v3/deposit".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3withdrawaladdresses" => self.request("v3/withdrawal-addresses".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3withdrawal" => self.request("v3/withdrawal".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3withdrawalfees" => self.request("v3/withdrawal-fees".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3ordersstatus" => self.request("v3/orders/status".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3ordersworking" => self.request("v3/orders/working".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetV3trades" => self.request("v3/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV3transfer" => self.request("v3/transfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV3withdrawal" => self.request("v3/withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostV3ordersplace" => self.request("v3/orders/place".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteV3orderscancel" => self.request("v3/orders/cancel".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteV3orderscancelall" => self.request("v3/orders/cancel-all".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => unimplemented!(),
                }
            },
            _ => unimplemented!()
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OxfunImpl(Value);
impl Exchange for OxfunImpl {}
impl Oxfun for OxfunImpl {}
impl ValueTrait for OxfunImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl OxfunImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = OxfunImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Oxfun::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

