#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Toobit : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "toobit",
            "name": "Toobit",
            "countries": [
                "KY"
            ],
            "enableRateLimit": true,
            "rateLimit": 20,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": true,
                "future": false,
                "option": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "cancelOrders": true,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBidsAsks": true,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": true,
                "fetchDeposits": true,
                "fetchFundingRateHistory": true,
                "fetchFundingRates": true,
                "fetchIndexOHLCV": true,
                "fetchL2OrderBook": true,
                "fetchLastPrices": true,
                "fetchLedger": true,
                "fetchMarkets": true,
                "fetchMarkOHLCV": true,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenOrders": true,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchStatus": true,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchTime": true,
                "fetchTrades": true,
                "fetchWithdrawals": true,
                "setMarginMode": true,
                "transfer": true,
                "watchBalance": true,
                "watchMyTrades": true,
                "watchOHLCV": true,
                "watchOHLCVForSymbols": true,
                "watchOrderBook": true,
                "watchOrderBookForSymbols": true,
                "watchOrders": true,
                "watchTicker": true,
                "watchTickers": true,
                "watchTrades": true,
                "watchTradesForSymbols": true,
                "withdraw": true,
                "ws": true
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/0c7a97d5-182c-492e-b921-23540c868e0e",
                "api": {
                    "common": "https://api.toobit.com",
                    "private": "https://api.toobit.com",
                    "ws": {
                        "common": "wss://stream.toobit.com"
                    }
                },
                "www": "https://www.toobit.com/",
                "doc": [
                    "https://toobit-docs.github.io/apidocs/spot/v1/en/",
                    "https://toobit-docs.github.io/apidocs/usdt_swap/v1/en/"
                ],
                "fees": "https://www.toobit.com/fee",
                "referral": {
                    "url": "https://www.toobit.com/en-US/r?i=IFFPy0",
                    "discount": 0.1
                }
            },
            "api": {
                "common": {
                    "get": {
                        "api/v1/time": 1,
                        "api/v1/ping": 1,
                        "api/v1/exchangeInfo": 1,
                        "quote/v1/depth": 1,
                        "quote/v1/depth/merged": 1,
                        "quote/v1/trades": 1,
                        "quote/v1/klines": 1,
                        "quote/v1/index/klines": 1,
                        "quote/v1/markPrice/klines": 1,
                        "quote/v1/markPrice": 1,
                        "quote/v1/index": 1,
                        "quote/v1/ticker/24hr": 40,
                        "quote/v1/contract/ticker/24hr": 40,
                        "quote/v1/ticker/price": 1,
                        "quote/v1/ticker/bookTicker": 1,
                        "api/v1/futures/fundingRate": 1,
                        "api/v1/futures/historyFundingRate": 1
                    }
                },
                "private": {
                    "get": {
                        "api/v1/account": 5,
                        "api/v1/account/checkApiKey": 1,
                        "api/v1/spot/order": 1.67,
                        "api/v1/spot/openOrders": 1.67,
                        "api/v1/futures/openOrders": 1.67,
                        "api/v1/spot/tradeOrders": 8.35,
                        "api/v1/futures/historyOrders": 8.35,
                        "api/v1/account/trades": 8.35,
                        "api/v1/account/balanceFlow": 5,
                        "api/v1/account/depositOrders": 5,
                        "api/v1/account/withdrawOrders": 5,
                        "api/v1/account/deposit/address": 1,
                        "api/v1/subAccount": 5,
                        "api/v1/futures/accountLeverage": 1,
                        "api/v1/futures/order": 1.67,
                        "api/v1/futures/positions": 8.35,
                        "api/v1/futures/balance": 5,
                        "api/v1/futures/userTrades": 8.35,
                        "api/v1/futures/balanceFlow": 5,
                        "api/v1/futures/commissionRate": 5,
                        "api/v1/futures/todayPnl": 5
                    },
                    "post": {
                        "api/v1/spot/orderTest": 1.67,
                        "api/v1/spot/order": 1.67,
                        "api/v1/futures/order": 1.67,
                        "api/v1/spot/batchOrders": 3.34,
                        "api/v1/subAccount/transfer": 1,
                        "api/v1/account/withdraw": 1,
                        "api/v1/futures/marginType": 1,
                        "api/v1/futures/leverage": 1,
                        "api/v1/futures/batchOrders": 3.34,
                        "api/v1/futures/position/trading-stop": 5.01,
                        "api/v1/futures/positionMargin": 1,
                        "api/v1/userDataStream": 1,
                        "api/v1/listenKey": 1
                    },
                    "delete": {
                        "api/v1/spot/order": 1.67,
                        "api/v1/futures/order": 1.67,
                        "api/v1/spot/openOrders": 8.35,
                        "api/v1/futures/batchOrders": 8.35,
                        "api/v1/spot/cancelOrderByIds": 8.35,
                        "api/v1/futures/cancelOrderByIds": 8.35,
                        "api/v1/listenKey": 1
                    },
                    "put": {
                        "api/v1/listenKey": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1m",
                "3m": "3m",
                "5m": "5m",
                "15m": "15m",
                "30m": "30m",
                "1h": "1h",
                "2h": "2h",
                "4h": "4h",
                "6h": "6h",
                "8h": "8h",
                "12h": "12h",
                "1d": "1d",
                "1w": "1w",
                "1M": "1M"
            },
            "fees": {
                "trading": {},
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {},
                "ws": {
                    "exact": {}
                }
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "options": {
                "defaultType": "spot",
                "accountsByType": {
                    "spot": "MAIN",
                    "swap": "FUTURES"
                },
                "networks": {
                    "BTC": "BTC",
                    "ERC20": "ETH",
                    "ETH": "ETH",
                    "BEP20": "BSC",
                    "TRC20": "TRX",
                    "SOL": "SOL",
                    "MATIC": "MATIC",
                    "ARBONE": "ARBITRUM",
                    "BASE": "BASE",
                    "TON": "TON",
                    "AVAXC": "AVAXC",
                    "DOGE": "DOGE",
                    "XRP": "XRP",
                    "DOT": "DOT",
                    "ADA": "ADA",
                    "LTC": "LTC",
                    "APT": "APT",
                    "ATOM": "ATOM",
                    "ALGO": "ALGO",
                    "NEAR": "NEAR",
                    "XLM": "XLM",
                    "SUI": "SUI",
                    "ETC": "ETC",
                    "EOS": "EOS",
                    "WAVES": "WAVES",
                    "ICP": "ICP",
                    "ONE": "ONE"
                },
                "networksById": {
                    "ETH": "ERC20",
                    "ERC20": "ERC20"
                },
                "ws": {
                    "timeframes": {
                        "1m": "1m",
                        "3m": "3m",
                        "5m": "5m",
                        "15m": "15m",
                        "30m": "30m",
                        "1h": "1h",
                        "2h": "2h",
                        "4h": "4h",
                        "6h": "6h",
                        "8h": "8h",
                        "12h": "12h",
                        "1d": "1d",
                        "1w": "1w",
                        "1M": "1M"
                    },
                    "watchOrderBook": {
                        "channel": "depth"
                    },
                    "listenKeyRefreshRate": 1200000
                }
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "untilDays": 100000,
                        "symbolRequired": true
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 500,
                        "daysBack": 100000,
                        "untilDays": 100000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    }
                },
                "forDerivatives": {},
                "swap": {},
                "future": {}
            },
            "streaming": {
                "keepAlive": 295000
            }
        }"###).unwrap())
    }

    fn ping(&mut self, mut client: Value) -> Value {
        return Value::Json(normalize(&Value::Json(json!({
            "ping": self.milliseconds()
        }))).unwrap());
    }

    fn handle_message(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // public
        //
        //     {
        //         topic: "trade",
        //         symbol: "DOGEUSDT",
        //         symbolName: "DOGEUSDT",
        //         params: {
        //             realtimeInterval: "24h",
        //             binary: "false",
        //         },
        //         data: [
        //             {
        //                 v: "4864732022868004630",
        //                 t: 1757243788405,
        //                 p: "0.21804",
        //                 q: "80",
        //                 m: true,
        //             },
        //         ],
        //         f: true,  // initial first snapshot or not
        //         sendTime: 1757244002117,
        //         shared: false,
        //     }
        //
        // private
        //
        //     [
        //       {
        //         e: 'outboundContractAccountInfo',
        //         E: '1758228398234',
        //         T: true,
        //         W: true,
        //         D: true,
        //         B: [ [Object] ]
        //       }
        //     ]
        //
        let mut topic: Value = self.safe_string(message.clone(), Value::from("topic"), Value::Undefined);
        if <Self as Toobit>::handle_error_message(self, client.clone(), message.clone()).is_truthy() {
            return Value::Undefined;
        };
        //
        // handle ping-pong: { ping: 1758540450000 }
        //
        let mut pong_timestamp: Value = self.safe_integer(message.clone(), Value::from("pong"), Value::Undefined);
        if pong_timestamp.clone().is_nonnullish() {
            <Self as Toobit>::handle_incoming_pong(self, client.clone(), pong_timestamp.clone());
            return Value::Undefined;
        };
        let mut methods: Value = Value::Json(normalize(&Value::Json(json!({
            "trade": self.get("handleTrades".into()),
            "kline": self.get("handleOHLCV".into()),
            "realtimes": self.get("handleTickers".into()),
            "depth": self.get("handleOrderBookPartialSnapshot".into()),
            "diffDepth": self.get("handleOrderBook".into()),
            "outboundAccountInfo": self.get("handleBalance".into()),
            "outboundContractAccountInfo": self.get("handleBalance".into()),
            "executionReport": self.get("handleOrder".into()),
            "contractExecutionReport": self.get("handleOrder".into()),
            "ticketInfo": self.get("handleMyTrade".into()),
            "outboundContractPositionInfo": self.get("handlePositions".into())
        }))).unwrap());
        let mut method: Value = self.safe_value(methods.clone(), topic.clone(), Value::Undefined);
        if method.clone().is_nonnullish() {
            method.call(self, client.clone(), message.clone());
        } else {
            // check private streams
            let mut i: usize = 0;
            while i < message.len() {
                let mut item: Value = message.get(i.into());
                let mut event: Value = self.safe_string(item.clone(), Value::from("e"), Value::Undefined);
                let mut method2: Value = self.safe_value(methods.clone(), event.clone(), Value::Undefined);
                if method2.clone().is_nonnullish() {
                    method2.call(self, client.clone(), item.clone());
                };
                i += 1;
            };
        };
        Value::Undefined
    }

    fn handle_incoming_pong(&mut self, mut client: Value, mut pong_timestamp: Value) -> Value {
        client.set("last_pong".into(), pong_timestamp.clone());
        Value::Undefined
    }

    async fn watch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Toobit>::watch_trades_for_symbols(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn watch_trades_for_symbols(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into());
        let mut message_hashes: Value = Value::new_array();
        let mut sub_params: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut market: Value = self.market(symbol.clone());
            message_hashes.push(Value::from("trade::") + symbol.clone());
            let mut raw_hash: Value = market.get(Value::from("id"));
            sub_params.push(raw_hash.clone());
            i += 1;
        };
        let mut market_ids: Value = self.market_ids(symbols.clone());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("common")) + Value::from("/quote/ws/v1");
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market_ids.join(Value::from(",")),
            "topic": "trade",
            "event": "sub"
        }))).unwrap());
        let mut trades: Value = self.watch_multiple(url.clone(), message_hashes.clone(), extend_2(request.clone(), params.clone()), message_hashes.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut first: Value = self.safe_value(trades.clone(), Value::from(0), Value::Undefined);
            let mut trade_symbol: Value = self.safe_string(first.clone(), Value::from("symbol"), Value::Undefined);
            limit = trades.get_limit(trade_symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_trades(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         symbol: "DOGEUSDT",
        //         symbolName: "DOGEUSDT",
        //         topic: "trade",
        //         params: {
        //             realtimeInterval: "24h",
        //             binary: "false",
        //         },
        //         data: [
        //             {
        //                 v: "4864732022868004630",
        //                 t: 1757243788405,
        //                 p: "0.21804",
        //                 q: "80",
        //                 m: true,
        //             },
        //         ],
        //         f: true,  // initial first snapshot or not
        //         sendTime: 1757244002117,
        //         shared: false,
        //     }
        //
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        if !self.get("trades".into()).contains_key(symbol.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            self.get("trades".into()).set(symbol.clone(), ArrayCache::new(limit));
        };
        let mut stored: Value = self.get("trades".into()).get(symbol.clone());
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut parsed: Value = self.parse_ws_trades(data.clone(), market.clone());
        let mut i: usize = 0;
        while i < parsed.len() {
            let mut trade: Value = parsed.get(i.into());
            trade.set("symbol".into(), symbol.clone());
            stored.append(trade.clone());
            i += 1;
        };
        let mut message_hash: Value = Value::from("trade::") + symbol.clone();
        client.resolve(stored.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_trade(&self, mut trade: Value, mut market: Value) -> Value {
        return self.parse_trade(trade.clone(), market.clone());
    }

    async fn watch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        timeframe = timeframe.or_default(Value::from("1m"));
        params = params.or_default(Value::new_object());
        params.set("callerMethodName".into(), Value::from("watchOHLCV"));
        let mut result: Value = <Self as Toobit>::watch_ohlcv_for_symbols(self, Value::Json(serde_json::Value::Array(vec![Value::Json(serde_json::Value::Array(vec![symbol.clone().into(), timeframe.clone().into()])).into()])), since.clone(), limit.clone(), params.clone()).await;
        return result.get(symbol.clone()).get(timeframe.clone());
    }

    async fn watch_ohlcv_for_symbols(&mut self, mut symbols_and_timeframes: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("common")) + Value::from("/quote/ws/v1");
        let mut message_hashes: Value = Value::new_array();
        let mut timeframes: Value = self.safe_dict(self.get("options".into()).get(Value::from("ws")), Value::from("timeframes"), Value::new_object());
        let mut market_ids: Value = Value::new_array();
        let mut selected_timeframe: Value = Value::Undefined;
        let mut i: usize = 0;
        while i < symbols_and_timeframes.len() {
            let mut data: Value = symbols_and_timeframes.get(i.into());
            let mut symbol_str: Value = self.safe_string(data.clone(), Value::from(0), Value::Undefined);
            let mut market: Value = self.market(symbol_str.clone());
            let mut market_id: Value = market.get(Value::from("id"));
            let mut unfied_timeframe: Value = self.safe_string(data.clone(), Value::from(1), Value::from("1m"));
            let mut raw_timeframe: Value = self.safe_string(timeframes.clone(), unfied_timeframe.clone(), unfied_timeframe.clone());
            if selected_timeframe.clone().is_nonnullish() && selected_timeframe.clone() != raw_timeframe.clone() {
                panic!(r###"NotSupported::new(self.get("id".into()) + Value::from(" watchOHLCVForSymbols() only supports a single timeframe for all symbols"))"###);
            } else {
                selected_timeframe = raw_timeframe.clone();
            };
            market_ids.push(market_id.clone());
            message_hashes.push(Value::from("ohlcv::") + symbol_str.clone() + Value::from("::") + unfied_timeframe.clone());
            i += 1;
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market_ids.join(Value::from(",")),
            "topic": Value::from("kline_") + selected_timeframe.clone(),
            "event": "sub"
        }))).unwrap());
        let (mut symbol, mut timeframe, mut stored) = shift_3(self.watch_multiple(url.clone(), message_hashes.clone(), extend_2(request.clone(), params.clone()), message_hashes.clone()).await);
        if self.get("newUpdates".into()).is_truthy() {
            limit = stored.get_limit(symbol.clone(), limit.clone());
        };
        let mut filtered: Value = self.filter_by_since_limit(stored.clone(), since.clone(), limit.clone(), Value::from(0), true.into());
        return self.create_ohlcv_object(symbol.clone(), timeframe.clone(), filtered.clone());
    }

    fn handle_ohlcv(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         symbol: 'DOGEUSDT',
        //         symbolName: 'DOGEUSDT',
        //         klineType: '1m',
        //         topic: 'kline',
        //         params: { realtimeInterval: '24h', klineType: '1m', binary: 'false' },
        //         data: [
        //             {
        //                 t: 1757251200000,
        //                 s: 'DOGEUSDT',
        //                 sn: 'DOGEUSDT',
        //                 c: '0.21889',
        //                 h: '0.21898',
        //                 l: '0.21889',
        //                 o: '0.21897',
        //                 v: '5247',
        //                 st: 0
        //             }
        //         ],
        //         f: true,
        //         sendTime: 1757251217643,
        //         shared: false
        //     }
        //
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"), Value::Undefined);
        let mut market: Value = self.market(market_id.clone());
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut params: Value = self.safe_dict(message.clone(), Value::from("params"), Value::new_object());
        let mut timeframe_id: Value = self.safe_string(params.clone(), Value::from("klineType"), Value::Undefined);
        let mut timeframe: Value = self.find_timeframe(timeframe_id.clone());
        if !self.get("ohlcvs".into()).contains_key(symbol.clone()) {
            self.get("ohlcvs".into()).set(symbol.clone(), Value::new_object());
        };
        if !self.get("ohlcvs".into()).get(symbol.clone()).contains_key(timeframe.clone()) {
            let mut limit: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("OHLCVLimit"), Value::from(1000));
            self.get("ohlcvs".into()).get(symbol.clone()).set(timeframe.clone(), ArrayCacheByTimestamp::new(limit));
        };
        let mut stored: Value = self.get("ohlcvs".into()).get(symbol.clone()).get(timeframe.clone());
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut i: usize = 0;
        while i < data.len() {
            let mut parsed: Value = <Self as Toobit>::parse_ws_ohlcv(self, data.get(i.into()), market.clone());
            stored.append(parsed.clone());
            i += 1;
        };
        let mut message_hash: Value = Value::from("ohlcv::") + symbol.clone() + Value::from("::") + timeframe.clone();
        let mut resolve_data: Value = Value::Json(serde_json::Value::Array(vec![symbol.clone().into(), timeframe.clone().into(), stored.clone().into()]));
        client.resolve(resolve_data.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        //
        //             {
        //                 t: 1757251200000,
        //                 o: '0.21897',
        //                 h: '0.21898',
        //                 l: '0.21889',
        //                 c: '0.21889',
        //                 v: '5247',
        //                 s: 'DOGEUSDT',
        //                 sn: 'DOGEUSDT',
        //                 st: 0
        //             }
        //
        let mut parsed: Value = self.parse_ohlcv(ohlcv.clone(), market.clone());
        return parsed.clone();
    }

    async fn watch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbol = self.symbol(symbol.clone());
        let mut tickers: Value = <Self as Toobit>::watch_tickers(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), params.clone()).await;
        return tickers.get(symbol.clone());
    }

    async fn watch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into());
        let mut message_hashes: Value = Value::new_array();
        let mut sub_params: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut market: Value = self.market(symbol.clone());
            message_hashes.push(Value::from("ticker::") + symbol.clone());
            let mut raw_hash: Value = market.get(Value::from("id"));
            sub_params.push(raw_hash.clone());
            i += 1;
        };
        let mut market_ids: Value = self.market_ids(symbols.clone());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("common")) + Value::from("/quote/ws/v1");
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market_ids.join(Value::from(",")),
            "topic": "realtimes",
            "event": "sub"
        }))).unwrap());
        let mut ticker: Value = self.watch_multiple(url.clone(), message_hashes.clone(), extend_2(request.clone(), params.clone()), message_hashes.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            let mut result: Value = Value::new_object();
            result.set(ticker.get(Value::from("symbol")), ticker.clone());
            return result.clone();
        };
        return self.filter_by_array(self.get("tickers".into()), Value::from("symbol"), symbols.clone());
    }

    fn handle_tickers(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "symbol": "DOGEUSDT",
        //        "symbolName": "DOGEUSDT",
        //        "topic": "realtimes",
        //        "params": {
        //            "realtimeInterval": "24h"
        //        },
        //        "data": [
        //            {
        //                "t": 1757257643683,
        //                "s": "DOGEUSDT",
        //                "o": "0.21462",
        //                "h": "0.22518",
        //                "l": "0.21229",
        //                "c": "0.2232",
        //                "v": "283337017",
        //                "qv": "62063771.42702",
        //                "sn": "DOGEUSDT",
        //                "m": "0.04",
        //                "e": 301,
        //                "c24h": "0.2232",
        //                "h24h": "0.22518",
        //                "l24h": "0.21229",
        //                "o24h": "0.21462",
        //                "v24h": "283337017",
        //                "qv24h": "62063771.42702",
        //                "m24h": "0.04"
        //            }
        //        ],
        //        "f": false,
        //        "sendTime": 1757257643751,
        //        "shared": false
        //    }
        //
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::Undefined);
        let mut new_tickers: Value = Value::new_object();
        let mut i: usize = 0;
        while i < data.len() {
            let mut ticker: Value = data.get(i.into());
            let mut parsed: Value = <Self as Toobit>::parse_ws_ticker(self, ticker.clone(), Value::Undefined);
            let mut symbol: Value = parsed.get(Value::from("symbol"));
            self.get("tickers".into()).set(symbol.clone(), parsed.clone());
            new_tickers.set(symbol.clone(), parsed.clone());
            let mut message_hash: Value = Value::from("ticker::") + symbol.clone();
            client.resolve(parsed.clone(), message_hash.clone());
            i += 1;
        };
        client.resolve(new_tickers.clone(), Value::from("tickers"));
        Value::Undefined
    }

    fn parse_ws_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        return self.parse_ticker(ticker.clone(), market.clone());
    }

    async fn watch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Toobit>::watch_order_book_for_symbols(self, Value::Json(serde_json::Value::Array(vec![symbol.clone().into()])), limit.clone(), params.clone()).await;
    }

    async fn watch_order_book_for_symbols(&mut self, mut symbols: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        symbols = self.market_symbols(symbols.clone(), Value::Undefined, false.into());
        let mut channel: Value = Value::Undefined;
        (channel, params) = shift_2(self.handle_option_and_params(params.clone(), Value::from("watchOrderBook"), Value::from("channel"), Value::from("depth")));
        let mut message_hashes: Value = Value::new_array();
        let mut sub_params: Value = Value::new_array();
        let mut i: usize = 0;
        while i < symbols.len() {
            let mut symbol: Value = symbols.get(i.into());
            let mut market: Value = self.market(symbol.clone());
            message_hashes.push(Value::from("orderBook::") + symbol.clone() + Value::from("::") + channel.clone());
            let mut raw_hash: Value = market.get(Value::from("id"));
            sub_params.push(raw_hash.clone());
            i += 1;
        };
        let mut market_ids: Value = self.market_ids(symbols.clone());
        let mut url: Value = self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("common")) + Value::from("/quote/ws/v1");
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market_ids.join(Value::from(",")),
            "topic": channel,
            "event": "sub"
        }))).unwrap());
        let mut orderbook: Value = self.watch_multiple(url.clone(), message_hashes.clone(), extend_2(request.clone(), params.clone()), message_hashes.clone()).await;
        return orderbook.limit();
    }

    fn handle_order_book(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         symbol: 'DOGEUSDT',
        //         symbolName: 'DOGEUSDT',
        //         topic: 'depth',
        //         params: { realtimeInterval: '24h' },
        //         data: [
        //             {
        //             e: 301,
        //             t: 1757304842860,
        //             v: '9814355_1E-18',
        //             b: [Array],
        //             a: [Array],
        //             o: 0
        //             }
        //         ],
        //         f: false,
        //         sendTime: 1757304843047,
        //         shared: false
        //     }
        //
        let mut is_snapshot: Value = self.safe_bool(message.clone(), Value::from("f"), false.into());
        if is_snapshot.is_truthy() {
            <Self as Toobit>::set_order_book_snapshot(self, client.clone(), message.clone(), Value::from("diffDepth"));
            return Value::Undefined;
        };
        let mut market_id: Value = self.safe_string(message.clone(), Value::from("symbol"), Value::Undefined);
        let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut i: usize = 0;
        while i < data.len() {
            let mut entry: Value = data.get(i.into());
            let mut message_hash: Value = Value::from("orderBook::") + symbol.clone() + Value::from("::") + Value::from("diffDepth");
            if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
                let mut limit: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("orderBookLimit"), Value::from(1000));
                self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::new_object(), limit.clone()));
            };
            let mut order_book: Value = self.get("orderbooks".into()).get(symbol.clone());
            let mut timestamp: Value = self.safe_integer(entry.clone(), Value::from("t"), Value::Undefined);
            let mut bids: Value = self.safe_list(entry.clone(), Value::from("b"), Value::new_array());
            let mut asks: Value = self.safe_list(entry.clone(), Value::from("a"), Value::new_array());
            self.handle_deltas(order_book.get(Value::from("asks")), asks.clone());
            self.handle_deltas(order_book.get(Value::from("bids")), bids.clone());
            order_book.set("timestamp".into(), timestamp.clone());
            self.get("orderbooks".into()).set(symbol.clone(), order_book.clone());
            client.resolve(order_book.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    fn handle_delta(&mut self, mut bookside: Value, mut delta: Value) -> Value {
        let mut bid_ask: Value = self.parse_bid_ask(delta.clone(), Value::Undefined, Value::Undefined);
        bookside.store_array(bid_ask.clone());
        Value::Undefined
    }

    fn handle_order_book_partial_snapshot(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //     {
        //         symbol: 'DOGEUSDT',
        //         symbolName: 'DOGEUSDT',
        //         topic: 'depth',
        //         params: { realtimeInterval: '24h' },
        //         data: [
        //             {
        //             e: 301,
        //             s: 'DOGEUSDT',
        //             t: 1757304842860,
        //             v: '9814355_1E-18',
        //             b: [Array],
        //             a: [Array],
        //             o: 0
        //             }
        //         ],
        //         f: false,
        //         sendTime: 1757304843047,
        //         shared: false
        //     }
        //
        <Self as Toobit>::set_order_book_snapshot(self, client.clone(), message.clone(), Value::from("depth"));
        Value::Undefined
    }

    fn set_order_book_snapshot(&mut self, mut client: Value, mut message: Value, mut channel: Value) -> Value {
        let mut data: Value = self.safe_list(message.clone(), Value::from("data"), Value::new_array());
        let mut length: usize = data.len();
        if length == 0 {
            return Value::Undefined;
        };
        let mut i: usize = 0;
        while i < length {
            let mut entry: Value = data.get(i.into());
            let mut market_id: Value = self.safe_string(entry.clone(), Value::from("s"), Value::Undefined);
            let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
            let mut message_hash: Value = Value::from("orderBook::") + symbol.clone() + Value::from("::") + channel.clone();
            if !self.get("orderbooks".into()).contains_key(symbol.clone()) {
                let mut limit: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("orderBookLimit"), Value::from(1000));
                self.get("orderbooks".into()).set(symbol.clone(), self.order_book(Value::new_object(), limit.clone()));
            };
            let mut orderbook: Value = self.get("orderbooks".into()).get(symbol.clone());
            let mut timestamp: Value = self.safe_integer(entry.clone(), Value::from("t"), Value::Undefined);
            let mut snapshot: Value = self.parse_order_book(entry.clone(), symbol.clone(), timestamp.clone(), Value::from("b"), Value::from("a"), Value::Undefined, Value::Undefined, Value::Undefined);
            orderbook.reset(snapshot.clone());
            client.resolve(orderbook.clone(), message_hash.clone());
            i += 1;
        };
        Value::Undefined
    }

    async fn watch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Toobit>::authenticate(self, Value::Undefined).await;
        let mut market_type: Value = Value::Undefined;
        (market_type, params) = shift_2(self.handle_market_type_and_params(Value::from("watchBalance"), Value::Undefined, params.clone()));
        let mut is_spot: Value = (market_type.clone() == Value::from("spot")).into();
        let mut r#type: Value = if is_spot.is_truthy() { Value::from("spot") } else { Value::from("contract") };
        let mut spot_sub_hash: Value = Value::from("spot:balance");
        let mut swap_sub_hash: Value = Value::from("contract:private");
        let mut spot_message_hash: Value = Value::from("spot:balance");
        let mut swap_message_hash: Value = Value::from("contract:balance");
        let mut message_hash: Value = if is_spot.is_truthy() { spot_message_hash.clone() } else { swap_message_hash.clone() };
        let mut subscription_hash: Value = if is_spot.is_truthy() { spot_sub_hash.clone() } else { swap_sub_hash.clone() };
        let mut url: Value = <Self as Toobit>::get_user_stream_url(self);
        let mut client: Value = self.client(url.clone());
        <Self as Toobit>::set_balance_cache(self, client.clone(), market_type.clone(), subscription_hash.clone(), params.clone());
        client.future(r#type.clone() + Value::from(":fetchBalanceSnapshot"));
        return self.watch(url.clone(), message_hash.clone(), params.clone(), subscription_hash.clone()).await;
    }

    fn set_balance_cache(&mut self, mut client: Value, mut market_type: Value, mut subscription_hash: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if client.get(subscriptions.clone()).contains_key(subscription_hash.clone()) {
            return Value::Undefined;
        };
        let mut r#type: Value = if market_type.clone() == Value::from("spot") { Value::from("spot") } else { Value::from("contract") };
        let mut message_hash: Value = r#type.clone() + Value::from(":fetchBalanceSnapshot");
        if !client.get(futures.clone()).contains_key(message_hash.clone()) {
            client.future(message_hash.clone());
            self.spawn(self.get("loadBalanceSnapshot".into()), client.clone(), message_hash.clone(), market_type.clone());
        };
        Value::Undefined
    }

    fn handle_balance(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // spot
        //
        // [
        //     {
        //         e: 'outboundAccountInfo',
        //         E: '1758226989725',
        //         T: true,
        //         W: true,
        //         D: true,
        //         B: [
        //             {
        //               a: "USDT",
        //               f: "6.37242839",
        //               l: "0",
        //             },
        //         ]
        //     }
        // ]
        //
        // contract
        //
        // [
        //     {
        //         e: 'outboundContractAccountInfo',
        //         E: '1758226989742',
        //         T: true,
        //         W: true,
        //         D: true,
        //         B: [ [Object] ]
        //     }
        // ]
        //
        let mut channel: Value = self.safe_string(message.clone(), Value::from("e"), Value::Undefined);
        let mut data: Value = self.safe_list(message.clone(), Value::from("B"), Value::new_array());
        let mut timestamp: Value = self.safe_integer(message.clone(), Value::from("E"), Value::Undefined);
        let mut r#type: Value = if channel.clone() == Value::from("outboundContractAccountInfo") { Value::from("contract") } else { Value::from("spot") };
        if !self.get("balance".into()).contains_key(r#type.clone()) {
            self.get("balance".into()).set(r#type.clone(), Value::new_object());
        };
        self.get("balance".into()).get(r#type.clone()).set("info".into(), data.clone());
        self.get("balance".into()).get(r#type.clone()).set("timestamp".into(), timestamp.clone());
        self.get("balance".into()).get(r#type.clone()).set("datetime".into(), self.iso8601(timestamp.clone()));
        let mut i: usize = 0;
        while i < data.len() {
            let mut balance: Value = data.get(i.into());
            let mut currency_id: Value = self.safe_string(balance.clone(), Value::from("a"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("info".into(), balance.clone());
            account.set("used".into(), self.safe_string(balance.clone(), Value::from("l"), Value::Undefined));
            account.set("free".into(), self.safe_string(balance.clone(), Value::from("f"), Value::Undefined));
            self.get("balance".into()).get(r#type.clone()).set(code.clone(), account.clone());
            i += 1;
        };
        self.get("balance".into()).set(r#type.clone(), self.safe_balance(self.get("balance".into()).get(r#type.clone())));
        client.resolve(self.get("balance".into()).get(r#type.clone()), r#type.clone() + Value::from(":balance"));
        Value::Undefined
    }

    async fn load_balance_snapshot(&mut self, mut client: Value, mut message_hash: Value, mut market_type: Value) -> Value {
        let mut response: Value = self.fetch_balance(Value::Json(normalize(&Value::Json(json!({
            "type": market_type
        }))).unwrap())).await;
        let mut r#type: Value = if market_type.clone() == Value::from("spot") { Value::from("spot") } else { Value::from("contract") };
        self.get("balance".into()).set(r#type.clone(), extend_2(response.clone(), self.safe_dict(self.get("balance".into()), r#type.clone(), Value::new_object())));
        // don't remove the future from the .futures cache
        if client.get(futures.clone()).contains_key(message_hash.clone()) {
            let mut future: Value = client.get(futures.clone()).get(message_hash.clone());
            future.resolve();
            client.resolve(self.get("balance".into()).get(r#type.clone()), r#type.clone() + Value::from(":fetchBalanceSnapshot"));
            client.resolve(self.get("balance".into()).get(r#type.clone()), r#type.clone() + Value::from(":balance"));
        };
        Value::Undefined
    }

    async fn watch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Toobit>::authenticate(self, Value::Undefined).await;
        let mut market: Value = self.market_or_null(symbol.clone());
        symbol = self.safe_string(market.clone(), Value::from("symbol"), symbol.clone());
        let mut message_hash: Value = Value::from("orders");
        if symbol.clone().is_nonnullish() {
            message_hash = message_hash.clone() + Value::from(":") + symbol.clone();
        };
        let mut url: Value = <Self as Toobit>::get_user_stream_url(self);
        let mut orders: Value = self.watch(url.clone(), message_hash.clone(), params.clone(), message_hash.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = orders.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_symbol_since_limit(orders.clone(), symbol.clone(), since.clone(), limit.clone(), true.into());
    }

    fn handle_order(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "e": "executionReport",
        //        "E": "1758311011844",
        //        "s": "DOGEUSDT",
        //        "c": "1758311011948",
        //        "S": "BUY",
        //        "o": "LIMIT",
        //        "f": "GTC",
        //        "q": "22",
        //        "p": "0.23",
        //        "pt": "INPUT",
        //        "X": "NEW",
        //        "i": "2043255292855185152",
        //        "l": "0", // Last executed quantity
        //        "z": "0", // Cumulative filled quantity
        //        "L": "0", // Last executed price
        //        "n": "0",
        //        "N": "",
        //        "u": true,
        //        "w": true,
        //        "m": false,
        //        "O": "1758311011833",
        //        "U": "1758311011841",
        //        "Z": "0",
        //        "C": false,
        //        "v": "0",
        //        "rp": "0",
        //        "td": "0"
        //    }
        //
        if self.get("orders".into()).is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("ordersLimit"), Value::from(1000));
            self.set("orders".into(), ArrayCacheBySymbolById::new(limit));
        };
        let mut orders: Value = self.get("orders".into());
        let mut order: Value = <Self as Toobit>::parse_ws_order(self, message.clone(), Value::Undefined);
        orders.append(order.clone());
        let mut message_hash: Value = Value::from("orders");
        client.resolve(orders.clone(), message_hash.clone());
        message_hash = Value::from("orders:") + self.safe_string(order.clone(), Value::from("symbol"), Value::Undefined);
        client.resolve(orders.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_ws_order(&self, mut order: Value, mut market: Value) -> Value {
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("O"), Value::Undefined);
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("s"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut price_type: Value = self.safe_string_lower(order.clone(), Value::from("pt"), Value::Undefined);
        let mut raw_order_type: Value = self.safe_string_lower(order.clone(), Value::from("o"), Value::Undefined);
        let mut order_type: Value = Value::Undefined;
        if price_type.clone() == Value::from("market") {
            order_type = Value::from("market");
        } else {
            order_type = raw_order_type.clone();
        };
        let mut fee_cost: Value = self.safe_number(order.clone(), Value::from("n"), Value::Undefined);
        let mut fee: Value = Value::Undefined;
        if fee_cost.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost,
                "currency": Value::Undefined
            }))).unwrap());
        };
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": order,
            "id": self.safe_string(order.clone(), Value::from("i"), Value::Undefined),
            "clientOrderId": self.safe_string(order.clone(), Value::from("c"), Value::Undefined),
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "lastUpdateTimestamp": self.safe_integer_2(order.clone(), Value::from("U"), Value::from("E"), Value::Undefined),
            "symbol": symbol,
            "type": order_type,
            "timeInForce": self.safe_string_upper(order.clone(), Value::from("f"), Value::Undefined),
            "postOnly": Value::Undefined,
            "side": self.safe_string_lower(order.clone(), Value::from("S"), Value::Undefined),
            "price": self.safe_string(order.clone(), Value::from("L"), Value::Undefined),
            "stopPrice": Value::Undefined,
            "triggerPrice": Value::Undefined,
            "amount": self.safe_string(order.clone(), Value::from("q"), Value::Undefined),
            "cost": Value::Undefined,
            "average": self.safe_string(order.clone(), Value::from("p"), Value::Undefined),
            "filled": self.safe_string(order.clone(), Value::from("z"), Value::Undefined),
            "remaining": Value::Undefined,
            "status": self.parse_order_status(self.safe_string(order.clone(), Value::from("X"), Value::Undefined)),
            "fee": fee,
            "trades": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn watch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Toobit>::authenticate(self, Value::Undefined).await;
        let mut market: Value = self.market_or_null(symbol.clone());
        symbol = self.safe_string(market.clone(), Value::from("symbol"), symbol.clone());
        let mut message_hash: Value = Value::from("myTrades");
        if symbol.clone().is_nonnullish() {
            message_hash = message_hash.clone() + Value::from(":") + symbol.clone();
        };
        let mut url: Value = <Self as Toobit>::get_user_stream_url(self);
        let mut trades: Value = self.watch(url.clone(), message_hash.clone(), params.clone(), message_hash.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            limit = trades.get_limit(symbol.clone(), limit.clone());
        };
        return self.filter_by_since_limit(trades.clone(), since.clone(), limit.clone(), Value::from("timestamp"), true.into());
    }

    fn handle_my_trade(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "e": "ticketInfo",
        //        "E": "1758314657847",
        //        "s": "DOGEUSDT",
        //        "q": "22.0",
        //        "t": "1758314657842",
        //        "p": "0.26667",
        //        "T": "4864732022877055421",
        //        "o": "2043285877770284800",
        //        "c": "1758314657002",
        //        "a": "1783404067076253952",
        //        "m": false,
        //        "S": "BUY"
        //    }
        //
        let mut my_trades: Value = self.get("myTrades".into());
        if my_trades.clone().is_nullish() {
            let mut limit: Value = self.safe_integer(self.get("options".into()), Value::from("tradesLimit"), Value::from(1000));
            my_trades = ArrayCacheBySymbolById::new(limit);
        };
        let mut trade: Value = <Self as Toobit>::parse_my_trade(self, message.clone(), Value::Undefined);
        my_trades.append(trade.clone());
        let mut message_hash: Value = Value::from("myTrades:") + trade.get(Value::from("symbol"));
        client.resolve(my_trades.clone(), message_hash.clone());
        message_hash = Value::from("myTrades");
        client.resolve(my_trades.clone(), message_hash.clone());
        Value::Undefined
    }

    fn parse_my_trade(&self, mut trade: Value, mut market: Value) -> Value {
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("s"), Value::Undefined);
        let mut ts: Value = self.safe_string(trade.clone(), Value::from("t"), Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "id": self.safe_string(trade.clone(), Value::from("T"), Value::Undefined),
            "timestamp": ts,
            "datetime": self.iso8601(ts.clone()),
            "symbol": self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined),
            "order": self.safe_string(trade.clone(), Value::from("o"), Value::Undefined),
            "type": Value::Undefined,
            "side": self.safe_string_lower(trade.clone(), Value::from("S"), Value::Undefined),
            "takerOrMaker": if self.safe_bool(trade.clone(), Value::from("m"), Value::Undefined).is_truthy() { Value::from("maker") } else { Value::from("taker") },
            "price": self.safe_string(trade.clone(), Value::from("p"), Value::Undefined),
            "amount": self.safe_string(trade.clone(), Value::from("q"), Value::Undefined),
            "cost": Value::Undefined,
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn watch_positions(&mut self, mut symbols: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        <Self as Toobit>::authenticate(self, Value::Undefined).await;
        let mut message_hash: Value = Value::from("");
        if !self.is_empty(symbols.clone()).is_truthy() {
            symbols = self.market_symbols(symbols.clone());
            message_hash = Value::from("::") + symbols.join(Value::from(","));
        };
        let mut url: Value = <Self as Toobit>::get_user_stream_url(self);
        let mut client: Value = self.client(url.clone());
        <Self as Toobit>::authenticate(self, url.clone()).await;
        <Self as Toobit>::set_positions_cache(self, client.clone(), symbols.clone(), Value::Undefined, Value::Undefined);
        let mut cache: Value = self.get("positions".into());
        if cache.clone().is_nullish() {
            let mut snapshot: Value = client.future(Value::from("fetchPositionsSnapshot")).await;
            return self.filter_by_symbols_since_limit(snapshot.clone(), symbols.clone(), since.clone(), limit.clone(), true.into());
        };
        let mut new_positions: Value = self.watch(url.clone(), message_hash.clone(), Value::Undefined, message_hash.clone()).await;
        if self.get("newUpdates".into()).is_truthy() {
            return new_positions.clone();
        };
        return self.filter_by_symbols_since_limit(cache.clone(), symbols.clone(), since.clone(), limit.clone(), true.into());
    }

    fn set_positions_cache(&mut self, mut client: Value, mut r#type: Value, mut symbols: Value, mut is_portfolio_margin: Value) -> Value {
        is_portfolio_margin = is_portfolio_margin.or_default(false.into());
        if self.get("positions".into()).is_nullish() {
            self.set("positions".into(), Value::new_object());
        };
        if self.get("positions".into()).contains_key(r#type.clone()) {
            return Value::Undefined;
        };
        let mut fetch_positions_snapshot: Value = self.handle_option(Value::from("watchPositions"), Value::from("fetchPositionsSnapshot"), false.into());
        if fetch_positions_snapshot.is_truthy() {
            let mut message_hash: Value = r#type.clone() + Value::from(":fetchPositionsSnapshot");
            if !client.get(futures.clone()).contains_key(message_hash.clone()) {
                client.future(message_hash.clone());
                self.spawn(self.get("loadPositionsSnapshot".into()), client.clone(), message_hash.clone(), r#type.clone(), is_portfolio_margin.clone());
            };
        } else {
            self.get("positions".into()).set(r#type.clone(), ArrayCacheBySymbolBySide::new());
        };
        Value::Undefined
    }

    async fn load_positions_snapshot(&mut self, mut client: Value, mut message_hash: Value, mut r#type: Value) -> Value {
        let mut params: Value = Value::Json(normalize(&Value::Json(json!({
            "type": r#type
        }))).unwrap());
        let mut positions: Value = self.fetch_positions(Value::Undefined, params.clone()).await;
        self.get("positions".into()).set(r#type.clone(), ArrayCacheBySymbolBySide::new());
        let mut cache: Value = self.get("positions".into()).get(r#type.clone());
        let mut i: usize = 0;
        while i < positions.len() {
            let mut position: Value = positions.get(i.into());
            cache.append(position.clone());
            i += 1;
        };
        // don't remove the future from the .futures cache
        if client.get(futures.clone()).contains_key(message_hash.clone()) {
            let mut future: Value = client.get(futures.clone()).get(message_hash.clone());
            future.resolve(cache.clone());
            client.resolve(cache.clone(), r#type.clone() + Value::from(":positions"));
        };
        Value::Undefined
    }

    fn handle_positions(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        // [
        //     {
        //         e: 'outboundContractPositionInfo',
        //         E: '1758316454554',
        //         A: '1783404067076253954',
        //         s: 'DOGE-SWAP-USDT',
        //         S: 'LONG',
        //         p: '0',
        //         P: '0',
        //         a: '0',
        //         f: '0.1228',
        //         m: '0',
        //         r: '0',
        //         up: '0',
        //         pr: '0',
        //         pv: '0',
        //         v: '3.0',
        //         mt: 'CROSS',
        //         mm: '0',
        //         mp: '0.265410000000000000'
        //     }
        // ]
        //
        let mut subscriptions: Value = client.get(subscriptions.clone()).keys();
        let mut account_type: Value = subscriptions.get(Value::from(0));
        if self.get("positions".into()).is_nullish() {
            self.set("positions".into(), Value::new_object());
        };
        if !self.get("positions".into()).contains_key(account_type.clone()) {
            self.get("positions".into()).set(account_type.clone(), ArrayCacheBySymbolBySide::new());
        };
        let mut cache: Value = self.get("positions".into()).get(account_type.clone());
        let mut new_positions: Value = Value::new_array();
        let mut i: usize = 0;
        while i < message.len() {
            let mut raw_position: Value = message.get(i.into());
            let mut position: Value = <Self as Toobit>::parse_ws_position(self, raw_position.clone(), Value::Undefined);
            let mut timestamp: Value = self.safe_integer(raw_position.clone(), Value::from("E"), Value::Undefined);
            position.set("timestamp".into(), timestamp.clone());
            position.set("datetime".into(), self.iso8601(timestamp.clone()));
            new_positions.push(position.clone());
            cache.append(position.clone());
            i += 1;
        };
        let mut message_hashes: Value = self.find_message_hashes(client.clone(), account_type.clone() + Value::from(":positions::"));
        let mut i: usize = 0;
        while i < message_hashes.len() {
            let mut message_hash: Value = message_hashes.get(i.into());
            let mut parts: Value = message_hash.split(Value::from("::"));
            let mut symbols_string: Value = parts.get(Value::from(1));
            let mut symbols: Value = symbols_string.split(Value::from(","));
            let mut positions: Value = self.filter_by_array(new_positions.clone(), Value::from("symbol"), symbols.clone(), false.into());
            if !self.is_empty(positions.clone()).is_truthy() {
                client.resolve(positions.clone(), message_hash.clone());
            };
            i += 1;
        };
        client.resolve(new_positions.clone(), account_type.clone() + Value::from(":positions"));
        Value::Undefined
    }

    fn parse_ws_position(&self, mut position: Value, mut market: Value) -> Value {
        let mut market_id: Value = self.safe_string(position.clone(), Value::from("s"), Value::Undefined);
        return self.safe_position(Value::Json(normalize(&Value::Json(json!({
            "info": position,
            "id": Value::Undefined,
            "symbol": self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined),
            "notional": self.omit_zero(self.safe_string(position.clone(), Value::from("pv"), Value::Undefined)),
            "marginMode": self.safe_string_lower(position.clone(), Value::from("mt"), Value::Undefined),
            "liquidationPrice": self.safe_string(position.clone(), Value::from("f"), Value::Undefined),
            "entryPrice": self.safe_string(position.clone(), Value::from("p"), Value::Undefined),
            "unrealizedPnl": self.safe_string(position.clone(), Value::from("up"), Value::Undefined),
            "realizedPnl": self.safe_number(position.clone(), Value::from("r"), Value::Undefined),
            "percentage": Value::Undefined,
            "contracts": Value::Undefined,
            "contractSize": Value::Undefined,
            "markPrice": self.safe_string(position.clone(), Value::from("mp"), Value::Undefined),
            "side": self.safe_string_lower(position.clone(), Value::from("S"), Value::Undefined),
            "hedged": Value::Undefined,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "maintenanceMargin": self.safe_string(position.clone(), Value::from("mm"), Value::Undefined),
            "maintenanceMarginPercentage": Value::Undefined,
            "collateral": Value::Undefined,
            "initialMargin": self.omit_zero(self.safe_string(position.clone(), Value::from("m"), Value::Undefined)),
            "initialMarginPercentage": Value::Undefined,
            "leverage": self.safe_string(position.clone(), Value::from("v"), Value::Undefined),
            "marginRatio": Value::Undefined
        }))).unwrap()));
    }

    async fn authenticate(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut client: Value = self.client(<Self as Toobit>::get_user_stream_url(self));
        let mut message_hash: Value = Value::from("authenticated");
        let mut future: Value = client.reusable_future(message_hash.clone());
        let mut authenticated: Value = self.safe_value(client.get(subscriptions.clone()), message_hash.clone(), Value::Undefined);
        if authenticated.clone().is_nullish() {
            self.check_required_credentials();
            let mut time: Value = self.milliseconds();
            let mut last_authenticated_time: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("lastAuthenticatedTime"), Value::from(0));
            let mut listen_key_refresh_rate: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("listenKeyRefreshRate"), Value::from(1200000));
            let mut delay: Value = self.sum(listen_key_refresh_rate.clone(), Value::from(10000));
            if time.clone() - last_authenticated_time.clone() > delay.clone() {
                                client.get(subscriptions.clone()).set(message_hash.clone(), true.into());
                let mut response: Value = self.dispatch("privatePostApiV1UserDataStream".into(), params.clone(), Value::Undefined).await;
                self.get("options".into()).get(Value::from("ws")).set("listenKey".into(), self.safe_string(response.clone(), Value::from("listenKey"), Value::Undefined));
                self.get("options".into()).get(Value::from("ws")).set("lastAuthenticatedTime".into(), time.clone());
                future.resolve(true.into());
                self.delay(listen_key_refresh_rate.clone(), self.get("keepAliveListenKey".into()), params.clone());
                // catch block omitted (no exception support in Value runtime)
;
            };
        };
        return future.clone();
    }

    async fn keep_alive_listen_key(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut options: Value = self.safe_value(self.get("options".into()), Value::from("ws"), Value::new_object());
        let mut listen_key: Value = self.safe_string(options.clone(), Value::from("listenKey"), Value::Undefined);
        if listen_key.clone().is_nullish() {
            // A network error happened: we can't renew a listen key that does not exist.
            return Value::Undefined;
        };
                let mut response: Value = self.dispatch("privatePostApiV1UserDataStream".into(), params.clone(), Value::Undefined).await;
        self.get("options".into()).get(Value::from("ws")).set("listenKey".into(), self.safe_string(response.clone(), Value::from("listenKey"), Value::Undefined));
        self.get("options".into()).get(Value::from("ws")).set("lastAuthenticatedTime".into(), self.milliseconds());
        // catch block omitted (no exception support in Value runtime)
;
        // whether or not to schedule another listenKey keepAlive request
        let mut listen_key_refresh_rate: Value = self.safe_integer(self.get("options".into()).get(Value::from("ws")), Value::from("listenKeyRefreshRate"), Value::from(1200000));
        self.delay(listen_key_refresh_rate.clone(), self.get("keepAliveListenKey".into()), params.clone());
        Value::Undefined
    }

    fn get_user_stream_url(&mut self) -> Value {
        return self.get("urls".into()).get(Value::from("api")).get(Value::from("ws")).get(Value::from("common")) + Value::from("/api/v1/ws/") + self.get("options".into()).get(Value::from("ws")).get(Value::from("listenKey"));
    }

    fn handle_error_message(&mut self, mut client: Value, mut message: Value) -> Value {
        //
        //    {
        //        "code": '-100010',
        //        "desc": "Invalid Symbols!"
        //    }
        //
        let mut code: Value = self.safe_string(message.clone(), Value::from("code"), Value::Undefined);
        if code.clone().is_nonnullish() {
            let mut desc: Value = self.safe_string(message.clone(), Value::from("desc"), Value::Undefined);
            let mut msg: Value = self.get("id".into()) + Value::from(" code: ") + code.clone() + Value::from(" message: ") + desc.clone();
            let mut exception: Value = ExchangeError::new(msg);
            // c# fix
            client.reject(exception.clone());
            return true.into();
        };
        return false.into();
    }

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "commonGetApiv1time" => self.request("api/v1/time".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetApiv1ping" => self.request("api/v1/ping".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetApiv1exchangeinfo" => self.request("api/v1/exchangeInfo".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1depth" => self.request("quote/v1/depth".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1depthmerged" => self.request("quote/v1/depth/merged".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1trades" => self.request("quote/v1/trades".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1klines" => self.request("quote/v1/klines".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1indexklines" => self.request("quote/v1/index/klines".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1markpriceklines" => self.request("quote/v1/markPrice/klines".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1markprice" => self.request("quote/v1/markPrice".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1index" => self.request("quote/v1/index".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1ticker24hr" => self.request("quote/v1/ticker/24hr".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1contractticker24hr" => self.request("quote/v1/contract/ticker/24hr".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1tickerprice" => self.request("quote/v1/ticker/price".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetQuotev1tickerbookticker" => self.request("quote/v1/ticker/bookTicker".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetApiv1futuresfundingrate" => self.request("api/v1/futures/fundingRate".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "commonGetApiv1futureshistoryfundingrate" => self.request("api/v1/futures/historyFundingRate".into(), "common".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1account" => self.request("api/v1/account".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountcheckapikey" => self.request("api/v1/account/checkApiKey".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotorder" => self.request("api/v1/spot/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spotopenorders" => self.request("api/v1/spot/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresopenorders" => self.request("api/v1/futures/openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1spottradeorders" => self.request("api/v1/spot/tradeOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futureshistoryorders" => self.request("api/v1/futures/historyOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accounttrades" => self.request("api/v1/account/trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountbalanceflow" => self.request("api/v1/account/balanceFlow".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountdepositorders" => self.request("api/v1/account/depositOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountwithdraworders" => self.request("api/v1/account/withdrawOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1accountdepositaddress" => self.request("api/v1/account/deposit/address".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1subaccount" => self.request("api/v1/subAccount".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresaccountleverage" => self.request("api/v1/futures/accountLeverage".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresorder" => self.request("api/v1/futures/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futurespositions" => self.request("api/v1/futures/positions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresbalance" => self.request("api/v1/futures/balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresusertrades" => self.request("api/v1/futures/userTrades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futuresbalanceflow" => self.request("api/v1/futures/balanceFlow".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futurescommissionrate" => self.request("api/v1/futures/commissionRate".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetApiv1futurestodaypnl" => self.request("api/v1/futures/todayPnl".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotordertest" => self.request("api/v1/spot/orderTest".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotorder" => self.request("api/v1/spot/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresorder" => self.request("api/v1/futures/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1spotbatchorders" => self.request("api/v1/spot/batchOrders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1subaccounttransfer" => self.request("api/v1/subAccount/transfer".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1accountwithdraw" => self.request("api/v1/account/withdraw".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresmargintype" => self.request("api/v1/futures/marginType".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresleverage" => self.request("api/v1/futures/leverage".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futuresbatchorders" => self.request("api/v1/futures/batchOrders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futurespositiontradingstop" => self.request("api/v1/futures/position/trading-stop".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1futurespositionmargin" => self.request("api/v1/futures/positionMargin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1userdatastream" => self.request("api/v1/userDataStream".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostApiv1listenkey" => self.request("api/v1/listenKey".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotorder" => self.request("api/v1/spot/order".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futuresorder" => self.request("api/v1/futures/order".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotopenorders" => self.request("api/v1/spot/openOrders".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futuresbatchorders" => self.request("api/v1/futures/batchOrders".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1spotcancelorderbyids" => self.request("api/v1/spot/cancelOrderByIds".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1futurescancelorderbyids" => self.request("api/v1/futures/cancelOrderByIds".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteApiv1listenkey" => self.request("api/v1/listenKey".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePutApiv1listenkey" => self.request("api/v1/listenKey".into(), "private".into(), "PUT".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToobitImpl(Value);
impl Exchange for ToobitImpl {}
impl Toobit for ToobitImpl {}
impl ValueTrait for ToobitImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl ToobitImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = ToobitImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Toobit::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

