# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.bitmart import bitmart
from ccxt.abstract.ob_bitmart import ImplicitAPI
from ccxt.base.types import Any, Market, Order, Str
from typing import List


class ob_bitmart(bitmart, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(ob_bitmart, self).describe(), {
            'id': 'ob_bitmart',
            'name': 'BitMart',
            'certified': False,
            'urls': {
            },
            'has': {
                'CORS': None,
                'spot': True,
                'margin': True,
                'swap': True,
                'future': False,
                'option': False,
                'fetchAccountId': True,
                'fetchPermissions': True,
                'getOrdersBrokerParameters': True,
            },
            'options': {
                'createMarketBuyOrderRequiresPrice': False,  # disable quote conversion
                'brokerId': 'OCTOBOTBROKER01',
                'octobot': {
                    'supportedElements': {
                        'spot': {
                            'orders': ['market', 'limit'],
                            'bundled_orders': {},
                        },
                        'futures': {
                            'orders': ['market', 'limit'],
                            'bundled_orders': {},
                        },
                    },
                    'fixMarketStatus': True,
                    'requireOrderFeesFromTrades': True,
                    'enableSpotBuyMarketWithCost': True,
                    'supportFetchingCancelledOrders': False,
                    'adjustForTimeDifference': True,
                    'hasBroker': True,
                },
            },
        })

    def fetch_permissions(self, params={}) -> List[str]:
        return self.ob_fetch_permissions_imaginary_cancel('12345', 'BTC/USDT', params, 'pair')

    def get_orders_broker_parameters(self, params={}) -> Any:
        return self.extend({}, params)

    def fetch_account_id(self, params={}, _ccxtTypesImportStr: Str = None) -> Str:
        return 'default_account_id'

    def parse_order(self, order: dict, market: Market = None) -> Order:
        # override the standard parseOrder to apply OctoBot's BitMartCCXTAdapter.fix_order:
        # 1) call the standard parseOrder
        # 2) adapt amount from filled or cost when missing(shared CCXTAdapter helper)
        # 3) when bitmart returns a market order tagged but filled, mark it
        parsed = super(ob_bitmart, self).parse_order(order, market)
        self.ob_adapt_amount_from_filled_or_cost(parsed)
        orderType = self.safe_string_lower(parsed, 'type')
        orderStatus = self.safe_string_lower(parsed, 'status')
        filled = self.safe_number(parsed, 'filled')
        if orderType == 'market' and orderStatus == 'canceled' and filled is not None and filled != 0:
            # consider & closed(Bitmart is sometimes tagging filled market orders as "canceled": ignore it)
            parsed['status'] = 'closed'
        return parsed

    def ob_adapt_amount_from_filled_or_cost(self, parsed: dict) -> dict:
        # shared OctoBot CCXTAdapter helper: when amount is missing, derive it from filled or cost/price
        orderType = self.safe_string_lower(parsed, 'type')
        orderSide = self.safe_string_lower(parsed, 'side')
        filled = self.safe_number(parsed, 'filled')
        if orderType == 'market' and orderSide == 'buy' and filled is not None and filled != 0:
            parsed['amount'] = filled
        amount = self.safe_number(parsed, 'amount')
        cost = self.safe_number(parsed, 'cost')
        price = self.safe_number(parsed, 'price')
        if (amount is None or amount == 0) and cost is not None and cost != 0 and price is not None and price != 0:
            parsed['amount'] = cost / price
        return parsed
