// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    privatePostDisputeagentsRegisterdisputeagent (params?: {}): Promise<implicitReturnType>;
    privatePostGetversionGetversion (params?: {}): Promise<implicitReturnType>;
    privatePostHelpGetmethodhelp (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetoffers (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetoffercategory (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetmyoffers (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetmyoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetbsqswapoffers (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetbsqswapoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetmybsqswapoffers (params?: {}): Promise<implicitReturnType>;
    privatePostOffersGetmybsqswapoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersEditoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersCreatebsqswapoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersCreateoffer (params?: {}): Promise<implicitReturnType>;
    privatePostOffersCanceloffer (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsCreatecryptocurrencypaymentaccount (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsCreatepaymentaccount (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsGetcryptocurrencypaymentmethods (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsGetpaymentaccountform (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsGetpaymentaccounts (params?: {}): Promise<implicitReturnType>;
    privatePostPaymentaccountsGetpaymentmethods (params?: {}): Promise<implicitReturnType>;
    privatePostPriceGetaveragebsqtradeprice (params?: {}): Promise<implicitReturnType>;
    privatePostPriceGetmarketprice (params?: {}): Promise<implicitReturnType>;
    privatePostShutdownserverStop (params?: {}): Promise<implicitReturnType>;
    privatePostTradesClosetrade (params?: {}): Promise<implicitReturnType>;
    privatePostTradesConfirmpaymentreceived (params?: {}): Promise<implicitReturnType>;
    privatePostTradesConfirmpaymentstarted (params?: {}): Promise<implicitReturnType>;
    privatePostTradesFailtrade (params?: {}): Promise<implicitReturnType>;
    privatePostTradesGettrade (params?: {}): Promise<implicitReturnType>;
    privatePostTradesGettrades (params?: {}): Promise<implicitReturnType>;
    privatePostTradesTakeoffer (params?: {}): Promise<implicitReturnType>;
    privatePostTradesUnfailtrade (params?: {}): Promise<implicitReturnType>;
    privatePostTradesWithdrawfunds (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGetaddressbalance (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGetbalances (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGetfundingaddresses (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGetnetwork (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGettransaction (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGettxfeerate (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsGetunusedbsqaddress (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsLockwallet (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsRemovewalletpassword (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsSendbsq (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsSendbtc (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsSettxfeeratepreference (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsSetwalletpassword (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsUnlockwallet (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsUnsettxfeeratepreference (params?: {}): Promise<implicitReturnType>;
    privatePostWalletsVerifybsqsenttoaddress (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
