// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetCurrencies (params?: {}): Promise<implicitReturnType>;
    publicGetCurrency (params?: {}): Promise<implicitReturnType>;
    publicGetCurrencySymbol (params?: {}): Promise<implicitReturnType>;
    publicGetPairs (params?: {}): Promise<implicitReturnType>;
    publicGetPairsSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetExchangeId (params?: {}): Promise<implicitReturnType>;
    publicPostEstimate (params?: {}): Promise<implicitReturnType>;
    publicPostExchange (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
