#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Bit2c : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bit2c",
            "name": "Bit2C",
            "countries": [
                "IL"
            ],
            "enableRateLimit": true,
            "rateLimit": 3000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelAllOrders": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createOrderWithTakeProfitAndStopLossWs": false,
                "createReduceOnlyOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": "emulated",
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": true,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchUnderlyingAssets": false,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": false,
                "ws": false,
                "repayMargin": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/db0bce50-6842-4c09-a1d5-0c87d22118aa",
                "api": {
                    "rest": "https://bit2c.co.il"
                },
                "www": "https://www.bit2c.co.il",
                "doc": [
                    "https://www.bit2c.co.il/home/api",
                    "https://github.com/OferE/bit2c"
                ],
                "referral": "https://bit2c.co.il/Aff/63bfed10-e359-420c-ab5a-ad368dab0baf"
            },
            "api": {
                "public": {
                    "get": [
                        "Exchanges/{pair}/Ticker",
                        "Exchanges/{pair}/orderbook",
                        "Exchanges/{pair}/trades",
                        "Exchanges/{pair}/lasttrades"
                    ]
                },
                "private": {
                    "post": [
                        "Merchant/CreateCheckout",
                        "Funds/AddCoinFundsRequest",
                        "Order/AddFund",
                        "Order/AddOrder",
                        "Order/GetById",
                        "Order/AddOrderMarketPriceBuy",
                        "Order/AddOrderMarketPriceSell",
                        "Order/CancelOrder",
                        "Order/AddCoinFundsRequest",
                        "Order/AddStopOrder",
                        "Payment/GetMyId",
                        "Payment/Send",
                        "Payment/Pay"
                    ],
                    "get": [
                        "Account/Balance",
                        "Account/Balance/v2",
                        "Order/MyOrders",
                        "Order/GetById",
                        "Order/AccountHistory",
                        "Order/OrderHistory"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "markets": {
                "BTC/NIS": {
                    "id": "BtcNis",
                    "symbol": "BTC/NIS",
                    "base": "BTC",
                    "quote": "NIS",
                    "baseId": "Btc",
                    "quoteId": "Nis",
                    "type": "spot",
                    "spot": true,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "index": false,
                    "contract": false,
                    "precision": {},
                    "limits": {
                        "leverage": {},
                        "amount": {},
                        "price": {},
                        "cost": {}
                    },
                    "marginModes": {}
                },
                "ETH/NIS": {
                    "id": "EthNis",
                    "symbol": "ETH/NIS",
                    "base": "ETH",
                    "quote": "NIS",
                    "baseId": "Eth",
                    "quoteId": "Nis",
                    "type": "spot",
                    "spot": true,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "index": false,
                    "contract": false,
                    "precision": {},
                    "limits": {
                        "leverage": {},
                        "amount": {},
                        "price": {},
                        "cost": {}
                    },
                    "marginModes": {}
                },
                "LTC/NIS": {
                    "id": "LtcNis",
                    "symbol": "LTC/NIS",
                    "base": "LTC",
                    "quote": "NIS",
                    "baseId": "Ltc",
                    "quoteId": "Nis",
                    "type": "spot",
                    "spot": true,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "index": false,
                    "contract": false,
                    "precision": {},
                    "limits": {
                        "leverage": {},
                        "amount": {},
                        "price": {},
                        "cost": {}
                    },
                    "marginModes": {}
                },
                "USDC/NIS": {
                    "id": "UsdcNis",
                    "symbol": "USDC/NIS",
                    "base": "USDC",
                    "quote": "NIS",
                    "baseId": "Usdc",
                    "quoteId": "Nis",
                    "type": "spot",
                    "spot": true,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "index": false,
                    "contract": false,
                    "precision": {},
                    "limits": {
                        "leverage": {},
                        "amount": {},
                        "price": {},
                        "cost": {}
                    },
                    "marginModes": {}
                }
            },
            "currencies": {},
            "fees": {
                "trading": {
                    "tierBased": true,
                    "percentage": true,
                    "taker": 0.03,
                    "maker": 0.025,
                    "tiers": {
                        "taker": [
                            [
                                0,
                                0.03
                            ],
                            [
                                20000,
                                0.0275
                            ],
                            [
                                50000,
                                0.025
                            ],
                            [
                                75000,
                                0.0225
                            ],
                            [
                                100000,
                                0.02
                            ],
                            [
                                250000,
                                0.015
                            ],
                            [
                                500000,
                                0.0125
                            ],
                            [
                                750000,
                                0.01
                            ],
                            [
                                1000000,
                                0.008
                            ],
                            [
                                2000000,
                                0.006
                            ],
                            [
                                3000000,
                                0.004
                            ],
                            [
                                4000000,
                                0.002
                            ]
                        ],
                        "maker": [
                            [
                                0,
                                0.025
                            ],
                            [
                                20000,
                                0.0225
                            ],
                            [
                                50000,
                                0.02
                            ],
                            [
                                75000,
                                0.0175
                            ],
                            [
                                100000,
                                0.015
                            ],
                            [
                                250000,
                                0.01
                            ],
                            [
                                500000,
                                0.0075
                            ],
                            [
                                750000,
                                0.005
                            ],
                            [
                                1000000,
                                0.004
                            ],
                            [
                                2000000,
                                0.003
                            ],
                            [
                                3000000,
                                0.002
                            ],
                            [
                                4000000,
                                0.001
                            ]
                        ]
                    }
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "options": {
                "fetchTradesMethod": "public_get_exchanges_pair_trades"
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 30,
                        "untilDays": 30,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    fn parse_balance(&self, mut response: Value) -> Value {
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined
        }))).unwrap());
        let mut codes: Value = self.get("currencies".into()).keys();
        let mut i: usize = 0;
        while i < codes.len() {
            let mut code: Value = codes.get(i.into());
            let mut account: Value = self.account();
            let mut currency: Value = self.currency(code.clone());
            let mut uppercase: Value = currency.get(Value::from("id")).to_upper_case();
            if response.contains_key(uppercase.clone()) {
                account.set("free".into(), self.safe_string(response.clone(), Value::from("AVAILABLE_") + uppercase.clone(), Value::Undefined));
                account.set("total".into(), self.safe_string(response.clone(), uppercase.clone(), Value::Undefined));
            };
            result.set(code.clone(), account.clone());
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetAccountBalanceV2".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "AVAILABLE_NIS": 0.0,
        //         "NIS": 0.0,
        //         "LOCKED_NIS": 0.0,
        //         "AVAILABLE_BTC": 0.0,
        //         "BTC": 0.0,
        //         "LOCKED_BTC": 0.0,
        //         "AVAILABLE_ETH": 0.0,
        //         "ETH": 0.0,
        //         "LOCKED_ETH": 0.0,
        //         "AVAILABLE_BCHSV": 0.0,
        //         "BCHSV": 0.0,
        //         "LOCKED_BCHSV": 0.0,
        //         "AVAILABLE_BCHABC": 0.0,
        //         "BCHABC": 0.0,
        //         "LOCKED_BCHABC": 0.0,
        //         "AVAILABLE_LTC": 0.0,
        //         "LTC": 0.0,
        //         "LOCKED_LTC": 0.0,
        //         "AVAILABLE_ETC": 0.0,
        //         "ETC": 0.0,
        //         "LOCKED_ETC": 0.0,
        //         "AVAILABLE_BTG": 0.0,
        //         "BTG": 0.0,
        //         "LOCKED_BTG": 0.0,
        //         "AVAILABLE_GRIN": 0.0,
        //         "GRIN": 0.0,
        //         "LOCKED_GRIN": 0.0,
        //         "Fees": {
        //             "BtcNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "EthNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "BchabcNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "LtcNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "EtcNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "BtgNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "LtcBtc": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "BchsvNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "GrinNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 }
        //         }
        //     }
        //
        return <Self as Bit2c>::parse_balance(self, response.clone());
    }

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bit2c>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut average_price: Value = self.safe_string(ticker.clone(), Value::from("av"), Value::Undefined);
        let mut base_volume: Value = self.safe_string(ticker.clone(), Value::from("a"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("ll"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "high": Value::Undefined,
            "low": Value::Undefined,
            "bid": self.safe_string(ticker.clone(), Value::from("h"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("l"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last,
            "last": last,
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": average_price,
            "baseVolume": base_volume,
            "quoteVolume": Value::Undefined,
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bit2c>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_trading_fees(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetAccountBalance".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "AVAILABLE_NIS": 0.0,
        //         "NIS": 0.0,
        //         "LOCKED_NIS": 0.0,
        //         "AVAILABLE_BTC": 0.0,
        //         "BTC": 0.0,
        //         "LOCKED_BTC": 0.0,
        //         ...
        //         "Fees": {
        //             "BtcNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             "EthNis": { "FeeMaker": 1.0, "FeeTaker": 1.0 },
        //             ...
        //         }
        //     }
        //
        let mut fees: Value = self.safe_value(response.clone(), Value::from("Fees"), Value::new_object());
        let mut keys: Value = fees.clone().keys();
        let mut result: Value = Value::new_object();
        let mut i: usize = 0;
        while i < keys.len() {
            let mut market_id: Value = keys.get(i.into());
            let mut symbol: Value = self.safe_symbol(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
            let mut fee: Value = self.safe_value(fees.clone(), market_id.clone(), Value::Undefined);
            let mut maker_string: Value = self.safe_string(fee.clone(), Value::from("FeeMaker"), Value::Undefined);
            let mut taker_string: Value = self.safe_string(fee.clone(), Value::from("FeeTaker"), Value::Undefined);
            let mut maker: Value = self.parse_number(Precise::string_div(maker_string.clone(), Value::from("100"), Value::Undefined), Value::Undefined);
            let mut taker: Value = self.parse_number(Precise::string_div(taker_string.clone(), Value::from("100"), Value::Undefined), Value::Undefined);
            result.set(symbol.clone(), Value::Json(normalize(&Value::Json(json!({
                "info": fee,
                "symbol": symbol,
                "taker": taker,
                "maker": maker,
                "percentage": true,
                "tierBased": true
            }))).unwrap()));
            i += 1;
        };
        return result.clone();
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut method: Value = Value::from("privatePostOrderAddOrder");
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "Amount": amount,
            "Pair": market.get(Value::from("id"))
        }))).unwrap());
        if r#type.clone() == Value::from("market") {
            method = method +  Value::from("MarketPrice") + self.capitalize(side.clone());
        } else {
            request.set("Price".into(), price.clone());
            let mut amount_string: Value = self.number_to_string(amount.clone());
            let mut price_string: Value = self.number_to_string(price.clone());
            request.set("Total".into(), self.parse_to_numeric(Precise::string_mul(amount_string.clone(), price_string.clone()), Value::Undefined));
            request.set("IsBid".into(), side.clone() == Value::from("buy"));
        };
        let mut response: Value = self.dispatch(method, extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return <Self as Bit2c>::parse_order(self, response.clone(), market.clone());
    }

    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "id": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostOrderCancelOrder".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return <Self as Bit2c>::parse_order(self, response.clone(), Value::Undefined);
    }

    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if symbol.clone().is_nullish() {
            panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" fetchOpenOrders() requires a symbol argument"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "pair": market.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetOrderMyOrders".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        let mut orders: Value = self.safe_value(response.clone(), market.get(Value::from("id")), Value::new_object());
        let mut asks: Value = self.safe_value(orders.clone(), Value::from("ask"), Value::new_array());
        let mut bids: Value = self.safe_list(orders.clone(), Value::from("bid"), Value::new_array());
        return self.parse_orders(self.array_concat(asks.clone(), bids.clone()), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "id": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetOrderGetById".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //         {
        //             "pair": "BtcNis",
        //             "status": "Completed",
        //             "created": 1666689837,
        //             "type": 0,
        //             "order_type": 0,
        //             "amount": 0.00000000,
        //             "price": 50000.00000000,
        //             "stop": 0,
        //             "id": 10951473,
        //             "initialAmount": 2.00000000
        //         }
        //
        return <Self as Bit2c>::parse_order(self, response.clone(), market.clone());
    }

    fn parse_order(&mut self, mut order: Value, mut market: Value) -> Value {
        //
        //      createOrder
        //      {
        //          "OrderResponse": {"pair": "BtcNis", "HasError": False, "Error": "", "Message": ""},
        //          "NewOrder": {
        //              "created": 1505531577,
        //              "type": 0,
        //              "order_type": 0,
        //              "status_type": 0,
        //              "amount": 0.01,
        //              "price": 10000,
        //              "stop": 0,
        //              "id": 9244416,
        //              "initialAmount": None,
        //          },
        //      }
        //      fetchOrder, fetchOpenOrders
        //      {
        //          "pair": "BtcNis",
        //          "status": "Completed",
        //          "created": 1535555837,
        //          "type": 0,
        //          "order_type": 0,
        //          "amount": 0.00000000,
        //          "price": 120000.00000000,
        //          "stop": 0,
        //          "id": 10555173,
        //          "initialAmount": 2.00000000
        //      }
        //
        let mut order_unified: Value = Value::Undefined;
        let mut is_new_order: Value = false.into();
        if order.contains_key(Value::from("NewOrder")) {
            order_unified = order.get(Value::from("NewOrder"));
            is_new_order = true.into();
        } else {
            order_unified = order.clone();
        };
        let mut id: Value = self.safe_string(order_unified.clone(), Value::from("id"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer_product(order_unified.clone(), Value::from("created"), Value::from(1000), Value::Undefined);
        // status field vary between responses
        // bit2c status type:
        // 0 = New
        // 1 = Open
        // 5 = Completed
        let mut status: Value = Value::Undefined;
        if is_new_order.is_truthy() {
            let mut temp_status: Value = self.safe_integer(order_unified.clone(), Value::from("status_type"), Value::Undefined);
            if temp_status.clone() == Value::from(0) || temp_status.clone() == Value::from(1) {
                status = Value::from("open");
            } else if temp_status.clone() == Value::from(5) {
                status = Value::from("closed");
            };
        } else {
            let mut temp_status: Value = self.safe_string(order_unified.clone(), Value::from("status"), Value::Undefined);
            if temp_status.clone() == Value::from("New") || temp_status.clone() == Value::from("Open") {
                status = Value::from("open");
            } else if temp_status.clone() == Value::from("Completed") {
                status = Value::from("closed");
            };
        };
        // bit2c order type:
        // 0 = LMT,  1 = MKT
        let mut r#type: Value = self.safe_string(order_unified.clone(), Value::from("order_type"), Value::Undefined);
        if r#type.clone() == Value::from("0") {
            r#type = Value::from("limit");
        } else if r#type.clone() == Value::from("1") {
            r#type = Value::from("market");
        };
        // bit2c side:
        // 0 = buy, 1 = sell
        let mut side: Value = self.safe_string(order_unified.clone(), Value::from("type"), Value::Undefined);
        if side.clone() == Value::from("0") {
            side = Value::from("buy");
        } else if side.clone() == Value::from("1") {
            side = Value::from("sell");
        };
        let mut price: Value = self.safe_string(order_unified.clone(), Value::from("price"), Value::Undefined);
        let mut amount: Value = Value::Undefined;
        let mut remaining: Value = Value::Undefined;
        if is_new_order.is_truthy() {
            amount = self.safe_string(order_unified.clone(), Value::from("amount"), Value::Undefined);
            // NOTE:'initialAmount' is currently not set on new order
            remaining = self.safe_string(order_unified.clone(), Value::from("amount"), Value::Undefined);
        } else {
            amount = self.safe_string(order_unified.clone(), Value::from("initialAmount"), Value::Undefined);
            remaining = self.safe_string(order_unified.clone(), Value::from("amount"), Value::Undefined);
        };
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "clientOrderId": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": Value::Undefined,
            "status": status,
            "symbol": symbol,
            "type": r#type,
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "side": side,
            "price": price,
            "triggerPrice": Value::Undefined,
            "amount": amount,
            "filled": Value::Undefined,
            "remaining": remaining,
            "cost": Value::Undefined,
            "trades": Value::Undefined,
            "fee": Value::Undefined,
            "info": order,
            "average": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = Value::Undefined;
        let mut request: Value = Value::new_object();
        if limit.clone().is_nonnullish() {
            request.set("take".into(), limit.clone());
        };
        request.set("take".into(), limit.clone());
        if since.clone().is_nonnullish() {
            request.set("toTime".into(), self.yyyymmdd(self.milliseconds(), Value::from(".")));
            request.set("fromTime".into(), self.yyyymmdd(since.clone(), Value::from(".")));
        };
        if symbol.clone().is_nonnullish() {
            market = self.market(symbol.clone());
            request.set("pair".into(), market.get(Value::from("id")));
        };
        let mut response: Value = self.dispatch("privateGetOrderOrderHistory".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     [
        //         {
        //             "ticks":1574767951,
        //             "created":"26/11/19 13:32",
        //             "action":1,
        //             "price":"1000",
        //             "pair":"EthNis",
        //             "reference":"EthNis|10867390|10867377",
        //             "fee":"0.5",
        //             "feeAmount":"0.08",
        //             "feeCoin":"₪",
        //             "firstAmount":"-0.015",
        //             "firstAmountBalance":"9",
        //             "secondAmount":"14.93",
        //             "secondAmountBalance":"130,233.28",
        //             "firstCoin":"ETH",
        //             "secondCoin":"₪"
        //         },
        //         {
        //             "ticks":1574767951,
        //             "created":"26/11/19 13:32",
        //             "action":0,
        //             "price":"1000",
        //             "pair":"EthNis",
        //             "reference":"EthNis|10867390|10867377",
        //             "fee":"0.5",
        //             "feeAmount":"0.08",
        //             "feeCoin":"₪",
        //             "firstAmount":"0.015",
        //             "firstAmountBalance":"9.015",
        //             "secondAmount":"-15.08",
        //             "secondAmountBalance":"130,218.35",
        //             "firstCoin":"ETH",
        //             "secondCoin":"₪"
        //         }
        //     ]
        //
        return self.parse_trades(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    fn remove_comma_from_value(&mut self, mut str: Value) -> Value {
        let mut new_string: Value = Value::from("");
        let mut str_parts: Value = str.split(Value::from(","));
        let mut i: usize = 0;
        while i < str_parts.len() {
            new_string = new_string +  str_parts.get(i.into());
            i += 1;
        };
        return new_string.clone();
    }

    fn parse_trade(&mut self, mut trade: Value, mut market: Value) -> Value {
        //
        // public fetchTrades
        //
        //     {
        //         "date":1651785980,
        //         "price":127975.68,
        //         "amount":0.3750321,
        //         "isBid":true,
        //         "tid":1261018
        //     }
        //
        // private fetchMyTrades
        //
        //     {
        //         "ticks":1574767951,
        //         "created":"26/11/19 13:32",
        //         "action":1,
        //         "price":"1,000",
        //         "pair":"EthNis",
        //         "reference":"EthNis|10867390|10867377",
        //         "fee":"0.5",
        //         "feeAmount":"0.08",
        //         "feeCoin":"₪",
        //         "firstAmount":"-0.015",
        //         "firstAmountBalance":"9",
        //         "secondAmount":"14.93",
        //         "secondAmountBalance":"130,233.28",
        //         "firstCoin":"ETH",
        //         "secondCoin":"₪"
        //         "isMaker": True,
        //     }
        //
        let mut timestamp: Value = Value::Undefined;
        let mut id: Value = Value::Undefined;
        let mut price: Value = Value::Undefined;
        let mut amount: Value = Value::Undefined;
        let mut order_id: Value = Value::Undefined;
        let mut fee: Value = Value::Undefined;
        let mut side: Value = Value::Undefined;
        let mut maker_or_taker: Value = Value::Undefined;
        let mut reference: Value = self.safe_string(trade.clone(), Value::from("reference"), Value::Undefined);
        if reference.clone().is_nonnullish() {
            id = reference.clone();
            timestamp = self.safe_timestamp(trade.clone(), Value::from("ticks"), Value::Undefined);
            price = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
            price = <Self as Bit2c>::remove_comma_from_value(self, price.clone());
            amount = self.safe_string(trade.clone(), Value::from("firstAmount"), Value::Undefined);
            let mut reference_parts: Value = reference.split(Value::from("|"));
            // reference contains 'pair|orderId_by_taker|orderId_by_maker'
            let mut market_id: Value = self.safe_string(trade.clone(), Value::from("pair"), Value::Undefined);
            market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
            market = self.safe_market(reference_parts.get(Value::from(0)), market.clone(), Value::Undefined, Value::Undefined);
            let mut is_maker: Value = self.safe_value(trade.clone(), Value::from("isMaker"), Value::Undefined);
            maker_or_taker = if is_maker.is_truthy() { Value::from("maker") } else { Value::from("taker") };
            order_id = if is_maker.is_truthy() { reference_parts.get(Value::from(2)) } else { reference_parts.get(Value::from(1)) };
            let mut action: Value = self.safe_integer(trade.clone(), Value::from("action"), Value::Undefined);
            if action.clone() == Value::from(0) {
                side = Value::from("buy");
            } else {
                side = Value::from("sell");
            };
            let mut fee_cost: Value = self.safe_string(trade.clone(), Value::from("feeAmount"), Value::Undefined);
            if fee_cost.clone().is_nonnullish() {
                fee = Value::Json(normalize(&Value::Json(json!({
                    "cost": fee_cost,
                    "currency": "NIS"
                }))).unwrap());
            };
        } else {
            timestamp = self.safe_timestamp(trade.clone(), Value::from("date"), Value::Undefined);
            id = self.safe_string(trade.clone(), Value::from("tid"), Value::Undefined);
            price = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
            amount = self.safe_string(trade.clone(), Value::from("amount"), Value::Undefined);
            side = self.safe_value(trade.clone(), Value::from("isBid"), Value::Undefined);
            if side.clone().is_nonnullish() {
                if side.is_truthy() {
                    side = Value::from("buy");
                } else {
                    side = Value::from("sell");
                };
            };
        };
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "id": id,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "order": order_id,
            "type": Value::Undefined,
            "side": side,
            "takerOrMaker": maker_or_taker,
            "price": price,
            "amount": amount,
            "cost": Value::Undefined,
            "fee": fee
        }))).unwrap()), market.clone());
    }

    fn is_fiat(&mut self, mut code: Value) -> Value {
        return (code.clone() == Value::from("NIS")).into();
    }

    async fn fetch_deposit_address(&mut self, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        if <Self as Bit2c>::is_fiat(self, code.clone()).is_truthy() {
            panic!(r###"NotSupported::new(self.get("id".into()) + Value::from(" fetchDepositAddress() does not support fiat currencies"))"###);
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "Coin": currency.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostFundsAddCoinFundsRequest".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "address": "0xf14b94518d74aff2b1a6d3429471bcfcd3881d42",
        //         "hasTx": False
        //     }
        //
        return <Self as Bit2c>::parse_deposit_address(self, response.clone(), currency.clone());
    }

    fn parse_deposit_address(&mut self, mut deposit_address: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "address": "0xf14b94518d74aff2b1a6d3429471bcfcd3881d42",
        //         "hasTx": False
        //     }
        //
        let mut address: Value = self.safe_string(deposit_address.clone(), Value::from("address"), Value::Undefined);
        self.check_address(address.clone());
        let mut code: Value = self.safe_currency_code(Value::Undefined, currency.clone());
        return Value::Json(normalize(&Value::Json(json!({
            "info": deposit_address,
            "currency": code,
            "network": Value::Undefined,
            "address": address,
            "tag": Value::Undefined
        }))).unwrap());
    }

    fn nonce(&self) -> Value {
        return self.milliseconds();
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetExchangespairticker" => self.request("Exchanges/{pair}/Ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetExchangespairorderbook" => self.request("Exchanges/{pair}/orderbook".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetExchangespairtrades" => self.request("Exchanges/{pair}/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetExchangespairlasttrades" => self.request("Exchanges/{pair}/lasttrades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostMerchantcreatecheckout" => self.request("Merchant/CreateCheckout".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostFundsaddcoinfundsrequest" => self.request("Funds/AddCoinFundsRequest".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddfund" => self.request("Order/AddFund".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddorder" => self.request("Order/AddOrder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrdergetbyid" => self.request("Order/GetById".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddordermarketpricebuy" => self.request("Order/AddOrderMarketPriceBuy".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddordermarketpricesell" => self.request("Order/AddOrderMarketPriceSell".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrdercancelorder" => self.request("Order/CancelOrder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddcoinfundsrequest" => self.request("Order/AddCoinFundsRequest".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrderaddstoporder" => self.request("Order/AddStopOrder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPaymentgetmyid" => self.request("Payment/GetMyId".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPaymentsend" => self.request("Payment/Send".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPaymentpay" => self.request("Payment/Pay".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountbalance" => self.request("Account/Balance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountbalancev2" => self.request("Account/Balance/v2".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrdermyorders" => self.request("Order/MyOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrdergetbyid" => self.request("Order/GetById".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderaccounthistory" => self.request("Order/AccountHistory".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrderorderhistory" => self.request("Order/OrderHistory".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Bit2cImpl(Value);
impl Exchange for Bit2cImpl {}
impl Bit2c for Bit2cImpl {}
impl ValueTrait for Bit2cImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl Bit2cImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = Bit2cImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bit2c::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

