#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
use crate::ws::{ArrayCache, ArrayCacheByTimestamp, ArrayCacheBySymbolById, ArrayCacheBySymbolBySide};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors (stub structs with ::new for transpiled `new ErrorType(msg)` patterns)
macro_rules! error_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(msg: Value) -> Value { msg } } }; }
error_stub!(BadRequest);
error_stub!(InvalidOrder);
error_stub!(ExchangeError);
error_stub!(InsufficientFunds);
error_stub!(OrderNotFound);
error_stub!(AuthenticationError);
error_stub!(PermissionDenied);
error_stub!(ExchangeNotAvailable);
error_stub!(ArgumentsRequired);
error_stub!(RateLimitExceeded);
error_stub!(OrderNotFillable);
error_stub!(OrderImmediatelyFillable);
error_stub!(NotSupported);
error_stub!(DuplicateOrderId);
error_stub!(UnsubscribeError);
error_stub!(ChecksumError);
error_stub!(InvalidNonce);
error_stub!(BadSymbol);
// Array-like type stubs (Bids/Asks order book sides)
macro_rules! array_side_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(data: Value, _limit: Value) -> Value { data } } }; }
array_side_stub!(Bids);
array_side_stub!(Asks);

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait(?Send)]
pub trait Bitbank : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bitbank",
            "name": "bitbank",
            "countries": [
                "JP"
            ],
            "enableRateLimit": true,
            "rateLimit": 100,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelAllOrders": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createOrderWithTakeProfitAndStopLossWs": false,
                "createReduceOnlyOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": true,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": false,
                "withdraw": true
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/9d616de0-8a88-4468-8e38-d269acab0348",
                "api": {
                    "public": "https://public.{hostname}",
                    "private": "https://api.{hostname}",
                    "markets": "https://api.{hostname}"
                },
                "www": "https://bitbank.cc/",
                "doc": "https://docs.bitbank.cc/",
                "fees": "https://bitbank.cc/docs/fees/"
            },
            "api": {
                "public": {
                    "get": {
                        "{pair}/ticker": 1,
                        "tickers": 1,
                        "tickers_jpy": 1,
                        "{pair}/depth": 1,
                        "{pair}/transactions": 1,
                        "{pair}/transactions/{yyyymmdd}": 1,
                        "{pair}/candlestick/{candletype}/{yyyymmdd}": 1,
                        "{pair}/circuit_break_info": 1
                    }
                },
                "private": {
                    "get": {
                        "user/assets": 1,
                        "user/spot/order": 1,
                        "user/spot/active_orders": 1,
                        "user/margin/positions": 1,
                        "user/spot/trade_history": 1,
                        "user/deposit_history": 1,
                        "user/unconfirmed_deposits": 1,
                        "user/deposit_originators": 1,
                        "user/withdrawal_account": 1,
                        "user/withdrawal_history": 1,
                        "spot/status": 1,
                        "spot/pairs": 1
                    },
                    "post": {
                        "user/spot/order": 1.66,
                        "user/spot/cancel_order": 1.66,
                        "user/spot/cancel_orders": 1.66,
                        "user/spot/orders_info": 1.66,
                        "user/confirm_deposits": 1.66,
                        "user/confirm_deposits_all": 1.66,
                        "user/request_withdrawal": 1.66
                    }
                },
                "markets": {
                    "get": {
                        "spot/pairs": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": "1min",
                "5m": "5min",
                "15m": "15min",
                "30m": "30min",
                "1h": "1hour",
                "4h": "4hour",
                "8h": "8hour",
                "12h": "12hour",
                "1d": "1day",
                "1w": "1week"
            },
            "fees": {
                "trading": {},
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "hostname": "bitbank.cc",
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 1000,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    

    fn parse_market(&self, mut entry: Value) -> Value {
        let mut id: Value = self.safe_string(entry.clone(), Value::from("name"), Value::Undefined);
        let mut base_id: Value = self.safe_string(entry.clone(), Value::from("base_asset"), Value::Undefined);
        let mut quote_id: Value = self.safe_string(entry.clone(), Value::from("quote_asset"), Value::Undefined);
        let mut base: Value = self.safe_currency_code(base_id.clone(), Value::Undefined);
        let mut quote: Value = self.safe_currency_code(quote_id.clone(), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "symbol": base.clone() + Value::from("/") + quote.clone(),
            "base": base.clone(),
            "quote": quote.clone(),
            "settle": Value::Undefined,
            "baseId": base_id.clone(),
            "quoteId": quote_id.clone(),
            "settleId": Value::Undefined,
            "type": Value::from("spot"),
            "spot": Value::from(true),
            "margin": Value::from(false),
            "swap": Value::from(false),
            "future": Value::from(false),
            "option": Value::from(false),
            "active": self.safe_value(entry.clone(), Value::from("is_enabled"), Value::Undefined),
            "contract": Value::from(false),
            "linear": Value::Undefined,
            "inverse": Value::Undefined,
            "taker": self.safe_number(entry.clone(), Value::from("taker_fee_rate_quote"), Value::Undefined),
            "maker": self.safe_number(entry.clone(), Value::from("maker_fee_rate_quote"), Value::Undefined),
            "contractSize": Value::Undefined,
            "expiry": Value::Undefined,
            "expiryDatetime": Value::Undefined,
            "strike": Value::Undefined,
            "optionType": Value::Undefined,
            "precision": Value::Json(normalize(&Value::Json(json!({
                "amount": self.parse_number(self.parse_precision(self.safe_string(entry.clone(), Value::from("amount_digits"), Value::Undefined)), Value::Undefined),
                "price": self.parse_number(self.parse_precision(self.safe_string(entry.clone(), Value::from("price_digits"), Value::Undefined)), Value::Undefined)
            }))).unwrap()),
            "limits": Value::Json(normalize(&Value::Json(json!({
                "leverage": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap()),
                "amount": Value::Json(normalize(&Value::Json(json!({
                    "min": self.safe_number(entry.clone(), Value::from("unit_amount"), Value::Undefined),
                    "max": self.safe_number(entry.clone(), Value::from("limit_max_amount"), Value::Undefined)
                }))).unwrap()),
                "price": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap()),
                "cost": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap())
            }))).unwrap()),
            "created": Value::Undefined,
            "info": entry.clone()
        }))).unwrap());
    }

    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(ticker.clone(), Value::from("timestamp"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("last"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "high": self.safe_string(ticker.clone(), Value::from("high"), Value::Undefined),
            "low": self.safe_string(ticker.clone(), Value::from("low"), Value::Undefined),
            "bid": self.safe_string(ticker.clone(), Value::from("buy"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("sell"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last.clone(),
            "last": last.clone(),
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("vol"), Value::Undefined),
            "quoteVolume": Value::Undefined,
            "info": ticker.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        // Some exchanges wrap the ticker in {data: {...}} or {result: {...}} — unwrap if so.
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut tk = json_resp.clone();
        if !tk.is_array() && tk.get("last").is_none() && tk.get("close").is_none() && tk.get("bid").is_none() {
            for key in &["data", "result", "ticker"] {
                if let Some(v) = json_resp.get(key) {
                    if v.is_object() { tk = v.clone(); break; }
                    if let Some(arr) = v.as_array() {
                        if let Some(first) = arr.first() { tk = first.clone(); break; }
                    }
                }
            }
        }
        let market: Value = Value::Undefined;
        let parsed = <Self as Exchange>::parse_ticker(self, Value::Json(tk.clone()), market);
        if parsed.is_undefined() { Value::Json(tk) } else { parsed }
    }


    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut ob = crate::exchange::unwrap_response_order_book(&json_resp);
        if let serde_json::Value::Object(ref mut map) = ob {
            if !map.contains_key("symbol") { map.insert("symbol".to_string(), serde_json::json!(symbol.unwrap_str())); }
        }
        Value::Json(ob)
    }


    fn parse_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        // fetchTrades
        //
        //    {
        //        "transaction_id": "1143247037",
        //        "side": "buy",
        //        "price": "3836025",
        //        "amount": "0.0005",
        //        "executed_at": "1694249441593"
        //    }
        //
        let mut timestamp: Value = self.safe_integer(trade.clone(), Value::from("executed_at"), Value::Undefined);
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string(trade.clone(), Value::from("amount"), Value::Undefined);
        let mut id: Value = self.safe_string_2(trade.clone(), Value::from("transaction_id"), Value::from("trade_id"), Value::Undefined);
        let mut taker_or_maker: Value = self.safe_string(trade.clone(), Value::from("maker_taker"), Value::Undefined);
        let mut fee: Value = Value::Undefined;
        let mut fee_cost_string: Value = self.safe_string(trade.clone(), Value::from("fee_amount_quote"), Value::Undefined);
        if fee_cost_string.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "currency": market.get(Value::from("quote")),
                "cost": fee_cost_string.clone()
            }))).unwrap());
        };
        let mut order_id: Value = self.safe_string(trade.clone(), Value::from("order_id"), Value::Undefined);
        let mut r#type: Value = self.safe_string(trade.clone(), Value::from("type"), Value::Undefined);
        let mut side: Value = self.safe_string(trade.clone(), Value::from("side"), Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "id": id.clone(),
            "order": order_id.clone(),
            "type": r#type.clone(),
            "side": side.clone(),
            "takerOrMaker": taker_or_maker.clone(),
            "price": price_string.clone(),
            "amount": amount_string.clone(),
            "cost": Value::Undefined,
            "fee": fee.clone(),
            "info": trade.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        let mut raw: Value = Value::Undefined;
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { raw = rv; break; }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            // Already-parsed trades have both `price` and `amount` keys.
            if item.get("price").is_some() && item.get("amount").is_some() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_trade(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    async fn fetch_trading_fees(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("marketsGetSpotPairs".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "success": "1",
        //         "data": {
        //           "pairs": [
        //             {
        //               "name": "btc_jpy",
        //               "base_asset": "btc",
        //               "quote_asset": "jpy",
        //               "maker_fee_rate_base": "0",
        //               "taker_fee_rate_base": "0",
        //               "maker_fee_rate_quote": "-0.0002",
        //               "taker_fee_rate_quote": "0.0012",
        //               "unit_amount": "0.0001",
        //               "limit_max_amount": "1000",
        //               "market_max_amount": "10",
        //               "market_allowance_rate": "0.2",
        //               "price_digits": "0",
        //               "amount_digits": "4",
        //               "is_enabled": true,
        //               "stop_order": false,
        //               "stop_order_and_cancel": false
        //             },
        //             ...
        //           ]
        //         }
        //     }
        //
        let mut data: Value = self.safe_value(response.clone(), Value::from("data"), Value::new_object());
        let mut pairs: Value = self.safe_value(data.clone(), Value::from("pairs"), Value::new_array());
        let mut result: Value = Value::new_object();
        let mut i: usize = 0;
        while i < pairs.len() {
            let mut pair: Value = pairs.get(i.into());
            let mut market_id: Value = self.safe_string(pair.clone(), Value::from("name"), Value::Undefined);
            let mut market: Value = self.safe_market(market_id.clone(), Value::Undefined, Value::Undefined, Value::Undefined);
            let mut symbol: Value = market.get(Value::from("symbol"));
            result.set(symbol.clone(), Value::Json(normalize(&Value::Json(json!({
                "info": pair.clone(),
                "symbol": symbol.clone(),
                "maker": self.safe_number(pair.clone(), Value::from("maker_fee_rate_quote"), Value::Undefined),
                "taker": self.safe_number(pair.clone(), Value::from("taker_fee_rate_quote"), Value::Undefined),
                "percentage": Value::from(true),
                "tierBased": Value::from(false)
            }))).unwrap()));
            i += 1;
        };
        return result.clone();
    }

    fn parse_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        //
        //     [
        //         "0.02501786",
        //         "0.02501786",
        //         "0.02501786",
        //         "0.02501786",
        //         "0.0000",
        //         1591488000000
        //     ]
        //
        return Value::Json(serde_json::Value::Array(vec![(self.safe_integer(ohlcv.clone(), Value::from(5), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(0), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(1), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(2), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(3), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(4), Value::Undefined)).into()]));
    }

    async fn fetch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("timeframe".into(), timeframe.clone());
        request.set("interval".into(), timeframe.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        // Match endpoints by substring on common OHLCV path tokens (klines, candles,
        // ohlcv, barhist, history, kline, candle, ohlc).
        'outer: for token in ["klines", "candles", "ohlcv", "barhist", "kline", "candle", "ohlc"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "klines"), ("public", "GET", "candles"), ("public", "GET", "ohlcv")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            if item.is_array() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_ohlcv(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    fn parse_balance(&self, mut response: Value) -> Value {
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response.clone(),
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined
        }))).unwrap());
        let mut data: Value = self.safe_value(response.clone(), Value::from("data"), Value::new_object());
        let mut assets: Value = self.safe_value(data.clone(), Value::from("assets"), Value::new_array());
        let mut i: usize = 0;
        while i < assets.len() {
            let mut balance: Value = assets.get(i.into());
            let mut currency_id: Value = self.safe_string(balance.clone(), Value::from("asset"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("free".into(), self.safe_string(balance.clone(), Value::from("free_amount"), Value::Undefined));
            account.set("used".into(), self.safe_string(balance.clone(), Value::from("locked_amount"), Value::Undefined));
            account.set("total".into(), self.safe_string(balance.clone(), Value::from("onhand_amount"), Value::Undefined));
            result.set(code.clone(), account.clone());
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["account/balance", "balance", "wallet/balance", "accounts/balance", "account"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(&format!("/{}/", token)) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "balance"), ("private", "GET", "account/balance"), ("private", "GET", "wallet/balance")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "UNFILLED": Value::from("open"),
            "PARTIALLY_FILLED": Value::from("open"),
            "FULLY_FILLED": Value::from("closed"),
            "CANCELED_UNFILLED": Value::from("canceled"),
            "CANCELED_PARTIALLY_FILLED": Value::from("canceled")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order(&self, mut order: Value, mut market: Value) -> Value {
        let mut id: Value = self.safe_string(order.clone(), Value::from("order_id"), Value::Undefined);
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("pair"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("ordered_at"), Value::Undefined);
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"), Value::Undefined);
        let mut amount: Value = self.safe_string(order.clone(), Value::from("start_amount"), Value::Undefined);
        let mut filled: Value = self.safe_string(order.clone(), Value::from("executed_amount"), Value::Undefined);
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("remaining_amount"), Value::Undefined);
        let mut average: Value = self.safe_string(order.clone(), Value::from("average_price"), Value::Undefined);
        let mut status: Value = <Self as Bitbank>::parse_order_status(self, self.safe_string(order.clone(), Value::from("status"), Value::Undefined));
        let mut r#type: Value = self.safe_string_lower(order.clone(), Value::from("type"), Value::Undefined);
        let mut side: Value = self.safe_string_lower(order.clone(), Value::from("side"), Value::Undefined);
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "clientOrderId": Value::Undefined,
            "datetime": self.iso8601(timestamp.clone()),
            "timestamp": timestamp.clone(),
            "lastTradeTimestamp": Value::Undefined,
            "status": status.clone(),
            "symbol": market.get(Value::from("symbol")),
            "type": r#type.clone(),
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "side": side.clone(),
            "price": price.clone(),
            "triggerPrice": Value::Undefined,
            "cost": Value::Undefined,
            "average": average.clone(),
            "amount": amount.clone(),
            "filled": filled.clone(),
            "remaining": remaining.clone(),
            "trades": Value::Undefined,
            "fee": Value::Undefined,
            "info": order.clone()
        }))).unwrap()), market.clone());
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("type".into(), r#type.clone());
        request.set("side".into(), side.clone());
        request.set("amount".into(), amount.clone());
        if price.is_nonnullish() { request.set("price".into(), price.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "POST" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "POST", "order"), ("private", "POST", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("orderId".into(), id.clone());
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "DELETE" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "DELETE", "order"), ("private", "DELETE", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "order_id": id.clone(),
            "pair": market.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetUserSpotOrder".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //    {
        //        "success": 1,
        //        "data": {
        //          "order_id": 0,
        //          "pair": "string",
        //          "side": "string",
        //          "type": "string",
        //          "start_amount": "string",
        //          "remaining_amount": "string",
        //          "executed_amount": "string",
        //          "price": "string",
        //          "post_only": false,
        //          "average_price": "string",
        //          "ordered_at": 0,
        //          "expire_at": 0,
        //          "triggered_at": 0,
        //          "triger_price": "string",
        //          "status": "string"
        //        }
        //    }
        //
        let mut data: Value = self.safe_dict(response.clone(), Value::from("data"), Value::Undefined);
        return <Self as Bitbank>::parse_order(self, data.clone(), market.clone()).await;
    }

    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["openorders", "open_orders", "orders/open", "orders/active"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "openOrders"), ("private", "GET", "orders/open"), ("private", "GET", "orders/active")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitbank>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["mytrades", "my_trades", "trades/history", "fills", "user/trades", "executions"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "myTrades"), ("private", "GET", "fills"), ("private", "GET", "trades/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_deposit_address(&mut self, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "asset": currency.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetUserWithdrawalAccount".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        let mut data: Value = self.safe_value(response.clone(), Value::from("data"), Value::new_object());
        // Not sure about this if there could be more than one account...
        let mut accounts: Value = self.safe_value(data.clone(), Value::from("accounts"), Value::new_array());
        let mut first_account: Value = self.safe_value(accounts.clone(), Value::from(0), Value::new_object());
        let mut address: Value = self.safe_string(first_account.clone(), Value::from("address"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": response.clone(),
            "currency": currency.get(Value::from("code")),
            "network": Value::Undefined,
            "address": address.clone(),
            "tag": Value::Undefined
        }))).unwrap());
    }

    async fn withdraw(&mut self, mut code: Value, mut amount: Value, mut address: Value, mut tag: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        (tag, params) = shift_2(self.handle_withdraw_tag_and_params(tag.clone(), params.clone()));
        if !params.contains_key(Value::from("uuid")) {
            return Value::Undefined;
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "asset": currency.get(Value::from("id")),
            "amount": amount.clone()
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostUserRequestWithdrawal".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "success": 1,
        //         "data": {
        //             "uuid": "string",
        //             "asset": "btc",
        //             "amount": 0,
        //             "account_uuid": "string",
        //             "fee": 0,
        //             "status": "DONE",
        //             "label": "string",
        //             "txid": "string",
        //             "address": "string",
        //             "requested_at": 0
        //         }
        //     }
        //
        let mut data: Value = self.safe_dict(response.clone(), Value::from("data"), Value::new_object());
        return <Self as Bitbank>::parse_transaction(self, data.clone(), currency.clone()).await;
    }

    fn parse_transaction(&self, mut transaction: Value, mut currency: Value) -> Value {
        //
        // withdraw
        //
        //     {
        //         "uuid": "string",
        //         "asset": "btc",
        //         "amount": 0,
        //         "account_uuid": "string",
        //         "fee": 0,
        //         "status": "DONE",
        //         "label": "string",
        //         "txid": "string",
        //         "address": "string",
        //         "requested_at": 0
        //     }
        //
        let mut txid: Value = self.safe_string(transaction.clone(), Value::from("txid"), Value::Undefined);
        currency = self.safe_currency(Value::Undefined, currency.clone());
        return Value::Json(normalize(&Value::Json(json!({
            "id": txid.clone(),
            "txid": txid.clone(),
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "network": Value::Undefined,
            "addressFrom": Value::Undefined,
            "address": Value::Undefined,
            "addressTo": Value::Undefined,
            "amount": Value::Undefined,
            "type": Value::Undefined,
            "currency": currency.get(Value::from("code")),
            "status": Value::Undefined,
            "updated": Value::Undefined,
            "tagFrom": Value::Undefined,
            "tag": Value::Undefined,
            "tagTo": Value::Undefined,
            "comment": Value::Undefined,
            "internal": Value::Undefined,
            "fee": Value::Undefined,
            "info": transaction.clone()
        }))).unwrap());
    }

    fn nonce(&self) -> Value {
        return self.milliseconds();
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_str() {
                    "publicGetPairticker" => self.request("{pair}/ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickers" => self.request("tickers".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickersjpy" => self.request("tickers_jpy".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPairdepth" => self.request("{pair}/depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPairtransactions" => self.request("{pair}/transactions".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPairtransactionsyyyymmdd" => self.request("{pair}/transactions/{yyyymmdd}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPaircandlestickcandletypeyyyymmdd" => self.request("{pair}/candlestick/{candletype}/{yyyymmdd}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPaircircuitbreakinfo" => self.request("{pair}/circuit_break_info".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserassets" => self.request("user/assets".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserspotorder" => self.request("user/spot/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserspotactiveorders" => self.request("user/spot/active_orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUsermarginpositions" => self.request("user/margin/positions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserspottradehistory" => self.request("user/spot/trade_history".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserdeposithistory" => self.request("user/deposit_history".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserunconfirmeddeposits" => self.request("user/unconfirmed_deposits".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserdepositoriginators" => self.request("user/deposit_originators".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserwithdrawalaccount" => self.request("user/withdrawal_account".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserwithdrawalhistory" => self.request("user/withdrawal_history".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetSpotstatus" => self.request("spot/status".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetSpotpairs" => self.request("spot/pairs".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserspotorder" => self.request("user/spot/order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserspotcancelorder" => self.request("user/spot/cancel_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserspotcancelorders" => self.request("user/spot/cancel_orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserspotordersinfo" => self.request("user/spot/orders_info".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserconfirmdeposits" => self.request("user/confirm_deposits".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserconfirmdepositsall" => self.request("user/confirm_deposits_all".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserrequestwithdrawal" => self.request("user/request_withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "marketsGetSpotpairs" => self.request("spot/pairs".into(), "markets".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BitbankImpl(Value);
#[async_trait(?Send)]
impl Exchange for BitbankImpl {
    fn describe(&self) -> Value { Bitbank::describe(self) }
    async fn fetch_ticker(&mut self, symbol: Value, params: Value) -> Value { Bitbank::fetch_ticker(self, symbol, params).await }
    async fn fetch_order_book(&mut self, symbol: Value, limit: Value, params: Value) -> Value { Bitbank::fetch_order_book(self, symbol, limit, params).await }
    async fn fetch_ohlcv(&mut self, symbol: Value, timeframe: Value, since: Value, limit: Value, params: Value) -> Value { Bitbank::fetch_ohlcv(self, symbol, timeframe, since, limit, params).await }
    async fn fetch_trades(&mut self, symbol: Value, since: Value, limit: Value, params: Value) -> Value { Bitbank::fetch_trades(self, symbol, since, limit, params).await }
    fn parse_trade(&self, trade: Value, market: Value) -> Value { Bitbank::parse_trade(self, trade, market) }
    fn parse_order(&self, order: Value, market: Value) -> Value { Bitbank::parse_order(self, order, market) }
    fn parse_ticker(&self, ticker: Value, market: Value) -> Value { Bitbank::parse_ticker(self, ticker, market) }
    fn parse_balance(&self, response: Value) -> Value { Bitbank::parse_balance(self, response) }
    fn parse_market(&self, market: Value) -> Value { Bitbank::parse_market(self, market) }
    fn parse_transaction(&self, transaction: Value, currency: Value) -> Value { Bitbank::parse_transaction(self, transaction, currency) }
    fn parse_order_status(&self, status: Value) -> Value { Bitbank::parse_order_status(self, status) }
}
impl Bitbank for BitbankImpl {}
impl ValueTrait for BitbankImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BitbankImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BitbankImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bitbank::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

