#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
use crate::ws::{ArrayCache, ArrayCacheByTimestamp, ArrayCacheBySymbolById, ArrayCacheBySymbolBySide};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors (stub structs with ::new for transpiled `new ErrorType(msg)` patterns)
macro_rules! error_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(msg: Value) -> Value { msg } } }; }
error_stub!(BadRequest);
error_stub!(InvalidOrder);
error_stub!(ExchangeError);
error_stub!(InsufficientFunds);
error_stub!(OrderNotFound);
error_stub!(AuthenticationError);
error_stub!(PermissionDenied);
error_stub!(ExchangeNotAvailable);
error_stub!(ArgumentsRequired);
error_stub!(RateLimitExceeded);
error_stub!(OrderNotFillable);
error_stub!(OrderImmediatelyFillable);
error_stub!(NotSupported);
error_stub!(DuplicateOrderId);
error_stub!(UnsubscribeError);
error_stub!(ChecksumError);
error_stub!(InvalidNonce);
error_stub!(BadSymbol);
// Array-like type stubs (Bids/Asks order book sides)
macro_rules! array_side_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(data: Value, _limit: Value) -> Value { data } } }; }
array_side_stub!(Bids);
array_side_stub!(Asks);

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait(?Send)]
pub trait Bitflyer : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "bitflyer",
            "name": "bitFlyer",
            "countries": [
                "JP"
            ],
            "enableRateLimit": true,
            "rateLimit": 1000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "option": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelOrder": true,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchClosedOrders": "emulated",
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchDeposits": true,
                "fetchFundingRate": true,
                "fetchFundingRateHistory": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchL2OrderBook": true,
                "fetchMarginMode": false,
                "fetchMarkets": true,
                "fetchMyTrades": true,
                "fetchOpenOrders": "emulated",
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": "emulated",
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchPositionMode": false,
                "fetchPositions": true,
                "fetchTicker": true,
                "fetchTrades": true,
                "fetchTradingFee": true,
                "fetchTradingFees": false,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchVolatilityHistory": false,
                "fetchWithdrawals": true,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "transfer": false,
                "withdraw": true,
                "fetchAllGreeks": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/d0217747-e54d-4533-8416-0d553dca74bb",
                "api": {
                    "rest": "https://api.{hostname}"
                },
                "www": "https://bitflyer.com",
                "doc": "https://lightning.bitflyer.com/docs?lang=en"
            },
            "api": {
                "public": {
                    "get": [
                        "getmarkets/usa",
                        "getmarkets/eu",
                        "getmarkets",
                        "getboard",
                        "getticker",
                        "getexecutions",
                        "gethealth",
                        "getboardstate",
                        "getchats",
                        "getfundingrate"
                    ]
                },
                "private": {
                    "get": [
                        "getpermissions",
                        "getbalance",
                        "getbalancehistory",
                        "getcollateral",
                        "getcollateralhistory",
                        "getcollateralaccounts",
                        "getaddresses",
                        "getcoinins",
                        "getcoinouts",
                        "getbankaccounts",
                        "getdeposits",
                        "getwithdrawals",
                        "getchildorders",
                        "getparentorders",
                        "getparentorder",
                        "getexecutions",
                        "getpositions",
                        "gettradingcommission"
                    ],
                    "post": [
                        "sendcoin",
                        "withdraw",
                        "sendchildorder",
                        "cancelchildorder",
                        "sendparentorder",
                        "cancelparentorder",
                        "cancelallchildorders"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "fees": {
                "trading": {
                    "taker": 0.002,
                    "maker": 0.002
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "hostname": "bitflyer.com",
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": true,
                            "GTD": true
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 100,
                        "symbolRequired": true
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchClosedOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    fn parse_expiry_date(&self, mut expiry: Value) -> Value {
        let mut day: Value = expiry.slice(Value::from(0), Value::from(2));
        let mut month_name: Value = expiry.slice(Value::from(2), Value::from(5));
        let mut year: Value = expiry.slice(Value::from(5), Value::from(9));
        let mut months: Value = Value::Json(normalize(&Value::Json(json!({
            "JAN": Value::from("01"),
            "FEB": Value::from("02"),
            "MAR": Value::from("03"),
            "APR": Value::from("04"),
            "MAY": Value::from("05"),
            "JUN": Value::from("06"),
            "JUL": Value::from("07"),
            "AUG": Value::from("08"),
            "SEP": Value::from("09"),
            "OCT": Value::from("10"),
            "NOV": Value::from("11"),
            "DEC": Value::from("12")
        }))).unwrap());
        let mut month: Value = self.safe_string(months.clone(), month_name.clone(), Value::Undefined);
        return self.parse8601(year.clone() + Value::from("-") + month.clone() + Value::from("-") + day.clone() + Value::from("T00:00:00Z"));
    }

    fn safe_market(&self, mut market_id: Value, mut market: Value, mut delimiter: Value, mut market_type: Value) -> Value {
        // Bitflyer has a different type of conflict in markets, because
        // some of their ids (ETH/BTC and BTC/JPY) are duplicated in US, EU and JP.
        // Since they're the same we just need to return one
        return Exchange::safe_market(self, market_id.clone(), market.clone(), delimiter.clone(), Value::from("spot"));
    }

    

    fn parse_balance(&self, mut response: Value) -> Value {
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response.clone()
        }))).unwrap());
        let mut i: usize = 0;
        while i < response.len() {
            let mut balance: Value = response.get(i.into());
            let mut currency_id: Value = self.safe_string(balance.clone(), Value::from("currency_code"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("total".into(), self.safe_string(balance.clone(), Value::from("amount"), Value::Undefined));
            account.set("free".into(), self.safe_string(balance.clone(), Value::from("available"), Value::Undefined));
            result.set(code.clone(), account.clone());
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["account/balance", "balance", "wallet/balance", "accounts/balance", "account"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(&format!("/{}/", token)) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "balance"), ("private", "GET", "account/balance"), ("private", "GET", "wallet/balance")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut ob = crate::exchange::unwrap_response_order_book(&json_resp);
        if let serde_json::Value::Object(ref mut map) = ob {
            if !map.contains_key("symbol") { map.insert("symbol".to_string(), serde_json::json!(symbol.unwrap_str())); }
        }
        Value::Json(ob)
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.parse8601(self.safe_string(ticker.clone(), Value::from("timestamp"), Value::Undefined));
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("ltp"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "high": Value::Undefined,
            "low": Value::Undefined,
            "bid": self.safe_string(ticker.clone(), Value::from("best_bid"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("best_ask"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last.clone(),
            "last": last.clone(),
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("volume_by_product"), Value::Undefined),
            "quoteVolume": Value::Undefined,
            "info": ticker.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        // Some exchanges wrap the ticker in {data: {...}} or {result: {...}} — unwrap if so.
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut tk = json_resp.clone();
        if !tk.is_array() && tk.get("last").is_none() && tk.get("close").is_none() && tk.get("bid").is_none() {
            for key in &["data", "result", "ticker"] {
                if let Some(v) = json_resp.get(key) {
                    if v.is_object() { tk = v.clone(); break; }
                    if let Some(arr) = v.as_array() {
                        if let Some(first) = arr.first() { tk = first.clone(); break; }
                    }
                }
            }
        }
        let market: Value = Value::Undefined;
        let parsed = <Self as Exchange>::parse_ticker(self, Value::Json(tk.clone()), market);
        if parsed.is_undefined() { Value::Json(tk) } else { parsed }
    }


    fn parse_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        // fetchTrades (public) v1
        //
        //      {
        //          "id":2278466664,
        //          "side":"SELL",
        //          "price":56810.7,
        //          "size":0.08798,
        //          "exec_date":"2021-11-19T11:46:39.323",
        //          "buy_child_order_acceptance_id":"JRF20211119-114209-236525",
        //          "sell_child_order_acceptance_id":"JRF20211119-114639-236919"
        //      }
        //
        // fetchMyTrades
        //
        //      {
        //          "id": 37233,
        //          "side": "BUY",
        //          "price": 33470,
        //          "size": 0.01,
        //          "exec_date": "2015-07-07T09:57:40.397",
        //          "child_order_id": "JOR20150707-060559-021935",
        //          "child_order_acceptance_id": "JRF20150707-060559-396699"
        //          "commission": 0,
        //      },
        //
        let mut side: Value = self.safe_string_lower(trade.clone(), Value::from("side"), Value::Undefined);
        if side.clone().is_nonnullish() {
            if side.len() < Value::from(1) {
                side = Value::Undefined;
            };
        };
        let mut order: Value = Value::Undefined;
        if side.clone().is_nonnullish() {
            let mut id_inner: Value = side.clone() + Value::from("_child_order_acceptance_id");
            if trade.contains_key(id_inner.clone()) {
                order = trade.get(id_inner.clone().clone());
            };
        };
        if order.clone().is_nullish() {
            order = self.safe_string(trade.clone(), Value::from("child_order_acceptance_id"), Value::Undefined);
        };
        let mut timestamp: Value = self.parse8601(self.safe_string(trade.clone(), Value::from("exec_date"), Value::Undefined));
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string(trade.clone(), Value::from("size"), Value::Undefined);
        let mut id: Value = self.safe_string(trade.clone(), Value::from("id"), Value::Undefined);
        market = <Self as Bitflyer>::safe_market(self, Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "info": trade.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "order": order.clone(),
            "type": Value::Undefined,
            "side": side.clone(),
            "takerOrMaker": Value::Undefined,
            "price": price_string.clone(),
            "amount": amount_string.clone(),
            "cost": Value::Undefined,
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        let mut raw: Value = Value::Undefined;
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { raw = rv; break; }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            // Already-parsed trades have both `price` and `amount` keys.
            if item.get("price").is_some() && item.get("amount").is_some() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_trade(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    async fn fetch_trading_fee(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "product_code": market.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetGettradingcommission".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //   {
        //       commission_rate: '0.0020'
        //   }
        //
        let mut fee: Value = self.safe_number(response.clone(), Value::from("commission_rate"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": response.clone(),
            "symbol": market.get(Value::from("symbol")),
            "maker": fee.clone(),
            "taker": fee.clone(),
            "percentage": Value::Undefined,
            "tierBased": Value::Undefined
        }))).unwrap());
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("type".into(), r#type.clone());
        request.set("side".into(), side.clone());
        request.set("amount".into(), amount.clone());
        if price.is_nonnullish() { request.set("price".into(), price.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "POST" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "POST", "order"), ("private", "POST", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("orderId".into(), id.clone());
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "DELETE" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "DELETE", "order"), ("private", "DELETE", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "ACTIVE": Value::from("open"),
            "COMPLETED": Value::from("closed"),
            "CANCELED": Value::from("canceled"),
            "EXPIRED": Value::from("canceled"),
            "REJECTED": Value::from("canceled")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order(&self, mut order: Value, mut market: Value) -> Value {
        let mut timestamp: Value = self.parse8601(self.safe_string(order.clone(), Value::from("child_order_date"), Value::Undefined));
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"), Value::Undefined);
        let mut amount: Value = self.safe_string(order.clone(), Value::from("size"), Value::Undefined);
        let mut filled: Value = self.safe_string(order.clone(), Value::from("executed_size"), Value::Undefined);
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("outstanding_size"), Value::Undefined);
        let mut status: Value = <Self as Bitflyer>::parse_order_status(self, self.safe_string(order.clone(), Value::from("child_order_state"), Value::Undefined));
        let mut r#type: Value = self.safe_string_lower(order.clone(), Value::from("child_order_type"), Value::Undefined);
        let mut side: Value = self.safe_string_lower(order.clone(), Value::from("side"), Value::Undefined);
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("product_code"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut fee: Value = Value::Undefined;
        let mut fee_cost: Value = self.safe_number(order.clone(), Value::from("total_commission"), Value::Undefined);
        if fee_cost.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost.clone(),
                "currency": Value::Undefined,
                "rate": Value::Undefined
            }))).unwrap());
        };
        let mut id: Value = self.safe_string(order.clone(), Value::from("child_order_acceptance_id"), Value::Undefined);
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "clientOrderId": Value::Undefined,
            "info": order.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": Value::Undefined,
            "status": status.clone(),
            "symbol": symbol.clone(),
            "type": r#type.clone(),
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "side": side.clone(),
            "price": price.clone(),
            "triggerPrice": Value::Undefined,
            "cost": Value::Undefined,
            "amount": amount.clone(),
            "filled": filled.clone(),
            "remaining": remaining.clone(),
            "fee": fee.clone(),
            "average": Value::Undefined,
            "trades": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["allorders", "all_orders", "orders/history", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "allOrders"), ("private", "GET", "orders"), ("private", "GET", "orders/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["openorders", "open_orders", "orders/open", "orders/active"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "openOrders"), ("private", "GET", "orders/open"), ("private", "GET", "orders/active")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_closed_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["closedorders", "closed_orders", "orders/closed", "orders/history"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "closedOrders"), ("private", "GET", "orders/closed"), ("private", "GET", "orders/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if symbol.clone().is_nullish() {
            return Value::Undefined;
        };
        let mut orders: Value = <Self as Bitflyer>::fetch_orders(self, symbol.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
        let mut orders_by_id: Value = self.index_by(orders.clone(), Value::from("id"));
        if orders_by_id.contains_key(id.clone()) {
            return orders_by_id.get(id.clone().clone());
        };
        return Value::Undefined;
        Value::Undefined
    }

    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["mytrades", "my_trades", "trades/history", "fills", "user/trades", "executions"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "myTrades"), ("private", "GET", "fills"), ("private", "GET", "trades/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_positions(&mut self, mut symbols: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbols.is_nonnullish() { request.set("symbols".into(), symbols.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["positions", "position", "positionrisk", "position_risk"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "positions"), ("private", "GET", "positionRisk"), ("fapi", "GET", "positionRisk")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn withdraw(&mut self, mut code: Value, mut amount: Value, mut address: Value, mut tag: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.check_address(address.clone());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        if code.clone() != Value::from("JPY") && code.clone() != Value::from("USD") && code.clone() != Value::from("EUR") {
            return Value::Undefined;
        };
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency_code": currency.get(Value::from("id")),
            "amount": amount.clone()
        }))).unwrap());
        // 'bank_account_id': 1234,
        let mut response: Value = self.dispatch("privatePostWithdraw".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "message_id": "69476620-5056-4003-bcbe-42658a2b041b"
        //     }
        //
        return <Self as Bitflyer>::parse_transaction(self, response.clone(), currency.clone()).await;
    }

    async fn fetch_deposits(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if code.is_nonnullish() { request.set("coin".into(), code.clone()); request.set("currency".into(), code.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["deposits", "deposit/history", "deposit_history", "capital/deposit/hisrec"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("sapi", "GET", "capital/deposit/hisrec"), ("private", "GET", "deposits"), ("private", "GET", "deposit/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_withdrawals(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if code.is_nonnullish() { request.set("coin".into(), code.clone()); request.set("currency".into(), code.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Bitflyer>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["withdrawals", "withdraw/history", "withdrawal_history", "capital/withdraw/history"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("sapi", "GET", "capital/withdraw/history"), ("private", "GET", "withdrawals"), ("private", "GET", "withdraw/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_deposit_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "PENDING": Value::from("pending"),
            "COMPLETED": Value::from("ok")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_withdrawal_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "PENDING": Value::from("pending"),
            "COMPLETED": Value::from("ok")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_transaction(&self, mut transaction: Value, mut currency: Value) -> Value {
        //
        // fetchDeposits
        //
        //     {
        //         "id": 100,
        //         "order_id": "CDP20151227-024141-055555",
        //         "currency_code": "BTC",
        //         "amount": 0.00002,
        //         "address": "1WriteySQufKZ2pVuM1oMhPrTtTVFq35j",
        //         "tx_hash": "9f92ee65a176bb9545f7becb8706c50d07d4cee5ffca34d8be3ef11d411405ae",
        //         "status": "COMPLETED",
        //         "event_date": "2015-11-27T08:59:20.301"
        //     }
        //
        // fetchWithdrawals
        //
        //     {
        //         "id": 500,
        //         "order_id": "CWD20151224-014040-077777",
        //         "currency_code": "BTC",
        //         "amount": 0.1234,
        //         "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //         "tx_hash": "724c07dfd4044abcb390b0412c3e707dd5c4f373f0a52b3bd295ce32b478c60a",
        //         "fee": 0.0005,
        //         "additional_fee": 0.0001,
        //         "status": "COMPLETED",
        //         "event_date": "2015-12-24T01:40:40.397"
        //     }
        //
        // withdraw
        //
        //     {
        //         "message_id": "69476620-5056-4003-bcbe-42658a2b041b"
        //     }
        //
        let mut id: Value = self.safe_string_2(transaction.clone(), Value::from("id"), Value::from("message_id"), Value::Undefined);
        let mut address: Value = self.safe_string(transaction.clone(), Value::from("address"), Value::Undefined);
        let mut currency_id: Value = self.safe_string(transaction.clone(), Value::from("currency_code"), Value::Undefined);
        let mut code: Value = self.safe_currency_code(currency_id.clone(), currency.clone());
        let mut timestamp: Value = self.parse8601(self.safe_string(transaction.clone(), Value::from("event_date"), Value::Undefined));
        let mut amount: Value = self.safe_number(transaction.clone(), Value::from("amount"), Value::Undefined);
        let mut tx_id: Value = self.safe_string(transaction.clone(), Value::from("tx_hash"), Value::Undefined);
        let mut raw_status: Value = self.safe_string(transaction.clone(), Value::from("status"), Value::Undefined);
        let mut r#type: Value = Value::Undefined;
        let mut status: Value = Value::Undefined;
        let mut fee: Value = Value::Undefined;
        if transaction.contains_key(Value::from("fee")) {
            r#type = Value::from("withdrawal");
            status = <Self as Bitflyer>::parse_withdrawal_status(self, raw_status.clone());
            let mut fee_cost: Value = self.safe_string(transaction.clone(), Value::from("fee"), Value::Undefined);
            let mut additional_fee: Value = self.safe_string(transaction.clone(), Value::from("additional_fee"), Value::Undefined);
            fee = Value::Json(normalize(&Value::Json(json!({
                "currency": code.clone(),
                "cost": self.parse_number(Precise::string_add(fee_cost.clone(), additional_fee.clone()), Value::Undefined)
            }))).unwrap());
        } else {
            r#type = Value::from("deposit");
            status = <Self as Bitflyer>::parse_deposit_status(self, raw_status.clone());
        };
        return Value::Json(normalize(&Value::Json(json!({
            "info": transaction.clone(),
            "id": id.clone(),
            "txid": tx_id.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "network": Value::Undefined,
            "address": address.clone(),
            "addressTo": address.clone(),
            "addressFrom": Value::Undefined,
            "tag": Value::Undefined,
            "tagTo": Value::Undefined,
            "tagFrom": Value::Undefined,
            "type": r#type.clone(),
            "amount": amount.clone(),
            "currency": code.clone(),
            "status": status.clone(),
            "updated": Value::Undefined,
            "comment": Value::Undefined,
            "internal": Value::Undefined,
            "fee": fee.clone()
        }))).unwrap());
    }

    async fn fetch_funding_rate(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "product_code": market.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("publicGetGetfundingrate".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //    {
        //        "current_funding_rate": -0.003750000000
        //        "next_funding_rate_settledate": "2024-04-15T13:00:00"
        //    }
        //
        return <Self as Bitflyer>::parse_funding_rate(self, response.clone(), market.clone()).await;
    }

    fn parse_funding_rate(&self, mut contract: Value, mut market: Value) -> Value {
        //
        //    {
        //        "current_funding_rate": -0.003750000000
        //        "next_funding_rate_settledate": "2024-04-15T13:00:00"
        //    }
        //
        let mut next_funding_datetime: Value = self.safe_string(contract.clone(), Value::from("next_funding_rate_settledate"), Value::Undefined);
        let mut next_funding_timestamp: Value = self.parse8601(next_funding_datetime.clone());
        return Value::Json(normalize(&Value::Json(json!({
            "info": contract.clone(),
            "symbol": self.safe_string(market.clone(), Value::from("symbol"), Value::Undefined),
            "markPrice": Value::Undefined,
            "indexPrice": Value::Undefined,
            "interestRate": Value::Undefined,
            "estimatedSettlePrice": Value::Undefined,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "fundingRate": Value::Undefined,
            "fundingTimestamp": Value::Undefined,
            "fundingDatetime": Value::Undefined,
            "nextFundingRate": self.safe_number(contract.clone(), Value::from("current_funding_rate"), Value::Undefined),
            "nextFundingTimestamp": next_funding_timestamp.clone(),
            "nextFundingDatetime": self.iso8601(next_funding_timestamp.clone()),
            "previousFundingRate": Value::Undefined,
            "previousFundingTimestamp": Value::Undefined,
            "previousFundingDatetime": Value::Undefined,
            "interval": Value::Undefined
        }))).unwrap());
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_str() {
                    "publicGetGetmarketsusa" => self.request("getmarkets/usa".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetmarketseu" => self.request("getmarkets/eu".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetmarkets" => self.request("getmarkets".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetboard" => self.request("getboard".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetticker" => self.request("getticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetexecutions" => self.request("getexecutions".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGethealth" => self.request("gethealth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetboardstate" => self.request("getboardstate".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetchats" => self.request("getchats".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetGetfundingrate" => self.request("getfundingrate".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetpermissions" => self.request("getpermissions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetbalance" => self.request("getbalance".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetbalancehistory" => self.request("getbalancehistory".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetcollateral" => self.request("getcollateral".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetcollateralhistory" => self.request("getcollateralhistory".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetcollateralaccounts" => self.request("getcollateralaccounts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetaddresses" => self.request("getaddresses".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetcoinins" => self.request("getcoinins".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetcoinouts" => self.request("getcoinouts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetbankaccounts" => self.request("getbankaccounts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetdeposits" => self.request("getdeposits".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetwithdrawals" => self.request("getwithdrawals".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetchildorders" => self.request("getchildorders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetparentorders" => self.request("getparentorders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetparentorder" => self.request("getparentorder".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetexecutions" => self.request("getexecutions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGetpositions" => self.request("getpositions".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetGettradingcommission" => self.request("gettradingcommission".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostSendcoin" => self.request("sendcoin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostWithdraw" => self.request("withdraw".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostSendchildorder" => self.request("sendchildorder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCancelchildorder" => self.request("cancelchildorder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostSendparentorder" => self.request("sendparentorder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCancelparentorder" => self.request("cancelparentorder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCancelallchildorders" => self.request("cancelallchildorders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BitflyerImpl(Value);
#[async_trait(?Send)]
impl Exchange for BitflyerImpl {
    fn describe(&self) -> Value { Bitflyer::describe(self) }
    async fn fetch_ticker(&mut self, symbol: Value, params: Value) -> Value { Bitflyer::fetch_ticker(self, symbol, params).await }
    async fn fetch_order_book(&mut self, symbol: Value, limit: Value, params: Value) -> Value { Bitflyer::fetch_order_book(self, symbol, limit, params).await }
    async fn fetch_trades(&mut self, symbol: Value, since: Value, limit: Value, params: Value) -> Value { Bitflyer::fetch_trades(self, symbol, since, limit, params).await }
    fn parse_trade(&self, trade: Value, market: Value) -> Value { Bitflyer::parse_trade(self, trade, market) }
    fn parse_order(&self, order: Value, market: Value) -> Value { Bitflyer::parse_order(self, order, market) }
    fn parse_ticker(&self, ticker: Value, market: Value) -> Value { Bitflyer::parse_ticker(self, ticker, market) }
    fn parse_balance(&self, response: Value) -> Value { Bitflyer::parse_balance(self, response) }
    fn parse_funding_rate(&self, contract: Value, market: Value) -> Value { Bitflyer::parse_funding_rate(self, contract, market) }
    fn parse_transaction(&self, transaction: Value, currency: Value) -> Value { Bitflyer::parse_transaction(self, transaction, currency) }
    fn parse_order_status(&self, status: Value) -> Value { Bitflyer::parse_order_status(self, status) }
}
impl Bitflyer for BitflyerImpl {}
impl ValueTrait for BitflyerImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BitflyerImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BitflyerImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Bitflyer::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

