#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Blockchaincom : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "blockchaincom",
            "name": "Blockchain.com",
            "countries": [
                "LX"
            ],
            "enableRateLimit": true,
            "rateLimit": 500,
            "timeout": 10000,
            "certified": false,
            "pro": true,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "CORS": false,
                "spot": true,
                "swap": false,
                "future": false,
                "option": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createStopLimitOrder": true,
                "createStopMarketOrder": true,
                "createStopOrder": true,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchCanceledOrders": true,
                "fetchClosedOrders": true,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchDeposit": true,
                "fetchDepositAddress": true,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDeposits": true,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingRates": false,
                "fetchIndexOHLCV": false,
                "fetchL2OrderBook": true,
                "fetchL3OrderBook": true,
                "fetchLedger": false,
                "fetchMarginMode": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyTrades": true,
                "fetchOHLCV": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchPositionMode": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchTrades": false,
                "fetchTradingFee": false,
                "fetchTradingFees": true,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchWithdrawal": true,
                "fetchWithdrawals": true,
                "fetchWithdrawalWhitelist": true,
                "transfer": false,
                "withdraw": true
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/975e3054-3399-4363-bcee-ec3c6d63d4e8",
                "api": {
                    "public": "https://api.blockchain.com/v3/exchange",
                    "private": "https://api.blockchain.com/v3/exchange"
                },
                "www": "https://blockchain.com",
                "doc": [
                    "https://api.blockchain.com/v3"
                ],
                "fees": "https://exchange.blockchain.com/fees",
                "test": {
                    "public": "https://testnet-api.delta.exchange",
                    "private": "https://testnet-api.delta.exchange"
                }
            },
            "api": {
                "public": {
                    "get": {
                        "tickers": 1,
                        "tickers/{symbol}": 1,
                        "symbols": 1,
                        "symbols/{symbol}": 1,
                        "l2/{symbol}": 1,
                        "l3/{symbol}": 1
                    }
                },
                "private": {
                    "get": {
                        "fees": 1,
                        "orders": 1,
                        "orders/{orderId}": 1,
                        "trades": 1,
                        "fills": 1,
                        "deposits": 1,
                        "deposits/{depositId}": 1,
                        "accounts": 1,
                        "accounts/{account}/{currency}": 1,
                        "whitelist": 1,
                        "whitelist/{currency}": 1,
                        "withdrawals": 1,
                        "withdrawals/{withdrawalId}": 1
                    },
                    "post": {
                        "orders": 1,
                        "deposits/{currency}": 1,
                        "withdrawals": 1
                    },
                    "delete": {
                        "orders": 1,
                        "orders/{orderId}": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": false,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "fees": {
                "trading": {
                    "tierBased": true,
                    "percentage": true,
                    "feeSide": "get",
                    "tiers": {
                        "taker": [
                            [
                                0,
                                0.0045
                            ],
                            [
                                10000,
                                0.0035
                            ],
                            [
                                50000,
                                0.0018
                            ],
                            [
                                100000,
                                0.0018
                            ],
                            [
                                500000,
                                0.0018
                            ],
                            [
                                1000000,
                                0.0018
                            ],
                            [
                                2500000,
                                0.0018
                            ],
                            [
                                5000000,
                                0.0016
                            ],
                            [
                                25000000,
                                0.0014
                            ],
                            [
                                100000000,
                                0.0011
                            ],
                            [
                                500000000,
                                0.0008
                            ],
                            [
                                1000000000,
                                0.0006
                            ]
                        ],
                        "maker": [
                            [
                                0,
                                0.004
                            ],
                            [
                                10000,
                                0.0017
                            ],
                            [
                                50000,
                                0.0015
                            ],
                            [
                                100000,
                                0.0008
                            ],
                            [
                                500000,
                                0.0007
                            ],
                            [
                                1000000,
                                0.0006
                            ],
                            [
                                2500000,
                                0.0005
                            ],
                            [
                                5000000,
                                0.0004
                            ],
                            [
                                25000000,
                                0.0003
                            ],
                            [
                                100000000,
                                0.0002
                            ],
                            [
                                500000000,
                                0.0001
                            ],
                            [
                                1000000000,
                                0
                            ]
                        ]
                    }
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v3",
            "options": {
                "networks": {
                    "ERC20": "ETH",
                    "TRC20": "TRX",
                    "ALGO": "ALGO",
                    "ADA": "ADA",
                    "AR": "AR",
                    "ATOM": "ATOM",
                    "AVAXC": "AVAX",
                    "BCH": "BCH",
                    "BSV": "BSV",
                    "BTC": "BTC",
                    "DCR": "DCR",
                    "DESO": "DESO",
                    "DASH": "DASH",
                    "CELO": "CELO",
                    "CHZ": "CHZ",
                    "MATIC": "MATIC",
                    "SOL": "SOL",
                    "DOGE": "DOGE",
                    "DOT": "DOT",
                    "EOS": "EOS",
                    "ETC": "ETC",
                    "FIL": "FIL",
                    "KAVA": "KAVA",
                    "LTC": "LTC",
                    "IOTA": "MIOTA",
                    "NEAR": "NEAR",
                    "STX": "STX",
                    "XLM": "XLM",
                    "XMR": "XMR",
                    "XRP": "XRP",
                    "XTZ": "XTZ",
                    "ZEC": "ZEC",
                    "ZIL": "ZIL"
                }
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": false,
                            "GTD": true
                        },
                        "hedged": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "trailing": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "untilDays": 100000,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "symbolRequired": false,
                        "trailing": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchClosedOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "daysBackCanceled": 1,
                        "untilDays": 100000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": false
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Blockchaincom>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_l3_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "symbol": market.get(Value::from("id"))
        }))).unwrap());
        if limit.clone().is_nonnullish() {
            request.set("depth".into(), limit.clone());
        };
        let mut response: Value = self.dispatch("publicGetL3Symbol".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.parse_order_book(response.clone(), market.get(Value::from("symbol")), Value::Undefined, Value::from("bids"), Value::from("asks"), Value::from("px"), Value::from("qty"), Value::Undefined);
    }

    async fn fetch_l2_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        //     {
        //     "symbol": "BTC-USD",
        //     "price_24h": 47791.86,
        //     "volume_24h": 362.88635738,
        //     "last_trade_price": 47587.75
        //     }
        //
        let mut market_id: Value = self.safe_string(ticker.clone(), Value::from("symbol"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::from("-"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("last_trade_price"), Value::Undefined);
        let mut base_volume: Value = self.safe_string(ticker.clone(), Value::from("volume_24h"), Value::Undefined);
        let mut open: Value = self.safe_string(ticker.clone(), Value::from("price_24h"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "high": Value::Undefined,
            "low": Value::Undefined,
            "bid": Value::Undefined,
            "bidVolume": Value::Undefined,
            "ask": Value::Undefined,
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": open,
            "close": Value::Undefined,
            "last": last,
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": Value::Undefined,
            "baseVolume": base_volume,
            "quoteVolume": Value::Undefined,
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Blockchaincom>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Blockchaincom>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["tickers", "ticker/24hr", "ticker", "bookticker"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "tickers"), ("public", "GET", "ticker")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_order_state(&self, mut state: Value) -> Value {
        let mut states: Value = Value::Json(normalize(&Value::Json(json!({
            "OPEN": "open",
            "REJECTED": "rejected",
            "FILLED": "closed",
            "CANCELED": "canceled",
            "PART_FILLED": "open",
            "EXPIRED": "expired"
        }))).unwrap());
        return self.safe_string(states.clone(), state.clone(), state.clone());
    }

    fn parse_order(&mut self, mut order: Value, mut market: Value) -> Value {
        //
        //     {
        //         "clOrdId": "00001",
        //         "ordType": "MARKET",
        //         "ordStatus": "FILLED",
        //         "side": "BUY",
        //         "symbol": "USDC-USDT",
        //         "exOrdId": "281775861306290",
        //         "price": null,
        //         "text": "Fill",
        //         "lastShares": "30.0",
        //         "lastPx": "0.9999",
        //         "leavesQty": "0.0",
        //         "cumQty": "30.0",
        //         "avgPx": "0.9999",
        //         "timestamp": "1633940339619"
        //     }
        //
        let mut client_order_id: Value = self.safe_string(order.clone(), Value::from("clOrdId"), Value::Undefined);
        let mut r#type: Value = self.safe_string_lower(order.clone(), Value::from("ordType"), Value::Undefined);
        let mut status_id: Value = self.safe_string(order.clone(), Value::from("ordStatus"), Value::Undefined);
        let mut state: Value = <Self as Blockchaincom>::parse_order_state(self, status_id.clone());
        let mut side: Value = self.safe_string_lower(order.clone(), Value::from("side"), Value::Undefined);
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("symbol"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::from("-"), Value::Undefined);
        let mut exchange_order_id: Value = self.safe_string(order.clone(), Value::from("exOrdId"), Value::Undefined);
        let mut price: Value = if r#type.clone() != Value::from("market") { self.safe_string(order.clone(), Value::from("price"), Value::Undefined) } else { Value::Undefined };
        let mut average: Value = self.safe_number(order.clone(), Value::from("avgPx"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("timestamp"), Value::Undefined);
        let mut datetime: Value = self.iso8601(timestamp.clone());
        let mut filled: Value = self.safe_string(order.clone(), Value::from("cumQty"), Value::Undefined);
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("leavesQty"), Value::Undefined);
        let mut result: Value = self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": exchange_order_id,
            "clientOrderId": client_order_id,
            "datetime": datetime,
            "timestamp": timestamp,
            "lastTradeTimestamp": Value::Undefined,
            "status": state,
            "symbol": symbol,
            "type": r#type,
            "timeInForce": Value::Undefined,
            "side": side,
            "price": price,
            "average": average,
            "amount": Value::Undefined,
            "filled": filled,
            "remaining": remaining,
            "cost": Value::Undefined,
            "trades": Value::new_array(),
            "fees": Value::new_array(),
            "info": order
        }))).unwrap()), Value::Undefined);
        return result.clone();
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut order_type: Value = self.safe_string(params.clone(), Value::from("ordType"), r#type.clone());
        let mut uppercase_order_type: Value = order_type.to_upper_case();
        let mut client_order_id: Value = self.safe_string_2(params.clone(), Value::from("clientOrderId"), Value::from("clOrdId"), self.uuid16());
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("ordType").into(), Value::from("clientOrderId").into(), Value::from("clOrdId").into()])));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "ordType": uppercase_order_type,
            "symbol": market.get(Value::from("id")),
            "side": side.to_upper_case(),
            "orderQty": self.amount_to_precision(symbol.clone(), amount.clone()),
            "clOrdId": client_order_id
        }))).unwrap());
        // 'stopPx' : limit price
        // 'timeInForce' : "GTC" for Good Till Cancel, "IOC" for Immediate or Cancel, "FOK" for Fill or Kill, "GTD" Good Till Date
        // 'expireDate' : expiry date in the format YYYYMMDD
        // 'minQty' : The minimum quantity required for an IOC fill
        let mut trigger_price: Value = self.safe_value_n(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("triggerPrice").into(), Value::from("stopPx").into(), Value::from("stopPrice").into()])), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("triggerPrice").into(), Value::from("stopPx").into(), Value::from("stopPrice").into()])));
        if uppercase_order_type.clone() == Value::from("STOP") || uppercase_order_type.clone() == Value::from("STOPLIMIT") {
            if trigger_price.clone().is_nullish() {
                panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" createOrder() requires a stopPx or triggerPrice param for a ") + uppercase_order_type.clone() + Value::from(" order"))"###);
            };
        };
        if trigger_price.clone().is_nonnullish() {
            if uppercase_order_type.clone() == Value::from("MARKET") {
                request.set("ordType".into(), Value::from("STOP"));
            } else if uppercase_order_type.clone() == Value::from("LIMIT") {
                request.set("ordType".into(), Value::from("STOPLIMIT"));
            };
        };
        let mut price_required: Value = false.into();
        let mut stop_price_required: Value = false.into();
        if request.get(Value::from("ordType")) == Value::from("LIMIT") || request.get(Value::from("ordType")) == Value::from("STOPLIMIT") {
            price_required = true.into();
        };
        if request.get(Value::from("ordType")) == Value::from("STOP") || request.get(Value::from("ordType")) == Value::from("STOPLIMIT") {
            stop_price_required = true.into();
        };
        if price_required.is_truthy() {
            request.set("price".into(), self.price_to_precision(symbol.clone(), price.clone()));
        };
        if stop_price_required.is_truthy() {
            request.set("stopPx".into(), self.price_to_precision(symbol.clone(), trigger_price.clone()));
        };
        let mut response: Value = self.dispatch("privatePostOrders".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return <Self as Blockchaincom>::parse_order(self, response.clone(), market.clone());
    }

    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "orderId": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privateDeleteOrdersOrderId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "info": response
        }))).unwrap()), Value::Undefined);
    }

    async fn cancel_all_orders(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        // cancels all open orders if no symbol specified
        // cancels all open orders of specified symbol, if symbol is specified
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'symbol': marketId,
        if symbol.clone().is_nonnullish() {
            let mut market_id: Value = self.market_id(symbol.clone());
            request.set("symbol".into(), market_id.clone());
        };
        let mut response: Value = self.dispatch("privateDeleteOrders".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        // {}
        //
        return Value::Json(serde_json::Value::Array(vec![self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap()), Value::Undefined).into()]));
    }

    async fn fetch_trading_fees(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetFees".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "makerRate": "0.002",
        //         "takerRate": "0.004",
        //         "volumeInUSD": "0.0"
        //     }
        //
        let mut maker_fee: Value = self.safe_number(response.clone(), Value::from("makerRate"), Value::Undefined);
        let mut taker_fee: Value = self.safe_number(response.clone(), Value::from("takerRate"), Value::Undefined);
        let mut result: Value = Value::new_object();
        let mut i: usize = 0;
        while i < self.get("symbols".into()).len() {
            let mut symbol: Value = self.get("symbols".into()).get(i.into());
            result.set(symbol.clone(), Value::Json(normalize(&Value::Json(json!({
                "info": response,
                "symbol": symbol,
                "maker": maker_fee,
                "taker": taker_fee
            }))).unwrap()));
            i += 1;
        };
        return result.clone();
    }

    async fn fetch_canceled_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut state: Value = Value::from("CANCELED");
        return <Self as Blockchaincom>::fetch_orders_by_state(self, state.clone(), symbol.clone(), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn fetch_closed_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut state: Value = Value::from("FILLED");
        return <Self as Blockchaincom>::fetch_orders_by_state(self, state.clone(), symbol.clone(), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut state: Value = Value::from("OPEN");
        return <Self as Blockchaincom>::fetch_orders_by_state(self, state.clone(), symbol.clone(), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn fetch_orders_by_state(&mut self, mut state: Value, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "status": state,
            "limit": 100
        }))).unwrap());
        // 'to': unix epoch ms
        // 'from': unix epoch ms
        let mut market: Value = Value::Undefined;
        if symbol.clone().is_nonnullish() {
            market = self.market(symbol.clone());
            request.set("symbol".into(), market.get(Value::from("id")));
        };
        let mut response: Value = self.dispatch("privateGetOrders".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.parse_orders(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    fn parse_trade(&mut self, mut trade: Value, mut market: Value) -> Value {
        //
        //     {
        //         "exOrdId":281685751028507,
        //         "tradeId":281685434947633,
        //         "execId":8847494003,
        //         "side":"BUY",
        //         "symbol":"AAVE-USDT",
        //         "price":405.34,
        //         "qty":0.1,
        //         "fee":0.162136,
        //         "timestamp":1634559249687
        //     }
        //
        let mut order_id: Value = self.safe_string(trade.clone(), Value::from("exOrdId"), Value::Undefined);
        let mut trade_id: Value = self.safe_string(trade.clone(), Value::from("tradeId"), Value::Undefined);
        let mut side: Value = self.safe_string(trade.clone(), Value::from("side"), Value::Undefined).to_lower_case();
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("symbol"), Value::Undefined);
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string(trade.clone(), Value::from("qty"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(trade.clone(), Value::from("timestamp"), Value::Undefined);
        let mut datetime: Value = self.iso8601(timestamp.clone());
        market = self.safe_market(market_id.clone(), market.clone(), Value::from("-"), Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut fee: Value = Value::Undefined;
        let mut fee_cost_string: Value = self.safe_string(trade.clone(), Value::from("fee"), Value::Undefined);
        if fee_cost_string.clone().is_nonnullish() {
            let mut fee_currency: Value = market.get(Value::from("quote"));
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost_string,
                "currency": fee_currency
            }))).unwrap());
        };
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "id": trade_id,
            "timestamp": timestamp,
            "datetime": datetime,
            "symbol": symbol,
            "order": order_id,
            "type": Value::Undefined,
            "side": side,
            "takerOrMaker": Value::Undefined,
            "price": price_string,
            "amount": amount_string,
            "cost": Value::Undefined,
            "fee": fee,
            "info": trade
        }))).unwrap()), market.clone());
    }

    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        if limit.clone().is_nonnullish() {
            request.set("limit".into(), limit.clone());
        };
        let mut market: Value = Value::Undefined;
        if symbol.clone().is_nonnullish() {
            request.set("symbol".into(), self.market_id(symbol.clone()));
            market = self.market(symbol.clone());
        };
        let mut trades: Value = self.dispatch("privateGetFills".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.parse_trades(trades.clone(), market.clone(), since.clone(), limit.clone(), params.clone());
    }

    async fn fetch_deposit_address(&mut self, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": currency.get(Value::from("id"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostDepositsCurrency".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        let mut raw_address: Value = self.safe_string(response.clone(), Value::from("address"), Value::Undefined);
        let mut tag: Value = Value::Undefined;
        let mut address: Value = Value::Undefined;
        if raw_address.clone().is_nonnullish() {
            let mut address_parts: Value = raw_address.split(Value::from(";"));
            // if a tag or memo is used it is separated by a colon in the 'address' value
            tag = self.safe_string(address_parts.clone(), Value::from(0), Value::Undefined);
            address = self.safe_string(address_parts.clone(), Value::from(1), Value::Undefined);
        };
        return Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "currency": currency.get(Value::from("code")),
            "network": Value::Undefined,
            "address": address,
            "tag": tag
        }))).unwrap());
    }

    fn parse_transaction_state(&self, mut state: Value) -> Value {
        let mut states: Value = Value::Json(normalize(&Value::Json(json!({
            "COMPLETED": "ok",
            "REJECTED": "failed",
            "PENDING": "pending",
            "FAILED": "failed",
            "REFUNDED": "refunded"
        }))).unwrap());
        return self.safe_string(states.clone(), state.clone(), state.clone());
    }

    fn parse_transaction(&self, mut transaction: Value, mut currency: Value) -> Value {
        //
        // deposit
        //
        //     {
        //         "depositId":"748e9180-be0d-4a80-e175-0156150efc95",
        //         "amount":0.009,
        //         "currency":"ETH",
        //         "address":"0xEC6B5929D454C8D9546d4221ace969E1810Fa92c",
        //         "state":"COMPLETED",
        //         "txHash":"582114562140e51a80b481c2dfebaf62b4ab9769b8ff54820bb67e34d4a3ab0c",
        //         "timestamp":1633697196241
        //     }
        //
        // withdrawal
        //
        //     {
        //         "amount":30.0,
        //         "currency":"USDT",
        //         "beneficiary":"cab00d11-6e7f-46b7-b453-2e8ef6f101fa", // blockchain specific id
        //         "withdrawalId":"99df5ef7-eab6-4033-be49-312930fbd1ea",
        //         "fee":34.005078,
        //         "state":"COMPLETED",
        //         "timestamp":1634218452549
        //     }
        //
        let mut r#type: Value = Value::Undefined;
        let mut id: Value = Value::Undefined;
        let mut amount: Value = self.safe_number(transaction.clone(), Value::from("amount"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(transaction.clone(), Value::from("timestamp"), Value::Undefined);
        let mut currency_id: Value = self.safe_string(transaction.clone(), Value::from("currency"), Value::Undefined);
        let mut code: Value = self.safe_currency_code(currency_id.clone(), currency.clone());
        let mut state: Value = self.safe_string(transaction.clone(), Value::from("state"), Value::Undefined);
        if transaction.contains_key(Value::from("depositId")) {
            r#type = Value::from("deposit");
            id = self.safe_string(transaction.clone(), Value::from("depositId"), Value::Undefined);
        } else if transaction.contains_key(Value::from("withdrawalId")) {
            r#type = Value::from("withdrawal");
            id = self.safe_string(transaction.clone(), Value::from("withdrawalId"), Value::Undefined);
        };
        let mut fee_cost: Value = if r#type.clone() == Value::from("withdrawal") { self.safe_number(transaction.clone(), Value::from("fee"), Value::Undefined) } else { Value::Undefined };
        let mut fee: Value = Value::Undefined;
        if fee_cost.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "currency": code,
                "cost": fee_cost
            }))).unwrap());
        };
        let mut address: Value = self.safe_string(transaction.clone(), Value::from("address"), Value::Undefined);
        let mut txid: Value = self.safe_string(transaction.clone(), Value::from("txhash"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": transaction,
            "id": id,
            "txid": txid,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "network": Value::Undefined,
            "addressFrom": Value::Undefined,
            "address": address,
            "addressTo": address,
            "tagFrom": Value::Undefined,
            "tag": Value::Undefined,
            "tagTo": Value::Undefined,
            "type": r#type,
            "amount": amount,
            "currency": code,
            "status": <Self as Blockchaincom>::parse_transaction_state(self, state.clone()),
            "updated": Value::Undefined,
            "comment": Value::Undefined,
            "internal": Value::Undefined,
            "fee": fee
        }))).unwrap());
    }

    async fn withdraw(&mut self, mut code: Value, mut amount: Value, mut address: Value, mut tag: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "amount": amount,
            "currency": currency.get(Value::from("id")),
            "beneficiary": address,
            "sendMax": false
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostWithdrawals".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "amount": "30.0",
        //         "currency": "USDT",
        //         "beneficiary": "adcd43fb-9ba6-41f7-8c0d-7013482cb88f",
        //         "withdrawalId": "99df5ef7-eab6-4033-be49-312930fbd1ea",
        //         "fee": "34.005078",
        //         "state": "PENDING",
        //         "timestamp": "1634218452595"
        //     },
        //
        return <Self as Blockchaincom>::parse_transaction(self, response.clone(), currency.clone());
    }

    async fn fetch_withdrawals(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'from' : integer timestamp in ms
        // 'to' : integer timestamp in ms
        if since.clone().is_nonnullish() {
            request.set("from".into(), since.clone());
        };
        let mut currency: Value = Value::Undefined;
        if code.clone().is_nonnullish() {
            currency = self.currency(code.clone());
        };
        let mut response: Value = self.dispatch("privateGetWithdrawals".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.parse_transactions(response.clone(), currency.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn fetch_withdrawal(&mut self, mut id: Value, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "withdrawalId": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetWithdrawalsWithdrawalId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return <Self as Blockchaincom>::parse_transaction(self, response.clone(), Value::Undefined);
    }

    async fn fetch_deposits(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'from' : integer timestamp in ms
        // 'to' : integer timestap in ms
        if since.clone().is_nonnullish() {
            request.set("from".into(), since.clone());
        };
        let mut currency: Value = Value::Undefined;
        if code.clone().is_nonnullish() {
            currency = self.currency(code.clone());
        };
        let mut response: Value = self.dispatch("privateGetDeposits".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.parse_transactions(response.clone(), currency.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn fetch_deposit(&mut self, mut id: Value, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut deposit_id: Value = self.safe_string(params.clone(), Value::from("depositId"), id.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "depositId": deposit_id
        }))).unwrap());
        let mut deposit: Value = self.dispatch("privateGetDepositsDepositId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return <Self as Blockchaincom>::parse_transaction(self, deposit.clone(), Value::Undefined);
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut account_name: Value = self.safe_string(params.clone(), Value::from("account"), Value::from("primary"));
        params = self.omit(params.clone(), Value::from("account"));
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "account": account_name
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetAccounts".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "primary": [
        //             {
        //                 "currency":"ETH",
        //                 "balance":0.009,
        //                 "available":0.009,
        //                 "balance_local":30.82869,
        //                 "available_local":30.82869,
        //                 "rate":3425.41
        //             },
        //             ...
        //         ]
        //     }
        //
        let mut balances: Value = self.safe_value(response.clone(), account_name.clone(), Value::Undefined);
        if balances.clone().is_nullish() {
            panic!(r###"ExchangeError::new(self.get("id".into()) + Value::from(r#" fetchBalance() could not find the ""#) + account_name.clone() + Value::from(r#"" account"#))"###);
        };
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap());
        let mut i: usize = 0;
        while i < balances.len() {
            let mut entry: Value = balances.get(i.into());
            let mut currency_id: Value = self.safe_string(entry.clone(), Value::from("currency"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("free".into(), self.safe_string(entry.clone(), Value::from("available"), Value::Undefined));
            account.set("total".into(), self.safe_string(entry.clone(), Value::from("balance"), Value::Undefined));
            result.set(code.clone(), account.clone());
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        // note: only works with exchange-order-id
        // does not work with clientOrderId
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "orderId": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetOrdersOrderId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "exOrdId": 11111111,
        //         "clOrdId": "ABC",
        //         "ordType": "MARKET",
        //         "ordStatus": "FILLED",
        //         "side": "BUY",
        //         "price": 0.12345,
        //         "text": "string",
        //         "symbol": "BTC-USD",
        //         "lastShares": 0.5678,
        //         "lastPx": 3500.12,
        //         "leavesQty": 10,
        //         "cumQty": 0.123345,
        //         "avgPx": 345.33,
        //         "timestamp": 1592830770594
        //     }
        //
        return <Self as Blockchaincom>::parse_order(self, response.clone(), Value::Undefined);
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetTickers" => self.request("tickers".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickerssymbol" => self.request("tickers/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetSymbols" => self.request("symbols".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetSymbolssymbol" => self.request("symbols/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetL2symbol" => self.request("l2/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetL3symbol" => self.request("l3/{symbol}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetFees" => self.request("fees".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrders" => self.request("orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOrdersorderid" => self.request("orders/{orderId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetTrades" => self.request("trades".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetFills" => self.request("fills".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetDeposits" => self.request("deposits".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetDepositsdepositid" => self.request("deposits/{depositId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccounts" => self.request("accounts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAccountsaccountcurrency" => self.request("accounts/{account}/{currency}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetWhitelist" => self.request("whitelist".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetWhitelistcurrency" => self.request("whitelist/{currency}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetWithdrawals" => self.request("withdrawals".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetWithdrawalswithdrawalid" => self.request("withdrawals/{withdrawalId}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrders" => self.request("orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostDepositscurrency" => self.request("deposits/{currency}".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostWithdrawals" => self.request("withdrawals".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteOrders" => self.request("orders".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteOrdersorderid" => self.request("orders/{orderId}".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BlockchaincomImpl(Value);
impl Exchange for BlockchaincomImpl {}
impl Blockchaincom for BlockchaincomImpl {}
impl ValueTrait for BlockchaincomImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BlockchaincomImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BlockchaincomImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Blockchaincom::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

