#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Btcbox : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "btcbox",
            "name": "BtcBox",
            "countries": [
                "JP"
            ],
            "enableRateLimit": true,
            "rateLimit": 1000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createOrderWithTakeProfitAndStopLossWs": false,
                "createPostOnlyOrder": false,
                "createReduceOnlyOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchTransfer": false,
                "fetchTransfers": false,
                "fetchVolatilityHistory": false,
                "fetchWithdrawal": false,
                "fetchWithdrawals": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": false,
                "withdraw": false,
                "ws": false,
                "repayMargin": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/1e2cb499-8d0f-4f8f-9464-3c015cfbc76b",
                "api": {
                    "rest": "https://www.btcbox.co.jp/api"
                },
                "www": "https://www.btcbox.co.jp/",
                "doc": "https://blog.btcbox.jp/en/archives/8762",
                "fees": "https://support.btcbox.co.jp/hc/en-us/articles/360001235694-Fees-introduction"
            },
            "api": {
                "public": {
                    "get": [
                        "depth",
                        "orders",
                        "ticker",
                        "tickers"
                    ]
                },
                "private": {
                    "post": [
                        "balance",
                        "trade_add",
                        "trade_cancel",
                        "trade_list",
                        "trade_view",
                        "wallet"
                    ]
                },
                "webApi": {
                    "get": [
                        "ajax/coin/coinInfo"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "fees": {
                "trading": {},
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {},
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "options": {
                "fetchMarkets": {
                    "webApiEnable": true,
                    "webApiRetries": 3
                },
                "amountPrecision": "0.0001"
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "trailing": false,
                        "iceberg": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 100,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    

    fn parse_market(&self, mut market: Value) -> Value {
        let mut base_id: Value = self.safe_string(market.clone(), Value::from("base"), Value::Undefined);
        let mut base: Value = self.safe_currency_code(base_id.clone(), Value::Undefined);
        let mut quote_id: Value = self.safe_string(market.clone(), Value::from("quote"), Value::Undefined);
        let mut quote: Value = self.safe_currency_code(quote_id.clone(), Value::Undefined);
        let mut symbol: Value = base.clone() + Value::from("/") + quote.clone();
        return Value::Json(normalize(&Value::Json(json!({
            "id": self.safe_string(market.clone(), Value::from("symbol"), Value::Undefined),
            "uppercaseId": Value::Undefined,
            "symbol": symbol,
            "base": base,
            "baseId": base_id,
            "quote": quote,
            "quoteId": quote_id,
            "settle": Value::Undefined,
            "settleId": Value::Undefined,
            "type": "spot",
            "spot": true,
            "margin": false,
            "swap": false,
            "future": false,
            "option": false,
            "contract": false,
            "linear": Value::Undefined,
            "inverse": Value::Undefined,
            "contractSize": Value::Undefined,
            "expiry": Value::Undefined,
            "expiryDatetime": Value::Undefined,
            "strike": Value::Undefined,
            "optionType": Value::Undefined,
            "limits": Value::Json(normalize(&Value::Json(json!({
                "amount": Value::Json(normalize(&Value::Json(json!({
                    "min": self.safe_number(market.clone(), Value::from("minLimitBaseAmount"), Value::Undefined),
                    "max": self.safe_number(market.clone(), Value::from("maxLimitBaseAmount"), Value::Undefined)
                }))).unwrap()),
                "price": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap()),
                "cost": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap()),
                "leverage": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap())
            }))).unwrap()),
            "precision": Value::Json(normalize(&Value::Json(json!({
                "price": self.parse_number(self.parse_precision(self.safe_string(market.clone(), Value::from("quotePrecision"), Value::Undefined)), Value::Undefined),
                "amount": self.parse_number(self.parse_precision(self.safe_string(market.clone(), Value::from("basePrecision"), Value::Undefined)), Value::Undefined)
            }))).unwrap()),
            "active": Value::Undefined,
            "created": Value::Undefined,
            "info": market
        }))).unwrap());
    }

    fn parse_balance(&self, mut response: Value) -> Value {
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap());
        let mut codes: Value = self.get("currencies".into()).keys();
        let mut i: usize = 0;
        while i < codes.len() {
            let mut code: Value = codes.get(i.into());
            let mut currency: Value = self.currency(code.clone());
            let mut currency_id: Value = currency.get(Value::from("id"));
            let mut free: Value = currency_id.clone() + Value::from("_balance");
            if response.contains_key(free.clone()) {
                let mut account: Value = self.account();
                let mut used: Value = currency_id.clone() + Value::from("_lock");
                account.set("free".into(), self.safe_string(response.clone(), free.clone(), Value::Undefined));
                account.set("used".into(), self.safe_string(response.clone(), used.clone(), Value::Undefined));
                result.set(code.clone(), account.clone());
            };
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privatePostBalance".into(), params.clone(), Value::Undefined).await;
        return <Self as Btcbox>::parse_balance(self, response.clone());
    }

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcbox>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = <Self as Btcbox>::request(self,path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = <Self as Btcbox>::request(self,path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("last"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "high": self.safe_string(ticker.clone(), Value::from("high"), Value::Undefined),
            "low": self.safe_string(ticker.clone(), Value::from("low"), Value::Undefined),
            "bid": self.safe_string(ticker.clone(), Value::from("buy"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("sell"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last,
            "last": last,
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("vol"), Value::Undefined),
            "quoteVolume": self.safe_string(ticker.clone(), Value::from("volume"), Value::Undefined),
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcbox>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = <Self as Btcbox>::request(self,path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")];
        for (api_name, method_name, path_name) in candidates {
            let rv = <Self as Btcbox>::request(self,path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcbox>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["tickers", "ticker/24hr", "ticker", "bookticker"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = <Self as Btcbox>::request(self,path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "tickers"), ("public", "GET", "ticker")];
        for (api_name, method_name, path_name) in candidates {
            let rv = <Self as Btcbox>::request(self,path_name.into(), api_name.into(), method_name.into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_trade(&mut self, mut trade: Value, mut market: Value) -> Value {
        //
        // fetchTrades (public)
        //
        //      {
        //          "date":"0",
        //          "price":3,
        //          "amount":0.1,
        //          "tid":"1",
        //          "type":"buy"
        //      }
        //
        let mut timestamp: Value = self.safe_timestamp(trade.clone(), Value::from("date"), Value::Undefined);
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut id: Value = self.safe_string(trade.clone(), Value::from("tid"), Value::Undefined);
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string(trade.clone(), Value::from("amount"), Value::Undefined);
        let mut r#type: Value = Value::Undefined;
        let mut side: Value = self.safe_string(trade.clone(), Value::from("type"), Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "id": id,
            "order": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "type": r#type,
            "side": side,
            "takerOrMaker": Value::Undefined,
            "price": price_string,
            "amount": amount_string,
            "cost": Value::Undefined,
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        for (api_name, method_name, path_name) in candidates {
            let rv = <Self as Btcbox>::request(self,path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "amount": amount,
            "price": price,
            "type": side,
            "coin": market.get(Value::from("baseId"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostTradeAdd".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "result":true,
        //         "id":"11"
        //     }
        //
        return <Self as Btcbox>::parse_order(self, response.clone(), market.clone());
    }

    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        // a special case for btcbox – default symbol is BTC/JPY
        if symbol.clone().is_nullish() {
            symbol = Value::from("BTC/JPY");
        };
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "coin": market.get(Value::from("baseId"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostTradeCancel".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {"result":true, "id":"11"}
        //
        return <Self as Btcbox>::parse_order(self, response.clone(), market.clone());
    }

    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "part": "open",
            "all": "closed",
            "cancelled": "canceled",
            "closed": "closed",
            "no": "closed"
        }))).unwrap());
        // TODO: complete list
        // not clarified in the docs...
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order(&mut self, mut order: Value, mut market: Value) -> Value {
        //
        //     {
        //         "id":11,
        //         "datetime":"2014-10-21 10:47:20",
        //         "type":"sell",
        //         "price":42000,
        //         "amount_original":1.2,
        //         "amount_outstanding":1.2,
        //         "status":"closed",
        //         "trades":[] // no clarification of trade value structure of order endpoint
        //     }
        //
        let mut id: Value = self.safe_string(order.clone(), Value::from("id"), Value::Undefined);
        let mut datetime_string: Value = self.safe_string(order.clone(), Value::from("datetime"), Value::Undefined);
        let mut timestamp: Value = Value::Undefined;
        if datetime_string.clone().is_nonnullish() {
            timestamp = self.parse8601(order.get(Value::from("datetime")) + Value::from("+09:00"));
        };
        // Tokyo time
        let mut amount: Value = self.safe_string(order.clone(), Value::from("amount_original"), Value::Undefined);
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("amount_outstanding"), Value::Undefined);
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"), Value::Undefined);
        // status is set by fetchOrder method only
        let mut status: Value = <Self as Btcbox>::parse_order_status(self, self.safe_string(order.clone(), Value::from("status"), Value::Undefined));
        // fetchOrders do not return status, use heuristic
        if status.clone().is_nullish() {
            if Precise::string_equals(remaining.clone(), Value::from("0")) {
                status = Value::from("closed");
            };
        };
        let mut trades: Value = Value::Undefined;
        // todo: this.parseTrades (order['trades']);
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut side: Value = self.safe_string(order.clone(), Value::from("type"), Value::Undefined);
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "clientOrderId": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": Value::Undefined,
            "amount": amount,
            "remaining": remaining,
            "filled": Value::Undefined,
            "side": side,
            "type": Value::Undefined,
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "status": status,
            "symbol": market.get(Value::from("symbol")),
            "price": price,
            "triggerPrice": Value::Undefined,
            "cost": Value::Undefined,
            "trades": trades,
            "fee": Value::Undefined,
            "info": order,
            "average": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        // a special case for btcbox – default symbol is BTC/JPY
        if symbol.clone().is_nullish() {
            symbol = Value::from("BTC/JPY");
        };
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = extend_2(Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "coin": market.get(Value::from("baseId"))
        }))).unwrap()), params.clone());
        let mut response: Value = self.dispatch("privatePostTradeView".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //      {
        //          "id":11,
        //          "datetime":"2014-10-21 10:47:20",
        //          "type":"sell",
        //          "price":42000,
        //          "amount_original":1.2,
        //          "amount_outstanding":1.2,
        //          "status":"closed",
        //          "trades":[]
        //      }
        //
        return <Self as Btcbox>::parse_order(self, response.clone(), market.clone());
    }

    async fn fetch_orders_by_type(&mut self, mut r#type: Value, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        // a special case for btcbox – default symbol is BTC/JPY
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": r#type,
            "coin": market.get(Value::from("baseId"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostTradeList".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        // [
        //      {
        //          "id":"7",
        //          "datetime":"2014-10-20 13:27:38",
        //          "type":"buy",
        //          "price":42750,
        //          "amount_original":0.235,
        //          "amount_outstanding":0.235
        //      },
        // ]
        //
        let mut orders: Value = self.parse_orders(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
        // status (open/closed/canceled) is undefined
        // btcbox does not return status, but we know it's 'open' as we queried for open orders
        if r#type.clone() == Value::from("open") {
            let mut i: usize = 0;
            while i < orders.len() {
                orders.get(i.into()).set("status".into(), Value::from("open"));
                i += 1;
            };
        };
        return orders.clone();
    }

    async fn fetch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Btcbox>::fetch_orders_by_type(self, Value::from("all"), symbol.clone(), since.clone(), limit.clone(), params.clone()).await;
    }

    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        return <Self as Btcbox>::fetch_orders_by_type(self, Value::from("open"), symbol.clone(), since.clone(), limit.clone(), params.clone()).await;
    }

    fn nonce(&self) -> Value {
        return self.milliseconds();
    }

    

    

    async fn request(&mut self, mut path: Value, mut api: Value, mut method: Value, mut params: Value, mut headers: Value, mut body: Value, mut config: Value) -> Value {
        fn first_string(v: &serde_json::Value) -> Option<String> {
            match v {
                serde_json::Value::String(s) => Some(s.clone()),
                serde_json::Value::Object(map) => {
                    for (_k, vv) in map {
                        if let Some(found) = first_string(vv) {
                            return Some(found);
                        }
                    }
                    None
                }
                serde_json::Value::Array(arr) => {
                    for vv in arr {
                        if let Some(found) = first_string(vv) {
                            return Some(found);
                        }
                    }
                    None
                }
                _ => None,
            }
        }

        let urls_api = <Self as Btcbox>::describe(self).get("urls".into()).get("api".into());
        let mut base = urls_api.get(api.clone());
        if !base.is_string() {
            base = urls_api.get("public".into());
        }
        if !base.is_string() {
            if let Value::Json(json_api) = urls_api.clone() {
                if let Some(found) = first_string(&json_api) {
                    base = Value::from(found);
                }
            }
        }
        if !base.is_string() {
            base = urls_api.clone();
        }
        if !base.is_string() || !path.is_string() {
            eprintln!(
                "ccxt-rs request skipped: base url missing (api='{}', path='{}')",
                api.unwrap_str(),
                path.unwrap_str()
            );
            return Value::Undefined;
        }
        let mut base_url = base.unwrap_str().to_string();
        let hostname = <Self as Btcbox>::describe(self).get("hostname".into());
        if hostname.is_string() {
            base_url = base_url.replace("{hostname}", hostname.unwrap_str());
        }
        while let Some(start) = base_url.find('{') {
            if let Some(rel_end) = base_url[start..].find('}') {
                let end = start + rel_end;
                let replacement = if hostname.is_string() { hostname.unwrap_str() } else { "" };
                base_url.replace_range(start..=end, replacement);
            } else {
                break;
            }
        }

        let mut url = format!("{}/{}", base_url.trim_end_matches('/'), path.unwrap_str());
        let method_upper = method.unwrap_str().to_uppercase();

        let mut query_pairs: Vec<String> = vec![];
        if let Value::Json(serde_json::Value::Object(map)) = params.clone() {
            for (k, v) in map {
                if v.is_null() { continue; }
                let value_str = match v {
                    serde_json::Value::String(s) => s,
                    serde_json::Value::Number(n) => n.to_string(),
                    serde_json::Value::Bool(b) => if b { "true".into() } else { "false".into() },
                    _ => v.to_string(),
                };
                query_pairs.push(format!("{}={}", urlencoding::encode(&k), urlencoding::encode(&value_str)));
            }
        }

        if method_upper == "GET" && !query_pairs.is_empty() {
            url.push('?');
            url.push_str(&query_pairs.join("&"));
        }

        let client = match reqwest::Client::builder()
            .no_proxy()
            .timeout(std::time::Duration::from_secs(20))
            .user_agent("ccxt-rs-smoke/0.1")
            .build()
        {
            Ok(c) => c,
            Err(err) => {
                eprintln!("ccxt-rs request client build failed for {}: {}", url, err);
                return Value::Undefined;
            }
        };
        let mut req = match method_upper.as_str() {
            "POST" => client.post(&url),
            "PUT" => client.put(&url),
            "DELETE" => client.delete(&url),
            _ => client.get(&url),
        };
        if method_upper != "GET" {
            if let Value::Json(serde_json::Value::Object(map)) = params.clone() {
                let body_text = serde_json::to_string(&map).unwrap_or_else(|_| "{}".to_string());
                req = req.header("content-type", "application/json").body(body_text);
            }
        }

        let response = match req.send().await {
            Ok(r) => r,
            Err(err) => {
                eprintln!("ccxt-rs request send failed for {} {}: {}", method_upper, url, err);
                return Value::Undefined;
            }
        };
        let text = match response.text().await {
            Ok(t) => t,
            Err(err) => {
                eprintln!("ccxt-rs request body read failed for {} {}: {}", method_upper, url, err);
                return Value::Undefined;
            }
        };
        match serde_json::from_str::<serde_json::Value>(&text) {
            Ok(json) => Value::Json(json),
            Err(_) => Value::from(text),
        }
    }


    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetDepth" => <Self as Btcbox>::request(self, "depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetOrders" => <Self as Btcbox>::request(self, "orders".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTicker" => <Self as Btcbox>::request(self, "ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickers" => <Self as Btcbox>::request(self, "tickers".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostBalance" => <Self as Btcbox>::request(self, "balance".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradeadd" => <Self as Btcbox>::request(self, "trade_add".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradecancel" => <Self as Btcbox>::request(self, "trade_cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradelist" => <Self as Btcbox>::request(self, "trade_list".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostTradeview" => <Self as Btcbox>::request(self, "trade_view".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostWallet" => <Self as Btcbox>::request(self, "wallet".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "webapiGetAjaxcoincoininfo" => <Self as Btcbox>::request(self, "ajax/coin/coinInfo".into(), "webApi".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BtcboxImpl(Value);
impl Exchange for BtcboxImpl {}
impl Btcbox for BtcboxImpl {}
impl ValueTrait for BtcboxImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BtcboxImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BtcboxImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Btcbox::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

