#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
use crate::ws::{ArrayCache, ArrayCacheByTimestamp, ArrayCacheBySymbolById, ArrayCacheBySymbolBySide};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors (stub structs with ::new for transpiled `new ErrorType(msg)` patterns)
macro_rules! error_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(msg: Value) -> Value { msg } } }; }
error_stub!(BadRequest);
error_stub!(InvalidOrder);
error_stub!(ExchangeError);
error_stub!(InsufficientFunds);
error_stub!(OrderNotFound);
error_stub!(AuthenticationError);
error_stub!(PermissionDenied);
error_stub!(ExchangeNotAvailable);
error_stub!(ArgumentsRequired);
error_stub!(RateLimitExceeded);
error_stub!(OrderNotFillable);
error_stub!(OrderImmediatelyFillable);
error_stub!(NotSupported);
error_stub!(DuplicateOrderId);
error_stub!(UnsubscribeError);
error_stub!(ChecksumError);
error_stub!(InvalidNonce);
error_stub!(BadSymbol);
// Array-like type stubs (Bids/Asks order book sides)
macro_rules! array_side_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(data: Value, _limit: Value) -> Value { data } } }; }
array_side_stub!(Bids);
array_side_stub!(Asks);

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait(?Send)]
pub trait Btcturk : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "btcturk",
            "name": "BTCTurk",
            "countries": [
                "TR"
            ],
            "enableRateLimit": true,
            "rateLimit": 100,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "CORS": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createDepositAddress": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createOrderWithTakeProfitAndStopLoss": false,
                "createOrderWithTakeProfitAndStopLossWs": false,
                "createPostOnlyOrder": false,
                "createReduceOnlyOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": false,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": true,
                "fetchOHLCV": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "ws": false,
                "repayMargin": false
            },
            "urls": {
                "logo": "https://github.com/user-attachments/assets/10e0a238-9f60-4b06-9dda-edfc7602f1d6",
                "api": {
                    "public": "https://api.btcturk.com/api/v2",
                    "private": "https://api.btcturk.com/api/v1",
                    "graph": "https://graph-api.btcturk.com/v1"
                },
                "www": "https://www.btcturk.com",
                "doc": "https://github.com/BTCTrader/broker-api-docs"
            },
            "api": {
                "public": {
                    "get": {
                        "orderbook": 1,
                        "ticker": 0.1,
                        "trades": 1,
                        "ohlc": 1,
                        "server/exchangeinfo": 1
                    }
                },
                "private": {
                    "get": {
                        "users/balances": 1,
                        "openOrders": 1,
                        "allOrders": 1,
                        "users/transactions/trade": 1
                    },
                    "post": {
                        "users/transactions/crypto": 1,
                        "users/transactions/fiat": 1,
                        "order": 1,
                        "cancelOrder": 1
                    },
                    "delete": {
                        "order": 1
                    }
                },
                "graph": {
                    "get": {
                        "ohlcs": 1,
                        "klines/history": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "1m": 1,
                "15m": 15,
                "30m": 30,
                "1h": 60,
                "4h": 240,
                "1d": "1 d",
                "1w": "1 w",
                "1y": "1 y"
            },
            "fees": {
                "trading": {
                    "taker": 0.0009,
                    "maker": 0.0005
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "leverage": false,
                        "marketBuyRequiresPrice": false,
                        "marketBuyByCost": false,
                        "selfTradePrevention": false,
                        "trailing": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 100,
                        "daysBack": 100000,
                        "untilDays": 30,
                        "symbolRequired": true
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "untilDays": 30,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOHLCV": {}
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    

    fn parse_market(&self, mut entry: Value) -> Value {
        let mut id: Value = self.safe_string(entry.clone(), Value::from("name"), Value::Undefined);
        let mut base_id: Value = self.safe_string(entry.clone(), Value::from("numerator"), Value::Undefined);
        let mut quote_id: Value = self.safe_string(entry.clone(), Value::from("denominator"), Value::Undefined);
        let mut base: Value = self.safe_currency_code(base_id.clone(), Value::Undefined);
        let mut quote: Value = self.safe_currency_code(quote_id.clone(), Value::Undefined);
        let mut filters: Value = self.safe_list(entry.clone(), Value::from("filters"), Value::new_array());
        let mut min_price: Value = Value::Undefined;
        let mut max_price: Value = Value::Undefined;
        let mut min_amount: Value = Value::Undefined;
        let mut max_amount: Value = Value::Undefined;
        let mut min_cost: Value = Value::Undefined;
        let mut j: usize = 0;
        while j < filters.len() {
            let mut filter: Value = filters.get(j.into());
            let mut filter_type: Value = self.safe_string(filter.clone(), Value::from("filterType"), Value::Undefined);
            if filter_type.clone() == Value::from("PRICE_FILTER") {
                min_price = self.safe_number(filter.clone(), Value::from("minPrice"), Value::Undefined);
                max_price = self.safe_number(filter.clone(), Value::from("maxPrice"), Value::Undefined);
                min_amount = self.safe_number(filter.clone(), Value::from("minAmount"), Value::Undefined);
                max_amount = self.safe_number(filter.clone(), Value::from("maxAmount"), Value::Undefined);
                min_cost = self.safe_number(filter.clone(), Value::from("minExchangeValue"), Value::Undefined);
            };
            j += 1;
        };
        let mut status: Value = self.safe_string(entry.clone(), Value::from("status"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "symbol": base.clone() + Value::from("/") + quote.clone(),
            "base": base.clone(),
            "quote": quote.clone(),
            "settle": Value::Undefined,
            "baseId": base_id.clone(),
            "quoteId": quote_id.clone(),
            "settleId": Value::Undefined,
            "type": Value::from("spot"),
            "spot": Value::from(true),
            "margin": Value::from(false),
            "swap": Value::from(false),
            "future": Value::from(false),
            "option": Value::from(false),
            "active": Value::from(status.clone() == Value::from("TRADING")),
            "contract": Value::from(false),
            "linear": Value::Undefined,
            "inverse": Value::Undefined,
            "contractSize": Value::Undefined,
            "expiry": Value::Undefined,
            "expiryDatetime": Value::Undefined,
            "strike": Value::Undefined,
            "optionType": Value::Undefined,
            "precision": Value::Json(normalize(&Value::Json(json!({
                "amount": self.parse_number(self.parse_precision(self.safe_string(entry.clone(), Value::from("numeratorScale"), Value::Undefined)), Value::Undefined),
                "price": self.parse_number(self.parse_precision(self.safe_string(entry.clone(), Value::from("denominatorScale"), Value::Undefined)), Value::Undefined)
            }))).unwrap()),
            "limits": Value::Json(normalize(&Value::Json(json!({
                "leverage": Value::Json(normalize(&Value::Json(json!({
                    "min": Value::Undefined,
                    "max": Value::Undefined
                }))).unwrap()),
                "amount": Value::Json(normalize(&Value::Json(json!({
                    "min": min_amount.clone(),
                    "max": max_amount.clone()
                }))).unwrap()),
                "price": Value::Json(normalize(&Value::Json(json!({
                    "min": min_price.clone(),
                    "max": max_price.clone()
                }))).unwrap()),
                "cost": Value::Json(normalize(&Value::Json(json!({
                    "min": min_cost.clone(),
                    "max": Value::Undefined
                }))).unwrap())
            }))).unwrap()),
            "created": Value::Undefined,
            "info": entry.clone()
        }))).unwrap());
    }

    fn parse_balance(&self, mut response: Value) -> Value {
        let mut data: Value = self.safe_list(response.clone(), Value::from("data"), Value::new_array());
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response.clone(),
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined
        }))).unwrap());
        let mut i: usize = 0;
        while i < data.len() {
            let mut entry: Value = data.get(i.into());
            let mut currency_id: Value = self.safe_string(entry.clone(), Value::from("asset"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("total".into(), self.safe_string(entry.clone(), Value::from("balance"), Value::Undefined));
            account.set("free".into(), self.safe_string(entry.clone(), Value::from("free"), Value::Undefined));
            account.set("used".into(), self.safe_string(entry.clone(), Value::from("locked"), Value::Undefined));
            result.set(code.clone(), account.clone());
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["account/balance", "balance", "wallet/balance", "accounts/balance", "account"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(&format!("/{}/", token)) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "balance"), ("private", "GET", "account/balance"), ("private", "GET", "wallet/balance")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut ob = crate::exchange::unwrap_response_order_book(&json_resp);
        if let serde_json::Value::Object(ref mut map) = ob {
            if !map.contains_key("symbol") { map.insert("symbol".to_string(), serde_json::json!(symbol.unwrap_str())); }
        }
        Value::Json(ob)
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        //   {
        //     "pair": "BTCTRY",
        //     "pairNormalized": "BTC_TRY",
        //     "timestamp": 1618826361234,
        //     "last": 462485,
        //     "high": 473976,
        //     "low": 444201,
        //     "bid": 461928,
        //     "ask": 462485,
        //     "open": 456915,
        //     "volume": 917.41368645,
        //     "average": 462868.29574589,
        //     "daily": 5570,
        //     "dailyPercent": 1.22,
        //     "denominatorSymbol": "TRY",
        //     "numeratorSymbol": "BTC",
        //     "order": 1000
        //   }
        //
        let mut market_id: Value = self.safe_string(ticker.clone(), Value::from("pair"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut symbol: Value = market.get(Value::from("symbol"));
        let mut timestamp: Value = self.safe_integer(ticker.clone(), Value::from("timestamp"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("last"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "high": self.safe_string(ticker.clone(), Value::from("high"), Value::Undefined),
            "low": self.safe_string(ticker.clone(), Value::from("low"), Value::Undefined),
            "bid": self.safe_string(ticker.clone(), Value::from("bid"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("ask"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": self.safe_string(ticker.clone(), Value::from("open"), Value::Undefined),
            "close": last.clone(),
            "last": last.clone(),
            "previousClose": Value::Undefined,
            "change": self.safe_string(ticker.clone(), Value::from("daily"), Value::Undefined),
            "percentage": self.safe_string(ticker.clone(), Value::from("dailyPercent"), Value::Undefined),
            "average": self.safe_string(ticker.clone(), Value::from("average"), Value::Undefined),
            "baseVolume": self.safe_string(ticker.clone(), Value::from("volume"), Value::Undefined),
            "quoteVolume": Value::Undefined,
            "info": ticker.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["tickers", "ticker/24hr", "ticker", "bookticker"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "tickers"), ("public", "GET", "ticker")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        // Some exchanges wrap the ticker in {data: {...}} or {result: {...}} — unwrap if so.
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut tk = json_resp.clone();
        if !tk.is_array() && tk.get("last").is_none() && tk.get("close").is_none() && tk.get("bid").is_none() {
            for key in &["data", "result", "ticker"] {
                if let Some(v) = json_resp.get(key) {
                    if v.is_object() { tk = v.clone(); break; }
                    if let Some(arr) = v.as_array() {
                        if let Some(first) = arr.first() { tk = first.clone(); break; }
                    }
                }
            }
        }
        let market: Value = Value::Undefined;
        let parsed = <Self as Exchange>::parse_ticker(self, Value::Json(tk.clone()), market);
        if parsed.is_undefined() { Value::Json(tk) } else { parsed }
    }


    fn parse_trade(&self, mut trade: Value, mut market: Value) -> Value {
        //
        // fetchTrades
        //     {
        //       "pair": "BTCUSDT",
        //       "pairNormalized": "BTC_USDT",
        //       "numerator": "BTC",
        //       "denominator": "USDT",
        //       "date": "1618916879083",
        //       "tid": "637545136790672520",
        //       "price": "55774",
        //       "amount": "0.27917100",
        //       "side": "buy"
        //     }
        //
        // fetchMyTrades
        //     {
        //       "price": "56000",
        //       "numeratorSymbol": "BTC",
        //       "denominatorSymbol": "USDT",
        //       "orderType": "buy",
        //       "orderId": "2606935102",
        //       "id": "320874372",
        //       "timestamp": "1618916479593",
        //       "amount": "0.00020000",
        //       "fee": "0",
        //       "tax": "0"
        //     }
        //
        let mut timestamp: Value = self.safe_integer_2(trade.clone(), Value::from("date"), Value::from("timestamp"), Value::Undefined);
        let mut id: Value = self.safe_string_2(trade.clone(), Value::from("tid"), Value::from("id"), Value::Undefined);
        let mut order: Value = self.safe_string(trade.clone(), Value::from("orderId"), Value::Undefined);
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = Precise::string_abs(self.safe_string(trade.clone(), Value::from("amount"), Value::Undefined));
        let mut market_id: Value = self.safe_string(trade.clone(), Value::from("pair"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut side: Value = self.safe_string_2(trade.clone(), Value::from("side"), Value::from("orderType"), Value::Undefined);
        let mut fee: Value = Value::Undefined;
        let mut fee_amount_string: Value = self.safe_string(trade.clone(), Value::from("fee"), Value::Undefined);
        if fee_amount_string.clone().is_nonnullish() {
            let mut fee_currency: Value = self.safe_string(trade.clone(), Value::from("denominatorSymbol"), Value::Undefined);
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": Precise::string_abs(fee_amount_string.clone()),
                "currency": self.safe_currency_code(fee_currency.clone(), Value::Undefined)
            }))).unwrap());
        };
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade.clone(),
            "id": id.clone(),
            "order": order.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": symbol.clone(),
            "type": Value::Undefined,
            "side": side.clone(),
            "takerOrMaker": Value::Undefined,
            "price": price_string.clone(),
            "amount": amount_string.clone(),
            "cost": Value::Undefined,
            "fee": fee.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        let mut raw: Value = Value::Undefined;
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { raw = rv; break; }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            // Already-parsed trades have both `price` and `amount` keys.
            if item.get("price").is_some() && item.get("amount").is_some() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_trade(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    fn parse_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        //
        //    {
        //        "timestamp": 1661990400,
        //        "high": 368388.0,
        //        "open": 368388.0,
        //        "low": 368388.0,
        //        "close": 368388.0,
        //        "volume": 0.00035208,
        //    }
        //
        return Value::Json(serde_json::Value::Array(vec![(self.safe_timestamp(ohlcv.clone(), Value::from("timestamp"), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from("open"), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from("high"), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from("low"), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from("close"), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from("volume"), Value::Undefined)).into()]));
    }

    async fn fetch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("timeframe".into(), timeframe.clone());
        request.set("interval".into(), timeframe.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        // Match endpoints by substring on common OHLCV path tokens (klines, candles,
        // ohlcv, barhist, history, kline, candle, ohlc).
        'outer: for token in ["klines", "candles", "ohlcv", "barhist", "kline", "candle", "ohlc"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "klines"), ("public", "GET", "candles"), ("public", "GET", "ohlcv")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            if item.is_array() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_ohlcv(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    fn parse_ohlcvs(&self, mut ohlcvs: Value, mut market: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut tail: Value) -> Value {
        timeframe = timeframe.or_default(Value::from("1m"));
        tail = tail.or_default(Value::from(false));
        let mut results: Value = Value::new_array();
        let mut timestamp: Value = self.safe_list(ohlcvs.clone(), Value::from("t"), Value::new_array());
        let mut high: Value = self.safe_list(ohlcvs.clone(), Value::from("h"), Value::new_array());
        let mut open: Value = self.safe_list(ohlcvs.clone(), Value::from("o"), Value::new_array());
        let mut low: Value = self.safe_list(ohlcvs.clone(), Value::from("l"), Value::new_array());
        let mut close: Value = self.safe_list(ohlcvs.clone(), Value::from("c"), Value::new_array());
        let mut volume: Value = self.safe_list(ohlcvs.clone(), Value::from("v"), Value::new_array());
        let mut i: usize = 0;
        while i < timestamp.len() {
            let mut ohlcv: Value = Value::Json(normalize(&Value::Json(json!({
                "timestamp": self.safe_integer(timestamp.clone(), Value::from(i), Value::Undefined),
                "high": self.safe_number(high.clone(), Value::from(i), Value::Undefined),
                "open": self.safe_number(open.clone(), Value::from(i), Value::Undefined),
                "low": self.safe_number(low.clone(), Value::from(i), Value::Undefined),
                "close": self.safe_number(close.clone(), Value::from(i), Value::Undefined),
                "volume": self.safe_number(volume.clone(), Value::from(i), Value::Undefined)
            }))).unwrap());
            results.push(<Self as Btcturk>::parse_ohlcv(self, ohlcv.clone(), market.clone()));
            i += 1;
        };
        let mut sorted: Value = self.sort_by(results.clone(), Value::from(0), Value::Undefined, Value::Undefined);
        return self.filter_by_since_limit(sorted.clone(), since.clone(), limit.clone(), Value::from(0), tail.clone());
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("type".into(), r#type.clone());
        request.set("side".into(), side.clone());
        request.set("amount".into(), amount.clone());
        if price.is_nonnullish() { request.set("price".into(), price.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "POST" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "POST", "order"), ("private", "POST", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("orderId".into(), id.clone());
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "DELETE" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "DELETE", "order"), ("private", "DELETE", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["openorders", "open_orders", "orders/open", "orders/active"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "openOrders"), ("private", "GET", "orders/open"), ("private", "GET", "orders/active")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["allorders", "all_orders", "orders/history", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "allOrders"), ("private", "GET", "orders"), ("private", "GET", "orders/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "Untouched": Value::from("open"),
            "Partial": Value::from("open"),
            "Canceled": Value::from("canceled"),
            "Closed": Value::from("closed")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order(&self, mut order: Value, mut market: Value) -> Value {
        //
        // fetchOrders / fetchOpenOrders
        //     {
        //       "id": 2605984008,
        //       "price": "55000",
        //       "amount": "0.00050000",
        //       "quantity": "0.00050000",
        //       "stopPrice": "0",
        //       "pairSymbol": "BTCUSDT",
        //       "pairSymbolNormalized": "BTC_USDT",
        //       "type": "buy",
        //       "method": "limit",
        //       "orderClientId": "f479bdb6-0965-4f03-95b5-daeb7aa5a3a5",
        //       "time": 0,
        //       "updateTime": 1618913083543,
        //       "status": "Untouched",
        //       "leftAmount": "0.00050000"
        //     }
        //
        // createOrder
        //     {
        //       "id": "2606935102",
        //       "quantity": "0.0002",
        //       "price": "56000",
        //       "stopPrice": null,
        //       "newOrderClientId": "98e5c491-7ed9-462b-9666-93553180fb28",
        //       "type": "buy",
        //       "method": "limit",
        //       "pairSymbol": "BTCUSDT",
        //       "pairSymbolNormalized": "BTC_USDT",
        //       "datetime": "1618916479523"
        //     }
        //
        let mut id: Value = self.safe_string(order.clone(), Value::from("id"), Value::Undefined);
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string_2(order.clone(), Value::from("amount"), Value::from("quantity"), Value::Undefined);
        let mut amount: Value = Precise::string_abs(amount_string.clone());
        let mut remaining: Value = self.safe_string(order.clone(), Value::from("leftAmount"), Value::Undefined);
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("pairSymbol"), Value::Undefined);
        let mut symbol: Value = self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut side: Value = self.safe_string(order.clone(), Value::from("type"), Value::Undefined);
        let mut r#type: Value = self.safe_string(order.clone(), Value::from("method"), Value::Undefined);
        let mut client_order_id: Value = self.safe_string(order.clone(), Value::from("orderClientId"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer_2(order.clone(), Value::from("updateTime"), Value::from("datetime"), Value::Undefined);
        let mut raw_status: Value = self.safe_string(order.clone(), Value::from("status"), Value::Undefined);
        let mut status: Value = <Self as Btcturk>::parse_order_status(self, raw_status.clone());
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": order.clone(),
            "id": id.clone(),
            "price": price.clone(),
            "amount": amount.clone(),
            "remaining": remaining.clone(),
            "filled": Value::Undefined,
            "cost": Value::Undefined,
            "average": Value::Undefined,
            "status": status.clone(),
            "side": side.clone(),
            "type": r#type.clone(),
            "clientOrderId": client_order_id.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": symbol.clone(),
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Btcturk>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["mytrades", "my_trades", "trades/history", "fills", "user/trades", "executions"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "myTrades"), ("private", "GET", "fills"), ("private", "GET", "trades/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn nonce(&self) -> Value {
        return self.milliseconds();
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_str() {
                    "publicGetOrderbook" => self.request("orderbook".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTicker" => self.request("ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTrades" => self.request("trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetOhlc" => self.request("ohlc".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetServerexchangeinfo" => self.request("server/exchangeinfo".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUsersbalances" => self.request("users/balances".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetOpenorders" => self.request("openOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAllorders" => self.request("allOrders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserstransactionstrade" => self.request("users/transactions/trade".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserstransactionscrypto" => self.request("users/transactions/crypto".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserstransactionsfiat" => self.request("users/transactions/fiat".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostOrder" => self.request("order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCancelorder" => self.request("cancelOrder".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteOrder" => self.request("order".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "graphGetOhlcs" => self.request("ohlcs".into(), "graph".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "graphGetKlineshistory" => self.request("klines/history".into(), "graph".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BtcturkImpl(Value);
#[async_trait(?Send)]
impl Exchange for BtcturkImpl {
    fn describe(&self) -> Value { Btcturk::describe(self) }
    async fn fetch_ticker(&mut self, symbol: Value, params: Value) -> Value { Btcturk::fetch_ticker(self, symbol, params).await }
    async fn fetch_tickers(&mut self, symbols: Value, params: Value) -> Value { Btcturk::fetch_tickers(self, symbols, params).await }
    async fn fetch_order_book(&mut self, symbol: Value, limit: Value, params: Value) -> Value { Btcturk::fetch_order_book(self, symbol, limit, params).await }
    async fn fetch_ohlcv(&mut self, symbol: Value, timeframe: Value, since: Value, limit: Value, params: Value) -> Value { Btcturk::fetch_ohlcv(self, symbol, timeframe, since, limit, params).await }
    async fn fetch_trades(&mut self, symbol: Value, since: Value, limit: Value, params: Value) -> Value { Btcturk::fetch_trades(self, symbol, since, limit, params).await }
    fn parse_trade(&self, trade: Value, market: Value) -> Value { Btcturk::parse_trade(self, trade, market) }
    fn parse_order(&self, order: Value, market: Value) -> Value { Btcturk::parse_order(self, order, market) }
    fn parse_ticker(&self, ticker: Value, market: Value) -> Value { Btcturk::parse_ticker(self, ticker, market) }
    fn parse_balance(&self, response: Value) -> Value { Btcturk::parse_balance(self, response) }
    fn parse_market(&self, market: Value) -> Value { Btcturk::parse_market(self, market) }
    fn parse_order_status(&self, status: Value) -> Value { Btcturk::parse_order_status(self, status) }
}
impl Btcturk for BtcturkImpl {}
impl ValueTrait for BtcturkImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl BtcturkImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = BtcturkImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Btcturk::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

