#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Latoken : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "latoken",
            "name": "Latoken",
            "countries": [
                "KY"
            ],
            "enableRateLimit": true,
            "rateLimit": 1000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelAllOrders": true,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createPostOnlyOrder": false,
                "createStopLimitOrder": true,
                "createStopMarketOrder": false,
                "createStopOrder": true,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": true,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": false,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchDepositsWithdrawals": true,
                "fetchDepositWithdrawFees": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchTickers": true,
                "fetchMarkPrices": false,
                "fetchTime": true,
                "fetchTrades": true,
                "fetchTradingFee": true,
                "fetchTradingFees": false,
                "fetchTransactions": "emulated",
                "fetchTransfer": false,
                "fetchTransfers": true,
                "fetchUnderlyingAssets": false,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "transfer": true,
                "fetchAllGreeks": false,
                "fetchMarkPrice": false
            },
            "urls": {
                "logo": "https://user-images.githubusercontent.com/1294454/61511972-24c39f00-aa01-11e9-9f7c-471f1d6e5214.jpg",
                "api": {
                    "rest": "https://api.latoken.com"
                },
                "www": "https://latoken.com",
                "doc": [
                    "https://api.latoken.com"
                ],
                "fees": "https://latoken.com/fees",
                "referral": "https://latoken.com/invite?r=mvgp2djk"
            },
            "api": {
                "public": {
                    "get": {
                        "book/{currency}/{quote}": 1,
                        "chart/week": 1,
                        "chart/week/{currency}/{quote}": 1,
                        "currency": 1,
                        "currency/available": 1,
                        "currency/quotes": 1,
                        "currency/{currency}": 1,
                        "pair": 1,
                        "pair/available": 1,
                        "ticker": 1,
                        "ticker/{base}/{quote}": 1,
                        "time": 1,
                        "trade/history/{currency}/{quote}": 1,
                        "trade/fee/{currency}/{quote}": 1,
                        "trade/feeLevels": 1,
                        "transaction/bindings": 1
                    }
                },
                "private": {
                    "get": {
                        "auth/account": 1,
                        "auth/account/currency/{currency}/{type}": 1,
                        "auth/order": 1,
                        "auth/order/getOrder/{id}": 1,
                        "auth/order/pair/{currency}/{quote}": 1,
                        "auth/order/pair/{currency}/{quote}/active": 1,
                        "auth/stopOrder": 1,
                        "auth/stopOrder/getOrder/{id}": 1,
                        "auth/stopOrder/pair/{currency}/{quote}": 1,
                        "auth/stopOrder/pair/{currency}/{quote}/active": 1,
                        "auth/trade": 1,
                        "auth/trade/pair/{currency}/{quote}": 1,
                        "auth/trade/fee/{currency}/{quote}": 1,
                        "auth/transaction": 1,
                        "auth/transaction/bindings": 1,
                        "auth/transaction/bindings/{currency}": 1,
                        "auth/transaction/{id}": 1,
                        "auth/transfer": 1
                    },
                    "post": {
                        "auth/order/cancel": 1,
                        "auth/order/cancelAll": 1,
                        "auth/order/cancelAll/{currency}/{quote}": 1,
                        "auth/order/place": 1,
                        "auth/spot/deposit": 1,
                        "auth/spot/withdraw": 1,
                        "auth/stopOrder/cancel": 1,
                        "auth/stopOrder/cancelAll": 1,
                        "auth/stopOrder/cancelAll/{currency}/{quote}": 1,
                        "auth/stopOrder/place": 1,
                        "auth/transaction/depositAddress": 1,
                        "auth/transaction/withdraw": 1,
                        "auth/transaction/withdraw/cancel": 1,
                        "auth/transaction/withdraw/confirm": 1,
                        "auth/transaction/withdraw/resendCode": 1,
                        "auth/transfer/email": 1,
                        "auth/transfer/id": 1,
                        "auth/transfer/phone": 1
                    }
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "fees": {
                "trading": {
                    "tierBased": false,
                    "percentage": true,
                    "taker": 0.0049,
                    "maker": 0.0049,
                    "feeSide": "get"
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "exceptions": {
                "exact": {},
                "broad": {}
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV",
                "BUX": "Buxcoin",
                "CBT": "Community Business Token",
                "CTC": "CyberTronchain",
                "DMD": "Diamond Coin",
                "FREN": "Frenchie",
                "GDX": "GoldenX",
                "GEC": "Geco One",
                "GEM": "NFTmall",
                "GMT": "GMT Token",
                "IMC": "IMCoin",
                "MT": "Monarch",
                "TPAY": "Tetra Pay",
                "TRADE": "Smart Trade Coin",
                "TSL": "Treasure SL",
                "UNO": "Unobtanium",
                "WAR": "Warrior Token"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v2",
            "options": {
                "defaultType": "spot",
                "types": {
                    "wallet": "ACCOUNT_TYPE_WALLET",
                    "funding": "ACCOUNT_TYPE_WALLET",
                    "spot": "ACCOUNT_TYPE_SPOT"
                },
                "accounts": {
                    "ACCOUNT_TYPE_WALLET": "wallet",
                    "ACCOUNT_TYPE_SPOT": "spot"
                },
                "fetchTradingFee": {
                    "method": "fetchPrivateTradingFee"
                },
                "timeDifference": 0,
                "adjustForTimeDifference": true
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": true,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": true,
                            "FOK": true,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "selfTradePrevention": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "symbolRequired": false
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": true,
                        "trailing": false,
                        "symbolRequired": false
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchClosedOrders": {
                        "marginMode": false,
                        "limit": 1000,
                        "daysBack": 100000,
                        "daysBackCanceled": 1,
                        "trigger": true,
                        "trailing": false,
                        "symbolRequired": false
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    fn nonce(&self) -> Value {
        return self.milliseconds() - self.get("options".into()).get(Value::from("timeDifference"));
    }

    async fn fetch_time(&mut self, mut params: Value) -> Value {
        let candidates = vec![("public", "GET", "time"), ("public", "GET", "server/time"), ("public", "GET", "timestamp")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    

    async fn fetch_currencies(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut response: Value = self.dispatch("publicGetCurrency".into(), params.clone(), Value::Undefined).await;
        //
        //     [
        //         {
        //             "id":"1a075819-9e0b-48fc-8784-4dab1d186d6d",
        //             "status":"CURRENCY_STATUS_ACTIVE",
        //             "type":"CURRENCY_TYPE_ALTERNATIVE", // CURRENCY_TYPE_CRYPTO, CURRENCY_TYPE_IEO
        //             "name":"MyCryptoBank",
        //             "tag":"MCB",
        //             "description":"",
        //             "logo":"",
        //             "decimals":18,
        //             "created":1572912000000,
        //             "tier":1,
        //             "assetClass":"ASSET_CLASS_UNKNOWN",
        //             "minTransferAmount":0
        //         },
        //         {
        //             "id":"db02758e-2507-46a5-a805-7bc60355b3eb",
        //             "status":"CURRENCY_STATUS_ACTIVE",
        //             "type":"CURRENCY_TYPE_FUTURES_CONTRACT",
        //             "name":"BTC USDT Futures Contract",
        //             "tag":"BTCUSDT",
        //             "description":"",
        //             "logo":"",
        //             "decimals":8,
        //             "created":1589459984395,
        //             "tier":1,
        //             "assetClass":"ASSET_CLASS_UNKNOWN",
        //             "minTransferAmount":0
        //         },
        //     ]
        //
        let mut result: Value = Value::new_object();
        let mut i: usize = 0;
        while i < response.len() {
            let mut currency: Value = response.get(i.into());
            let mut id: Value = self.safe_string(currency.clone(), Value::from("id"), Value::Undefined);
            let mut tag: Value = self.safe_string(currency.clone(), Value::from("tag"), Value::Undefined);
            let mut code: Value = self.safe_currency_code(tag.clone(), Value::Undefined);
            let mut currency_type: Value = self.safe_string(currency.clone(), Value::from("type"), Value::Undefined);
            let mut is_crypto: Value = (currency_type.clone() == Value::from("CURRENCY_TYPE_CRYPTO") || currency_type.clone() == Value::from("CURRENCY_TYPE_IEO")).into();
            result.set(code.clone(), self.safe_currency_structure(Value::Json(normalize(&Value::Json(json!({
                "id": id,
                "code": code,
                "info": currency,
                "name": self.safe_string(currency.clone(), Value::from("name"), Value::Undefined),
                "type": if is_crypto.is_truthy() { Value::from("crypto") } else { Value::from("other") },
                "active": self.safe_string(currency.clone(), Value::from("status"), Value::Undefined) == Value::from("CURRENCY_STATUS_ACTIVE"),
                "deposit": Value::Undefined,
                "withdraw": Value::Undefined,
                "fee": self.safe_number(currency.clone(), Value::from("fee"), Value::Undefined),
                "precision": self.parse_number(self.parse_precision(self.safe_string(currency.clone(), Value::from("decimals"), Value::Undefined)), Value::Undefined),
                "limits": Value::Json(normalize(&Value::Json(json!({
                    "amount": Value::Json(normalize(&Value::Json(json!({
                        "min": self.safe_number(currency.clone(), Value::from("minTransferAmount"), Value::Undefined),
                        "max": Value::Undefined
                    }))).unwrap()),
                    "withdraw": Value::Json(normalize(&Value::Json(json!({
                        "min": Value::Undefined,
                        "max": Value::Undefined
                    }))).unwrap())
                }))).unwrap()),
                "networks": Value::new_object()
            }))).unwrap())));
            i += 1;
        };
        return result.clone();
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetAuthAccount".into(), params.clone(), Value::Undefined).await;
        //
        //     [
        //         {
        //             "id": "e5852e02-8711-431c-9749-a6f5503c6dbe",
        //             "status": "ACCOUNT_STATUS_ACTIVE",
        //             "type": "ACCOUNT_TYPE_WALLET",
        //             "timestamp": "1635920106506",
        //             "currency": "0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "available": "100.000000",
        //             "blocked": "0.000000"
        //         },
        //         {
        //             "id": "369df204-acbc-467e-a25e-b16e3cc09cf6",
        //             "status": "ACCOUNT_STATUS_ACTIVE",
        //             "type": "ACCOUNT_TYPE_SPOT",
        //             "timestamp": "1635920106504",
        //             "currency": "0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "available": "100.000000",
        //             "blocked": "0.000000"
        //         }
        //     ]
        //
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined
        }))).unwrap());
        let mut max_timestamp: Value = Value::Undefined;
        let mut default_type: Value = self.safe_string_2(self.get("options".into()), Value::from("fetchBalance"), Value::from("defaultType"), Value::from("spot"));
        let mut r#type: Value = self.safe_string(params.clone(), Value::from("type"), default_type.clone());
        let mut types: Value = self.safe_value(self.get("options".into()), Value::from("types"), Value::new_object());
        let mut account_type: Value = self.safe_string(types.clone(), r#type.clone(), r#type.clone());
        let mut balances_by_type: Value = self.group_by(response.clone(), Value::from("type"));
        let mut balances: Value = self.safe_value(balances_by_type.clone(), account_type.clone(), Value::new_array());
        let mut i: usize = 0;
        while i < balances.len() {
            let mut balance: Value = balances.get(i.into());
            let mut currency_id: Value = self.safe_string(balance.clone(), Value::from("currency"), Value::Undefined);
            let mut timestamp: Value = self.safe_integer(balance.clone(), Value::from("timestamp"), Value::Undefined);
            if timestamp.clone().is_nonnullish() {
                if max_timestamp.clone().is_nullish() {
                    max_timestamp = timestamp.clone();
                } else {
                    max_timestamp = Math::max(max_timestamp.clone(), timestamp.clone());
                };
            };
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            let mut account: Value = self.account();
            account.set("free".into(), self.safe_string(balance.clone(), Value::from("available"), Value::Undefined));
            account.set("used".into(), self.safe_string(balance.clone(), Value::from("blocked"), Value::Undefined));
            result.set(code.clone(), account.clone());
            i += 1;
        };
        result.set("timestamp".into(), max_timestamp.clone());
        result.set("datetime".into(), self.iso8601(max_timestamp.clone()));
        return self.safe_balance(result.clone());
    }

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Latoken>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        //    {
        //        "symbol": "92151d82-df98-4d88-9a4d-284fa9eca49f/0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //        "baseCurrency": "92151d82-df98-4d88-9a4d-284fa9eca49f",
        //        "quoteCurrency": "0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //        "volume24h": "165723597.189022176000000000",
        //        "volume7d": "934505768.625109571000000000",
        //        "change24h": "0.0200",
        //        "change7d": "-6.4200",
        //        "amount24h": "6438.457663100000000000",
        //        "amount7d": "35657.785013800000000000",
        //        "lastPrice": "25779.16",
        //        "lastQuantity": "0.248403300000000000",
        //        "bestBid": "25778.74",
        //        "bestBidQuantity": "0.6520232",
        //        "bestAsk": "25779.17",
        //        "bestAskQuantity": "0.4956043",
        //        "updateTimestamp": "1693965231406"
        //    }
        //
        let mut market_id: Value = self.safe_string(ticker.clone(), Value::from("symbol"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("lastPrice"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer_omit_zero(ticker.clone(), Value::from("updateTimestamp"), Value::Undefined);
        // sometimes latoken provided '0' ts from /ticker endpoint
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": self.safe_symbol(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined),
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "low": Value::Undefined,
            "high": Value::Undefined,
            "bid": self.safe_string(ticker.clone(), Value::from("bestBid"), Value::Undefined),
            "bidVolume": self.safe_string(ticker.clone(), Value::from("bestBidQuantity"), Value::Undefined),
            "ask": self.safe_string(ticker.clone(), Value::from("bestAsk"), Value::Undefined),
            "askVolume": self.safe_string(ticker.clone(), Value::from("bestAskQuantity"), Value::Undefined),
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last,
            "last": last,
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": self.safe_string(ticker.clone(), Value::from("change24h"), Value::Undefined),
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("amount24h"), Value::Undefined),
            "quoteVolume": self.safe_string(ticker.clone(), Value::from("volume24h"), Value::Undefined),
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Latoken>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_tickers(&mut self, mut symbols: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Latoken>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["tickers", "ticker/24hr", "ticker", "bookticker"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "tickers"), ("public", "GET", "ticker")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), params.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_trade(&mut self, mut trade: Value, mut market: Value) -> Value {
        //
        // fetchTrades (public)
        //
        //     {
        //         "id":"c152f814-8eeb-44f0-8f3f-e5c568f2ffcf",
        //         "isMakerBuyer":false,
        //         "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //         "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //         "price":"4435.56",
        //         "quantity":"0.32534",
        //         "cost":"1443.0650904",
        //         "timestamp":1635854642725,
        //         "makerBuyer":false
        //     }
        //
        // fetchMyTrades (private)
        //
        //     {
        //         "id":"02e02533-b4bf-4ba9-9271-24e2108dfbf7",
        //         "isMakerBuyer":false,
        //         "direction":"TRADE_DIRECTION_BUY",
        //         "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //         "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //         "price":"4564.32",
        //         "quantity":"0.01000",
        //         "cost":"45.6432",
        //         "fee":"0.223651680000000000",
        //         "order":"c9cac6a0-484c-4892-88e7-ad51b39f2ce1",
        //         "timestamp":1635921580399,
        //         "makerBuyer":false
        //     }
        //
        let mut r#type: Value = Value::Undefined;
        let mut timestamp: Value = self.safe_integer(trade.clone(), Value::from("timestamp"), Value::Undefined);
        let mut price_string: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_string: Value = self.safe_string(trade.clone(), Value::from("quantity"), Value::Undefined);
        let mut cost_string: Value = self.safe_string(trade.clone(), Value::from("cost"), Value::Undefined);
        let mut maker_buyer: Value = self.safe_value(trade.clone(), Value::from("makerBuyer"), Value::Undefined);
        let mut side: Value = self.safe_string(trade.clone(), Value::from("direction"), Value::Undefined);
        if side.clone().is_nullish() {
            side = if maker_buyer.is_truthy() { Value::from("sell") } else { Value::from("buy") };
        } else {
            if side.clone() == Value::from("TRADE_DIRECTION_BUY") {
                side = Value::from("buy");
            } else if side.clone() == Value::from("TRADE_DIRECTION_SELL") {
                side = Value::from("sell");
            };
        };
        let mut is_buy: Value = (side.clone() == Value::from("buy")).into();
        let mut taker_or_maker: Value = if maker_buyer.is_truthy() && is_buy.is_truthy() { Value::from("maker") } else { Value::from("taker") };
        let mut base_id: Value = self.safe_string(trade.clone(), Value::from("baseCurrency"), Value::Undefined);
        let mut quote_id: Value = self.safe_string(trade.clone(), Value::from("quoteCurrency"), Value::Undefined);
        let mut base: Value = self.safe_currency_code(base_id.clone(), Value::Undefined);
        let mut quote: Value = self.safe_currency_code(quote_id.clone(), Value::Undefined);
        let mut symbol: Value = base.clone() + Value::from("/") + quote.clone();
        if self.get("markets".into()).contains_key(symbol.clone()) {
            market = self.market(symbol.clone());
        };
        let mut id: Value = self.safe_string(trade.clone(), Value::from("id"), Value::Undefined);
        let mut order_id: Value = self.safe_string(trade.clone(), Value::from("order"), Value::Undefined);
        let mut fee_cost: Value = self.safe_string(trade.clone(), Value::from("fee"), Value::Undefined);
        let mut fee: Value = Value::Undefined;
        if fee_cost.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost,
                "currency": quote
            }))).unwrap());
        };
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": symbol,
            "id": id,
            "order": order_id,
            "type": r#type,
            "takerOrMaker": taker_or_maker,
            "side": side,
            "price": price_string,
            "amount": amount_string,
            "cost": cost_string,
            "fee": fee
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_trading_fee(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut options: Value = self.safe_value(self.get("options".into()), Value::from("fetchTradingFee"), Value::new_object());
        let mut default_method: Value = self.safe_string(options.clone(), Value::from("method"), Value::from("fetchPrivateTradingFee"));
        let mut method: Value = self.safe_string(params.clone(), Value::from("method"), default_method.clone());
        params = self.omit(params.clone(), Value::from("method"));
        if method.clone() == Value::from("fetchPrivateTradingFee") {
            return <Self as Latoken>::fetch_private_trading_fee(self, symbol.clone(), params.clone()).await;
        } else if method.clone() == Value::from("fetchPublicTradingFee") {
            return <Self as Latoken>::fetch_public_trading_fee(self, symbol.clone(), params.clone()).await;
        } else {
            panic!(r###"NotSupported::new(self.get("id".into()) + Value::from(" not support this method"))"###);
        };
        Value::Undefined
    }

    async fn fetch_public_trading_fee(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": market.get(Value::from("baseId")),
            "quote": market.get(Value::from("quoteId"))
        }))).unwrap());
        let mut response: Value = self.dispatch("publicGetTradeFeeCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "makerFee": "0.004900000000000000",
        //         "takerFee": "0.004900000000000000",
        //         "type": "FEE_SCHEME_TYPE_PERCENT_QUOTE",
        //         "take": "FEE_SCHEME_TAKE_PROPORTION"
        //     }
        //
        return Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "symbol": market.get(Value::from("symbol")),
            "maker": self.safe_number(response.clone(), Value::from("makerFee"), Value::Undefined),
            "taker": self.safe_number(response.clone(), Value::from("takerFee"), Value::Undefined),
            "percentage": Value::Undefined,
            "tierBased": Value::Undefined
        }))).unwrap());
    }

    async fn fetch_private_trading_fee(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": market.get(Value::from("baseId")),
            "quote": market.get(Value::from("quoteId"))
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetAuthTradeFeeCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "makerFee": "0.004900000000000000",
        //         "takerFee": "0.004900000000000000",
        //         "type": "FEE_SCHEME_TYPE_PERCENT_QUOTE",
        //         "take": "FEE_SCHEME_TAKE_PROPORTION"
        //     }
        //
        return Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "symbol": market.get(Value::from("symbol")),
            "maker": self.safe_number(response.clone(), Value::from("makerFee"), Value::Undefined),
            "taker": self.safe_number(response.clone(), Value::from("takerFee"), Value::Undefined),
            "percentage": Value::Undefined,
            "tierBased": Value::Undefined
        }))).unwrap());
    }

    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'currency': market['baseId'],
        // 'quote': market['quoteId'],
        // 'from': this.milliseconds (),
        // 'limit': limit, // default '100'
        let mut market: Value = Value::Undefined;
        if limit.clone().is_nonnullish() {
            request.set("limit".into(), limit.clone());
        };
        // default 100
        let mut response: Value = Value::Undefined;
        if symbol.clone().is_nonnullish() {
            market = self.market(symbol.clone());
            request.set("currency".into(), market.get(Value::from("baseId")));
            request.set("quote".into(), market.get(Value::from("quoteId")));
            response = self.dispatch("privateGetAuthTradePairCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privateGetAuthTrade".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //     [
        //         {
        //             "id":"02e02533-b4bf-4ba9-9271-24e2108dfbf7",
        //             "isMakerBuyer":false,
        //             "direction":"TRADE_DIRECTION_BUY",
        //             "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //             "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "price":"4564.32",
        //             "quantity":"0.01000",
        //             "cost":"45.6432",
        //             "fee":"0.223651680000000000",
        //             "order":"c9cac6a0-484c-4892-88e7-ad51b39f2ce1",
        //             "timestamp":1635921580399,
        //             "makerBuyer":false
        //         }
        //     ]
        //
        return self.parse_trades(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "ORDER_STATUS_PLACED": "open",
            "ORDER_STATUS_CLOSED": "closed",
            "ORDER_STATUS_CANCELLED": "canceled"
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order_type(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "ORDER_TYPE_MARKET": "market",
            "ORDER_TYPE_LIMIT": "limit"
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_time_in_force(&self, mut time_in_force: Value) -> Value {
        let mut time_in_forces: Value = Value::Json(normalize(&Value::Json(json!({
            "ORDER_CONDITION_GOOD_TILL_CANCELLED": "GTC",
            "ORDER_CONDITION_IMMEDIATE_OR_CANCEL": "IOC",
            "ORDER_CONDITION_FILL_OR_KILL": "FOK"
        }))).unwrap());
        return self.safe_string(time_in_forces.clone(), time_in_force.clone(), time_in_force.clone());
    }

    fn parse_order(&mut self, mut order: Value, mut market: Value) -> Value {
        //
        // createOrder
        //
        //    {
        //        "baseCurrency": "f7dac554-8139-4ff6-841f-0e586a5984a0",
        //        "quoteCurrency": "a5a7a7a9-e2a3-43f9-8754-29a02f6b709b",
        //        "side": "BID",
        //        "clientOrderId": "my-wonderful-order-number-71566",
        //        "price": "10103.19",
        //        "stopPrice": "10103.19",
        //        "quantity": "3.21",
        //        "timestamp": 1568185507
        //    }
        //
        // fetchOrder, fetchOpenOrders, fetchOrders
        //
        //     {
        //         "id":"a76bd262-3560-4bfb-98ac-1cedd394f4fc",
        //         "status":"ORDER_STATUS_PLACED",
        //         "side":"ORDER_SIDE_BUY",
        //         "condition":"ORDER_CONDITION_GOOD_TILL_CANCELLED",
        //         "type":"ORDER_TYPE_LIMIT",
        //         "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //         "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //         "clientOrderId":"web-macos_chrome_1a6a6659-6f7c-4fac-be0b-d1d7ac06d",
        //         "price":"4000.00",
        //         "quantity":"0.01",
        //         "cost":"40.000000000000000000",
        //         "filled":"0",
        //         "trader":"7244bb3a-b6b2-446a-ac78-fa4bce5b59a9",
        //         "creator":"ORDER_CREATOR_USER",
        //         "creatorId":"",
        //         "timestamp":1635920767648
        //     }
        //
        // cancelOrder
        //
        //     {
        //         "message":"cancellation request successfully submitted",
        //         "status":"SUCCESS",
        //         "id":"a631426d-3543-45ba-941e-75f7825afb0f"
        //     }
        //
        let mut id: Value = self.safe_string(order.clone(), Value::from("id"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(order.clone(), Value::from("timestamp"), Value::Undefined);
        let mut base_id: Value = self.safe_string(order.clone(), Value::from("baseCurrency"), Value::Undefined);
        let mut quote_id: Value = self.safe_string(order.clone(), Value::from("quoteCurrency"), Value::Undefined);
        let mut base: Value = self.safe_currency_code(base_id.clone(), Value::Undefined);
        let mut quote: Value = self.safe_currency_code(quote_id.clone(), Value::Undefined);
        let mut symbol: Value = Value::Undefined;
        if base.clone().is_nonnullish() && quote.clone().is_nonnullish() {
            symbol = base.clone() + Value::from("/") + quote.clone();
            if self.get("markets".into()).contains_key(symbol.clone()) {
                market = self.market(symbol.clone());
            };
        };
        let mut order_side: Value = self.safe_string(order.clone(), Value::from("side"), Value::Undefined);
        let mut side: Value = Value::Undefined;
        if order_side.clone().is_nonnullish() {
            let mut parts: Value = order_side.split(Value::from("_"));
            let mut parts_length: Value = Value::from(parts.len());
            side = self.safe_string_lower(parts.clone(), parts_length.clone() - Value::from(1), Value::Undefined);
        };
        let mut r#type: Value = <Self as Latoken>::parse_order_type(self, self.safe_string(order.clone(), Value::from("type"), Value::Undefined));
        let mut price: Value = self.safe_string(order.clone(), Value::from("price"), Value::Undefined);
        let mut amount: Value = self.safe_string(order.clone(), Value::from("quantity"), Value::Undefined);
        let mut filled: Value = self.safe_string(order.clone(), Value::from("filled"), Value::Undefined);
        let mut cost: Value = self.safe_string(order.clone(), Value::from("cost"), Value::Undefined);
        let mut status: Value = <Self as Latoken>::parse_order_status(self, self.safe_string(order.clone(), Value::from("status"), Value::Undefined));
        let mut message: Value = self.safe_string(order.clone(), Value::from("message"), Value::Undefined);
        if message.clone().is_nonnullish() {
            if message.index_of(Value::from("cancel")) >= Value::from(0) {
                status = Value::from("canceled");
            } else if message.index_of(Value::from("accept")) >= Value::from(0) {
                status = Value::from("open");
            };
        };
        let mut client_order_id: Value = self.safe_string(order.clone(), Value::from("clientOrderId"), Value::Undefined);
        let mut time_in_force: Value = <Self as Latoken>::parse_time_in_force(self, self.safe_string(order.clone(), Value::from("condition"), Value::Undefined));
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "id": id,
            "clientOrderId": client_order_id,
            "info": order,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": Value::Undefined,
            "status": status,
            "symbol": symbol,
            "type": r#type,
            "timeInForce": time_in_force,
            "postOnly": Value::Undefined,
            "side": side,
            "price": price,
            "triggerPrice": self.safe_string(order.clone(), Value::from("stopPrice"), Value::Undefined),
            "cost": cost,
            "amount": amount,
            "filled": filled,
            "average": Value::Undefined,
            "remaining": Value::Undefined,
            "fee": Value::Undefined,
            "trades": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if symbol.clone().is_nullish() {
            panic!(r###"ArgumentsRequired::new(self.get("id".into()) + Value::from(" fetchOpenOrders() requires a symbol argument"))"###);
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = Value::Undefined;
        let mut is_trigger: Value = self.safe_value_2(params.clone(), Value::from("trigger"), Value::from("stop"), Value::Undefined);
        params = self.omit(params.clone(), Value::from("stop"));
        // privateGetAuthOrderActive doesn't work even though its listed at https://api.latoken.com/doc/v2/#tag/Order/operation/getMyActiveOrders
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": market.get(Value::from("baseId")),
            "quote": market.get(Value::from("quoteId"))
        }))).unwrap());
        if is_trigger.is_truthy() {
            response = self.dispatch("privateGetAuthStopOrderPairCurrencyQuoteActive".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privateGetAuthOrderPairCurrencyQuoteActive".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //     [
        //         {
        //             "id":"a76bd262-3560-4bfb-98ac-1cedd394f4fc",
        //             "status":"ORDER_STATUS_PLACED",
        //             "side":"ORDER_SIDE_BUY",
        //             "condition":"ORDER_CONDITION_GOOD_TILL_CANCELLED",
        //             "type":"ORDER_TYPE_LIMIT",
        //             "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //             "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "clientOrderId":"web-macos_chrome_1a6a6659-6f7c-4fac-be0b-d1d7ac06d",
        //             "price":"4000.00",
        //             "quantity":"0.01000",
        //             "cost":"40.00",
        //             "filled":"0.00000",
        //             "trader":"7244bb3a-b6b2-446a-ac78-fa4bce5b59a9",
        //             "creator":"USER",
        //             "creatorId":"",
        //             "timestamp":1635920767648
        //         }
        //     ]
        //
        return self.parse_orders(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn fetch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'currency': market['baseId'],
        // 'quote': market['quoteId'],
        // 'from': this.milliseconds (),
        // 'limit': limit, // default '100'
        let mut market: Value = Value::Undefined;
        let mut is_trigger: Value = self.safe_value_2(params.clone(), Value::from("trigger"), Value::from("stop"), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("stop").into(), Value::from("trigger").into()])));
        if limit.clone().is_nonnullish() {
            request.set("limit".into(), limit.clone());
        };
        // default 100
        let mut response: Value = Value::Undefined;
        if symbol.clone().is_nonnullish() {
            market = self.market(symbol.clone());
            request.set("currency".into(), market.get(Value::from("baseId")));
            request.set("quote".into(), market.get(Value::from("quoteId")));
            if is_trigger.is_truthy() {
                response = self.dispatch("privateGetAuthStopOrderPairCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            } else {
                response = self.dispatch("privateGetAuthOrderPairCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            };
        } else {
            if is_trigger.is_truthy() {
                response = self.dispatch("privateGetAuthStopOrder".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            } else {
                response = self.dispatch("privateGetAuthOrder".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            };
        };
        //
        //     [
        //         {
        //             "id":"a76bd262-3560-4bfb-98ac-1cedd394f4fc",
        //             "status":"ORDER_STATUS_PLACED",
        //             "side":"ORDER_SIDE_BUY",
        //             "condition":"ORDER_CONDITION_GOOD_TILL_CANCELLED",
        //             "type":"ORDER_TYPE_LIMIT",
        //             "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //             "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "clientOrderId":"web-macos_chrome_1a6a6659-6f7c-4fac-be0b-d1d7ac06d",
        //             "price":"4000.00",
        //             "quantity":"0.01000",
        //             "cost":"40.00",
        //             "filled":"0.00000",
        //             "trader":"7244bb3a-b6b2-446a-ac78-fa4bce5b59a9",
        //             "creator":"USER",
        //             "creatorId":"",
        //             "timestamp":1635920767648
        //         }
        //     ]
        //
        return self.parse_orders(response.clone(), market.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "id": id
        }))).unwrap());
        let mut is_trigger: Value = self.safe_value_2(params.clone(), Value::from("trigger"), Value::from("stop"), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("stop").into(), Value::from("trigger").into()])));
        let mut response: Value = Value::Undefined;
        if is_trigger.is_truthy() {
            response = self.dispatch("privateGetAuthStopOrderGetOrderId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privateGetAuthOrderGetOrderId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //     {
        //         "id":"a76bd262-3560-4bfb-98ac-1cedd394f4fc",
        //         "status":"ORDER_STATUS_PLACED",
        //         "side":"ORDER_SIDE_BUY",
        //         "condition":"ORDER_CONDITION_GOOD_TILL_CANCELLED",
        //         "type":"ORDER_TYPE_LIMIT",
        //         "baseCurrency":"620f2019-33c0-423b-8a9d-cde4d7f8ef7f",
        //         "quoteCurrency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //         "clientOrderId":"web-macos_chrome_1a6a6659-6f7c-4fac-be0b-d1d7ac06d",
        //         "price":"4000.00",
        //         "quantity":"0.01",
        //         "cost":"40.000000000000000000",
        //         "filled":"0",
        //         "trader":"7244bb3a-b6b2-446a-ac78-fa4bce5b59a9",
        //         "creator":"ORDER_CREATOR_USER",
        //         "creatorId":"",
        //         "timestamp":1635920767648
        //     }
        //
        return <Self as Latoken>::parse_order(self, response.clone(), Value::Undefined);
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut uppercase_type: Value = r#type.to_upper_case();
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "baseCurrency": market.get(Value::from("baseId")),
            "quoteCurrency": market.get(Value::from("quoteId")),
            "side": side.to_upper_case(),
            "condition": "GTC",
            "type": uppercase_type,
            "clientOrderId": self.uuid(),
            "quantity": self.amount_to_precision(symbol.clone(), amount.clone()),
            "timestamp": self.seconds()
        }))).unwrap());
        // 'price': this.priceToPrecision (symbol, price),
        // 'quantity': this.amountToPrecision (symbol, amount),
        if uppercase_type.clone() == Value::from("LIMIT") {
            request.set("price".into(), self.price_to_precision(symbol.clone(), price.clone()));
        };
        let mut trigger_price: Value = self.safe_string_2(params.clone(), Value::from("triggerPrice"), Value::from("stopPrice"), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("triggerPrice").into(), Value::from("stopPrice").into()])));
        let mut response: Value = Value::Undefined;
        if trigger_price.clone().is_nonnullish() {
            request.set("stopPrice".into(), self.price_to_precision(symbol.clone(), trigger_price.clone()));
            response = self.dispatch("privatePostAuthStopOrderPlace".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privatePostAuthOrderPlace".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //    {
        //        "baseCurrency": "f7dac554-8139-4ff6-841f-0e586a5984a0",
        //        "quoteCurrency": "a5a7a7a9-e2a3-43f9-8754-29a02f6b709b",
        //        "side": "BID",
        //        "clientOrderId": "my-wonderful-order-number-71566",
        //        "price": "10103.19",
        //        "stopPrice": "10103.19",
        //        "quantity": "3.21",
        //        "timestamp": 1568185507
        //    }
        //
        return <Self as Latoken>::parse_order(self, response.clone(), market.clone());
    }

    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "id": id
        }))).unwrap());
        let mut is_trigger: Value = self.safe_value_2(params.clone(), Value::from("trigger"), Value::from("stop"), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("stop").into(), Value::from("trigger").into()])));
        let mut response: Value = Value::Undefined;
        if is_trigger.is_truthy() {
            response = self.dispatch("privatePostAuthStopOrderCancel".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privatePostAuthOrderCancel".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //     {
        //         "id": "12345678-1234-1244-1244-123456789012",
        //         "message": "cancellation request successfully submitted",
        //         "status": "SUCCESS",
        //         "error": "",
        //         "errors": { }
        //     }
        //
        return <Self as Latoken>::parse_order(self, response.clone(), Value::Undefined);
    }

    async fn cancel_all_orders(&mut self, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'currency': market['baseId'],
        // 'quote': market['quoteId'],
        let mut market: Value = Value::Undefined;
        let mut is_trigger: Value = self.safe_value_2(params.clone(), Value::from("trigger"), Value::from("stop"), Value::Undefined);
        params = self.omit(params.clone(), Value::Json(serde_json::Value::Array(vec![Value::from("stop").into(), Value::from("trigger").into()])));
        let mut response: Value = Value::Undefined;
        if symbol.clone().is_nonnullish() {
            market = self.market(symbol.clone());
            request.set("currency".into(), market.get(Value::from("baseId")));
            request.set("quote".into(), market.get(Value::from("quoteId")));
            if is_trigger.is_truthy() {
                response = self.dispatch("privatePostAuthStopOrderCancelAllCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            } else {
                response = self.dispatch("privatePostAuthOrderCancelAllCurrencyQuote".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            };
        } else {
            if is_trigger.is_truthy() {
                response = self.dispatch("privatePostAuthStopOrderCancelAll".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            } else {
                response = self.dispatch("privatePostAuthOrderCancelAll".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
            };
        };
        //
        //     {
        //         "message":"cancellation request successfully submitted",
        //         "status":"SUCCESS"
        //     }
        //
        return Value::Json(serde_json::Value::Array(vec![self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap()), Value::Undefined).into()]));
    }

    async fn fetch_transactions(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::new_object();
        // 'page': '1',
        // 'size': 100,
        let mut response: Value = self.dispatch("privateGetAuthTransaction".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "hasNext":false,
        //         "content":[
        //             {
        //                 "id":"fbf7d0d1-2629-4ad8-9def-7a1dba423362",
        //                 "status":"TRANSACTION_STATUS_CONFIRMED",
        //                 "type":"TRANSACTION_TYPE_DEPOSIT",
        //                 "senderAddress":"",
        //                 "recipientAddress":"0x3c46fa2e3f9023bc4897828ed173f8ecb3a554bc",
        //                 "amount":"200.000000000000000000",
        //                 "transactionFee":"0.000000000000000000",
        //                 "timestamp":1635893208404,
        //                 "transactionHash":"0x28bad3b74a042df13d64ddfbca855566a51bf7f190b8cd565c236a18d5cd493f#42",
        //                 "blockHeight":13540262,
        //                 "currency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //                 "memo":null,
        //                 "paymentProvider":"a8d6d1cb-f84a-4e9d-aa82-c6a08b356ee1",
        //                 "requiresCode":false
        //             }
        //         ],
        //         "first":true,
        //         "hasContent":true,
        //         "pageSize":10
        //     }
        //
        let mut currency: Value = Value::Undefined;
        if code.clone().is_nonnullish() {
            currency = self.currency(code.clone());
        };
        let mut content: Value = self.safe_list(response.clone(), Value::from("content"), Value::new_array());
        return self.parse_transactions(content.clone(), currency.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    fn parse_transaction(&self, mut transaction: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "id":"fbf7d0d1-2629-4ad8-9def-7a1dba423362",
        //         "status":"TRANSACTION_STATUS_CONFIRMED",
        //         "type":"TRANSACTION_TYPE_DEPOSIT",
        //         "senderAddress":"",
        //         "recipientAddress":"0x3c46fa2e3f9023bc4897828ed173f8ecb3a554bc",
        //         "amount":"200.000000000000000000",
        //         "transactionFee":"0.000000000000000000",
        //         "timestamp":1635893208404,
        //         "transactionHash":"0x28bad3b74a042df13d64ddfbca855566a51bf7f190b8cd565c236a18d5cd493f#42",
        //         "blockHeight":13540262,
        //         "currency":"0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //         "memo":null,
        //         "paymentProvider":"a8d6d1cb-f84a-4e9d-aa82-c6a08b356ee1",
        //         "requiresCode":false
        //     }
        //
        let mut id: Value = self.safe_string(transaction.clone(), Value::from("id"), Value::Undefined);
        let mut timestamp: Value = self.safe_integer(transaction.clone(), Value::from("timestamp"), Value::Undefined);
        let mut currency_id: Value = self.safe_string(transaction.clone(), Value::from("currency"), Value::Undefined);
        let mut code: Value = self.safe_currency_code(currency_id.clone(), currency.clone());
        let mut status: Value = <Self as Latoken>::parse_transaction_status(self, self.safe_string(transaction.clone(), Value::from("status"), Value::Undefined));
        let mut amount: Value = self.safe_number(transaction.clone(), Value::from("amount"), Value::Undefined);
        let mut address_from: Value = self.safe_string(transaction.clone(), Value::from("senderAddress"), Value::Undefined);
        let mut address_to: Value = self.safe_string(transaction.clone(), Value::from("recipientAddress"), Value::Undefined);
        let mut txid: Value = self.safe_string(transaction.clone(), Value::from("transactionHash"), Value::Undefined);
        let mut tag_to: Value = self.safe_string(transaction.clone(), Value::from("memo"), Value::Undefined);
        let mut fee: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": Value::Undefined,
            "cost": Value::Undefined,
            "rate": Value::Undefined
        }))).unwrap());
        let mut fee_cost: Value = self.safe_number(transaction.clone(), Value::from("transactionFee"), Value::Undefined);
        if fee_cost.clone().is_nonnullish() {
            fee.set("cost".into(), fee_cost.clone());
            fee.set("currency".into(), code.clone());
        };
        let mut r#type: Value = <Self as Latoken>::parse_transaction_type(self, self.safe_string(transaction.clone(), Value::from("type"), Value::Undefined));
        return Value::Json(normalize(&Value::Json(json!({
            "info": transaction,
            "id": id,
            "txid": txid,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "network": Value::Undefined,
            "addressFrom": address_from,
            "addressTo": address_to,
            "address": address_to,
            "tagFrom": Value::Undefined,
            "tagTo": tag_to,
            "tag": tag_to,
            "type": r#type,
            "amount": amount,
            "currency": code,
            "status": status,
            "updated": Value::Undefined,
            "comment": Value::Undefined,
            "internal": Value::Undefined,
            "fee": fee
        }))).unwrap());
    }

    fn parse_transaction_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "TRANSACTION_STATUS_CONFIRMED": "ok",
            "TRANSACTION_STATUS_EXECUTED": "ok",
            "TRANSACTION_STATUS_CHECKING": "pending",
            "TRANSACTION_STATUS_CANCELLED": "canceled",
            "TRANSACTION_STATUS_FAILED": "failed",
            "TRANSACTION_STATUS_REJECTED": "rejected"
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_transaction_type(&self, mut r#type: Value) -> Value {
        let mut types: Value = Value::Json(normalize(&Value::Json(json!({
            "TRANSACTION_TYPE_DEPOSIT": "deposit",
            "TRANSACTION_TYPE_WITHDRAWAL": "withdrawal"
        }))).unwrap());
        return self.safe_string(types.clone(), r#type.clone(), r#type.clone());
    }

    async fn fetch_transfers(&mut self, mut code: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut response: Value = self.dispatch("privateGetAuthTransfer".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "hasNext": true,
        //         "content": [
        //             {
        //             "id": "ebd6312f-cb4f-45d1-9409-4b0b3027f21e",
        //             "status": "TRANSFER_STATUS_COMPLETED",
        //             "type": "TRANSFER_TYPE_WITHDRAW_SPOT",
        //             "fromAccount": "c429c551-adbb-4078-b74b-276bea308a36",
        //             "toAccount": "631c6203-bd62-4734-a04d-9b2a951f43b9",
        //             "transferringFunds": 1259.0321785,
        //             "usdValue": 1259.032179,
        //             "rejectReason": null,
        //             "timestamp": 1633515579530,
        //             "direction": "INTERNAL",
        //             "method": "TRANSFER_METHOD_UNKNOWN",
        //             "recipient": null,
        //             "sender": null,
        //             "currency": "0c3a106d-bde3-4c13-a26e-3fd2394529e5",
        //             "codeRequired": false,
        //             "fromUser": "ce555f3f-585d-46fb-9ae6-487f66738073",
        //             "toUser": "ce555f3f-585d-46fb-9ae6-487f66738073",
        //             "fee": 0
        //             },
        //             ...
        //         ],
        //         "first": true,
        //         "pageSize": 20,
        //         "hasContent": true
        //     }
        //
        let mut transfers: Value = self.safe_list(response.clone(), Value::from("content"), Value::new_array());
        return self.parse_transfers(transfers.clone(), currency.clone(), since.clone(), limit.clone(), Value::Undefined);
    }

    async fn transfer(&mut self, mut code: Value, mut amount: Value, mut from_account: Value, mut to_account: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": currency.get(Value::from("id")),
            "recipient": to_account,
            "value": self.currency_to_precision(code.clone(), amount.clone(), Value::Undefined)
        }))).unwrap());
        let mut response: Value = Value::Undefined;
        if to_account.index_of(Value::from("@")) >= Value::from(0) {
            response = self.dispatch("privatePostAuthTransferEmail".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else if to_account.len() == 36 {
            response = self.dispatch("privatePostAuthTransferId".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        } else {
            response = self.dispatch("privatePostAuthTransferPhone".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        };
        //
        //     {
        //         "id": "e6fc4ace-7750-44e4-b7e9-6af038ac7107",
        //         "status": "TRANSFER_STATUS_COMPLETED",
        //         "type": "TRANSFER_TYPE_DEPOSIT_SPOT",
        //         "fromAccount": "3bf61015-bf32-47a6-b237-c9f70df772ad",
        //         "toAccount": "355eb279-7c7e-4515-814a-575a49dc0325",
        //         "transferringFunds": "500000.000000000000000000",
        //         "usdValue": "0.000000000000000000",
        //         "rejectReason": "",
        //         "timestamp": 1576844438402,
        //         "direction": "INTERNAL",
        //         "method": "TRANSFER_METHOD_UNKNOWN",
        //         "recipient": "",
        //         "sender": "",
        //         "currency": "40af7879-a8cc-4576-a42d-7d2749821b58",
        //         "codeRequired": false,
        //         "fromUser": "cd555555-666d-46fb-9ae6-487f66738073",
        //         "toUser": "cd555555-666d-46fb-9ae6-487f66738073",
        //         "fee": 0
        //     }
        //
        return <Self as Latoken>::parse_transfer(self, response.clone(), Value::Undefined);
    }

    fn parse_transfer(&self, mut transfer: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "id": "e6fc4ace-7750-44e4-b7e9-6af038ac7107",
        //         "status": "TRANSFER_STATUS_COMPLETED",
        //         "type": "TRANSFER_TYPE_DEPOSIT_SPOT",
        //         "fromAccount": "3bf61015-bf32-47a6-b237-c9f70df772ad",
        //         "toAccount": "355eb279-7c7e-4515-814a-575a49dc0325",
        //         "transferringFunds": "500000.000000000000000000",
        //         "usdValue": "0.000000000000000000",
        //         "rejectReason": "",
        //         "timestamp": 1576844438402,
        //         "direction": "INTERNAL",
        //         "method": "TRANSFER_METHOD_UNKNOWN",
        //         "recipient": "",
        //         "sender": "",
        //         "currency": "40af7879-a8cc-4576-a42d-7d2749821b58",
        //         "codeRequired": false,
        //         "fromUser": "cd555555-666d-46fb-9ae6-487f66738073",
        //         "toUser": "cd555555-666d-46fb-9ae6-487f66738073",
        //         "fee": 0
        //     }
        //
        let mut timestamp: Value = self.safe_timestamp(transfer.clone(), Value::from("timestamp"), Value::Undefined);
        let mut currency_id: Value = self.safe_string(transfer.clone(), Value::from("currency"), Value::Undefined);
        let mut status: Value = self.safe_string(transfer.clone(), Value::from("status"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": transfer,
            "id": self.safe_string(transfer.clone(), Value::from("id"), Value::Undefined),
            "timestamp": self.safe_integer(transfer.clone(), Value::from("timestamp"), Value::Undefined),
            "datetime": self.iso8601(timestamp.clone()),
            "currency": self.safe_currency_code(currency_id.clone(), currency.clone()),
            "amount": self.safe_number(transfer.clone(), Value::from("transferringFunds"), Value::Undefined),
            "fromAccount": self.safe_string(transfer.clone(), Value::from("fromAccount"), Value::Undefined),
            "toAccount": self.safe_string(transfer.clone(), Value::from("toAccount"), Value::Undefined),
            "status": <Self as Latoken>::parse_transfer_status(self, status.clone())
        }))).unwrap());
    }

    fn parse_transfer_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "TRANSFER_STATUS_COMPLETED": "ok",
            "TRANSFER_STATUS_PENDING": "pending",
            "TRANSFER_STATUS_REJECTED": "failed",
            "TRANSFER_STATUS_UNVERIFIED": "pending",
            "TRANSFER_STATUS_CANCELLED": "canceled"
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetBookcurrencyquote" => self.request("book/{currency}/{quote}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetChartweek" => self.request("chart/week".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetChartweekcurrencyquote" => self.request("chart/week/{currency}/{quote}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCurrency" => self.request("currency".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCurrencyavailable" => self.request("currency/available".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCurrencyquotes" => self.request("currency/quotes".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCurrencycurrency" => self.request("currency/{currency}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPair" => self.request("pair".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetPairavailable" => self.request("pair/available".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTicker" => self.request("ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTickerbasequote" => self.request("ticker/{base}/{quote}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTime" => self.request("time".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTradehistorycurrencyquote" => self.request("trade/history/{currency}/{quote}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTradefeecurrencyquote" => self.request("trade/fee/{currency}/{quote}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTradefeelevels" => self.request("trade/feeLevels".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetTransactionbindings" => self.request("transaction/bindings".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthaccount" => self.request("auth/account".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthaccountcurrencycurrencytype" => self.request("auth/account/currency/{currency}/{type}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthorder" => self.request("auth/order".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthordergetorderid" => self.request("auth/order/getOrder/{id}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthorderpaircurrencyquote" => self.request("auth/order/pair/{currency}/{quote}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthorderpaircurrencyquoteactive" => self.request("auth/order/pair/{currency}/{quote}/active".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthstoporder" => self.request("auth/stopOrder".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthstopordergetorderid" => self.request("auth/stopOrder/getOrder/{id}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthstoporderpaircurrencyquote" => self.request("auth/stopOrder/pair/{currency}/{quote}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthstoporderpaircurrencyquoteactive" => self.request("auth/stopOrder/pair/{currency}/{quote}/active".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtrade" => self.request("auth/trade".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtradepaircurrencyquote" => self.request("auth/trade/pair/{currency}/{quote}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtradefeecurrencyquote" => self.request("auth/trade/fee/{currency}/{quote}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtransaction" => self.request("auth/transaction".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtransactionbindings" => self.request("auth/transaction/bindings".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtransactionbindingscurrency" => self.request("auth/transaction/bindings/{currency}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtransactionid" => self.request("auth/transaction/{id}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetAuthtransfer" => self.request("auth/transfer".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthordercancel" => self.request("auth/order/cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthordercancelall" => self.request("auth/order/cancelAll".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthordercancelallcurrencyquote" => self.request("auth/order/cancelAll/{currency}/{quote}".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthorderplace" => self.request("auth/order/place".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthspotdeposit" => self.request("auth/spot/deposit".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthspotwithdraw" => self.request("auth/spot/withdraw".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthstopordercancel" => self.request("auth/stopOrder/cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthstopordercancelall" => self.request("auth/stopOrder/cancelAll".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthstopordercancelallcurrencyquote" => self.request("auth/stopOrder/cancelAll/{currency}/{quote}".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthstoporderplace" => self.request("auth/stopOrder/place".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransactiondepositaddress" => self.request("auth/transaction/depositAddress".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransactionwithdraw" => self.request("auth/transaction/withdraw".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransactionwithdrawcancel" => self.request("auth/transaction/withdraw/cancel".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransactionwithdrawconfirm" => self.request("auth/transaction/withdraw/confirm".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransactionwithdrawresendcode" => self.request("auth/transaction/withdraw/resendCode".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransferemail" => self.request("auth/transfer/email".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransferid" => self.request("auth/transfer/id".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostAuthtransferphone" => self.request("auth/transfer/phone".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LatokenImpl(Value);
impl Exchange for LatokenImpl {}
impl Latoken for LatokenImpl {}
impl ValueTrait for LatokenImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl LatokenImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = LatokenImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Latoken::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

