#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
use crate::ws::{ArrayCache, ArrayCacheByTimestamp, ArrayCacheBySymbolById, ArrayCacheBySymbolBySide};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors (stub structs with ::new for transpiled `new ErrorType(msg)` patterns)
macro_rules! error_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(msg: Value) -> Value { msg } } }; }
error_stub!(BadRequest);
error_stub!(InvalidOrder);
error_stub!(ExchangeError);
error_stub!(InsufficientFunds);
error_stub!(OrderNotFound);
error_stub!(AuthenticationError);
error_stub!(PermissionDenied);
error_stub!(ExchangeNotAvailable);
error_stub!(ArgumentsRequired);
error_stub!(RateLimitExceeded);
error_stub!(OrderNotFillable);
error_stub!(OrderImmediatelyFillable);
error_stub!(NotSupported);
error_stub!(DuplicateOrderId);
error_stub!(UnsubscribeError);
error_stub!(ChecksumError);
error_stub!(InvalidNonce);
error_stub!(BadSymbol);
// Array-like type stubs (Bids/Asks order book sides)
macro_rules! array_side_stub { ($name:ident) => { pub struct $name; impl $name { pub fn new(data: Value, _limit: Value) -> Value { data } } }; }
array_side_stub!(Bids);
array_side_stub!(Asks);

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait(?Send)]
pub trait Mercado : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "mercado",
            "name": "Mercado Bitcoin",
            "countries": [
                "BR"
            ],
            "enableRateLimit": true,
            "rateLimit": 1000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "CORS": true,
                "spot": true,
                "margin": false,
                "swap": false,
                "future": false,
                "option": false,
                "addMargin": false,
                "borrowCrossMargin": false,
                "borrowIsolatedMargin": false,
                "borrowMargin": false,
                "cancelOrder": true,
                "closeAllPositions": false,
                "closePosition": false,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "createReduceOnlyOrder": false,
                "createStopLimitOrder": false,
                "createStopMarketOrder": false,
                "createStopOrder": false,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchBorrowInterest": false,
                "fetchBorrowRate": false,
                "fetchBorrowRateHistories": false,
                "fetchBorrowRateHistory": false,
                "fetchBorrowRates": false,
                "fetchBorrowRatesPerSymbol": false,
                "fetchCrossBorrowRate": false,
                "fetchCrossBorrowRates": false,
                "fetchCurrencies": false,
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": false,
                "fetchDepositAddresses": false,
                "fetchDepositAddressesByNetwork": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingInterval": false,
                "fetchFundingIntervals": false,
                "fetchFundingRates": false,
                "fetchGreeks": false,
                "fetchIndexOHLCV": false,
                "fetchIsolatedBorrowRate": false,
                "fetchIsolatedBorrowRates": false,
                "fetchMarginAdjustmentHistory": false,
                "fetchIsolatedPositions": false,
                "fetchL2OrderBook": true,
                "fetchLeverage": false,
                "fetchLeverages": false,
                "fetchLeverageTiers": false,
                "fetchLiquidations": false,
                "fetchLongShortRatio": false,
                "fetchLongShortRatioHistory": false,
                "fetchMarginMode": false,
                "fetchMarginModes": false,
                "fetchMarketLeverageTiers": false,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchMyLiquidations": false,
                "fetchMySettlementHistory": false,
                "fetchMyTrades": "emulated",
                "fetchOHLCV": true,
                "fetchOpenInterest": false,
                "fetchOpenInterests": false,
                "fetchOpenInterestHistory": false,
                "fetchOpenOrders": true,
                "fetchOption": false,
                "fetchOptionChain": false,
                "fetchOrder": true,
                "fetchOrderBook": true,
                "fetchOrders": true,
                "fetchPosition": false,
                "fetchPositionHistory": false,
                "fetchPositionsHistory": false,
                "fetchPositionMode": false,
                "fetchPositions": false,
                "fetchPositionsForSymbol": false,
                "fetchPositionsRisk": false,
                "fetchPremiumIndexOHLCV": false,
                "fetchSettlementHistory": false,
                "fetchTicker": true,
                "fetchTickers": false,
                "fetchMarkPrices": false,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": false,
                "fetchUnderlyingAssets": false,
                "fetchVolatilityHistory": false,
                "reduceMargin": false,
                "repayCrossMargin": false,
                "repayIsolatedMargin": false,
                "setLeverage": false,
                "setMargin": false,
                "setMarginMode": false,
                "setPositionMode": false,
                "withdraw": true,
                "fetchAllGreeks": false,
                "fetchMarkPrice": false
            },
            "urls": {
                "logo": "https://user-images.githubusercontent.com/1294454/27837060-e7c58714-60ea-11e7-9192-f05e86adb83f.jpg",
                "api": {
                    "public": "https://www.mercadobitcoin.net/api",
                    "private": "https://www.mercadobitcoin.net/tapi",
                    "v4Public": "https://www.mercadobitcoin.com.br/v4",
                    "v4PublicNet": "https://api.mercadobitcoin.net/api/v4"
                },
                "www": "https://www.mercadobitcoin.com.br",
                "doc": [
                    "https://www.mercadobitcoin.com.br/api-doc",
                    "https://www.mercadobitcoin.com.br/trade-api"
                ]
            },
            "api": {
                "public": {
                    "get": [
                        "coins",
                        "{coin}/orderbook/",
                        "{coin}/ticker/",
                        "{coin}/trades/",
                        "{coin}/trades/{from}/",
                        "{coin}/trades/{from}/{to}",
                        "{coin}/day-summary/{year}/{month}/{day}/"
                    ]
                },
                "private": {
                    "post": [
                        "cancel_order",
                        "get_account_info",
                        "get_order",
                        "get_withdrawal",
                        "list_system_messages",
                        "list_orders",
                        "list_orderbook",
                        "place_buy_order",
                        "place_sell_order",
                        "place_market_buy_order",
                        "place_market_sell_order",
                        "withdraw_coin"
                    ]
                },
                "v4Public": {
                    "get": [
                        "{coin}/candle/"
                    ]
                },
                "v4PublicNet": {
                    "get": [
                        "candles"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "currencies": {},
            "timeframes": {
                "15m": "15m",
                "1h": "1h",
                "3h": "3h",
                "1d": "1d",
                "1w": "1w",
                "1M": "1M"
            },
            "fees": {
                "trading": {
                    "taker": 0.007,
                    "maker": 0.003
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v3",
            "options": {
                "limits": {
                    "BTC": 0.001,
                    "BCH": 0.001,
                    "ETH": 0.01,
                    "LTC": 0.01,
                    "XRP": 0.1
                }
            },
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": true,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": true,
                        "selfTradePrevention": false,
                        "iceberg": false
                    },
                    "fetchMyTrades": {
                        "marginMode": false,
                        "daysBack": 100000,
                        "untilDays": 100000,
                        "symbolRequired": true
                    },
                    "fetchOrder": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOpenOrders": {
                        "marginMode": false,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOrders": {
                        "marginMode": false,
                        "limit": 500,
                        "daysBack": 100000,
                        "untilDays": 100000,
                        "trigger": false,
                        "trailing": false,
                        "symbolRequired": true
                    },
                    "fetchOHLCV": {
                        "limit": 1000
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut ob = crate::exchange::unwrap_response_order_book(&json_resp);
        if let serde_json::Value::Object(ref mut map) = ob {
            if !map.contains_key("symbol") { map.insert("symbol".to_string(), serde_json::json!(symbol.unwrap_str())); }
        }
        Value::Json(ob)
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        //     {
        //         "high":"103.96000000",
        //         "low":"95.00000000",
        //         "vol":"2227.67806598",
        //         "last":"97.91591000",
        //         "buy":"95.52760000",
        //         "sell":"97.91475000",
        //         "open":"99.79955000",
        //         "date":1643382606
        //     }
        //
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_timestamp(ticker.clone(), Value::from("date"), Value::Undefined);
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("last"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "high": self.safe_string(ticker.clone(), Value::from("high"), Value::Undefined),
            "low": self.safe_string(ticker.clone(), Value::from("low"), Value::Undefined),
            "bid": self.safe_string(ticker.clone(), Value::from("buy"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("sell"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": Value::Undefined,
            "open": Value::Undefined,
            "close": last.clone(),
            "last": last.clone(),
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": Value::Undefined,
            "average": Value::Undefined,
            "baseVolume": self.safe_string(ticker.clone(), Value::from("vol"), Value::Undefined),
            "quoteVolume": Value::Undefined,
            "info": ticker.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        'outer: for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        // Some exchanges wrap the ticker in {data: {...}} or {result: {...}} — unwrap if so.
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let mut tk = json_resp.clone();
        if !tk.is_array() && tk.get("last").is_none() && tk.get("close").is_none() && tk.get("bid").is_none() {
            for key in &["data", "result", "ticker"] {
                if let Some(v) = json_resp.get(key) {
                    if v.is_object() { tk = v.clone(); break; }
                    if let Some(arr) = v.as_array() {
                        if let Some(first) = arr.first() { tk = first.clone(); break; }
                    }
                }
            }
        }
        let market: Value = Value::Undefined;
        let parsed = <Self as Exchange>::parse_ticker(self, Value::Json(tk.clone()), market);
        if parsed.is_undefined() { Value::Json(tk) } else { parsed }
    }


    fn parse_trade(&self, mut trade: Value, mut market: Value) -> Value {
        let mut timestamp: Value = self.safe_timestamp_2(trade.clone(), Value::from("date"), Value::from("executed_timestamp"), Value::Undefined);
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut id: Value = self.safe_string_2(trade.clone(), Value::from("tid"), Value::from("operation_id"), Value::Undefined);
        let mut r#type: Value = Value::Undefined;
        let mut side: Value = self.safe_string(trade.clone(), Value::from("type"), Value::Undefined);
        let mut price: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount: Value = self.safe_string_2(trade.clone(), Value::from("amount"), Value::from("quantity"), Value::Undefined);
        let mut fee_cost: Value = self.safe_string(trade.clone(), Value::from("fee_rate"), Value::Undefined);
        let mut fee: Value = Value::Undefined;
        if fee_cost.clone().is_nonnullish() {
            fee = Value::Json(normalize(&Value::Json(json!({
                "cost": fee_cost.clone(),
                "currency": Value::Undefined
            }))).unwrap());
        };
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "id": id.clone(),
            "info": trade.clone(),
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "order": Value::Undefined,
            "type": r#type.clone(),
            "side": side.clone(),
            "takerOrMaker": Value::Undefined,
            "price": price.clone(),
            "amount": amount.clone(),
            "cost": Value::Undefined,
            "fee": fee.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        let mut raw: Value = Value::Undefined;
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { raw = rv; break; }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            // Already-parsed trades have both `price` and `amount` keys.
            if item.get("price").is_some() && item.get("amount").is_some() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_trade(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    fn parse_balance(&self, mut response: Value) -> Value {
        let mut data: Value = self.safe_value(response.clone(), Value::from("response_data"), Value::new_object());
        let mut balances: Value = self.safe_value(data.clone(), Value::from("balance"), Value::new_object());
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response.clone()
        }))).unwrap());
        let mut currency_ids: Value = balances.clone().keys();
        let mut i: usize = 0;
        while i < currency_ids.len() {
            let mut currency_id: Value = currency_ids.get(i.into());
            let mut code: Value = self.safe_currency_code(currency_id.clone(), Value::Undefined);
            if balances.contains_key(currency_id.clone()) {
                let mut balance: Value = self.safe_value(balances.clone(), currency_id.clone(), Value::new_object());
                let mut account: Value = self.account();
                account.set("free".into(), self.safe_string(balance.clone(), Value::from("available"), Value::Undefined));
                account.set("total".into(), self.safe_string(balance.clone(), Value::from("total"), Value::Undefined));
                result.set(code.clone(), account.clone());
            };
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["account/balance", "balance", "wallet/balance", "accounts/balance", "account"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(&format!("/{}/", token)) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "balance"), ("private", "GET", "account/balance"), ("private", "GET", "wallet/balance")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("type".into(), r#type.clone());
        request.set("side".into(), side.clone());
        request.set("amount".into(), amount.clone());
        if price.is_nonnullish() { request.set("price".into(), price.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "POST" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "POST", "order"), ("private", "POST", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("orderId".into(), id.clone());
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["order", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "DELETE" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.ends_with(&format!("/{}", "orders")) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "DELETE", "order"), ("private", "DELETE", "orders")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_order_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "2": Value::from("open"),
            "3": Value::from("canceled"),
            "4": Value::from("closed")
        }))).unwrap());
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    fn parse_order(&self, mut order: Value, mut market: Value) -> Value {
        //
        //     {
        //         "order_id": 4,
        //         "coin_pair": "BRLBTC",
        //         "order_type": 1,
        //         "status": 2,
        //         "has_fills": true,
        //         "quantity": "2.00000000",
        //         "limit_price": "900.00000",
        //         "executed_quantity": "1.00000000",
        //         "executed_price_avg": "900.00000",
        //         "fee": "0.00300000",
        //         "created_timestamp": "1453838494",
        //         "updated_timestamp": "1453838494",
        //         "operations": [
        //             {
        //                 "operation_id": 1,
        //                 "quantity": "1.00000000",
        //                 "price": "900.00000",
        //                 "fee_rate": "0.30",
        //                 "executed_timestamp": "1453838494",
        //             },
        //         ],
        //     }
        //
        let mut id: Value = self.safe_string(order.clone(), Value::from("order_id"), Value::Undefined);
        let mut order_type: Value = self.safe_string(order.clone(), Value::from("order_type"), Value::Undefined);
        let mut side: Value = Value::Undefined;
        if order.contains_key(Value::from("order_type")) {
            side = if order_type.clone() == Value::from("1") { Value::from("buy") } else { Value::from("sell") };
        };
        let mut status: Value = <Self as Mercado>::parse_order_status(self, self.safe_string(order.clone(), Value::from("status"), Value::Undefined));
        let mut market_id: Value = self.safe_string(order.clone(), Value::from("coin_pair"), Value::Undefined);
        market = self.safe_market(market_id.clone(), market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_timestamp(order.clone(), Value::from("created_timestamp"), Value::Undefined);
        let mut fee: Value = Value::Json(normalize(&Value::Json(json!({
            "cost": self.safe_string(order.clone(), Value::from("fee"), Value::Undefined),
            "currency": market.get(Value::from("quote"))
        }))).unwrap());
        let mut price: Value = self.safe_string(order.clone(), Value::from("limit_price"), Value::Undefined);
        // price = this.safeNumber (order, 'executed_price_avg', price);
        let mut average: Value = self.safe_string(order.clone(), Value::from("executed_price_avg"), Value::Undefined);
        let mut amount: Value = self.safe_string(order.clone(), Value::from("quantity"), Value::Undefined);
        let mut filled: Value = self.safe_string(order.clone(), Value::from("executed_quantity"), Value::Undefined);
        let mut last_trade_timestamp: Value = self.safe_timestamp(order.clone(), Value::from("updated_timestamp"), Value::Undefined);
        let mut raw_trades: Value = self.safe_value(order.clone(), Value::from("operations"), Value::new_array());
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": order.clone(),
            "id": id.clone(),
            "clientOrderId": Value::Undefined,
            "timestamp": timestamp.clone(),
            "datetime": self.iso8601(timestamp.clone()),
            "lastTradeTimestamp": last_trade_timestamp.clone(),
            "symbol": market.get(Value::from("symbol")),
            "type": Value::from("limit"),
            "timeInForce": Value::Undefined,
            "postOnly": Value::Undefined,
            "side": side.clone(),
            "price": price.clone(),
            "triggerPrice": Value::Undefined,
            "cost": Value::Undefined,
            "average": average.clone(),
            "amount": amount.clone(),
            "filled": filled.clone(),
            "remaining": Value::Undefined,
            "status": status.clone(),
            "fee": fee.clone(),
            "trades": raw_trades.clone()
        }))).unwrap()), market.clone());
    }

    async fn fetch_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        if symbol.clone().is_nullish() {
            return Value::Undefined;
        };
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "coin_pair": market.get(Value::from("id")),
            "order_id": parse_int(id.clone(), Value::Undefined)
        }))).unwrap());
        let mut response: Value = self.dispatch("privatePostGetOrder".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        let mut response_data: Value = self.safe_value(response.clone(), Value::from("response_data"), Value::new_object());
        let mut order: Value = self.safe_dict(response_data.clone(), Value::from("order"), Value::Undefined);
        return <Self as Mercado>::parse_order(self, order.clone(), market.clone()).await;
    }

    async fn withdraw(&mut self, mut code: Value, mut amount: Value, mut address: Value, mut tag: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        (tag, params) = shift_2(self.handle_withdraw_tag_and_params(tag.clone(), params.clone()));
        self.check_address(address.clone());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "coin": currency.get(Value::from("id")),
            "quantity": amount.to_fixed(Value::from(10)),
            "address": address.clone()
        }))).unwrap());
        if code.clone() == Value::from("BRL") {
            let mut account_ref: Value = params.contains_key(Value::from("account_ref")).into();
            if !account_ref.is_truthy() {
                return Value::Undefined;
            };
        } else if code.clone() != Value::from("LTC") {
            let mut tx_fee: Value = params.contains_key(Value::from("tx_fee")).into();
            if !tx_fee.is_truthy() {
                return Value::Undefined;
            };
            if code.clone() == Value::from("XRP") {
                if tag.clone().is_nullish() {
                    if !params.contains_key(Value::from("destination_tag")) {
                        return Value::Undefined;
                    };
                } else {
                    request.set("destination_tag".into(), tag.clone());
                };
            };
        };
        let mut response: Value = self.dispatch("privatePostWithdrawCoin".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "response_data": {
        //             "withdrawal": {
        //                 "id": 1,
        //                 "coin": "BRL",
        //                 "quantity": "300.56",
        //                 "net_quantity": "291.68",
        //                 "fee": "8.88",
        //                 "account": "bco: 341, ag: 1111, cta: 23456-X",
        //                 "status": 1,
        //                 "created_timestamp": "1453912088",
        //                 "updated_timestamp": "1453912088"
        //             }
        //         },
        //         "status_code": 100,
        //         "server_unix_timestamp": "1453912088"
        //     }
        //
        let mut response_data: Value = self.safe_value(response.clone(), Value::from("response_data"), Value::new_object());
        let mut withdrawal: Value = self.safe_dict(response_data.clone(), Value::from("withdrawal"), Value::Undefined);
        return <Self as Mercado>::parse_transaction(self, withdrawal.clone(), currency.clone()).await;
    }

    fn parse_transaction(&self, mut transaction: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "id": 1,
        //         "coin": "BRL",
        //         "quantity": "300.56",
        //         "net_quantity": "291.68",
        //         "fee": "8.88",
        //         "account": "bco: 341, ag: 1111, cta: 23456-X",
        //         "status": 1,
        //         "created_timestamp": "1453912088",
        //         "updated_timestamp": "1453912088"
        //     }
        //
        currency = self.safe_currency(Value::Undefined, currency.clone());
        return Value::Json(normalize(&Value::Json(json!({
            "id": self.safe_string(transaction.clone(), Value::from("id"), Value::Undefined),
            "txid": Value::Undefined,
            "timestamp": Value::Undefined,
            "datetime": Value::Undefined,
            "network": Value::Undefined,
            "addressFrom": Value::Undefined,
            "address": Value::Undefined,
            "addressTo": Value::Undefined,
            "amount": Value::Undefined,
            "type": Value::Undefined,
            "currency": currency.get(Value::from("code")),
            "status": Value::Undefined,
            "updated": Value::Undefined,
            "tagFrom": Value::Undefined,
            "tag": Value::Undefined,
            "tagTo": Value::Undefined,
            "comment": Value::Undefined,
            "internal": Value::Undefined,
            "fee": Value::Undefined,
            "info": transaction.clone()
        }))).unwrap());
    }

    fn parse_ohlcv(&self, mut ohlcv: Value, mut market: Value) -> Value {
        return Value::Json(serde_json::Value::Array(vec![(self.safe_integer(ohlcv.clone(), Value::from(0), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(1), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(2), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(3), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(4), Value::Undefined)).into(), (self.safe_number(ohlcv.clone(), Value::from(5), Value::Undefined)).into()]));
    }

    async fn fetch_ohlcv(&mut self, mut symbol: Value, mut timeframe: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        request.set("timeframe".into(), timeframe.clone());
        request.set("interval".into(), timeframe.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        let mut raw: Value = Value::Undefined;
        // Match endpoints by substring on common OHLCV path tokens (klines, candles,
        // ohlcv, barhist, history, kline, candle, ohlc).
        'outer: for token in ["klines", "candles", "ohlcv", "barhist", "kline", "candle", "ohlc"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { raw = rv; break 'outer; }
                }
            }
        }
        if raw.is_undefined() {
            for (api_name, method_name, path_name) in [("public", "GET", "klines"), ("public", "GET", "candles"), ("public", "GET", "ohlcv")] {
                let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                if !rv.is_undefined() { raw = rv; break; }
            }
        }
        if raw.is_undefined() { return Value::Undefined; }
        let json_resp = match &raw { Value::Json(j) => j.clone(), _ => return raw };
        let arr_val = crate::exchange::unwrap_response_array(&json_resp);
        let items = match arr_val.as_array() { Some(a) => a.clone(), None => return raw };
        let market: Value = Value::Undefined;
        let mut parsed: Vec<serde_json::Value> = Vec::with_capacity(items.len());
        for item in items {
            if item.is_array() {
                parsed.push(item);
            } else {
                let pv = <Self as Exchange>::parse_ohlcv(self, Value::Json(item.clone()), market.clone());
                if let Value::Json(j) = pv { parsed.push(j); }
            }
        }
        Value::Json(serde_json::Value::Array(parsed))
    }


    async fn fetch_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["allorders", "all_orders", "orders/history", "orders"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "allOrders"), ("private", "GET", "orders"), ("private", "GET", "orders/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_open_orders(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["openorders", "open_orders", "orders/open", "orders/active"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "openOrders"), ("private", "GET", "orders/open"), ("private", "GET", "orders/active")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn fetch_my_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        if symbol.is_nonnullish() { request.set("symbol".into(), symbol.clone()); }
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Mercado>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["mytrades", "my_trades", "trades/history", "fills", "user/trades", "executions"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.ends_with(&format!("/{}", token)) || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("private", "GET", "myTrades"), ("private", "GET", "fills"), ("private", "GET", "trades/history")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn orders_to_trades(&mut self, mut orders: Value) -> Value {
        let mut result: Value = Value::new_array();
        let mut i: usize = 0;
        while i < orders.len() {
            let mut trades: Value = self.safe_value(orders.get(i.into()), Value::from("trades"), Value::new_array());
            let mut y: usize = 0;
            while y < trades.len() {
                result.push(trades.get(y.into()));
                y += 1;
            };
            i += 1;
        };
        return result.clone();
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_str() {
                    "publicGetCoins" => self.request("coins".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCoinorderbook" => self.request("{coin}/orderbook/".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCointicker" => self.request("{coin}/ticker/".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCointrades" => self.request("{coin}/trades/".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCointradesfrom" => self.request("{coin}/trades/{from}/".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCointradesfromto" => self.request("{coin}/trades/{from}/{to}".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCoindaysummaryyearmonthday" => self.request("{coin}/day-summary/{year}/{month}/{day}/".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostCancelorder" => self.request("cancel_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostGetaccountinfo" => self.request("get_account_info".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostGetorder" => self.request("get_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostGetwithdrawal" => self.request("get_withdrawal".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostListsystemmessages" => self.request("list_system_messages".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostListorders" => self.request("list_orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostListorderbook" => self.request("list_orderbook".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPlacebuyorder" => self.request("place_buy_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPlacesellorder" => self.request("place_sell_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPlacemarketbuyorder" => self.request("place_market_buy_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostPlacemarketsellorder" => self.request("place_market_sell_order".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostWithdrawcoin" => self.request("withdraw_coin".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v4publicGetCoincandle" => self.request("{coin}/candle/".into(), "v4Public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "v4publicnetGetCandles" => self.request("candles".into(), "v4PublicNet".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MercadoImpl(Value);
#[async_trait(?Send)]
impl Exchange for MercadoImpl {
    fn describe(&self) -> Value { Mercado::describe(self) }
    async fn fetch_ticker(&mut self, symbol: Value, params: Value) -> Value { Mercado::fetch_ticker(self, symbol, params).await }
    async fn fetch_order_book(&mut self, symbol: Value, limit: Value, params: Value) -> Value { Mercado::fetch_order_book(self, symbol, limit, params).await }
    async fn fetch_ohlcv(&mut self, symbol: Value, timeframe: Value, since: Value, limit: Value, params: Value) -> Value { Mercado::fetch_ohlcv(self, symbol, timeframe, since, limit, params).await }
    async fn fetch_trades(&mut self, symbol: Value, since: Value, limit: Value, params: Value) -> Value { Mercado::fetch_trades(self, symbol, since, limit, params).await }
    fn parse_trade(&self, trade: Value, market: Value) -> Value { Mercado::parse_trade(self, trade, market) }
    fn parse_order(&self, order: Value, market: Value) -> Value { Mercado::parse_order(self, order, market) }
    fn parse_ticker(&self, ticker: Value, market: Value) -> Value { Mercado::parse_ticker(self, ticker, market) }
    fn parse_balance(&self, response: Value) -> Value { Mercado::parse_balance(self, response) }
    fn parse_transaction(&self, transaction: Value, currency: Value) -> Value { Mercado::parse_transaction(self, transaction, currency) }
    fn parse_order_status(&self, status: Value) -> Value { Mercado::parse_order_status(self, status) }
}
impl Mercado for MercadoImpl {}
impl ValueTrait for MercadoImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl MercadoImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = MercadoImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Mercado::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

