#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unused_imports)]
#![allow(unused_assignments)]
#![allow(unused_comparisons)]
#![allow(unused_mut)]
#![allow(unused_variables)]

use async_trait::async_trait;
use std::str::FromStr;
use serde::{Deserialize, Serialize};
use serde_json::json;
use crate::exchange::{Exchange, ExchangeImpl, Precise, Value, ValueTrait, BoolExt, JSON, Array, Object, Math, Promise, parse_int, shift_2, extend_2, normalize};
// Crypto hash identifiers
fn sha256() -> Value { Value::from("sha256()") }
fn sha384() -> Value { Value::from("sha384()") }
fn sha512() -> Value { Value::from("sha512()") }
fn md5() -> Value { Value::from("md5()") }
fn ed25519() -> Value { Value::from("ed25519()") }
fn rsa(msg: Value, secret: Value, _hash: Value) -> Value { msg }
fn eddsa(msg: Value, secret: Value, _curve: Value) -> Value { msg }
fn secp256k1() -> Value { Value::from("secp256k1()") }
fn keccak() -> Value { Value::from("keccak()") }
fn ecdsa(msg: Value, secret: Value, algo: Value, hash_fn: Value) -> Value { msg }
fn totp(secret: Value) -> Value { Value::Undefined }
fn jwt(data: Value, secret: Value, hash: Value, is_rsa: Value) -> Value { Value::Undefined }
fn parse_float(value: Value) -> Value { value }
fn decimals(value: Value) -> Value { Value::from(0) }
fn shift_1(value: Value) -> Value { value }
fn shift_3(value: Value) -> (Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined) }
fn shift_4(value: Value) -> (Value, Value, Value, Value) { (value.clone(), Value::Undefined, Value::Undefined, Value::Undefined) }
// Error type constructors
fn BadRequest(msg: Value) -> Value { msg }
fn InvalidOrder(msg: Value) -> Value { msg }
fn ExchangeError(msg: Value) -> Value { msg }
fn InsufficientFunds(msg: Value) -> Value { msg }
fn OrderNotFound(msg: Value) -> Value { msg }
fn AuthenticationError(msg: Value) -> Value { msg }
fn PermissionDenied(msg: Value) -> Value { msg }
fn ExchangeNotAvailable(msg: Value) -> Value { msg }
fn ArgumentsRequired(msg: Value) -> Value { msg }
fn RateLimitExceeded(msg: Value) -> Value { msg }
fn OrderNotFillable(msg: Value) -> Value { msg }
fn OrderImmediatelyFillable(msg: Value) -> Value { msg }
fn NotSupported(msg: Value) -> Value { msg }
fn DuplicateOrderId(msg: Value) -> Value { msg }

use crate::exchange::{PRECISE_BASE, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN};
use crate::exchange::{DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE, NO_PADDING, PAD_WITH_ZERO};

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

#[async_trait]
pub trait Paymium : Exchange {
    fn describe(&self) -> Value {
        Value::Json(serde_json::Value::from_str(r###"{
            "id": "paymium",
            "name": "Paymium",
            "countries": [
                "FR",
                "EU"
            ],
            "enableRateLimit": true,
            "rateLimit": 2000,
            "timeout": 10000,
            "certified": false,
            "pro": false,
            "alias": false,
            "dex": false,
            "has": {
                "publicAPI": true,
                "privateAPI": true,
                "CORS": true,
                "spot": true,
                "swap": false,
                "future": false,
                "option": false,
                "cancelOrder": true,
                "createDepositAddress": true,
                "createLimitOrder": true,
                "createMarketOrder": true,
                "createMarketOrderWs": true,
                "createOrder": true,
                "editOrder": "emulated",
                "fetchBalance": true,
                "fetchCurrencies": "emulated",
                "fetchCurrenciesWs": "emulated",
                "fetchDepositAddress": true,
                "fetchDepositAddresses": true,
                "fetchDepositAddressesByNetwork": false,
                "fetchFundingHistory": false,
                "fetchFundingRate": false,
                "fetchFundingRateHistory": false,
                "fetchFundingRates": false,
                "fetchIndexOHLCV": false,
                "fetchL2OrderBook": true,
                "fetchMarkets": true,
                "fetchMarkOHLCV": false,
                "fetchOpenInterestHistory": false,
                "fetchOrderBook": true,
                "fetchPremiumIndexOHLCV": false,
                "fetchTicker": true,
                "fetchTrades": true,
                "fetchTradingFee": false,
                "fetchTradingFees": false,
                "transfer": true
            },
            "urls": {
                "logo": "https://user-images.githubusercontent.com/51840849/87153930-f0f02200-c2c0-11ea-9c0a-40337375ae89.jpg",
                "api": {
                    "rest": "https://paymium.com/api"
                },
                "www": "https://www.paymium.com",
                "doc": [
                    "https://github.com/Paymium/api-documentation",
                    "https://www.paymium.com/page/developers",
                    "https://paymium.github.io/api-documentation/"
                ],
                "fees": "https://www.paymium.com/page/help/fees",
                "referral": "https://www.paymium.com/page/sign-up?referral=eDAzPoRQFMvaAB8sf-qj"
            },
            "api": {
                "public": {
                    "get": [
                        "countries",
                        "currencies",
                        "data/{currency}/ticker",
                        "data/{currency}/trades",
                        "data/{currency}/depth",
                        "bitcoin_charts/{id}/trades",
                        "bitcoin_charts/{id}/depth"
                    ]
                },
                "private": {
                    "get": [
                        "user",
                        "user/addresses",
                        "user/addresses/{address}",
                        "user/orders",
                        "user/orders/{uuid}",
                        "user/price_alerts",
                        "merchant/get_payment/{uuid}"
                    ],
                    "post": [
                        "user/addresses",
                        "user/orders",
                        "user/withdrawals",
                        "user/email_transfers",
                        "user/payment_requests",
                        "user/price_alerts",
                        "merchant/create_payment"
                    ],
                    "delete": [
                        "user/orders/{uuid}",
                        "user/orders/{uuid}/cancel",
                        "user/price_alerts/{id}"
                    ]
                }
            },
            "requiredCredentials": {
                "apiKey": true,
                "secret": true,
                "uid": false,
                "accountId": false,
                "login": false,
                "password": false,
                "twofa": false,
                "privateKey": false,
                "walletAddress": false,
                "token": false
            },
            "markets": {
                "BTC/EUR": {
                    "id": "eur",
                    "symbol": "BTC/EUR",
                    "base": "BTC",
                    "quote": "EUR",
                    "baseId": "btc",
                    "quoteId": "eur",
                    "type": "spot",
                    "spot": true,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "index": false,
                    "contract": false,
                    "precision": {},
                    "limits": {
                        "leverage": {},
                        "amount": {},
                        "price": {},
                        "cost": {}
                    },
                    "marginModes": {}
                }
            },
            "currencies": {},
            "fees": {
                "trading": {
                    "taker": 0.005,
                    "maker": -0.001
                },
                "funding": {
                    "withdraw": {},
                    "deposit": {}
                }
            },
            "status": {
                "status": "ok"
            },
            "httpExceptions": {},
            "commonCurrencies": {
                "XBT": "BTC",
                "BCHSV": "BSV"
            },
            "precisionMode": 4,
            "paddingMode": 5,
            "limits": {
                "leverage": {},
                "amount": {},
                "price": {},
                "cost": {}
            },
            "rollingWindowSize": 60000,
            "version": "v1",
            "features": {
                "spot": {
                    "sandbox": false,
                    "createOrder": {
                        "marginMode": false,
                        "triggerPrice": false,
                        "triggerDirection": false,
                        "stopLossPrice": false,
                        "takeProfitPrice": false,
                        "timeInForce": {
                            "IOC": false,
                            "FOK": false,
                            "PO": false,
                            "GTD": false
                        },
                        "hedged": false,
                        "trailing": false,
                        "leverage": false,
                        "marketBuyByCost": true,
                        "marketBuyRequiresPrice": false,
                        "selfTradePrevention": false,
                        "iceberg": false
                    }
                },
                "swap": {},
                "future": {}
            }
        }"###).unwrap())
    }

    fn parse_balance(&self, mut response: Value) -> Value {
        let mut result: Value = Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap());
        let mut currencies: Value = self.get("currencies".into()).keys();
        let mut i: usize = 0;
        while i < currencies.len() {
            let mut code: Value = currencies.get(i.into());
            let mut currency: Value = self.currency(code.clone());
            let mut currency_id: Value = currency.get(Value::from("id"));
            let mut free: Value = Value::from("balance_") + currency_id.clone();
            if response.contains_key(free.clone()) {
                let mut account: Value = self.account();
                let mut used: Value = Value::from("locked_") + currency_id.clone();
                account.set("free".into(), self.safe_string(response.clone(), free.clone(), Value::Undefined));
                account.set("used".into(), self.safe_string(response.clone(), used.clone(), Value::Undefined));
                result.set(code.clone(), account.clone());
            };
            i += 1;
        };
        return self.safe_balance(result.clone());
    }

    async fn fetch_balance(&mut self, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetUser".into(), params.clone(), Value::Undefined).await;
        return <Self as Paymium>::parse_balance(self, response.clone());
    }

    async fn fetch_order_book(&mut self, mut symbol: Value, mut limit: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Paymium>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["depth", "orderbook", "order_book"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "depth"), ("public", "GET", "orderbook"), ("public", "GET", "order_book")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_ticker(&self, mut ticker: Value, mut market: Value) -> Value {
        //
        // {
        //     "high":"33740.82",
        //     "low":"32185.15",
        //     "volume":"4.7890433",
        //     "bid":"33313.53",
        //     "ask":"33497.97",
        //     "midpoint":"33405.75",
        //     "vwap":"32802.5263553",
        //     "at":1643381654,
        //     "price":"33143.91",
        //     "open":"33116.86",
        //     "variation":"0.0817",
        //     "currency":"EUR",
        //     "trade_id":"ce2f5152-3ac5-412d-9b24-9fa72338474c",
        //     "size":"0.00041087"
        // }
        //
        let mut symbol: Value = self.safe_symbol(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut timestamp: Value = self.safe_timestamp(ticker.clone(), Value::from("at"), Value::Undefined);
        let mut vwap: Value = self.safe_string(ticker.clone(), Value::from("vwap"), Value::Undefined);
        let mut base_volume: Value = self.safe_string(ticker.clone(), Value::from("volume"), Value::Undefined);
        let mut quote_volume: Value = Precise::string_mul(base_volume.clone(), vwap.clone());
        let mut last: Value = self.safe_string(ticker.clone(), Value::from("price"), Value::Undefined);
        return self.safe_ticker(Value::Json(normalize(&Value::Json(json!({
            "symbol": symbol,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "high": self.safe_string(ticker.clone(), Value::from("high"), Value::Undefined),
            "low": self.safe_string(ticker.clone(), Value::from("low"), Value::Undefined),
            "bid": self.safe_string(ticker.clone(), Value::from("bid"), Value::Undefined),
            "bidVolume": Value::Undefined,
            "ask": self.safe_string(ticker.clone(), Value::from("ask"), Value::Undefined),
            "askVolume": Value::Undefined,
            "vwap": vwap,
            "open": self.safe_string(ticker.clone(), Value::from("open"), Value::Undefined),
            "close": last,
            "last": last,
            "previousClose": Value::Undefined,
            "change": Value::Undefined,
            "percentage": self.safe_string(ticker.clone(), Value::from("variation"), Value::Undefined),
            "average": Value::Undefined,
            "baseVolume": base_volume,
            "quoteVolume": quote_volume,
            "info": ticker
        }))).unwrap()), market.clone());
    }

    async fn fetch_ticker(&mut self, mut symbol: Value, mut params: Value) -> Value {
        fn collect_routes(node: &serde_json::Value, api_name: &str, out: &mut Vec<(String, String, String)>) {
            if let serde_json::Value::Object(map) = node {
                for (k, v) in map { let kl = k.to_lowercase(); if kl == "get" || kl == "post" || kl == "put" || kl == "delete" { if let serde_json::Value::Object(paths) = v { for (p, _cost) in paths { out.push((api_name.to_string(), kl.to_uppercase(), p.clone())); } } } else { collect_routes(v, api_name, out); } }
            }
        }
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        let mut dynamic_calls: Vec<(String, String, String)> = vec![];
        if let Value::Json(serde_json::Value::Object(api_map)) = <Self as Paymium>::describe(self).get("api".into()) {
            for (api_name, node) in api_map { collect_routes(&node, &api_name, &mut dynamic_calls); }
        }
        for token in ["ticker/24hr", "ticker", "ticker/price", "bookticker", "tickers"] {
            for (api_name, method_name, path_name) in &dynamic_calls {
                if method_name.as_str() != "GET" || path_name.contains('{') { continue; }
                let p = path_name.to_lowercase();
                if p == token || p.contains(token) {
                    let rv = self.request(path_name.clone().into(), api_name.clone().into(), method_name.clone().into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
                    if !rv.is_undefined() { return rv; }
                }
            }
        }
        let candidates = vec![("public", "GET", "ticker/24hr"), ("public", "GET", "ticker"), ("public", "GET", "ticker/price")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    fn parse_trade(&mut self, mut trade: Value, mut market: Value) -> Value {
        let mut timestamp: Value = self.safe_timestamp(trade.clone(), Value::from("created_at_int"), Value::Undefined);
        let mut id: Value = self.safe_string(trade.clone(), Value::from("uuid"), Value::Undefined);
        market = self.safe_market(Value::Undefined, market.clone(), Value::Undefined, Value::Undefined);
        let mut side: Value = self.safe_string(trade.clone(), Value::from("side"), Value::Undefined);
        let mut price: Value = self.safe_string(trade.clone(), Value::from("price"), Value::Undefined);
        let mut amount_field: Value = Value::from("traded_") + market.get(Value::from("base")).to_lower_case();
        let mut amount: Value = self.safe_string(trade.clone(), amount_field.clone(), Value::Undefined);
        return self.safe_trade(Value::Json(normalize(&Value::Json(json!({
            "info": trade,
            "id": id,
            "order": Value::Undefined,
            "timestamp": timestamp,
            "datetime": self.iso8601(timestamp.clone()),
            "symbol": market.get(Value::from("symbol")),
            "type": Value::Undefined,
            "side": side,
            "takerOrMaker": Value::Undefined,
            "price": price,
            "amount": amount,
            "cost": Value::Undefined,
            "fee": Value::Undefined
        }))).unwrap()), market.clone());
    }

    async fn fetch_trades(&mut self, mut symbol: Value, mut since: Value, mut limit: Value, mut params: Value) -> Value {
        let mut request = if params.is_object() { params.clone() } else { Value::new_object() };
        request.set("symbol".into(), symbol.clone());
        if since.is_nonnullish() { request.set("since".into(), since.clone()); request.set("startTime".into(), since.clone()); }
        if limit.is_nonnullish() { request.set("limit".into(), limit.clone()); }
        let candidates = vec![("public", "GET", "trades"), ("public", "GET", "recent_trades"), ("public", "GET", "aggTrades")];
        for (api_name, method_name, path_name) in candidates {
            let rv = self.request(path_name.into(), api_name.into(), method_name.into(), request.clone(), Value::Undefined, Value::Undefined, Value::Undefined).await;
            if !rv.is_undefined() { return rv; }
        }
        Value::Undefined
    }


    async fn create_deposit_address(&mut self, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privatePostUserAddresses".into(), params.clone(), Value::Undefined).await;
        //
        //     {
        //         "address": "1HdjGr6WCTcnmW1tNNsHX7fh4Jr5C2PeKe",
        //         "valid_until": 1620041926,
        //         "currency": "BTC",
        //         "label": "Savings"
        //     }
        //
        return <Self as Paymium>::parse_deposit_address(self, response.clone(), Value::Undefined);
    }

    async fn fetch_deposit_address(&mut self, mut code: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "address": code
        }))).unwrap());
        let mut response: Value = self.dispatch("privateGetUserAddressesAddress".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "address": "1HdjGr6WCTcnmW1tNNsHX7fh4Jr5C2PeKe",
        //         "valid_until": 1620041926,
        //         "currency": "BTC",
        //         "label": "Savings"
        //     }
        //
        return <Self as Paymium>::parse_deposit_address(self, response.clone(), Value::Undefined);
    }

    async fn fetch_deposit_addresses(&mut self, mut codes: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut response: Value = self.dispatch("privateGetUserAddresses".into(), params.clone(), Value::Undefined).await;
        //
        //     [
        //         {
        //             "address": "1HdjGr6WCTcnmW1tNNsHX7fh4Jr5C2PeKe",
        //             "valid_until": 1620041926,
        //             "currency": "BTC",
        //             "label": "Savings"
        //         }
        //     ]
        //
        return self.parse_deposit_addresses(response.clone(), codes.clone(), Value::Undefined, Value::Undefined);
    }

    fn parse_deposit_address(&mut self, mut deposit_address: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "address": "1HdjGr6WCTcnmW1tNNsHX7fh4Jr5C2PeKe",
        //         "valid_until": 1620041926,
        //         "currency": "BTC",
        //         "label": "Savings"
        //     }
        //
        let mut address: Value = self.safe_string(deposit_address.clone(), Value::from("address"), Value::Undefined);
        let mut currency_id: Value = self.safe_string(deposit_address.clone(), Value::from("currency"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": deposit_address,
            "currency": self.safe_currency_code(currency_id.clone(), currency.clone()),
            "network": Value::Undefined,
            "address": address,
            "tag": Value::Undefined
        }))).unwrap());
    }

    async fn create_order(&mut self, mut symbol: Value, mut r#type: Value, mut side: Value, mut amount: Value, mut price: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut market: Value = self.market(symbol.clone());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "type": self.capitalize(r#type.clone()) + Value::from("Order"),
            "currency": market.get(Value::from("id")),
            "direction": side,
            "amount": amount
        }))).unwrap());
        if r#type.clone() != Value::from("market") {
            request.set("price".into(), price.clone());
        };
        let mut response: Value = self.dispatch("privatePostUserOrders".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": response,
            "id": response.get(Value::from("uuid"))
        }))).unwrap()), market.clone());
    }

    async fn cancel_order(&mut self, mut id: Value, mut symbol: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "uuid": id
        }))).unwrap());
        let mut response: Value = self.dispatch("privateDeleteUserOrdersUuidCancel".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        return self.safe_order(Value::Json(normalize(&Value::Json(json!({
            "info": response
        }))).unwrap()), Value::Undefined);
    }

    async fn transfer(&mut self, mut code: Value, mut amount: Value, mut from_account: Value, mut to_account: Value, mut params: Value) -> Value {
        params = params.or_default(Value::new_object());
        self.load_markets(Value::Undefined, Value::Undefined).await;
        let mut currency: Value = self.currency(code.clone());
        if to_account.index_of(Value::from("@")) < Value::from(0) {
            panic!(r###"ExchangeError::new(self.get("id".into()) + Value::from(" transfer() only allows transfers to an email address"))"###);
        };
        if code.clone() != Value::from("BTC") && code.clone() != Value::from("EUR") {
            panic!(r###"ExchangeError::new(self.get("id".into()) + Value::from(" transfer() only allows BTC or EUR"))"###);
        };
        let mut request: Value = Value::Json(normalize(&Value::Json(json!({
            "currency": currency.get(Value::from("id")),
            "amount": self.currency_to_precision(code.clone(), amount.clone(), Value::Undefined),
            "email": to_account
        }))).unwrap());
        // 'comment': 'a small note explaining the transfer'
        let mut response: Value = self.dispatch("privatePostUserEmailTransfers".into(), extend_2(request.clone(), params.clone()), Value::Undefined).await;
        //
        //     {
        //         "uuid": "968f4580-e26c-4ad8-8bcd-874d23d55296",
        //         "type": "Transfer",
        //         "currency": "BTC",
        //         "currency_amount": "string",
        //         "created_at": "2013-10-24T10:34:37.000Z",
        //         "updated_at": "2013-10-24T10:34:37.000Z",
        //         "amount": "1.0",
        //         "state": "executed",
        //         "currency_fee": "0.0",
        //         "btc_fee": "0.0",
        //         "comment": "string",
        //         "traded_btc": "string",
        //         "traded_currency": "string",
        //         "direction": "buy",
        //         "price": "string",
        //         "account_operations": [
        //             {
        //                 "uuid": "968f4580-e26c-4ad8-8bcd-874d23d55296",
        //                 "amount": "1.0",
        //                 "currency": "BTC",
        //                 "created_at": "2013-10-24T10:34:37.000Z",
        //                 "created_at_int": 1389094259,
        //                 "name": "account_operation",
        //                 "address": "1FPDBXNqSkZMsw1kSkkajcj8berxDQkUoc",
        //                 "tx_hash": "string",
        //                 "is_trading_account": true
        //             }
        //         ]
        //     }
        //
        return <Self as Paymium>::parse_transfer(self, response.clone(), currency.clone());
    }

    fn parse_transfer(&self, mut transfer: Value, mut currency: Value) -> Value {
        //
        //     {
        //         "uuid": "968f4580-e26c-4ad8-8bcd-874d23d55296",
        //         "type": "Transfer",
        //         "currency": "BTC",
        //         "currency_amount": "string",
        //         "created_at": "2013-10-24T10:34:37.000Z",
        //         "updated_at": "2013-10-24T10:34:37.000Z",
        //         "amount": "1.0",
        //         "state": "executed",
        //         "currency_fee": "0.0",
        //         "btc_fee": "0.0",
        //         "comment": "string",
        //         "traded_btc": "string",
        //         "traded_currency": "string",
        //         "direction": "buy",
        //         "price": "string",
        //         "account_operations": [
        //             {
        //                 "uuid": "968f4580-e26c-4ad8-8bcd-874d23d55296",
        //                 "amount": "1.0",
        //                 "currency": "BTC",
        //                 "created_at": "2013-10-24T10:34:37.000Z",
        //                 "created_at_int": 1389094259,
        //                 "name": "account_operation",
        //                 "address": "1FPDBXNqSkZMsw1kSkkajcj8berxDQkUoc",
        //                 "tx_hash": "string",
        //                 "is_trading_account": true
        //             }
        //         ]
        //     }
        //
        let mut currency_id: Value = self.safe_string(transfer.clone(), Value::from("currency"), Value::Undefined);
        let mut updated_at: Value = self.safe_string(transfer.clone(), Value::from("updated_at"), Value::Undefined);
        let mut timetstamp: Value = self.parse_date(updated_at.clone());
        let mut account_operations: Value = self.safe_value(transfer.clone(), Value::from("account_operations"), Value::Undefined);
        let mut first_operation: Value = self.safe_value(account_operations.clone(), Value::from(0), Value::new_object());
        let mut status: Value = self.safe_string(transfer.clone(), Value::from("state"), Value::Undefined);
        return Value::Json(normalize(&Value::Json(json!({
            "info": transfer,
            "id": self.safe_string(transfer.clone(), Value::from("uuid"), Value::Undefined),
            "timestamp": timetstamp,
            "datetime": self.iso8601(timetstamp.clone()),
            "currency": self.safe_currency_code(currency_id.clone(), currency.clone()),
            "amount": self.safe_number(transfer.clone(), Value::from("amount"), Value::Undefined),
            "fromAccount": Value::Undefined,
            "toAccount": self.safe_string(first_operation.clone(), Value::from("address"), Value::Undefined),
            "status": <Self as Paymium>::parse_transfer_status(self, status.clone())
        }))).unwrap());
    }

    fn parse_transfer_status(&self, mut status: Value) -> Value {
        let mut statuses: Value = Value::Json(normalize(&Value::Json(json!({
            "executed": "ok"
        }))).unwrap());
        // what are the other statuses?
        return self.safe_string(statuses.clone(), status.clone(), status.clone());
    }

    

    

    
    async fn dispatch(&mut self, method: Value, params: Value, context: Value) -> Value {
        match method {
            Value::Json(serde_json::Value::String(ref m)) => {
                match m.as_ref() {
                    "publicGetCountries" => self.request("countries".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetCurrencies" => self.request("currencies".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetDatacurrencyticker" => self.request("data/{currency}/ticker".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetDatacurrencytrades" => self.request("data/{currency}/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetDatacurrencydepth" => self.request("data/{currency}/depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetBitcoinchartsidtrades" => self.request("bitcoin_charts/{id}/trades".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "publicGetBitcoinchartsiddepth" => self.request("bitcoin_charts/{id}/depth".into(), "public".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUser" => self.request("user".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUseraddresses" => self.request("user/addresses".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUseraddressesaddress" => self.request("user/addresses/{address}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserorders" => self.request("user/orders".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserordersuuid" => self.request("user/orders/{uuid}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetUserpricealerts" => self.request("user/price_alerts".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateGetMerchantgetpaymentuuid" => self.request("merchant/get_payment/{uuid}".into(), "private".into(), "GET".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUseraddresses" => self.request("user/addresses".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserorders" => self.request("user/orders".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserwithdrawals" => self.request("user/withdrawals".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUseremailtransfers" => self.request("user/email_transfers".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserpaymentrequests" => self.request("user/payment_requests".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostUserpricealerts" => self.request("user/price_alerts".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privatePostMerchantcreatepayment" => self.request("merchant/create_payment".into(), "private".into(), "POST".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteUserordersuuid" => self.request("user/orders/{uuid}".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteUserordersuuidcancel" => self.request("user/orders/{uuid}/cancel".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    "privateDeleteUserpricealertsid" => self.request("user/price_alerts/{id}".into(), "private".into(), "DELETE".into(), params, Value::Undefined, Value::Undefined, Value::Undefined).await,
                    _ => panic!("Unknown API method: {}", m),
                }
            },
            _ => panic!("dispatch: method must be a string, got {:?}", method)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PaymiumImpl(Value);
impl Exchange for PaymiumImpl {}
impl Paymium for PaymiumImpl {}
impl ValueTrait for PaymiumImpl {
    fn is_undefined(&self) -> bool { self.0.is_undefined() }
    fn is_nullish(&self) -> bool { self.0.is_nullish() }
    fn is_nonnullish(&self) -> bool { self.0.is_nonnullish() }
    fn is_truthy(&self) -> bool { self.0.is_truthy() }
    fn or_default(&self, default: Value) -> Value { self.0.or_default(default) }
    fn is_number(&self) -> bool { self.0.is_number() }
    fn is_string(&self) -> bool { self.0.is_string() }
    fn is_object(&self) -> bool { self.0.is_object() }
    fn is_falsy(&self) -> bool { self.0.is_falsy() }
    fn to_upper_case(&self) -> Value { self.0.to_upper_case() }
    fn unwrap_str(&self) -> &str { self.0.unwrap_str() }
    fn unwrap_usize(&self) -> usize { self.0.unwrap_usize() }
    fn unwrap_bool(&self) -> bool { self.0.unwrap_bool() }
    fn unwrap_precise(&self) -> &Precise { self.0.unwrap_precise() }
    fn unwrap_json(&self) -> &serde_json::Value { self.0.unwrap_json() }
    fn unwrap_json_mut(&mut self) -> &mut serde_json::Value { self.0.unwrap_json_mut() }
    fn unwrap_precise_mut(&mut self) -> &mut Precise { self.0.unwrap_precise_mut() }
    fn len(&self) -> usize { self.0.len() }
    fn get(&self, key: Value) -> Value { self.0.get(key) }
    fn set(&mut self, key: Value, value: Value) { self.0.set(key, value) }
    fn push(&mut self, value: Value) { self.0.push(value) }
    fn split(&self, separator: Value) -> Value { self.0.split(separator) }
    fn contains_key(&self, key: Value) -> bool { self.0.contains_key(key) }
    fn keys(&self) -> Value { self.0.keys() }
    fn values(&self) -> Value { self.0.values() }
    fn to_array(&self, x: Value) -> Value { self.0.to_array(x) }
    fn index_of(&self, x: Value) -> Value { self.0.index_of(x) }
    fn join(&self, glue: Value) -> Value { self.0.join(glue) }
    fn to_string(&self) -> Value { self.0.to_string() }
    fn typeof_(&self) -> Value { self.0.typeof_() }
    fn slice(&self, start: Value, end: Value) -> Value { self.0.slice(start, end) }
}

impl PaymiumImpl {
    pub fn new(params: Value) -> Self {
        let mut rv = PaymiumImpl(match params {
            Value::Json(_) => params,
            _ => Value::new_object()
        });
        ExchangeImpl::init(&mut rv.0);

        let config_entries = Paymium::describe(&rv);
        for k in config_entries.keys() {
            rv.set(k.clone(), config_entries.get(k).clone());
        }
        rv
    }
}

