[package]
name = "ccxt"
version = "0.1.0"
edition = "2024"

[features]
default = []
full-exchanges = []
full-pro = ["full-exchanges"]

[dependencies]
anyhow = "1.0.101"
async-trait = "0.1.89"
base64 = "0.20.0"
chrono = "0.4.43"
hex = "0.4.3"
hmac = "0.12.1"
md-5 = "0.10.6"
num-bigint = { version = "0.4.6", features = ["serde"] }
num-integer = "0.1.46"
num-traits = "0.2.19"
rand = "0.8.5"
regex = "1.12.3"
reqwest = "0.11.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["unbounded_depth"] }
sha2 = "0.10.9"
sha3 = "0.10.8"
tokio = { version = "1.49.0", features = ["full"] }
urlencoding = "2.1.3"

[lib]
name = "ccxt"
path = "src/lib.rs"

[[bin]]
name = "ccxt-rs-test"
path = "src/bin/test.rs"

[profile.release]
debug = true
